import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

const routes = [
  ["homepage", "/?lang=cs"],
  ["country", "/country.html?code=CZE&lang=cs"],
  ["capitals", "/eu-capitals.html?lang=cs"],
  ["state budget", "/cesky-rozpocet.html?lang=cs"],
  ["municipality", "/cz/obce/praha/?lang=cs"],
  ["directory", "/cz/obce/?lang=cs"],
  ["cities", "/cz/mesta/?lang=cs"],
];

for (const [name, path] of routes) {
  test(`${name} renders without serious accessibility or runtime failures`, async ({ page }) => {
    const failures = [];
    page.on("pageerror", (error) => failures.push(error.message));
    page.on("console", (message) => {
      if (message.type() === "error") failures.push(message.text());
    });
    const response = await page.goto(path, { waitUntil: "networkidle" });
    expect(response?.ok()).toBeTruthy();
    await expect(page.locator("body")).toBeVisible();
    expect(failures).toEqual([]);
    const results = await new AxeBuilder({ page }).disableRules(["color-contrast"]).analyze();
    const serious = results.violations.filter((item) => ["serious", "critical"].includes(item.impact));
    expect(serious).toEqual([]);
  });
}

test("language state survives navigation", async ({ page }) => {
  await page.goto("/?lang=en", { waitUntil: "networkidle" });
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await page.goto("/country.html?code=DEU&lang=en", { waitUntil: "networkidle" });
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page.locator("#country-name")).toContainText("Germany");
});

test("country profiles expose sortable ten-year health, social and transport comparisons", async ({ page }) => {
  await page.goto("/country.html?code=CZE&lang=en", { waitUntil: "networkidle" });
  for (const id of ["healthcare", "social-system", "transportation"]) {
    const section=page.locator(`#${id}`);
    await expect(section.locator(".function-bar-column")).toHaveCount(10);
    await expect(section.locator("tbody tr")).toHaveCount(10);
    await expect(section.locator(".sortable-header-button")).toHaveCount(5);
  }
  await expect(page.locator("#healthcare-system")).toBeHidden();
  await page.locator("#country-switch").selectOption("DEU");
  await expect(page.locator("#healthcare-system")).toBeVisible();
  await expect(page.locator("#country-function-health-title")).toHaveText("Ten years of health.");
});

test("country cash-in keeps municipal and company layers separate", async ({ page }) => {
  await page.goto("/country.html?code=CZE&lang=en", { waitUntil: "networkidle" });
  await expect(page.locator("#cash-in .cash-consolidated")).toContainText("The only comparable total");
  await expect(page.locator("#cash-in .cash-layer-card")).toHaveCount(4);
  await expect(page.locator("#cash-in")).toContainText("534.1 bn CZK");
  await expect(page.locator("#cash-in")).toContainText("689.5 bn CZK");
  await expect(page.locator("#cash-in .cash-nonadd")).toContainText("Do not add these cards");
  await expect(page.locator("#cash-in tbody tr")).toHaveCount(20);
  await expect(page.locator("#cash-in .sortable-header-button")).toHaveCount(5);
  await page.locator("#country-switch").selectOption("DEU");
  await expect(page.locator("#cash-in .cash-layer-card")).toHaveCount(0);
  await expect(page.locator("#cash-in .cash-detail-missing")).toBeVisible();
});

test("municipal directory explains the aggregate balance in both languages", async ({ page }) => {
  await page.goto("/cz/obce/?lang=cs", { waitUntil: "networkidle" });
  const story = page.locator(".municipal-aggregate-story");
  await expect(story).toContainText("43,4 mld. Kč vytvořily přebytkové obce.");
  await expect(story.locator(".aggregate-cohort")).toHaveCount(3);
  await expect(story).toContainText("+14,9 mld. Kč");
  await expect(story.locator(".piggy-panel li")).toHaveCount(5);
  await expect(story).toContainText("16,9 mld. Kč");

  await page.goto("/cz/obce/?lang=en", { waitUntil: "networkidle" });
  await expect(page.locator(".municipal-aggregate-story")).toContainText("CZK 43.4bn generated by surplus municipalities.");
  await expect(page.locator(".piggy-panel")).toContainText("The five largest deficits reduced the result by CZK 2bn.");
});

test("nationwide municipal explorer drives the aggregate story and directory year", async ({ page }) => {
  await page.goto("/cz/obce/?lang=cs&year=2010", { waitUntil: "networkidle" });
  await expect(page.locator("#municipality-year")).toHaveValue("2010");
  await expect(page.locator("#municipality-year-coverage")).toContainText("6 245 obcí");
  await expect(page.locator("#nationwide-history-kpis")).toContainText("283,6 mld. Kč");
  await expect(page.locator("#nationwide-history-chart .history-line")).toHaveCount(3);
  await expect(page.locator("#spending-benchmark-summary")).toContainText("27 295 Kč / obyv.");
  await expect(page.locator("#spending-benchmark-chart article")).toHaveCount(8);
  await expect(page.locator("#municipality-count")).toContainText("6 245 s daty za 2010");
  await expect(page.locator("#municipality-grid .entity-card").first()).toContainText("2010 · IČO");

  await page.locator("#municipality-year").selectOption("2023");
  await expect(page).toHaveURL(/year=2023/);
  await expect(page.locator("#nationwide-history-kpis")).toContainText("+55,7 mld. Kč");
  await expect(page.locator("#municipality-directory-year")).toHaveText("2023");
  await expect(page.locator("#nationwide-history-table-body .selected-history-row th")).toHaveText("2023");

  await page.locator("#municipality-year").selectOption("2010");
  await page.locator("#municipality-query").fill("Poličná");
  await expect(page.locator("#municipality-count")).toContainText("0 s daty za 2010");
  await expect(page.locator("#municipality-grid .entity-card")).toContainText("—");

  await page.locator("#municipality-year").selectOption("2025");
  await page.locator("#municipality-query").fill("Abertamy");
  await expect(page.locator("#municipality-grid .entity-card")).toContainText("822 obyvatel");
  await expect(page.locator("#municipality-grid .entity-spending-benchmark")).toContainText("38 856 Kč / obyv.");
  await page.locator("#municipality-sort").selectOption("expense_per_capita");
  await expect(page.locator("#municipality-sort")).toHaveValue("expense_per_capita");
});

test("municipal profiles expose 2010–2025 history and preserve genuine coverage gaps", async ({ page }) => {
  await page.goto("/cz/obce/abertamy/?lang=cs", { waitUntil: "networkidle" });
  await expect(page.locator("#history-explorer .kicker")).toHaveText("16 let / 2010–2025");
  await expect(page.locator("#history-table-body tr")).toHaveCount(16);
  await expect(page.locator("#history-kpis")).toContainText("Součet výsledků za 16 let");
  await expect(page.locator('.source-list a[href$="/data/municipal-history/00254398.json"]')).toBeVisible();

  await page.goto("/cz/obce/abertamy/?lang=en", { waitUntil: "networkidle" });
  await expect(page.locator("#history-explorer .kicker")).toHaveText("16 years / 2010-2025");
  await expect(page.locator("#history-kpis")).toContainText("16-year cumulative balance");

  await page.goto("/cz/obce/policna/?lang=cs", { waitUntil: "networkidle" });
  await expect(page.locator("#history-table-body tr")).toHaveCount(13);
  await expect(page.locator("#history-kpis")).toContainText("Součet výsledků za 13 let");
  await expect(page.locator("#history-table-body")).not.toContainText("2010");
});

test("all representative page menus resolve and primary navigation routes correctly", async ({ page, request }) => {
  for (const route of routes.map(([, path]) => path)) {
    await page.goto(route, { waitUntil: "networkidle" });
    const hrefs = await page.locator("header a[href], header nav a[href], .detail-nav a[href], .breadcrumbs a[href]").evaluateAll((links) =>
      [...new Set(links.map((link) => link.href).filter((href) => href.startsWith(location.origin)))]
    );
    expect(hrefs.length).toBeGreaterThan(0);
    for (const href of hrefs) {
      const target = new URL(href); target.hash = "";
      const response = await request.get(target.href);
      expect(response.ok(), `${route} menu target failed: ${target.href}`).toBeTruthy();
    }
  }

  await page.goto("/?lang=cs", { waitUntil: "networkidle" });
  await page.locator('[data-global-nav="capitals"]').click();
  await expect(page).toHaveURL(/\/eu-capitals\.html\?lang=cs/);
  await page.goto("/?lang=cs", { waitUntil: "networkidle" });
  await page.locator(".country-menu summary").click();
  await expect(page.locator(".country-menu-panel a")).toHaveCount(12);
  await page.locator('.country-menu-panel a[href*="code=CZE"]').click();
  await expect(page).toHaveURL(/\/country\.html\?code=CZE&lang=cs/);
});

test("cities use the functional unified menu on desktop and mobile", async ({ page }) => {
  await page.goto("/cz/mesta/?lang=cs", { waitUntil: "networkidle" });
  const countryMenu = page.locator(".country-menu");
  await countryMenu.locator("summary").click();
  await expect(countryMenu).toHaveAttribute("open", "");
  await expect(countryMenu.locator(".country-menu-panel a")).toHaveCount(12);
  const panelBox = await countryMenu.locator(".country-menu-panel").boundingBox();
  expect(panelBox?.width).toBeLessThanOrEqual(430);
  expect(panelBox?.height).toBeLessThan(700);

  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload({ waitUntil: "networkidle" });
  await expect(page.locator(".global-nav")).toBeVisible();
  await expect(page.locator('[data-global-nav="cities"]')).toBeVisible();
  await page.locator('[data-global-nav="home"]').click();
  await expect(page).toHaveURL(/\/index\.html\?lang=cs/);
});
