// Editorial metadata, not a data pipeline. Only published entries enter the site.
export default [
  {
    slug:'the-world-is-having-fewer-children',status:'published',format:'story',
    title:'The world is having fewer children. What changes next?',
    titleCs:'Ve světě se rodí méně dětí. Co se změní dál?',
    description:'Follow 65 years of fertility and birth rates across 217 countries and territories—and what the transition means for families, schools and public budgets.',
    descriptionCs:'Sledujte 65 let plodnosti a porodnosti ve 217 zemích a územích a význam demografické proměny pro rodiny, školy a veřejné rozpočty.',
    date:'2026-10-05',updated:'2026-10-05',minutes:14,topic:'Demography & public budgets',author:'Public Spending Data',language:'en',featured:false,
    takeaway:'Most countries are below the approximate replacement benchmark. The global aggregate is still above it.',
    takeawayCs:'Většina zemí je pod přibližnou hranicí prosté reprodukce. Světový agregát zůstává nad ní.',
    edition:'World Bank WDI snapshot · 1960–2024 · 217 countries / territories · Source vintage: 13 July 2026 · Acquired 5 October 2026.',
    editionCs:'Snímek WDI Světové banky · 1960–2024 · 217 zemí / území · Verze zdroje: 13. července 2026 · Získáno 5. října 2026.',
  },
  {
    slug:'where-carbon-auction-money-goes',status:'published',format:'story',
    title:'Europe puts a price on carbon. Where does the money go?',
    titleCs:'Evropa zpoplatňuje emise. Kam míří peníze?',
    description:'Follow an allowance from allocation to surrender, and auction revenue from buyers to public budgets and European funds.',
    descriptionCs:'Sledujte povolenku od přidělení po odevzdání a aukční výnosy od kupujících do veřejných rozpočtů a evropských fondů.',
    date:'2026-10-05',updated:'2026-10-05',minutes:5,topic:'Carbon markets & public money',author:'Public Spending Data',language:'en',featured:false,
    takeaway:'One market produces two records: a flow of allowances and a flow of public money.',
    takeawayCs:'Jeden trh vytváří dvě stopy: tok povolenek a tok veřejných peněz.',
    edition:'Editorial snapshot · EU ETS1 auction revenue: 2024 · Source coverage checked 5 October 2026 · Not a live tracker.',
    editionCs:'Redakční snímek · Aukční výnosy EU ETS1: 2024 · Pokrytí zdrojů ověřeno 5. října 2026 · Nejde o živý přehled.',
  },
  {
    slug:'trade-surged-around-russia',status:'published',format:'story',
    title:'Trade surged around Russia. Where did the goods go?',
    description:'Follow suppliers, product baskets and onward exports through Kazakhstan and Kyrgyzstan—and test how much the trade statistics can establish.',
    date:'2026-09-27',updated:'2026-09-27',minutes:5,topic:'Trade & sanctions',author:'Public Spending Data',language:'en',featured:false,
    takeaway:'Larger neighbouring markets offer clues about trade detours. Matching shipments requires more evidence.',
    edition:'Editorial snapshot · Annual hub history: 2014–2025 · Supplier comparison: 2019–2025 · Evidence checked 27 September 2026.',
  },
  {
    slug:'the-great-oil-pivot',status:'published',format:'interactive',
    title:'The great oil pivot.',description:'By 2025, China and India remain the major buyers of Russian crude in this comparison. Follow the shift from Europe on one globe.',
    date:'2026-09-26',updated:'2026-10-04',minutes:4,topic:'Energy & trade',author:'Public Spending Data',language:'en',featured:true,
    takeaway:'The pivot holds in 2025: China and India lead, while the EU’s reported subtotal falls again.',
    edition:'Updated 4 October 2026 · Annual: 2020–2025 · EU-27 reported subtotal · Monthly India: October 2025–July 2026.',
    cover:{eyebrow:'THE WORLD, IN MOTION',title:'The great oil pivot.',note:'Europe. China. India.',detail:'Now through 2025. Explore the evidence.'},
  },
  {
    slug: 'tariffs-went-up-did-america-win', status: 'published', format: 'story',
    title: 'Tariffs went up. Did America come out ahead?',
    description: 'Seven charts follow implemented tariffs, car imports, reciprocal duties and the cash the U.S. government actually kept.',
    date: '2026-09-20', updated: '2026-09-20', minutes: 7, topic: 'Trade & tariffs',
    author: 'Public Spending Data', language: 'en', featured: false,
    takeaway: 'Higher barriers. Uneven trade. No proven overall winner.',
  },
  {
    slug: 'customs-revenue-gross-is-not-net', status: 'published', format: 'mini',
    title: 'The customs headline is not the cash kept.',
    description: 'Gross customs collections rose sharply. Refunds explain why net fiscal-year-to-date revenue tells a different story.',
    date: '2026-09-20', updated: '2026-09-20', minutes: 2, topic: 'Public revenue',
    author: 'Public Spending Data', language: 'en',
    takeaway: '$167.3bn net, after $125.2bn in refunds.',
  },
  {
    slug: 'reciprocal-tariffs-are-not-equal', status: 'published', format: 'mini',
    title: '“Reciprocal” does not mean equal.',
    description: 'Look at the same car category in both directions: Canada, China, Europe and Mexico show very different tariff gaps.',
    date: '2026-09-20', updated: '2026-09-20', minutes: 2, topic: 'Trade & tariffs',
    author: 'Public Spending Data', language: 'en',
    takeaway: 'Same product. Different border. Different rate.',
  },
];
