(() => {
  const state={code:window.PSDCountryRoutes.codeFromLocation(),lang:document.documentElement.lang==="en"?"en":"cs",data:null,spending:null,coverage:null,manifest:null};
  const $=selector=>document.querySelector(selector);
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const t={
    cs:{kicker:"01 / Veškeré veřejné příjmy",title:"Kolik do země přiteče.",copy:"Jeden konsolidovaný celek a jeho oddělené vrstvy. Příjmy obcí a krajů ukazujeme vedle státu; obrat firem zůstává mimo rozpočet.",consolidated:"Konsolidované veřejné příjmy",onlyTotal:"Jediný srovnatelný celkový součet",revenue:"Příjmy",expense:"Výdaje",balance:"Saldo",gdp:"HDP",state:"Státní rozpočet",municipal:"Obce",regions:"Kraje bez Prahy",companies:"Státní firmy",entities:"subjektů",topLine:"Celkový objem",bottomLine:"Výsledek",cash:"Stav peněžních prostředků",turnover:"Obrat",result:"Výsledek hospodaření",ownerTransfers:"Platby do rozpočtu",notAdd:"Tyto karty nesčítejte",notAddCopy:"Stát, obce a kraje si navzájem posílají transfery. Obrat firem je prodej zboží a služeb, nikoli daňový příjem. Konsolidovaný celek nahoře vnitřní toky eliminuje.",detailMissing:"Detail územních rozpočtů zatím nemáme ve společné otevřené struktuře. Načtený národní rozpočet a portfolio veřejných subjektů jsou proto zobrazené odděleně.",largest:"Největší a nejmenší objemy",name:"Subjekt",group:"Skupina",year:"Rok",sources:"Zdroje",largestGroup:"Největší",smallestGroup:"Nejmenší",loadedBudget:"Načtený národní rozpočet",classifiedExpense:"Klasifikované výdaje",budgetLines:"zdrojových řádků",publicUniverse:"Oficiální veřejný sektor",comparisonBoundary:"srovnávací hranice",storedRoster:"Řádkový registr",represented:"zastoupených subjektů",financialRows:"účetních výkazů",openRegistry:"Otevřít registr subjektů",loadedLayers:"Načtené národní vrstvy"},
    en:{kicker:"01 / Total public cash-in",title:"What flows into the country.",copy:"One consolidated total and its separate layers. Municipal and regional revenue sits beside the state; company turnover stays outside the budget.",consolidated:"Consolidated public revenue",onlyTotal:"The only comparable total",revenue:"Revenue",expense:"Expenditure",balance:"Balance",gdp:"GDP",state:"State budget",municipal:"Municipalities",regions:"Regions excluding Prague",companies:"State-owned companies",entities:"entities",topLine:"Top line",bottomLine:"Bottom line",cash:"Cash holdings",turnover:"Turnover",result:"Net result",ownerTransfers:"Payments to budget",notAdd:"Do not add these cards",notAddCopy:"The state, municipalities and regions transfer money among themselves. Company turnover is sales of goods and services, not tax revenue. The consolidated total above eliminates internal flows.",detailMissing:"Territorial-budget detail is not yet available in a common open structure. The loaded national budget and public-entity portfolio are therefore shown as separate accounting layers.",largest:"Largest and smallest top lines",name:"Entity",group:"Group",year:"Year",sources:"Sources",largestGroup:"Largest",smallestGroup:"Smallest",loadedBudget:"Loaded national budget",classifiedExpense:"Classified expenditure",budgetLines:"source lines",publicUniverse:"Official public-sector universe",comparisonBoundary:"comparison boundary",storedRoster:"Row-level registry",represented:"represented entities",financialRows:"financial statements",openRegistry:"Open entity registry",loadedLayers:"Loaded national layers"}
  };
  t.cs.kicker="Fiskální vrstvy / Veškeré veřejné příjmy";
  t.en.kicker="Fiscal layers / Total public revenue";
  const locale=()=>state.lang==="en"?"en-GB":"cs-CZ";
  const n=(value,digits=1)=>Number(value).toLocaleString(locale(),{minimumFractionDigits:digits,maximumFractionDigits:digits});
  const money=(value,currency)=>`${n(value,Math.abs(value)<1?3:1)} ${state.lang==="en"?"bn":"mld."} ${currency}`;
  const signed=(value,currency)=>`${value>0?"+":""}${money(value,currency)}`;
  const card=(label,year,topLabel,top,bottomLabel,bottom,extra="")=>`<article class="cash-layer-card"><header><span>${esc(label)}</span><b>${year}</b></header><div><small>${esc(topLabel)} · ${year}</small><strong>${top}</strong></div><div><small>${esc(bottomLabel)} · ${year}</small><strong class="${String(bottom).startsWith("-")?"negative":""}">${bottom}</strong></div>${extra}</article>`;
  function rankingRows(items,kind,group){const c=state.data.countries[state.code],x=t[state.lang];return items.map(item=>`<tr><td>${esc(item.name)}</td><td>${esc(group)}</td><td data-sort-value="${kind==="municipal"?item.revenue_local_bn:item.turnover_local_bn}">${money(kind==="municipal"?item.revenue_local_bn:item.turnover_local_bn,c.currency)}</td><td data-sort-value="${kind==="municipal"?item.balance_local_bn:item.net_result_local_bn}">${signed(kind==="municipal"?item.balance_local_bn:item.net_result_local_bn,c.currency)}</td><td>${kind==="municipal"?2025:2024}</td></tr>`).join("")}
  const words=value=>String(value??"").replaceAll("_"," ");
  function loadedLayers(c,x){
    const spending=state.spending?.countries.find(country=>country.code===state.code);
    const coverage=state.coverage?.countries?.[state.code];
    const manifest=state.manifest?.countries?.find(country=>country.country_code===state.code);
    if(!spending&&!coverage&&!manifest)return `<div class="cash-detail-missing">${esc(x.detailMissing)}</div>`;
    const perimeter=coverage?.comparison_perimeter;
    const universe=coverage?.broad_entity_count??coverage?.perimeters?.[perimeter]?.represented_entity_count;
    const sourceLinks=(coverage?.sources||[]).map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.publisher||source.source_id)} ↗</a>`).join("");
    return `<div class="cash-loaded-grid" aria-label="${esc(x.loadedLayers)}">
      <article><span>${x.loadedBudget}</span><strong>${spending?money(spending.totals.current,spending.currency):"—"}</strong><small>${spending?`${esc(spending.periods.current.label)} · ${spending.rows.length} ${x.budgetLines} · ${esc(spending[`scope_${state.lang}`])}`:"—"}</small></article>
      <article><span>${x.publicUniverse}</span><strong>${Number.isFinite(universe)?n(universe,0):"—"}</strong><small>${perimeter?`${esc(words(perimeter))} · ${x.comparisonBoundary}`:"—"}</small></article>
      <article><span>${x.storedRoster}</span><strong>${manifest?n(manifest.record_count,0):"—"}</strong><small>${manifest?`${n(manifest.represented_entity_count,0)} ${x.represented} · ${n(manifest.financial_record_count,0)} ${x.financialRows}`:"—"}</small></article>
    </div><aside class="cash-nonadd"><b>${x.notAdd}.</b><span>${x.detailMissing}</span></aside><div class="cash-loaded-sources"><a href="#public-entities">${x.openRegistry} ↓</a>${sourceLinks}</div>`;
  }
  function render(){
    if(!state.data?.countries[state.code])return;const x=t[state.lang],c=state.data.countries[state.code],g=c.consolidated,root=$("#country-cash-in-root");
    const consolidated=`<article class="cash-consolidated"><div><span>${x.consolidated} · ${g.year}</span><strong>${money(g.revenue_local_bn,c.currency)}</strong><small>${n(g.revenue_pct_gdp)} % ${x.gdp} · ${x.onlyTotal}</small></div><dl><div><dt>${x.revenue} · ${g.year}</dt><dd>${n(g.revenue_pct_gdp)}%</dd></div><div><dt>${x.expense} · ${g.year}</dt><dd>${n(g.expense_pct_gdp)}%</dd></div><div><dt>${x.balance} · ${g.year}</dt><dd class="${g.balance_pct_gdp<0?"negative":""}">${g.balance_pct_gdp>0?"+":""}${n(g.balance_pct_gdp)}%</dd></div></dl></article>`;
    let detail=loadedLayers(c,x);
    if(c.layers?.state_budget){const l=c.layers;detail=`<div class="cash-layer-grid">${card(x.state,l.state_budget.year,x.topLine+" / "+x.revenue,money(l.state_budget.revenue_local_bn,c.currency),x.bottomLine+" / "+x.balance,signed(l.state_budget.balance_local_bn,c.currency))}${card(`${x.municipal} · ${n(l.municipalities.entity_count,0)} ${x.entities}`,l.municipalities.year,x.topLine+" / "+x.revenue,money(l.municipalities.revenue_local_bn,c.currency),x.bottomLine+" / "+x.balance,signed(l.municipalities.balance_local_bn,c.currency),`<p>${x.cash} · ${l.municipalities.year}: <b>${money(l.municipalities.cash_local_bn,c.currency)}</b></p>`)}${card(`${x.regions} · ${l.regions.entity_count}`,l.regions.year,x.topLine+" / "+x.revenue,money(l.regions.revenue_local_bn,c.currency),x.bottomLine+" / "+x.balance,signed(l.regions.balance_local_bn,c.currency),`<p>${x.cash} · ${l.regions.year}: <b>${money(l.regions.cash_local_bn,c.currency)}</b></p>`)}${card(`${x.companies} · ${l.companies.entity_count}`,l.companies.year,x.topLine+" / "+x.turnover,money(l.companies.turnover_local_bn,c.currency),x.bottomLine+" / "+x.result,signed(l.companies.net_result_local_bn,c.currency),`<p>${x.ownerTransfers} · ${l.companies.year}: <b>${money(l.companies.owner_transfers_local_bn,c.currency)}</b></p>`)}</div><aside class="cash-nonadd"><b>${x.notAdd}.</b><span>${x.notAddCopy}</span></aside><div class="cash-rankings"><header><span>${x.largest}</span><strong>${state.lang==="en"?"TOP / BOTTOM 5":"5 NEJVĚTŠÍCH / NEJMENŠÍCH"}</strong></header><div><table><thead><tr><th>${x.name}</th><th>${x.group}</th><th>${x.topLine}</th><th>${x.bottomLine}</th><th>${x.year}</th></tr></thead><tbody>${rankingRows(l.municipalities.top,"municipal",`${x.municipal} · ${x.largestGroup}`)}${rankingRows(l.municipalities.bottom,"municipal",`${x.municipal} · ${x.smallestGroup}`)}${rankingRows(l.companies.top,"company",`${x.companies} · ${x.largestGroup}`)}${rankingRows(l.companies.bottom,"company",`${x.companies} · ${x.smallestGroup}`)}</tbody></table></div></div>`}
    root.innerHTML=`<div class="detail-heading"><div><span class="kicker">${x.kicker}</span><h2 id="country-cash-in-title">${x.title}</h2></div><p>${x.copy}</p></div>${consolidated}${detail}<details class="cash-sources"><summary>${x.sources}</summary><p>${esc(state.data.methodology[state.lang])}</p><div>${state.data.sources.map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.title)} ↗</a>`).join("")}</div></details>`;
  }
  addEventListener("countryprofilechange",event=>{state.code=event.detail.code;state.lang=event.detail.lang==="en"?"en":"cs";render()});
  Promise.all(["data/country-cash-in.v1.json","data/country-spending-2025-2026.v1.json","data/public-entity-coverage.v1.json","data/public-entity-directory/manifest.v1.json"].map(url=>fetch(url).then(response=>{if(!response.ok)throw new Error(`${url}: ${response.status}`);return response.json()}))).then(([data,spending,coverage,manifest])=>{state.data=data;state.spending=spending;state.coverage=coverage;state.manifest=manifest;render()}).catch(error=>console.error("Country cash-in",error));
})();
