// Generated from lib/data/sovereign-benchmark.v1.json - the same name_cs / name_en /
// iso2 fields country.js reads once that eight-megabyte payload lands. The profile
// shell needs the country identity at first paint, a second before the dataset can
// possibly arrive, so the names ship as a static map keyed by ISO-3 code.
(() => {
  const countries = Object.freeze({
    CZE:["Česko","Czechia","cz"],UKR:["Ukrajina","Ukraine","ua"],POL:["Polsko","Poland","pl"],
    DEU:["Německo","Germany","de"],GBR:["Spojené království","United Kingdom","gb"],
    FRA:["Francie","France","fr"],USA:["USA","United States","us"],CHE:["Švýcarsko","Switzerland","ch"],
    SWE:["Švédsko","Sweden","se"],DNK:["Dánsko","Denmark","dk"],FIN:["Finsko","Finland","fi"],
    BRA:["Brazílie","Brazil","br"],ESP:["Španělsko","Spain","es"],JPN:["Japonsko","Japan","jp"],
    NLD:["Nizozemsko","Netherlands","nl"],NOR:["Norsko","Norway","no"],GRC:["Řecko","Greece","gr"],
    AFG:["Afghánistán","Afghanistan","af"],ALB:["Albánie","Albania","al"],DZA:["Alžírsko","Algeria","dz"],
    AND:["Andorra","Andorra","ad"],AGO:["Angola","Angola","ao"],
    ATG:["Antigua a Barbuda","Antigua and Barbuda","ag"],ARG:["Argentina","Argentina","ar"],
    ARM:["Arménie","Armenia","am"],AUS:["Austrálie","Australia","au"],AUT:["Rakousko","Austria","at"],
    AZE:["Ázerbájdžán","Azerbaijan","az"],BHS:["Bahamy","Bahamas","bs"],BHR:["Bahrajn","Bahrain","bh"],
    BGD:["Bangladéš","Bangladesh","bd"],BRB:["Barbados","Barbados","bb"],BLR:["Bělorusko","Belarus","by"],
    BEL:["Belgie","Belgium","be"],BLZ:["Belize","Belize","bz"],BEN:["Benin","Benin","bj"],
    BTN:["Bhútán","Bhutan","bt"],BOL:["Bolívie","Bolivia","bo"],
    BIH:["Bosna a Hercegovina","Bosnia and Herzegovina","ba"],BWA:["Botswana","Botswana","bw"],
    BRN:["Brunej","Brunei Darussalam","bn"],BGR:["Bulharsko","Bulgaria","bg"],
    BFA:["Burkina Faso","Burkina Faso","bf"],BDI:["Burundi","Burundi","bi"],KHM:["Kambodža","Cambodia","kh"],
    CMR:["Kamerun","Cameroon","cm"],CAN:["Kanada","Canada","ca"],CPV:["Kapverdy","Cape Verde","cv"],
    CAF:["Středoafrická republika","Central African Republic","cf"],TCD:["Čad","Chad","td"],
    CHL:["Chile","Chile","cl"],CHN:["Čína","China","cn"],COL:["Kolumbie","Colombia","co"],
    COM:["Komory","Comoros","km"],CRI:["Kostarika","Costa Rica","cr"],HRV:["Chorvatsko","Croatia","hr"],
    CUB:["Kuba","Cuba","cu"],CYP:["Kypr","Cyprus","cy"],CIV:["Pobřeží slonoviny","Côte d'Ivoire","ci"],
    COD:["Kongo – Kinshasa","Democratic Republic of Congo","cd"],DJI:["Džibutsko","Djibouti","dj"],
    DMA:["Dominika","Dominica","dm"],DOM:["Dominikánská republika","Dominican Republic","do"],
    ECU:["Ekvádor","Ecuador","ec"],EGY:["Egypt","Egypt","eg"],SLV:["Salvador","El Salvador","sv"],
    GNQ:["Rovníková Guinea","Equatorial Guinea","gq"],ERI:["Eritrea","Eritrea","er"],
    EST:["Estonsko","Estonia","ee"],ETH:["Etiopie","Ethiopia","et"],
    FSM:["Mikronésie","Federated States of Micronesia","fm"],FJI:["Fidži","Fiji","fj"],
    GAB:["Gabon","Gabon","ga"],GMB:["Gambie","Gambia","gm"],GEO:["Gruzie","Georgia","ge"],
    GHA:["Ghana","Ghana","gh"],GRD:["Grenada","Grenada","gd"],GTM:["Guatemala","Guatemala","gt"],
    GIN:["Guinea","Guinea","gn"],GNB:["Guinea-Bissau","Guinea-Bissau","gw"],GUY:["Guyana","Guyana","gy"],
    HTI:["Haiti","Haiti","ht"],HND:["Honduras","Honduras","hn"],HUN:["Maďarsko","Hungary","hu"],
    ISL:["Island","Iceland","is"],IND:["Indie","India","in"],IDN:["Indonésie","Indonesia","id"],
    IRN:["Írán","Iran","ir"],IRQ:["Irák","Iraq","iq"],IRL:["Irsko","Ireland","ie"],ISR:["Izrael","Israel","il"],
    ITA:["Itálie","Italy","it"],JAM:["Jamajka","Jamaica","jm"],JOR:["Jordánsko","Jordan","jo"],
    KAZ:["Kazachstán","Kazakhstan","kz"],KEN:["Keňa","Kenya","ke"],KIR:["Kiribati","Kiribati","ki"],
    KWT:["Kuvajt","Kuwait","kw"],KGZ:["Kyrgyzstán","Kyrgyzstan","kg"],
    LAO:["Laos","Lao People's Democratic Republic","la"],LVA:["Lotyšsko","Latvia","lv"],
    LBN:["Libanon","Lebanon","lb"],LSO:["Lesotho","Lesotho","ls"],LBR:["Libérie","Liberia","lr"],
    LBY:["Libye","Libya","ly"],LIE:["Lichtenštejnsko","Liechtenstein","li"],LTU:["Litva","Lithuania","lt"],
    LUX:["Lucembursko","Luxembourg","lu"],MKD:["Severní Makedonie","Macedonia","mk"],
    MDG:["Madagaskar","Madagascar","mg"],MWI:["Malawi","Malawi","mw"],MYS:["Malajsie","Malaysia","my"],
    MDV:["Maledivy","Maldives","mv"],MLI:["Mali","Mali","ml"],MLT:["Malta","Malta","mt"],
    MHL:["Marshallovy ostrovy","Marshall Islands","mh"],MRT:["Mauritánie","Mauritania","mr"],
    MUS:["Mauricius","Mauritius","mu"],MEX:["Mexiko","Mexico","mx"],MDA:["Moldavsko","Moldova","md"],
    MCO:["Monako","Monaco","mc"],MNG:["Mongolsko","Mongolia","mn"],MNE:["Černá Hora","Montenegro","me"],
    MAR:["Maroko","Morocco","ma"],MOZ:["Mosambik","Mozambique","mz"],MMR:["Myanmar (Barma)","Myanmar","mm"],
    NAM:["Namibie","Namibia","na"],NRU:["Nauru","Nauru","nr"],NPL:["Nepál","Nepal","np"],
    NZL:["Nový Zéland","New Zealand","nz"],NIC:["Nikaragua","Nicaragua","ni"],NER:["Niger","Niger","ne"],
    NGA:["Nigérie","Nigeria","ng"],PRK:["Severní Korea","North Korea","kp"],OMN:["Omán","Oman","om"],
    PAK:["Pákistán","Pakistan","pk"],PLW:["Palau","Palau","pw"],
    PSE:["Palestinská území","Palestinian Territories","ps"],PAN:["Panama","Panama","pa"],
    PNG:["Papua-Nová Guinea","Papua New Guinea","pg"],PRY:["Paraguay","Paraguay","py"],PER:["Peru","Peru","pe"],
    PHL:["Filipíny","Philippines","ph"],PRT:["Portugalsko","Portugal","pt"],QAT:["Katar","Qatar","qa"],
    COG:["Kongo – Brazzaville","Republic of Congo","cg"],ROU:["Rumunsko","Romania","ro"],
    RUS:["Rusko","Russia","ru"],RWA:["Rwanda","Rwanda","rw"],
    KNA:["Svatý Kryštof a Nevis","Saint Kitts and Nevis","kn"],LCA:["Svatá Lucie","Saint Lucia","lc"],
    VCT:["Svatý Vincenc a Grenadiny","Saint Vincent and the Grenadines","vc"],WSM:["Samoa","Samoa","ws"],
    SMR:["San Marino","San Marino","sm"],STP:["Svatý Tomáš a Princův ostrov","Sao Tome and Principe","st"],
    SAU:["Saúdská Arábie","Saudi Arabia","sa"],SEN:["Senegal","Senegal","sn"],SRB:["Srbsko","Serbia","rs"],
    SYC:["Seychely","Seychelles","sc"],SLE:["Sierra Leone","Sierra Leone","sl"],
    SGP:["Singapur","Singapore","sg"],SVK:["Slovensko","Slovakia","sk"],SVN:["Slovinsko","Slovenia","si"],
    SLB:["Šalamounovy ostrovy","Solomon Islands","sb"],SOM:["Somálsko","Somalia","so"],
    ZAF:["Jihoafrická republika","South Africa","za"],KOR:["Jižní Korea","South Korea","kr"],
    SSD:["Jižní Súdán","South Sudan","ss"],LKA:["Srí Lanka","Sri Lanka","lk"],SDN:["Súdán","Sudan","sd"],
    SUR:["Surinam","Suriname","sr"],SWZ:["Eswatini","Swaziland","sz"],SYR:["Sýrie","Syria","sy"],
    TJK:["Tádžikistán","Tajikistan","tj"],TZA:["Tanzanie","Tanzania","tz"],THA:["Thajsko","Thailand","th"],
    TLS:["Východní Timor","Timor-Leste","tl"],TGO:["Togo","Togo","tg"],TON:["Tonga","Tonga","to"],
    TTO:["Trinidad a Tobago","Trinidad and Tobago","tt"],TUN:["Tunisko","Tunisia","tn"],
    TUR:["Turecko","Turkey","tr"],TKM:["Turkmenistán","Turkmenistan","tm"],TUV:["Tuvalu","Tuvalu","tv"],
    UGA:["Uganda","Uganda","ug"],ARE:["Spojené arabské emiráty","United Arab Emirates","ae"],
    URY:["Uruguay","Uruguay","uy"],UZB:["Uzbekistán","Uzbekistan","uz"],VUT:["Vanuatu","Vanuatu","vu"],
    VAT:["Vatikán","Vatican City","va"],VEN:["Venezuela","Venezuela","ve"],VNM:["Vietnam","Vietnam","vn"],
    YEM:["Jemen","Yemen","ye"],ZMB:["Zambie","Zambia","zm"],ZWE:["Zimbabwe","Zimbabwe","zw"]
  });
  const entry = code => countries[String(code || "").toUpperCase()];
  // Mirrors country.js: Czech names for the Czech UI, English names for the English UI.
  const name = (code, lang) => entry(code)?.[lang === "en" ? 1 : 0] || "";
  const iso2 = code => entry(code)?.[2] || "";
  window.PSDCountryNames = Object.freeze({ countries, name, iso2 });
})();
