import {createLedgers,missingLedger,ledgerRows,ledgerSources,teachingExample} from './lib/funding-ledgers.mjs';
import {countries,tr} from './lib/funding-deep-dive.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={education:'/data/education-deep-dive.v1.json',healthInsurers:'/data/cz-health-insurers-2024.json',health:'/data/country-health.v1.json'};
let ledgers=[],loadError=false,active={code:'CZE',lang:'cs'},per100=new URLSearchParams(location.search).get('unit')==='100';
let generation=0;
const ready=Promise.all(Object.entries(paths).map(async([key,path])=>{const r=await fetch(path);if(!r.ok)throw Error(path);return [key,await r.json()];})).then(rows=>{ledgers=createLedgers(Object.fromEntries(rows));}).catch(()=>{loadError=true;});
const labels={illustrative:tr('Fictional teaching example','Smyšlený výukový příklad'),actual:tr('Reported outturn','Vykázaná skutečnost'),derived:tr('Derived reconciliation','Odvozené sladění'),plan:tr('Budget plan · not payments','Rozpočtový plán · nikoli platby'),accrual:tr('Reported accrual expense','Vykázané účetní náklady'),unknown:tr('Amounts not verified','Částky neověřeny'),classification:tr('Spending / financing category','Kategorie výdajů / financování')};
const colors={public:'#a8b63f',local:'#8b8d83',derived:'#d2ccc1',merge:'#a8b63f'};
const wrap=(text,max)=>{const lines=[];let line='';for(const word of text.split(' ')){if((line+' '+word).trim().length>max&&line){lines.push(line);line=word;}else line=(line+' '+word).trim();}if(line)lines.push(line);return lines;};
function svgText(text,x,y,{max=30,size=13,color='#faf7ef',weight=400,anchor='start',height=17}={}){return `<text x="${x}" y="${y}" fill="${color}" font-size="${size}" font-weight="${weight}" text-anchor="${anchor}">${wrap(text,max).map((line,i)=>`<tspan x="${x}" dy="${i?height:0}">${esc(line)}</tspan>`).join('')}</text>`;}
function renderPlate(host,g,lang){
 const t=x=>x[lang],say=(en,cs)=>lang==='en'?en:cs;
 const share=per100||g.unit==='share',format=v=>v===null?'—':new Intl.NumberFormat(lang==='en'?'en-GB':'cs-CZ',{maximumFractionDigits:2,minimumFractionDigits:share?1:g.unit==='euros'?0:2}).format(share?v/g.total*100:g.unit==='euros'?v*1e9:v);
 const amount=v=>v===null?say('Not quantified','Nevyčísleno'):format(v)+(share?' / 100':g.unit==='euros'?' EUR':(lang==='en'?`bn ${g.currency}`:` mld. ${g.currency}`));
 const unit=share?say('Units per 100 of the stated total','Jednotky na 100 uvedeného celku'):g.unit==='euros'?say('EUR per year · fictional amounts','EUR za rok · smyšlené částky'):say(`${g.currency} billions`,`${g.currency} v miliardách`);
 const country=countries.find(c=>c.code===g.country),w=1040,nodeW=286,nodeH=170,step=302,top=28;
 const nodes=g.nodes.map(n=>({...n,x:20+n.col*(w-40-nodeW),y:top+n.row*step}));
 const by=Object.fromEntries(nodes.map(n=>[n.id,n]));
 const h=Math.max(...nodes.map(n=>n.y))+nodeH+25;
 const edges=g.edges.map((e,i)=>{
  const a=by[e.from],b=by[e.to],out=g.edges.filter(x=>x.from===e.from),incoming=g.edges.filter(x=>x.to===e.to);
  const x1=a.x+nodeW*(out.indexOf(e)+1)/(out.length+1),x2=b.x+nodeW*(incoming.indexOf(e)+1)/(incoming.length+1),y1=a.y+nodeH,y2=b.y;
  const mid=(y1+y2)/2;return {...e,i,x:(x1+x2)/2,y:mid+(i%2?12:-12),d:`M${x1},${y1}C${x1},${mid} ${x2},${mid} ${x2},${y2}`,color:e.status==='unknown'?'#8b8d83':colors[a.kind]||colors.public};
 });
 const graphic=`<svg class="ledger-svg" xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="${g.id}-title ${g.id}-desc"><title id="${g.id}-title">${esc(t(g.title))}</title><desc id="${g.id}-desc">${esc(unit+'. '+g.edges.map(e=>`${t(by[e.from].label)} → ${t(by[e.to].label)}: ${amount(e.value)}`).join('; '))}</desc><rect width="${w}" height="${h}" fill="#171918"/><defs><marker id="${g.id}-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="8" markerHeight="8" markerUnits="userSpaceOnUse" orient="auto"><path d="M1 1 9 5 1 9" fill="none" stroke="#a8b63f" stroke-width="1.7"/></marker></defs><g font-family="Arial,Helvetica,sans-serif">${edges.map(e=>`<path id="${g.id}-edge-${e.i}" d="${e.d}" fill="none" stroke="${e.color}" stroke-width="${e.value===null?1.5:Math.max(1,25*e.value/g.total)}" ${['unknown','derived','plan'].includes(e.status)?'stroke-dasharray="6 5"':''} opacity=".72" marker-end="url(#${g.id}-arrow)"/>`).join('')}${nodes.map(n=>{
 const light=n.kind==='merge',ink=light?'#171918':'#faf7ef',muted=light?'#55594f':'#c6c8bd',titleLines=wrap(t(n.label),32).length;
 return `<g data-ledger-node="${n.id}"><rect x="${n.x}" y="${n.y}" width="${nodeW}" height="${nodeH}" fill="${light?'#f1ede3':'#242724'}" stroke="${light?'#d2ccc1':'#41453a'}"/><path d="M${n.x},${n.y}h${nodeW}" stroke="${colors[n.kind]||colors.public}" stroke-width="3"/>${svgText(t(n.label),n.x+18,n.y+27,{max:32,size:14,color:ink,weight:600})}<text data-node-amount="${n.id}" x="${n.x+18}" y="${n.y+86}" font-family="Georgia,serif" font-size="35" fill="${ink}">${esc(format(n.value))}</text>${svgText(n.value===null?say('Amount missing, not zero','Chybějící částka, nikoli nula'):share?say('per 100 of the stated total','na 100 uvedeného celku'):unit,n.x+18,n.y+106,{max:38,size:11,color:muted})}${svgText(t(n.note),n.x+18,n.y+130,{max:39,size:11,color:muted,height:15})}</g>`;
 }).join('')}${edges.map(e=>`<g><rect x="${e.x-102}" y="${e.y-15}" width="204" height="48" rx="1" fill="#171918"/>${svgText(amount(e.value),e.x,e.y,{anchor:'middle',size:14,weight:600,max:32})}${svgText(t(e.label),e.x,e.y+20,{anchor:'middle',size:10,color:'#c6c8bd',max:34,height:12})}</g>`).join('')}</g></svg>`;
 const refs=g.sourceIds.map(id=>ledgerSources[id]).concat(g.references||[]);
 host.innerHTML=`<article class="ledger-plate" data-ledger="${g.id}"><div class="ledger-top"><div><p class="ledger-eyebrow">${esc(t(country.name))} / ${g.year??(g.stage==='illustrative'?say('Worked example','Výukový příklad'):say('Year not verified','Rok neověřen'))} / ${esc(t(labels[g.stage]))}</p><h3>${esc(t(g.title))}</h3></div><div class="ledger-actions"><label>${say('Display','Zobrazení')}<select class="ledger-unit" aria-label="${say('Flow units','Jednotky toku')}" ${g.total===null||g.unit==='share'?'disabled':''}><option value="money" ${!share?'selected':''}>${say('Money amounts','Peněžní částky')}</option><option value="100" ${share?'selected':''}>${say('Per 100 of total','Na 100 celku')}</option></select></label><button type="button" class="ledger-play" ${g.edges.every(e=>e.value===null)?'disabled':''}>${say('Follow amounts ↓','Sledovat částky ↓')}</button></div></div><div class="ledger-legend"><span><i></i>${say('Reported amount / category','Vykázaná částka / kategorie')}</span><span><i class="dashed"></i>${say('Plan, calculation or missing amount','Plán, dopočet nebo chybějící částka')}</span><span>${esc(unit)} · ${say('small flows enlarged','malé toky zvětšeny')}</span></div><div class="ledger-chart">${graphic}<div class="ledger-mobile">${nodes.map(n=>{
 const incoming=g.edges.filter(e=>e.to===n.id);return `<div class="ledger-mobile-step">${incoming.map(e=>`<div class="ledger-mobile-arrow"><span>${esc(t(by[e.from].label))}</span><b>↓ ${esc(amount(e.value))}</b><small>${esc(t(e.label))}</small></div>`).join('')}<div class="ledger-mobile-node ${n.kind==='merge'?'is-merge':''}"><h4>${esc(t(n.label))}</h4><strong>${esc(format(n.value))}</strong><small>${n.value===null?say('Amount missing, not zero','Chybějící částka, nikoli nula'):esc(unit)}</small><p>${esc(t(n.note))}</p></div></div>`;
 }).join('')}</div></div>${g.balance?`<p class="ledger-balance">${esc(t(g.balance))}</p>`:''}<p class="ledger-live" role="status">${say('Read each stage once. Repeated amounts follow the same money.','Čtěte každou fázi zvlášť. Opakované částky sledují stejné peníze.')}</p></article><div class="ledger-evidence"><p>${esc(t(g.note))}</p><div class="ledger-source-links">${refs.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a>`).join('')}${g.localData?`<a href="${g.localData}">${say('Underlying PSD data (JSON)','Podkladová data PSD (JSON)')} ↗</a>`:''}</div></div>`;
 const chart=host.querySelector('.ledger-chart'),rows=ledgerRows(g,lang,share).map(r=>({...r,value:r.value===null?null:Number((!share&&g.unit==='euros'?r.value*1e9:r.value).toFixed(3)),status:t(labels[r.status])}));
 if(window.PSDChart)window.PSDChart.register({slug:`funding-ledger-${g.topic}`,el:chart,title:()=>t(g.title),columns:[{key:'from',label:say('From','Odkud')},{key:'to',label:say('To','Kam')},{key:'value',label:unit,numeric:true},{key:'year',label:say('Year','Rok')},{key:'status',label:say('Evidence','Doklad')},{key:'meaning',label:say('Meaning','Význam')}],rows:()=>rows,exports:['csv','png'],embeddable:false,source:{name:refs.map(s=>s.title).join(' · '),url:refs[0]?.url,definition:t(g.title),excludes:t(g.note),caveat:say('Flows repeat amounts across stages. Do not sum every arrow. Unknown is not zero.','Toky opakují částky v jednotlivých fázích. Nesčítejte všechny šipky. Neznámá částka není nula.'),table:refs.map(s=>s.table||s.vintage||'').join('; '),extracted:'2026-09-20',vintage:g.stage==='illustrative'?'fictional teaching example':g.stage==='plan'?'plan':g.stage==='unknown'?'documented structure':'outturn'}});
 host.querySelector('.ledger-unit').addEventListener('change',event=>{per100=event.target.value==='100';const url=new URL(location.href);if(per100)url.searchParams.set('unit','100');else url.searchParams.delete('unit');history.pushState(null,'',url);renderLedgers(active.code,active.lang);});
 host.querySelector('.ledger-play').addEventListener('click',()=>{
  const live=host.querySelector('.ledger-live');live.textContent=g.edges.filter(e=>e.value!==null).map(e=>`${t(by[e.from].label)} → ${t(by[e.to].label)}: ${amount(e.value)}`).join(' · ');
  if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const svg=host.querySelector('.ledger-svg');svg.querySelectorAll('.ledger-travelling').forEach(n=>n.remove());
  edges.filter(e=>e.value!==null).forEach(e=>{const group=document.createElementNS('http://www.w3.org/2000/svg','g');group.classList.add('ledger-travelling');const delay=by[e.from].row*.95;group.innerHTML=`<rect x="-65" y="-15" width="130" height="28" fill="#a8b63f"/><text text-anchor="middle" y="4" fill="#171918" font-size="12" font-family="Arial">${esc(amount(e.value))}</text><animateMotion begin="indefinite" dur=".9s" fill="freeze" path="${e.d}"/>`;group.setAttribute('visibility','hidden');svg.append(group);const motion=group.querySelector('animateMotion');motion.addEventListener('beginEvent',()=>group.setAttribute('visibility','visible'));motion.addEventListener('endEvent',()=>group.remove());motion.beginElementAt(delay);});
 });
}
export async function renderLedgers(code,lang){
 active={code,lang};const ticket=++generation;await ready;if(ticket!==generation)return;
 per100=new URLSearchParams(location.search).get('unit')==='100';
 const exampleHost=document.getElementById('fund-example-ledger');if(exampleHost)renderPlate(exampleHost,teachingExample,lang);
 for(const topic of ['school','health','pension','social']){
  const host=document.getElementById(`fund-${topic}-ledger`);if(!host)continue;
  if(loadError){host.innerHTML=`<p class="fund-reading" role="alert">${lang==='en'?'Numerical data could not be loaded. Reload this page to retry. The institutional routes and sources remain available below.':'Číselná data se nepodařilo načíst. Zkuste stránku obnovit. Institucionální cesty a zdroje zůstávají dostupné níže.'}</p>`;continue;}
  renderPlate(host,ledgers.find(g=>g.country===code&&g.topic===topic)||missingLedger(code,topic),lang);
 }
}
