/* Pure decoding rules shared by browser and tests. No interpolation or zero filling. */
(function(root){
'use strict';
function cell(raw){const text=String(raw??'').trim();const m=text.match(/^(-?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)(?:\s+(.*))?$/);return {value:m&&Number.isFinite(Number(m[1]))?Number(m[1]):null,flag:m?(m[2]||''):text.replace(/^:/,'').trim(),raw:text};}
function position(period){if(/^\d{4}$/.test(period))return +period;if(/^\d{4}-\d{2}$/.test(period))return +period.slice(0,4)+(+period.slice(5)-1)/12;if(/^\d{4}-Q[1-4]$/.test(period))return +period.slice(0,4)+(+period.slice(-1)-1)/4;if(/^\d{4}-S[12]$/.test(period))return +period.slice(0,4)+(+period.slice(-1)-1)/2;return NaN;}
function step(period){return /^\d{4}$/.test(period)?1:/-Q/.test(period)?1/4:/-S/.test(period)?1/2:1/12;}
const quantityUnits={'1000':'GT','1050':'CGT','1100':'carat','1200':'elements','1300':'tonnes carrying capacity','1400':'g','1500':'kg','1510':'kg Al2O3','1511':'kg B2O3','1512':'kg BaCO3','1513':'kg Cl','1514':'kg F','1515':'kg HCl','1516':'kg H2O2','1517':'kg KOH','1518':'kg K2O','1519':'kg K2CO3','1520':'kg N','1521':'kg NaOH','1522':'kg Na2CO3','1523':'kg Na2S2O5','1524':'kg PbO','1525':'kg P2O5','1526':'kg S','1527':'kg SO2','1528':'kg SiO2','1529':'kg TiO2','1530':'kg active substance','1531':'kg 90% dry','1532':'kg HF','1534':'kg H2SO4','1700':'km','1800':'kW','1900':'1000 kWh','2000':'litre','2100':'litre pure alcohol','2200':'m','2300':'m²','2400':'m³','2500':'pairs','2600':'items','2900':'TJ'};
const productFlags={APRODQNT:'APQNTFLAG',PRODVAL:'PVALFLAG',PRODQNT:'PQNTFLAG',OWNPRODVAL:'OWNVALFLAG',OWNPRODQNT:'OWNQNTFLAG',SCPRODVAL:'SCVALFLAG',SCPRODQNT:'SCQNTFLAG'};
function normalizeUnit(unit){const aliases={KG:'kg',M2:'m²',m2:'m²',M3:'m³',m3:'m³',L:'litre',l:'litre',PCE:'items',pce:'items'};return aliases[unit]||unit;}
function comparableCurrency(unit){return !/(?:NAC|NAT|PPS)/i.test(unit||'');}
function series(row,meta,rows){if(!row)return [];const dim=meta.dimension_order;const ind=dim.indexOf('indicators');const product=ind>=0;const indicator=product?row[0][ind]:null;const find=code=>rows.find(r=>r[0].every((v,i)=>i===ind?v===code:v===row[0][i]));const flagRow=product&&productFlags[indicator]?find(productFlags[indicator]):null;const unitRow=product?find('QNTUNIT'):null;const baseRow=product&&productFlags[indicator]?find(productFlags[indicator].replace('FLAG','BASE')):null;
return meta.periods.map((period,i)=>{const c=cell(row[1][i]);let flag=c.flag;const separate=flagRow?String(flagRow[1][i]||'').trim():'';if(separate&&![':', '-'].includes(separate))flag=[flag,separate].filter(Boolean).join(' ');if(/(?:^|[\s:])[CU](?:\s|$)/i.test(flag))c.value=null;let unit=dim.includes('unit')?row[0][dim.indexOf('unit')]:'';if(!unit){const metric=dim.includes('indic_sbs')?row[0][dim.indexOf('indic_sbs')]:dim.includes('indic')?row[0][dim.indexOf('indic')]:'';unit=/(?:_|-)PC$/.test(metric)?'PC':/_MEUR$/.test(metric)?'MIO_EUR':/_TEUR$/.test(metric)?'THS_EUR':/_EUR$/.test(metric)?'EUR':/_NR$/.test(metric)?'NR':/-BAL$/.test(metric)?'BAL':'';}if(product){if(indicator==='QNTUNIT'){unit='metadata';c.value=null;}else if(indicator.includes('VAL')&&!indicator.includes('FLAG')&&!indicator.includes('BASE'))unit='EUR';else if(indicator.includes('QNT')&&!indicator.includes('FLAG')&&!indicator.includes('BASE')){const rawUnit=unitRow?String(unitRow[1][i]||'').trim():'';const uc=cell(rawUnit).value;unit=quantityUnits[String(uc)]|| (rawUnit&&!rawUnit.startsWith(':')?rawUnit:'unknown quantity unit');}else {unit='metadata';c.value=null;}}return {...c,flag,period,unit:normalizeUnit(unit),roundingBase:baseRow?cell(baseRow[1][i]).value:null};});}
function segments(points){const out=[];let line=[];for(const p of points){const prev=line.at(-1);if(p.value===null||!Number.isFinite(position(p.period))){if(line.length)out.push(line);line=[];continue;}if(prev&&(position(p.period)-position(prev.period)>step(p.period)*1.1||p.unit!==prev.unit||/(^|\s)b($|\s)/i.test(p.flag))){out.push(line);line=[];}line.push(p);}if(line.length)out.push(line);return out;}
function yearRange(from,to,current){const a=Number(from),b=Number(to);return Number.isInteger(a)&&Number.isInteger(b)&&a>=2010&&b>=a&&b<=2100?{from:a,to:b}:{from:2010,to:current};}
const api={yearRange,normalizeUnit,comparableCurrency,cell,position,step,series,segments,quantityUnits};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.IndustrialData=api;
})(typeof window==='undefined'?globalThis:window);
