(() => {
  const assetRoot = document.currentScript?.src ? new URL(".", document.currentScript.src).href : "../../";
  const requestedLanguage = new URLSearchParams(location.search).get("lang");
  const initialLanguage = ["cs", "en"].includes(requestedLanguage) ? requestedLanguage : (document.documentElement.lang === "en" ? "en" : "cs");
  const state = {lang:initialLanguage,data:null,history:null,fx:null,currency:"CZK",historyYear:2025,benchmark:null,benchmarkExpanded:false,query:"",shown:24};
  const C = {
    cs:{viewEurope:"Evropa",viewCzechia:"Česko",eyebrow:"Česko · skutečnost 2025",title:"České obce.<br><em>Celý obraz.</em>",intro:"Celostátní výsledek, dlouhá řada velkých měst a detail každé z 6 254 obcí patří na jedno místo.",municipalities:"Obce",coverage:"úplné pokrytí · 2025",navInsights:"Co data říkají",navBenchmark:"Evropský benchmark",navExplore:"Prozkoumat",navMethod:"Jak data číst",insightsKicker:"01 / Celostátní pohled",insightsTitle:"Rok 2025 v jednom řezu.",insightsCopy:"Součty jsou po konsolidaci uvnitř každé obce. Nejsou konsolidované mezi obcemi navzájem.",exploreKicker:"03 / Navigátor",exploreTitle:"Od celku ke konkrétnímu městu.",exploreCopy:"Vyberte úplný adresář, dvacetiletou řadu velkých měst nebo fiskální profil Prahy mezi evropskými metropolemi.",directoryTitle:"Všechny obce",directoryCopy:"Filtrujte podle kraje, salda, výdajů na obyvatele nebo roku a otevřete detail obce.",openDirectory:"Otevřít adresář →",citiesTitle:"Velká města",citiesCopy:"Dvacet let příjmů, výdajů, výsledků hospodaření a stavu účtů.",openCities:"Otevřít města →",pragueTitle:"Praha mezi metropolemi",pragueCopy:"Rozpočet, saldo, obyvatelé a turistická přenocování ve srovnání hlavních měst EU.",openPrague:"Otevřít Prahu →",methodKicker:"04 / Přesné hranice",methodTitle:"Skutečnost, ne plán.",method1:"6 254 účetních jednotek",method1Copy:"Každá obec má vlastní profil a národní identifikátor IČO.",method2:"Výsledek po konsolidaci",method2Copy:"Příjmy minus výdaje po konsolidaci uvnitř účetní jednotky.",method3:"Dlouhá historie",method3Copy:"Úplný obecní adresář sahá do roku 2010; 27 velkých měst do roku 2006.",footer:"České obecní finance · Monitor státní pokladny",top:"Nahoru ↑",revenue:"Skutečné příjmy",expense:"Skutečné výdaje",result:"Výsledek hospodaření",cash:"Stav účtů",surplus:"přebytek",year:"2025 · nominální CZK",countryHomepage:"Stránka země"},
    en:{viewEurope:"Europe",viewCzechia:"Czechia",eyebrow:"Czechia · 2025 actuals",title:"Czech municipalities.<br><em>The full picture.</em>",intro:"The national result, a long series for large cities and the detail of all 6,254 municipalities belong in one place.",municipalities:"Municipalities",coverage:"full coverage · 2025",navInsights:"What the data says",navBenchmark:"European benchmark",navExplore:"Explore",navMethod:"How to read the data",insightsKicker:"01 / National view",insightsTitle:"2025 in one cut.",insightsCopy:"Totals are consolidated within each municipality. They are not consolidated between municipalities.",exploreKicker:"03 / Navigator",exploreTitle:"From the whole to a specific city.",exploreCopy:"Choose the complete directory, the twenty-year series for large cities, or Prague's fiscal profile among European capitals.",directoryTitle:"All municipalities",directoryCopy:"Filter by region, balance, spend per resident or year, then open a municipality detail.",openDirectory:"Open directory →",citiesTitle:"Large cities",citiesCopy:"Twenty years of revenue, expenditure, fiscal results and cash balances.",openCities:"Open cities →",pragueTitle:"Prague among capitals",pragueCopy:"Budget, balance, population and tourist nights compared with other EU capitals.",openPrague:"Open Prague →",methodKicker:"04 / Exact boundaries",methodTitle:"Actuals, not a plan.",method1:"6,254 reporting entities",method1Copy:"Every municipality has its own profile and national identifier.",method2:"Consolidated result",method2Copy:"Revenue minus expenditure after consolidation within the reporting entity.",method3:"Long history",method3Copy:"The complete municipality directory reaches back to 2010; 27 large cities to 2006.",footer:"Czech municipal finance · Treasury Monitor",top:"Back to top ↑",revenue:"Actual revenue",expense:"Actual expenditure",result:"Fiscal result",cash:"Cash balance",surplus:"surplus",year:"2025 · nominal CZK",countryHomepage:"Country homepage"}
  };
  Object.assign(C.cs,{title:"Rozpočty českých obcí",intro:"Celostátní souhrn, rozpočty 6 254 obcí a dvacetiletá řada velkých měst.",insightsTitle:"Souhrn za rok 2025",exploreKicker:"05 / Další pohledy",exploreTitle:"Otevřete pokročilý adresář nebo profil města",methodKicker:"06 / Metodika",methodTitle:"Skutečné výsledky za rok 2025"});
  Object.assign(C.en,{title:"Budgets of Czech municipalities",intro:"A national summary, budgets for 6,254 municipalities and a twenty-year series for large cities.",insightsTitle:"2025 summary",exploreKicker:"05 / More views",exploreTitle:"Open the advanced directory or a city profile",methodKicker:"06 / Methodology",methodTitle:"Actual results for 2025"});
  Object.assign(C.cs,{navRankings:"Rozpočtové žebříčky",navDirectory:"Najít obec",rankingsKicker:"02 / Rozpočtové žebříčky",rankingsTitle:"Kde tečou největší rozpočty.",rankingsCopy:"Skutečné výdaje ukazují velikost rozpočtu. Přebytek a schodek jsou příjmy minus výdaje za jediný rok, nikoli známka kvality vedení.",loadingBudgets:"Načítám rozpočtové žebříčky…",directoryKicker:"03 / Všech 6 254 obcí",inlineDirectoryTitle:"Najděte libovolnou obec.",inlineDirectoryCopy:"Hledejte podle názvu, IČO, okresu nebo kraje. Každý výsledek vede na úplný rozpočtový profil obce.",searchLabel:"Hledat obec",searchPlaceholder:"Název obce, IČO, okres nebo kraj…",clearSearch:"Vymazat",noResults:"Žádná obec neodpovídá hledání.",showMoreResults:"Zobrazit další výsledky",advancedFilters:"Potřebujete rok, kraj, saldo nebo řazení?",openAdvancedDirectory:"Otevřít pokročilý adresář →"});
  Object.assign(C.en,{navRankings:"Budget rankings",navDirectory:"Find a municipality",rankingsKicker:"02 / Budget rankings",rankingsTitle:"Where the largest budgets flow.",rankingsCopy:"Actual expenditure shows budget size. Surplus and deficit mean revenue minus expenditure for one year; neither is a score of management quality.",loadingBudgets:"Loading budget rankings…",directoryKicker:"03 / All 6,254 municipalities",inlineDirectoryTitle:"Find any municipality.",inlineDirectoryCopy:"Search by name, national ID, district or region. Every result opens the municipality's complete budget profile.",searchLabel:"Find a municipality",searchPlaceholder:"Municipality, national ID, district or region…",clearSearch:"Clear",noResults:"No municipality matches this search.",showMoreResults:"Show more results",advancedFilters:"Need a year, region, balance or sorting filter?",openAdvancedDirectory:"Open the advanced directory →"});
  Object.assign(C.cs,{insightsTitle:"Vývoj obecních rozpočtů",insightsCopy:"Příjmy, výdaje a stav účtů všech obcí od roku 2010. Částky lze zobrazit v korunách nebo přepočítat na eura.",historyYear:"Vybraný rok",currencyLabel:"Měna",historyNote:"Nominální hodnoty. Součty jsou konsolidované uvnitř každé obce, nikoli mezi obcemi navzájem.",municipalitiesSurplus:"Obce v přebytku"});
  Object.assign(C.en,{insightsTitle:"Municipal budgets over time",insightsCopy:"Revenue, expenditure and cash for all municipalities since 2010. Display the amounts in Czech koruna or convert them to euros.",historyYear:"Selected year",currencyLabel:"Currency",historyNote:"Nominal values. Totals are consolidated within each municipality, not between municipalities.",municipalitiesSurplus:"Municipalities in surplus"});
  const t=()=>C[state.lang], english=()=>state.lang==="en";
  const routes={bolivia:["Bolívie","Bolivia"],brazil:["Brazílie","Brazil"],chile:["Chile","Chile"],colombia:["Kolumbie","Colombia"],"costa-rica":["Kostarika","Costa Rica"],czechia:["Česko","Czechia"],denmark:["Dánsko","Denmark"],"el-salvador":["Salvador","El Salvador"],england:["Anglie","England"],finland:["Finsko","Finland"],france:["Francie","France"],georgia:["Gruzie","Georgia"],guatemala:["Guatemala","Guatemala"],italy:["Itálie","Italy"],japan:["Japonsko","Japan"],mexico:["Mexiko","Mexico"],netherlands:["Nizozemsko","Netherlands"],norway:["Norsko","Norway"],peru:["Peru","Peru"],poland:["Polsko","Poland"],"south-korea":["Jižní Korea","South Korea"],spain:["Španělsko","Spain"],sweden:["Švédsko","Sweden"],ukraine:["Ukrajina","Ukraine"]};
  const converted=(value)=>state.currency==="EUR"&&Number.isFinite(state.fx?.local_per_eur?.CZK)?value/state.fx.local_per_eur.CZK:value;
  const format=(value)=>new Intl.NumberFormat(english()?"en-GB":"cs-CZ",{style:"currency",currency:state.currency,notation:"compact",maximumFractionDigits:1}).format(converted(value));
  const integer=(value)=>new Intl.NumberFormat(english()?"en-GB":"cs-CZ",{maximumFractionDigits:0}).format(value);
  const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]);
  const normalized=(value)=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("cs");
  const municipalityHref=(entity)=>`${entity.seo.path}${english()?"?lang=en":""}`;

  function translate(){
    document.documentElement.lang=state.lang;
    document.title=english()?"Czech municipalities — Public Spending Data":"České obce — Public Spending Data";
    document.querySelector('meta[name="description"]')?.setAttribute("content",english()?"Insights, long-run city budgets and a complete directory of all 6,254 Czech municipalities.":"Přehledy, dlouhé rozpočtové řady měst a úplný adresář všech 6 254 českých obcí.");
    document.querySelectorAll("[data-copy]").forEach((element)=>{const value=t()[element.dataset.copy];if(value)element.innerHTML=value;});
    document.querySelectorAll("[data-placeholder]").forEach((element)=>{const value=t()[element.dataset.placeholder];if(value)element.placeholder=value;});
    document.querySelectorAll("[data-lang]").forEach((button)=>{const active=button.dataset.lang===state.lang;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));});
    document.querySelector(".municipality-lang-switch")?.setAttribute("aria-label",english()?"Language":"Jazyk");
    const countrySelect=document.querySelector("#municipality-country-switch");
    countrySelect?.setAttribute("aria-label",english()?"Municipality country page":"Stránka obcí podle země");
    document.querySelector('[data-view-link="europe"]')?.setAttribute("href",`../?lang=${state.lang}`);
    if(countrySelect){
      countrySelect.innerHTML=Object.entries(routes).map(([slug,names])=>`<option value="${slug}"${slug==="czechia"?" selected":""}>${names[english()?1:0]}</option>`).join("");
      const wrapper=countrySelect.closest("label");wrapper.classList.add("dynamic-country-picker");
      wrapper.querySelector(":scope > span")?.replaceChildren(english()?"Choose a country":"Vyberte zemi");
      let readout=wrapper.querySelector(".country-picker-readout");
      if(!readout){readout=document.createElement("span");readout.className="country-picker-readout";countrySelect.before(readout);}
      const count=state.data?.summary?.municipalities?.entity_count||6254;
      readout.innerHTML=`<img src="${assetRoot}assets/flags/cz.svg" alt=""><span><strong>${english()?"Czechia":"Česko"}</strong><small>${integer(count)} ${english()?"entities":"jednotek"} · 2025</small></span><b aria-hidden="true">⌄</b>`;
    }
    document.querySelectorAll('[data-destination="directory"]').forEach((link)=>link.setAttribute("href",`${assetRoot}cz/municipalities/?lang=${state.lang}`));
    document.querySelector('[data-destination="cities"]')?.setAttribute("href",`${assetRoot}cz/mesta/?lang=${state.lang}`);
    document.querySelector('[data-destination="prague"]')?.setAttribute("href",`${assetRoot}eu-capitals.html?lang=${state.lang}&city=prague-cz#city-detail`);
    if(state.data){renderInsights();renderBudgetRankings();renderInlineDirectory();}
    if(state.benchmark)renderMunicipalSizeBenchmark();
  }

  function renderInsights(){
    const summary=state.history?.annual?.find((row)=>row.year===state.historyYear)||state.data.summary.municipalities,result=summary.budget_balance;
    const year=summary.year||2025,entityCount=summary.entity_count||state.data.summary.municipalities.entity_count;
    document.querySelector("#cz-insight-grid").innerHTML=[{label:t().revenue,value:format(summary.revenue_actual)},{label:t().expense,value:format(summary.expense_actual)},{label:t().result,value:`${result>=0?"+":""}${format(result)}`,tone:result>=0?"positive":"negative"},{label:t().municipalitiesSurplus,value:integer(summary.surplus_count??state.data.municipalities.filter((entity)=>entity.amounts?.budget_balance>=0).length),note:Number.isFinite(summary.surplus_count)?`${(summary.surplus_count/entityCount*100).toLocaleString(english()?"en-GB":"cs-CZ",{maximumFractionDigits:1})} %`:""}].map((item)=>`<article><span>${item.label}</span><strong class="${item.tone||""}">${item.value}</strong><small>${item.note||`${year} · ${state.currency}`}</small></article>`).join("");
    document.querySelector("#cz-total-entities").textContent=new Intl.NumberFormat(english()?"en-GB":"cs-CZ").format(summary.entity_count);
    const yearSelect=document.querySelector("#cz-history-year");
    if(state.history&&yearSelect){yearSelect.innerHTML=[...state.history.annual].reverse().map((row)=>`<option value="${row.year}"${row.year===state.historyYear?" selected":""}>${row.year}</option>`).join("");yearSelect.setAttribute("aria-label",t().historyYear);}
    document.querySelectorAll("[data-currency]").forEach((button)=>button.setAttribute("aria-pressed",String(button.dataset.currency===state.currency)));
    const fxNote=document.querySelector("#cz-fx-note"),rate=state.fx?.local_per_eur?.CZK;
    if(fxNote)fxNote.textContent=Number.isFinite(rate)?(english()?`ECB reference rate · 18 Aug 2026 · EUR 1 = CZK ${rate}`:`Referenční kurz ECB · 18. 8. 2026 · 1 EUR = ${rate.toLocaleString("cs-CZ")} CZK`):"";
    renderHistoryChart();
  }

  function niceAxis(maximum,target=5){const rough=maximum/target,power=10**Math.floor(Math.log10(rough)),step=([1,2,2.5,5,10].find((candidate)=>candidate>=rough/power)||10)*power,max=Math.ceil(maximum/step)*step;return {max,ticks:Array.from({length:Math.round(max/step)+1},(_,index)=>index*step)};}

  function renderHistoryChart(){
    const host=document.querySelector("#cz-national-history-chart");if(!host||!state.history)return;
    const rows=state.history.annual,width=1120,height=430,left=78,right=30,top=30,bottom=58;
    const values=rows.flatMap((row)=>[row.revenue_actual,row.expense_actual,row.cash_current]).map(converted),axis=niceAxis(Math.max(...values)*1.04);
    const x=(index)=>left+(index+.5)*((width-left-right)/rows.length),y=(value)=>top+(axis.max-converted(value))/axis.max*(height-top-bottom);
    const unit=state.currency==="EUR"?(english()?"EUR bn":"mld. EUR"):(english()?"CZK bn":"mld. Kč");
    const number=new Intl.NumberFormat(english()?"en-GB":"cs-CZ",{maximumFractionDigits:0});
    const grid=axis.ticks.map((value)=>`<line x1="${left}" x2="${width-right}" y1="${y(state.currency==="EUR"?value*(state.fx?.local_per_eur?.CZK||1):value)}" y2="${y(state.currency==="EUR"?value*(state.fx?.local_per_eur?.CZK||1):value)}"/><text x="${left-12}" y="${y(state.currency==="EUR"?value*(state.fx?.local_per_eur?.CZK||1):value)+4}" text-anchor="end">${number.format(value/1e9)}</text>`).join("");
    const line=(field)=>rows.map((row,index)=>`${index?"L":"M"}${x(index).toFixed(1)},${y(row[field]).toFixed(1)}`).join(" ");
    const labels=rows.map((row,index)=>index%2===0||row.year===state.historyYear||index===rows.length-1?`<text x="${x(index)}" y="${height-24}" text-anchor="middle" class="${row.year===state.historyYear?"selected-label":""}">${row.year}</text>`:"").join("");
    const selectedIndex=rows.findIndex((row)=>row.year===state.historyYear),selected=rows[selectedIndex];
    const hits=rows.map((row,index)=>`<circle class="year-hit" data-history-year="${row.year}" cx="${x(index)}" cy="${y(row.revenue_actual)}" r="17"><title>${row.year} · ${format(row.revenue_actual)}</title></circle>`).join("");
    host.setAttribute("aria-label",english()?"Nationwide municipal revenue, expenditure and cash from 2010 to 2025":"Celostátní vývoj obecních příjmů, výdajů a stavu účtů 2010 až 2025");
    const chartLabel=english()?"Nationwide municipal revenue, expenditure and cash from 2010 to 2025":"Celostátní vývoj obecních příjmů, výdajů a stavu účtů 2010 až 2025";
    host.innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${chartLabel}"><g class="history-grid">${grid}${labels}<text x="18" y="22">${unit}</text></g><line class="selected-year" x1="${x(selectedIndex)}" x2="${x(selectedIndex)}" y1="${top}" y2="${height-bottom}"/><path class="history-line revenue-line" d="${line("revenue_actual")}"/><path class="history-line expense-line" d="${line("expense_actual")}"/><path class="history-line cash-line" d="${line("cash_current")}"/>${hits}<circle class="year-dot" cx="${x(selectedIndex)}" cy="${y(selected.revenue_actual)}" r="6"/></svg>`;
  }

  function rankedRows(title,subtitle,entities,field,tone){
    const maximum=Math.max(...entities.map((entity)=>Math.abs(entity.amounts[field])),1);
    return `<article class="municipal-ranking-card ${tone}"><header><span>${title}</span><small>${subtitle}</small></header><ol>${entities.map((entity,index)=>{const value=entity.amounts[field],href=municipalityHref(entity);return `<li><a href="${escapeHtml(href)}"><span class="municipal-rank-number">${String(index+1).padStart(2,"0")}</span><span class="municipal-rank-name"><strong>${escapeHtml(entity.short_name)}</strong><small>${escapeHtml(entity.territory.region_name)}</small></span><i><b style="width:${(Math.abs(value)/maximum*100).toFixed(2)}%"></b></i><em>${field==="budget_balance"&&value>0?"+":""}${format(value)}</em></a></li>`;}).join("")}</ol></article>`;
  }

  function renderBudgetRankings(){
    const entities=state.data.municipalities.filter((entity)=>Number.isFinite(entity.amounts?.expense_actual)&&Number.isFinite(entity.amounts?.budget_balance));
    const largest=[...entities].sort((a,b)=>b.amounts.expense_actual-a.amounts.expense_actual).slice(0,8);
    const surplus=[...entities].filter((entity)=>entity.amounts.budget_balance>=0).sort((a,b)=>b.amounts.budget_balance-a.amounts.budget_balance).slice(0,8);
    const deficit=[...entities].filter((entity)=>entity.amounts.budget_balance<0).sort((a,b)=>a.amounts.budget_balance-b.amounts.budget_balance).slice(0,8);
    const surplusCount=entities.filter((entity)=>entity.amounts.budget_balance>=0).length,deficitCount=entities.length-surplusCount;
    const share=decimal=>`${decimal.toLocaleString(english()?"en-GB":"cs-CZ",{maximumFractionDigits:1})} %`;
    document.querySelector("#municipal-balance-split").innerHTML=`<article><span>${english()?"Municipalities in surplus":"Obce v přebytku"}</span><strong>${integer(surplusCount)}</strong><small>${share(surplusCount/entities.length*100)}</small></article><article><span>${english()?"Municipalities in deficit":"Obce ve schodku"}</span><strong>${integer(deficitCount)}</strong><small>${share(deficitCount/entities.length*100)}</small></article><p>${english()?"Together, all municipalities finished 2025 at":"Všechny obce dohromady uzavřely rok 2025 výsledkem"} <strong>${state.data.summary.municipalities.budget_balance>=0?"+":""}${format(state.data.summary.municipalities.budget_balance)}</strong>.</p>`;
    const labels=english()?{largest:"Largest budgets",largestSub:"Actual expenditure · 2025",surplus:"Largest surpluses",surplusSub:"Revenue minus expenditure · 2025",deficit:"Largest deficits",deficitSub:"Revenue minus expenditure · 2025"}:{largest:"Největší rozpočty",largestSub:"Skutečné výdaje · 2025",surplus:"Největší přebytky",surplusSub:"Příjmy minus výdaje · 2025",deficit:"Největší schodky",deficitSub:"Příjmy minus výdaje · 2025"};
    document.querySelector("#municipal-ranking-grid").innerHTML=rankedRows(labels.largest,labels.largestSub,largest,"expense_actual","scale")+rankedRows(labels.surplus,labels.surplusSub,surplus,"budget_balance","surplus")+rankedRows(labels.deficit,labels.deficitSub,deficit,"budget_balance","deficit");
  }

  function searchedMunicipalities(){
    const query=normalized(state.query.trim());
    const list=state.data.municipalities.filter((entity)=>!query||normalized(`${entity.short_name} ${entity.name} ${entity.national_id} ${entity.territory.district_name} ${entity.territory.region_name}`).includes(query));
    if(!query)return list.sort((a,b)=>b.amounts.expense_actual-a.amounts.expense_actual);
    const relevance=(entity)=>{const shortName=normalized(entity.short_name),fullName=normalized(entity.name),id=normalized(entity.national_id),district=normalized(entity.territory.district_name),region=normalized(entity.territory.region_name);if(id===query||shortName===query)return 0;if(shortName.startsWith(query))return 1;if(shortName.includes(query))return 2;if(fullName.includes(query))return 3;if(district===query)return 4;if(district.includes(query))return 5;if(region.includes(query))return 6;return 7;};
    return list.sort((a,b)=>relevance(a)-relevance(b)||b.amounts.expense_actual-a.amounts.expense_actual||a.short_name.localeCompare(b.short_name,"cs"));
  }

  function inlineCard(entity){
    const balance=entity.amounts.budget_balance;
    return `<article><header><span>${escapeHtml(entity.territory.region_name)}</span><small>IČO ${escapeHtml(entity.national_id)}</small></header><h3><a href="${escapeHtml(municipalityHref(entity))}">${escapeHtml(entity.short_name)}</a></h3><dl><div><dt>${english()?"Revenue":"Příjmy"}</dt><dd>${format(entity.amounts.revenue_actual)}</dd></div><div><dt>${english()?"Expenditure":"Výdaje"}</dt><dd>${format(entity.amounts.expense_actual)}</dd></div><div><dt>${english()?"Balance":"Výsledek"}</dt><dd class="${balance>=0?"positive":"negative"}">${balance>0?"+":""}${format(balance)}</dd></div></dl><a class="municipal-inline-profile" href="${escapeHtml(municipalityHref(entity))}">${english()?"Profile and data":"Profil a data"} →</a></article>`;
  }

  function renderInlineDirectory(){
    const results=searchedMunicipalities(),visible=results.slice(0,state.shown);
    const count=document.querySelector("#municipal-inline-count"),grid=document.querySelector("#municipal-inline-results"),empty=document.querySelector("#municipal-inline-empty"),more=document.querySelector("#municipal-inline-more");
    count.textContent=state.query?(english()?`${results.length.toLocaleString("en-GB")} matches across 6,254 municipalities`:`${results.length.toLocaleString("cs-CZ")} výsledků z 6 254 obcí`):(english()?"Showing the largest budgets first · search covers all 6,254 municipalities":"Nejprve největší rozpočty · hledání prochází všech 6 254 obcí");
    grid.innerHTML=visible.map(inlineCard).join("");empty.hidden=results.length>0;more.hidden=state.shown>=results.length;
  }

  function renderMunicipalSizeBenchmark(){
    const dataset=state.benchmark,expanded=state.benchmarkExpanded,czech=dataset.countries.find((country)=>country.iso3==="CZE");
    const regular=dataset.countries.filter((country)=>country.mean<70000),visible=expanded?regular:regular.slice(0,13),outliers=dataset.countries.filter((country)=>country.mean>=70000);
    const width=1080,left=178,right=100,top=54,rowHeight=34,bottom=34,height=top+visible.length*rowHeight+bottom,max=70000,x=(value)=>left+value/max*(width-left-right);
    const axis=[0,10000,20000,30000,40000,50000,60000,70000].map((value)=>`<g><line x1="${x(value)}" x2="${x(value)}" y1="${top-22}" y2="${height-bottom+4}"/><text x="${x(value)}" y="${top-31}" text-anchor="middle">${value?integer(value/1000)+(english()?"k":" tis."):"0"}</text></g>`).join("");
    const rows=visible.map((country,index)=>{const y=top+index*rowHeight+rowHeight/2,active=country.iso3==="CZE",name=english()?country.name_en:country.name_cs;return `<g class="municipal-size-row${active?" active":""}"><text class="municipal-size-rank" x="0" y="${y+4}">${String(index+1).padStart(2,"0")}</text><text class="municipal-size-name" x="30" y="${y+4}">${escapeHtml(name)}</text><rect class="municipal-size-track" x="${left}" y="${y-6}" width="${width-left-right}" height="12"/><rect class="municipal-size-mean" x="${left}" y="${y-6}" width="${Math.max(2,x(country.mean)-left)}" height="12"><title>${escapeHtml(name)} · ${integer(country.mean)} ${english()?"people per municipality":"obyvatel na obec"}</title></rect><circle class="municipal-size-median" cx="${x(country.median)}" cy="${y}" r="5"><title>${english()?"Median":"Medián"}: ${integer(country.median)}</title></circle><text class="municipal-size-value" x="${width-2}" y="${y+4}" text-anchor="end">${integer(country.mean)}</text></g>`;}).join("");
    const copy=english()?{kicker:`02 / European benchmark · OECD ${dataset.reference_year}`,title:"Czechia has Europe's smallest municipalities.",intro:"The average municipality has 1,741 people. The median is only 453 — a clearer picture of how fragmented the system really is.",mean:"People per municipality",median:"Median municipality",small:"Municipalities under 2,000",eu:"Of the EU27 average",meanLegend:"Average population",medianLegend:"Median",euLegend:"EU27 average",more:"Show all countries",less:"Show compact view",note:"A smaller value means a more fragmented municipal structure. This indicator does not measure staff numbers, service quality or administrative efficiency. Competences differ across countries.",source:"Source: OECD · Municipal level government by population size",outlier:"people per municipality · outside chart scale"}:{kicker:`02 / Evropský benchmark · OECD ${dataset.reference_year}`,title:"Česko má nejmenší obce v Evropě.",intro:"Průměrná obec má 1 741 obyvatel. Medián je jen 453 — a ukazuje ještě přesněji, jak roztříštěný český systém je.",mean:"Obyvatel na obec",median:"Medián obce",small:"Obcí pod 2 000 obyvatel",eu:"Průměru EU27",meanLegend:"Průměrný počet obyvatel",medianLegend:"Medián",euLegend:"Průměr EU27",more:"Zobrazit všechny země",less:"Zobrazit kratší výběr",note:"Nižší hodnota znamená roztříštěnější obecní strukturu. Ukazatel neměří počet úředníků, kvalitu služeb ani efektivitu správy. Kompetence obcí se mezi zeměmi liší.",source:"Zdroj: OECD · Municipal level government by population size",outlier:"obyvatel na obec · mimo měřítko grafu"};
    copy.kicker=copy.kicker.replace(/^02 /,"04 ");
    const cards=outliers.map((country)=>`<article><span>${escapeHtml(english()?country.name_en:country.name_cs)}</span><strong>${integer(country.mean)}</strong><small>${copy.outlier}</small></article>`).join("");
    document.querySelector("#municipality-size").innerHTML=`<div class="municipal-size-heading"><div><span class="kicker">${copy.kicker}</span><h2>${copy.title}</h2></div><p>${copy.intro}</p></div><div class="municipal-size-kpis"><article><span>${copy.mean}</span><strong>${integer(czech.mean)}</strong><small>№ 1 / ${dataset.countries.length}</small></article><article><span>${copy.median}</span><strong>${integer(czech.median)}</strong><small>${english()?"people":"obyvatel"}</small></article><article><span>${copy.small}</span><strong>${integer(czech.under_2000_pct)} %</strong><small>${english()?"of all municipalities":"všech obcí"}</small></article><article><span>${copy.eu}</span><strong>${integer(czech.mean/dataset.eu27_mean*100)} %</strong><small>EU27 · ${integer(dataset.eu27_mean)}</small></article></div><div class="municipal-size-chart-card"><div class="municipal-size-legend"><span><i class="mean-key"></i>${copy.meanLegend}</span><span><i class="median-key"></i>${copy.medianLegend}</span><span><i class="eu-key"></i>${copy.euLegend}</span></div><div class="municipal-size-chart-scroll" tabindex="0" role="region" aria-label="${escapeHtml(copy.title)}"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeHtml(copy.title)}"><g class="municipal-size-axis">${axis}</g><line class="municipal-size-eu" x1="${x(dataset.eu27_mean)}" x2="${x(dataset.eu27_mean)}" y1="${top-22}" y2="${height-bottom+4}"/>${rows}</svg></div><button class="municipal-size-toggle" type="button">${expanded?copy.less:copy.more}</button></div><div class="municipal-size-outliers">${cards}</div><div class="municipal-size-method"><p>${copy.note}</p><a href="${escapeHtml(dataset.source.explorer_url)}" target="_blank" rel="noopener">${copy.source} ↗</a></div>`;
    document.querySelector(".municipal-size-toggle")?.addEventListener("click",()=>{state.benchmarkExpanded=!state.benchmarkExpanded;renderMunicipalSizeBenchmark();});
  }

  document.querySelectorAll("[data-lang]").forEach((button)=>button.onclick=()=>{state.lang=button.dataset.lang;localStorage.setItem("psd-lang",state.lang);history.replaceState(null,"",`?lang=${state.lang}${location.hash}`);translate();});
  document.querySelector("#municipality-country-switch")?.addEventListener("change",(event)=>{if(event.target.value!=="czechia")location.href=`../${event.target.value}/?lang=${state.lang}`;});
  document.querySelector("#municipal-inline-search")?.addEventListener("input",(event)=>{if(event.target.id!=="municipal-inline-query")return;state.query=event.target.value;state.shown=24;if(state.data)renderInlineDirectory();});
  document.querySelector("#municipal-inline-search")?.addEventListener("reset",()=>setTimeout(()=>{state.query="";state.shown=24;if(state.data)renderInlineDirectory();}));
  document.querySelector("#municipal-inline-more")?.addEventListener("click",()=>{state.shown+=24;if(state.data)renderInlineDirectory();});
  document.querySelector("#cz-history-year")?.addEventListener("change",(event)=>{state.historyYear=Number(event.target.value);renderInsights();});
  document.querySelector("#cz-national-history-chart")?.addEventListener("click",(event)=>{const hit=event.target.closest("[data-history-year]");if(!hit)return;state.historyYear=Number(hit.dataset.historyYear);renderInsights();});
  document.querySelectorAll("[data-currency]").forEach((button)=>button.addEventListener("click",()=>{state.currency=button.dataset.currency;try{localStorage.setItem("psd-municipal-currency",state.currency);}catch{}translate();}));
  Promise.all([fetch(`${assetRoot}data/municipal-snapshot.v1.json`).then((response)=>response.json()),fetch(`${assetRoot}data/municipal-history-directory.v1.json`).then((response)=>response.json()),fetch(`${assetRoot}data/country-spending-comparison.v1.json`).then((response)=>response.json())]).then(([data,historyData,spending])=>{state.data=data;state.history=historyData;state.fx=spending.fx;translate();}).catch((error)=>{console.error(error);document.querySelector("#cz-insight-grid").innerHTML="<p>Data could not be loaded.</p>";});
  fetch(`${assetRoot}data/municipal-size-benchmark.v1.json`).then((response)=>{if(!response.ok)throw new Error(`Municipal size benchmark returned ${response.status}`);return response.json();}).then((data)=>{state.benchmark=data;renderMunicipalSizeBenchmark();}).catch((error)=>{console.error(error);document.querySelector("#municipality-size").innerHTML=`<p class="benchmark-loading">${english()?"European benchmark could not be loaded.":"Evropský benchmark se nepodařilo načíst."}</p>`;});
  translate();
})();
