(()=>{
  const assetRoot=document.currentScript?.src?new URL(".",document.currentScript.src).href:"../../";
  const state={lang:new URLSearchParams(location.search).get("lang")==="en"?"en":"cs",data:null,country:null,query:"",year:"all",shown:48};
  const code=document.body.dataset.countryCode;
  const slug=document.body.dataset.countrySlug;
  const slugs={CZE:"czechia",POL:"poland",DNK:"denmark",FRA:"france",SWE:"sweden",GBR:"england",UKR:"ukraine"};
  const profiles={
    POL:{cs:{eyebrow:"Polsko · gminy",title:"Polské gminy.<br><em>Jeden celostátní adresář.</em>",intro:"Roční výkazy Rb-27S a Rb-28S drží místní příjmy a výdaje ve společném národním systému.",insights:"Co polská vrstva skutečně pokrývá.",copy:"Adresář je úplný; zveřejněná fáze a rozsah ukazují, které hodnoty lze později srovnávat.",note:"Polská jednotka",noteCopy:"Základní místní jednotkou je gmina. Tato vrstva drží všechny gminy z ročních výkazů."},en:{eyebrow:"Poland · gminas",title:"Polish gminas.<br><em>One national directory.</em>",intro:"Annual Rb-27S and Rb-28S returns keep local revenue and expenditure in one national system.",insights:"What the Polish layer actually covers.",copy:"The directory is complete; published stages and scope show which values can later be compared.",note:"The Polish unit",noteCopy:"The basic local unit is the gmina. This layer keeps every gmina from the annual returns."}},
    DNK:{cs:{eyebrow:"Dánsko · 98 obcí",title:"Dánské obce.<br><em>Rozpočet i závěrečný účet.</em>",intro:"Malý počet velkých obcí a jednotný StatBank dávají Dánsku mimořádně čitelnou místní vrstvu.",insights:"Celá země v 98 řádcích.",copy:"Rozpočty a skutečné účty jsou oddělené, takže plán nemusí předstírat výsledek.",note:"Dánský model",noteCopy:"Po reformě místní správy tvoří celou obecní úroveň 98 obcí; všechny jsou v adresáři."},en:{eyebrow:"Denmark · 98 municipalities",title:"Danish municipalities.<br><em>Budget and final accounts.</em>",intro:"A small number of large municipalities and one StatBank make Denmark's local layer unusually legible.",insights:"The whole country in 98 rows.",copy:"Budgets and actual accounts remain separate, so a plan never has to masquerade as an outcome.",note:"The Danish model",noteCopy:"After local-government reform, 98 municipalities form the entire municipal tier; all are in the directory."}},
    FRA:{cs:{eyebrow:"Francie · communes",title:"Francouzské obce.<br><em>Největší adresář.</em>",intro:"Desítky tisíc communes vytvářejí nejjemnější obecní mapu v této evropské vrstvě.",insights:"Rozsah, který mění měřítko.",copy:"Hlavní i vedlejší rozpočty a funkční detail se řídí tím, co konkrétní obec vykazuje.",note:"Francouzský rozsah",noteCopy:"Vrstva zahrnuje všechny communes. Funkční členění je dostupné jen tam, kde jej obec vykazuje."},en:{eyebrow:"France · communes",title:"French communes.<br><em>The largest directory.</em>",intro:"Tens of thousands of communes create the finest-grained municipal map in this European layer.",insights:"Coverage that changes the scale.",copy:"Main and supplementary budgets, and functional detail, follow what each commune actually reports.",note:"French scope",noteCopy:"The layer includes every commune. Functional detail is present only where the commune reports it."}},
    SWE:{cs:{eyebrow:"Švédsko · 290 kommuner",title:"Švédské obce.<br><em>Náklady, výnosy, rozvaha.</em>",intro:"Všech 290 obcí je v jedné vrstvě postavené na obecních účtech švédské statistiky.",insights:"Účetní pohled na místní stát.",copy:"Švédská data přinášejí náklady, výnosy a rozvahu; pojmy proto nepřekládáme automaticky na rozpočtové příjmy a výdaje.",note:"Švédský rozsah",noteCopy:"Úplný census 290 kommuner vychází z národních obecních účtů SCB."},en:{eyebrow:"Sweden · 290 kommuner",title:"Swedish municipalities.<br><em>Costs, income, balance sheet.</em>",intro:"All 290 municipalities sit in one layer built from Statistics Sweden's municipal accounts.",insights:"An accounting view of local government.",copy:"Swedish data exposes costs, income and balance sheets; those terms are not silently relabelled as budget revenue and expenditure.",note:"Swedish scope",noteCopy:"The complete census of 290 kommuner comes from SCB's national municipal accounts."}},
    GBR:{cs:{eyebrow:"Anglie · councils",title:"Anglické místní úřady.<br><em>Výsledky bez skrytých sborů.</em>",intro:"Adresář spojuje odevzdané výkazy councils a GLA, ale vědomě odděluje policii a hasiče.",insights:"Jasná hranice anglické vrstvy.",copy:"Čísla jsou skutečné výsledky, nikoli schválené plány; rozsah místních orgánů zůstává explicitní.",note:"Co je vyloučeno",noteCopy:"Policejní a hasičské orgány nejsou obecní jednotky této vrstvy a nejsou započítané."},en:{eyebrow:"England · councils",title:"English local authorities.<br><em>Outturn without hidden bodies.</em>",intro:"The directory joins submitted council and GLA returns while deliberately separating police and fire bodies.",insights:"A clear boundary for the English layer.",copy:"The figures are actual outturns, not approved plans; the scope of local authorities remains explicit.",note:"What is excluded",noteCopy:"Police and fire authorities are outside this municipal layer and are not counted."}},
    UKR:{cs:{eyebrow:"Ukrajina · 1 467 územních komunit",title:"Ukrajinské komunity.<br><em>Dva kompletní roky.</em>",intro:"Rozpočty všech aktivních územních komunit včetně Kyjeva pocházejí z otevřeného rozpočtového API za roky 2024 a 2025.",insights:"4,12 milionu ověřených rozpočtových řádků.",copy:"Příjmy a výdaje zachovávají původní ukrajinskou programovou a ekonomickou klasifikaci i rozpočtovou fázi.",note:"Ukrajinská hranice",noteCopy:"Vrstva drží územní komunity včetně Kyjeva; oblasti a rajóny jsou mimo obecní úroveň."},en:{eyebrow:"Ukraine · 1,467 territorial communities",title:"Ukrainian communities.<br><em>Two complete years.</em>",intro:"Budgets for every active territorial community, including Kyiv, come from the open-budget API for 2024 and 2025.",insights:"4.12 million validated budget lines.",copy:"Revenue and expenditure preserve the original Ukrainian programme and economic classifications and budget stage.",note:"Ukrainian boundary",noteCopy:"The layer keeps territorial communities including Kyiv; oblast and district budgets sit outside the municipal tier."}}
  };
  const copy={cs:{viewEurope:"Evropa",countryHomepage:"Stránka země",covered:"Pokryté místní jednotky",navInsights:"Co data říkají",navDirectory:"Adresář",navContext:"Kontext a zdroj",insightsKicker:"01 / Datový profil",directoryKicker:"02 / Místní úroveň",directoryTitle:"Najděte konkrétní obec.",search:"Hledat",searchPlaceholder:"Název nebo národní kód…",year:"Rok",reset:"Vymazat filtry",more:"Načíst další",contextKicker:"03 / Co je uvnitř",contextTitle:"Rozsah zůstává viditelný.",contextCopy:"Národní zdroj a účetní hranice jsou součástí výsledku, ne poznámka pod čarou.",top:"Nahoru ↑",entities:"jednotek",shown:"zobrazeno",years:"dostupné roky",stages:"rozpočtové fáze",measures:"účetní oblasti",source:"Otevřít národní zdroj ↗",capital:"Hlavní město",capitalLink:"Otevřít fiskální profil →",noCapital:"Samostatný fiskální profil hlavního města zatím v evropské vrstvě není.",detail:"Detail →",complete:"Úplné pokrytí",partial:"Částečné pokrytí",downloading:"Probíhá import",actual:"skutečnost",enacted:"schválený",revised:"upravený",revenue:"příjmy",expenditure:"výdaje",balance:"rozvaha",cash:"stav účtů",financing:"financování"},en:{viewEurope:"Europe",countryHomepage:"Country homepage",covered:"Covered local units",navInsights:"What the data says",navDirectory:"Directory",navContext:"Context and source",insightsKicker:"01 / Data profile",directoryKicker:"02 / Local tier",directoryTitle:"Find a specific municipality.",search:"Search",searchPlaceholder:"Name or national code…",year:"Year",reset:"Reset filters",more:"Load more",contextKicker:"03 / What is inside",contextTitle:"Scope stays visible.",contextCopy:"The national source and accounting boundary are part of the result, not a footnote.",top:"Back to top ↑",entities:"entities",shown:"shown",years:"available years",stages:"budget stages",measures:"accounting areas",source:"Open national source ↗",capital:"Capital city",capitalLink:"Open fiscal profile →",noCapital:"A separate fiscal profile for the capital is not yet in the European layer.",detail:"Detail →",complete:"Full coverage",partial:"Partial coverage",downloading:"Import running",actual:"actual",enacted:"approved",revised:"revised",revenue:"revenue",expenditure:"expenditure",balance:"balance sheet",cash:"cash",financing:"financing"}};
  const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const t=()=>copy[state.lang], p=()=>profiles[code][state.lang], fmt=n=>new Intl.NumberFormat(state.lang==="en"?"en-GB":"cs-CZ").format(n);
  function translate(){
    document.documentElement.lang=state.lang;
    document.querySelectorAll("[data-copy]").forEach(el=>{if(t()[el.dataset.copy])el.textContent=t()[el.dataset.copy];});
    document.querySelectorAll("[data-placeholder]").forEach(el=>el.placeholder=t()[el.dataset.placeholder]);
    document.querySelectorAll("[data-lang]").forEach(el=>{const active=el.dataset.lang===state.lang;el.classList.toggle("active",active);el.setAttribute("aria-pressed",String(active));});
    $(".municipality-lang-switch")?.setAttribute("aria-label",state.lang==="en"?"Language":"Jazyk");
    $("#municipality-country-switch")?.setAttribute("aria-label",state.lang==="en"?"Municipality country page":"Stránka obcí podle země");
    $('[data-view-link="europe"]').href=`../?lang=${state.lang}`;
    if(state.data)render();
  }
  function renderSwitch(){
    $("#municipality-country-switch").innerHTML=state.data.countries.map(c=>`<option value="${slugs[c.code]}"${c.code===code?" selected":""}>${esc(c[`name_${state.lang}`])}</option>`).join("");
  }
  function render(){
    const c=state.country, profile=p();
    renderSwitch(); $("#country-eyebrow").textContent=profile.eyebrow; $("#country-title").innerHTML=profile.title; $("#country-intro").textContent=profile.intro;
    $("#country-total").textContent=fmt(c.directory_count); $("#country-coverage").textContent=`${t()[c.status]} · ${c.years.join(" + ")}`;
    $("#insights-title").textContent=profile.insights; $("#insights-copy").textContent=profile.copy;
    $("#country-insight-grid").innerHTML=[{n:fmt(c.directory_count),h:t().entities,p:c[`coverage_${state.lang}`]},{n:c.years.join(" + "),h:t().years,p:c.years.length>1?`${c.years.length} ${t().years}`:t().years},{n:String(c.stages.length),h:t().stages,p:c.stages.map(x=>t()[x]).join(" · ")},{n:String(c.measures.length),h:t().measures,p:c.measures.map(x=>t()[x]).join(" · ")}].map(x=>`<article><strong>${esc(x.n)}</strong><h3>${esc(x.h)}</h3><p>${esc(x.p)}</p></article>`).join("");
    const years=[...c.years].sort((a,b)=>b-a); $("#country-year-filter").innerHTML=`<option value="all">${years.join(" + ")}</option>`+years.map(y=>`<option>${y}</option>`).join(""); $("#country-year-filter").value=state.year;
    const capitalIds={POL:"warsaw-pl",DNK:"copenhagen-dk",FRA:"paris-fr",SWE:"stockholm-se",GBR:"london-gb"}; const capital=state.capitals?.find(x=>x.city_id===capitalIds[code]);
    $("#country-context-grid").innerHTML=`<article><img class="country-flag" src="${assetRoot}assets/flags/${c.alpha2.toLowerCase()}.svg" alt=""><span class="kicker">${esc(c.code)} · ${esc(c.currency)}</span><h3>${esc(profile.note)}</h3><p>${esc(profile.noteCopy)}</p><a href="${esc(c.source)}" target="_blank" rel="noopener">${t().source}</a></article><article><span class="kicker">${t().capital}</span><h3>${esc(capital?.city||"—")}</h3><p>${esc(capital?capital.scope:t().noCapital)}</p>${capital?`<a href="${assetRoot}eu-capitals.html?lang=${state.lang}&city=${capital.city_id}#city-detail">${t().capitalLink}</a>`:""}</article>`;
    $("#country-footer").textContent=`${c[`name_${state.lang}`]} · ${c[`coverage_${state.lang}`]}`; renderDirectory();
  }
  function filtered(){const q=state.query.trim().toLocaleLowerCase();return state.data.entities.filter(e=>e.country===code&&(state.year==="all"||e.years.includes(Number(state.year)))&&(!q||`${e.name} ${e.code} ${e.region||""}`.toLocaleLowerCase().includes(q)));}
  function renderDirectory(){const result=filtered();$("#country-directory-count").textContent=`${fmt(Math.min(result.length,state.shown))} ${t().shown} · ${fmt(result.length)} ${t().entities}`;$("#country-municipality-grid").innerHTML=result.slice(0,state.shown).map(e=>`<article class="municipality-card"><header><img src="${assetRoot}assets/flags/${state.country.alpha2.toLowerCase()}.svg" alt=""><span>${esc(state.country[`name_${state.lang}`])}</span><small>${esc(e.code)}</small></header><h3>${esc(e.name)}</h3><p>${esc(e.region||state.country[`coverage_${state.lang}`])}</p><footer>${e.years.map(y=>`<b>${y}</b>`).join("")}${e.url?`<a href="${esc(e.url)}?lang=${state.lang}">${t().detail}</a>`:""}</footer></article>`).join("");$("#country-load-more").hidden=state.shown>=result.length;}
  function bind(){
    document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;history.replaceState(null,"",`?lang=${state.lang}${location.hash}`);translate();});
    $("#municipality-country-switch").onchange=e=>location.href=`../${e.target.value}/?lang=${state.lang}`;
    $("#country-municipality-search").oninput=e=>{state.query=e.target.value;state.shown=48;renderDirectory();};
    $("#country-year-filter").onchange=e=>{state.year=e.target.value;state.shown=48;renderDirectory();};
    $("#country-reset").onclick=()=>{state.query="";state.year="all";state.shown=48;$("#country-municipality-search").value="";$("#country-year-filter").value="all";renderDirectory();};
    $("#country-load-more").onclick=()=>{state.shown+=48;renderDirectory();};
  }
  Promise.all([fetch(`${assetRoot}data/international-municipalities.v1.json`).then(r=>r.json()),fetch(`${assetRoot}data/eu-capital-budgets.v1.json`).then(r=>r.json())]).then(([data,capitals])=>{state.data=data;state.capitals=capitals.cities;state.country=data.countries.find(c=>c.code===code);if(!state.country||!profiles[code])throw new Error(`Unknown municipality country ${code}`);translate();bind();}).catch(error=>{console.error(error);$("#country-title").textContent="Data could not be loaded.";});
})();
