(() => {
  const assetRoot = document.currentScript?.src ? new URL(".", document.currentScript.src).href : "../../";
  const requestedLanguage = new URLSearchParams(location.search).get("lang");
  const initialLanguage = ["cs", "en"].includes(requestedLanguage) ? requestedLanguage : (document.documentElement.lang === "en" ? "en" : "cs");
  const state = {lang:initialLanguage,data:null,benchmark:null,benchmarkExpanded:false};
  const C = {
    cs:{viewEurope:"Evropa",viewCzechia:"Česko",eyebrow:"Česko · skutečnost 2025",title:"České obce.<br><em>Celý obraz.</em>",intro:"Celostátní výsledek, dlouhá řada velkých měst a detail každé z 6 254 obcí patří na jedno místo.",municipalities:"Obce",coverage:"úplné pokrytí · 2025",navInsights:"Co data říkají",navBenchmark:"Evropský benchmark",navExplore:"Prozkoumat",navMethod:"Jak data číst",insightsKicker:"01 / Celostátní pohled",insightsTitle:"Rok 2025 v jednom řezu.",insightsCopy:"Součty jsou po konsolidaci uvnitř každé obce. Nejsou konsolidované mezi obcemi navzájem.",exploreKicker:"03 / Navigátor",exploreTitle:"Od celku ke konkrétnímu městu.",exploreCopy:"Vyberte úplný adresář, dvacetiletou řadu velkých měst nebo fiskální profil Prahy mezi evropskými metropolemi.",directoryTitle:"Všechny obce",directoryCopy:"Filtrujte podle kraje, salda, výdajů na obyvatele nebo roku a otevřete detail obce.",openDirectory:"Otevřít adresář →",citiesTitle:"Velká města",citiesCopy:"Dvacet let příjmů, výdajů, výsledků hospodaření a stavu účtů.",openCities:"Otevřít města →",pragueTitle:"Praha mezi metropolemi",pragueCopy:"Rozpočet, saldo, obyvatelé a turistická přenocování ve srovnání hlavních měst EU.",openPrague:"Otevřít Prahu →",methodKicker:"04 / Přesné hranice",methodTitle:"Skutečnost, ne plán.",method1:"6 254 účetních jednotek",method1Copy:"Každá obec má vlastní profil a národní identifikátor IČO.",method2:"Výsledek po konsolidaci",method2Copy:"Příjmy minus výdaje po konsolidaci uvnitř účetní jednotky.",method3:"Dlouhá historie",method3Copy:"Úplný obecní adresář sahá do roku 2010; 27 velkých měst do roku 2006.",footer:"České obecní finance · Monitor státní pokladny",top:"Nahoru ↑",revenue:"Skutečné příjmy",expense:"Skutečné výdaje",result:"Výsledek hospodaření",cash:"Stav účtů",surplus:"přebytek",year:"2025 · nominální CZK",countryHomepage:"Stránka země"},
    en:{viewEurope:"Europe",viewCzechia:"Czechia",eyebrow:"Czechia · 2025 actuals",title:"Czech municipalities.<br><em>The full picture.</em>",intro:"The national result, a long series for large cities and the detail of all 6,254 municipalities belong in one place.",municipalities:"Municipalities",coverage:"full coverage · 2025",navInsights:"What the data says",navBenchmark:"European benchmark",navExplore:"Explore",navMethod:"How to read the data",insightsKicker:"01 / National view",insightsTitle:"2025 in one cut.",insightsCopy:"Totals are consolidated within each municipality. They are not consolidated between municipalities.",exploreKicker:"03 / Navigator",exploreTitle:"From the whole to a specific city.",exploreCopy:"Choose the complete directory, the twenty-year series for large cities, or Prague's fiscal profile among European capitals.",directoryTitle:"All municipalities",directoryCopy:"Filter by region, balance, spend per resident or year, then open a municipality detail.",openDirectory:"Open directory →",citiesTitle:"Large cities",citiesCopy:"Twenty years of revenue, expenditure, fiscal results and cash balances.",openCities:"Open cities →",pragueTitle:"Prague among capitals",pragueCopy:"Budget, balance, population and tourist nights compared with other EU capitals.",openPrague:"Open Prague →",methodKicker:"04 / Exact boundaries",methodTitle:"Actuals, not a plan.",method1:"6,254 reporting entities",method1Copy:"Every municipality has its own profile and national identifier.",method2:"Consolidated result",method2Copy:"Revenue minus expenditure after consolidation within the reporting entity.",method3:"Long history",method3Copy:"The complete municipality directory reaches back to 2010; 27 large cities to 2006.",footer:"Czech municipal finance · Treasury Monitor",top:"Back to top ↑",revenue:"Actual revenue",expense:"Actual expenditure",result:"Fiscal result",cash:"Cash balance",surplus:"surplus",year:"2025 · nominal CZK",countryHomepage:"Country homepage"}
  };
  const t=()=>C[state.lang], english=()=>state.lang==="en";
  const routes={czechia:["Česko","Czechia"],poland:["Polsko","Poland"],denmark:["Dánsko","Denmark"],france:["Francie","France"],sweden:["Švédsko","Sweden"],england:["Anglie","England"],ukraine:["Ukrajina","Ukraine"],norway:["Norsko","Norway"],netherlands:["Nizozemsko","Netherlands"],finland:["Finsko","Finland"]};
  const format=(value)=>new Intl.NumberFormat(english()?"en-GB":"cs-CZ",{style:"currency",currency:"CZK",notation:"compact",maximumFractionDigits:1}).format(value);
  const integer=(value)=>new Intl.NumberFormat(english()?"en-GB":"cs-CZ",{maximumFractionDigits:0}).format(value);
  const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]);

  function translate(){
    document.documentElement.lang=state.lang;
    document.querySelectorAll("[data-copy]").forEach((element)=>{const value=t()[element.dataset.copy];if(value)element.innerHTML=value;});
    document.querySelectorAll("[data-lang]").forEach((button)=>{const active=button.dataset.lang===state.lang;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));});
    document.querySelector(".municipality-lang-switch")?.setAttribute("aria-label",english()?"Language":"Jazyk");
    const countrySelect=document.querySelector("#municipality-country-switch");
    countrySelect?.setAttribute("aria-label",english()?"Municipality country page":"Stránka obcí podle země");
    document.querySelector('[data-view-link="europe"]')?.setAttribute("href",`../?lang=${state.lang}`);
    if(countrySelect){
      countrySelect.innerHTML=Object.entries(routes).map(([slug,names])=>`<option value="${slug}"${slug==="czechia"?" selected":""}>${names[english()?1:0]}</option>`).join("");
      const wrapper=countrySelect.closest("label");wrapper.classList.add("dynamic-country-picker");
      wrapper.querySelector(":scope > span")?.replaceChildren(english()?"Choose a country":"Vyberte zemi");
      let readout=wrapper.querySelector(".country-picker-readout");
      if(!readout){readout=document.createElement("span");readout.className="country-picker-readout";countrySelect.before(readout);}
      const count=state.data?.summary?.municipalities?.entity_count||6254;
      readout.innerHTML=`<img src="${assetRoot}assets/flags/cz.svg" alt=""><span><strong>${english()?"Czechia":"Česko"}</strong><small>${integer(count)} ${english()?"entities":"jednotek"} · 2025</small></span><b aria-hidden="true">⌄</b>`;
    }
    document.querySelector('[data-destination="directory"]')?.setAttribute("href",`${assetRoot}cz/obce/?lang=${state.lang}`);
    document.querySelector('[data-destination="cities"]')?.setAttribute("href",`${assetRoot}cz/mesta/?lang=${state.lang}`);
    document.querySelector('[data-destination="prague"]')?.setAttribute("href",`${assetRoot}eu-capitals.html?lang=${state.lang}&city=prague-cz#city-detail`);
    if(state.data)renderInsights();
    if(state.benchmark)renderMunicipalSizeBenchmark();
  }

  function renderInsights(){
    const summary=state.data.summary.municipalities,result=summary.budget_balance;
    document.querySelector("#cz-insight-grid").innerHTML=[{label:t().revenue,value:format(summary.revenue_actual)},{label:t().expense,value:format(summary.expense_actual)},{label:t().result,value:`${result>=0?"+":""}${format(result)}`,note:result>=0?t().surplus:""},{label:t().cash,value:format(summary.cash_current)}].map((item)=>`<article><strong>${item.value}</strong><h3>${item.label}</h3><p>${item.note||t().year}</p></article>`).join("");
    document.querySelector("#cz-total-entities").textContent=new Intl.NumberFormat(english()?"en-GB":"cs-CZ").format(summary.entity_count);
  }

  function renderMunicipalSizeBenchmark(){
    const dataset=state.benchmark,expanded=state.benchmarkExpanded,czech=dataset.countries.find((country)=>country.iso3==="CZE");
    const regular=dataset.countries.filter((country)=>country.mean<70000),visible=expanded?regular:regular.slice(0,13),outliers=dataset.countries.filter((country)=>country.mean>=70000);
    const width=1080,left=178,right=100,top=54,rowHeight=34,bottom=34,height=top+visible.length*rowHeight+bottom,max=70000,x=(value)=>left+value/max*(width-left-right);
    const axis=[0,10000,20000,30000,40000,50000,60000,70000].map((value)=>`<g><line x1="${x(value)}" x2="${x(value)}" y1="${top-22}" y2="${height-bottom+4}"/><text x="${x(value)}" y="${top-31}" text-anchor="middle">${value?integer(value/1000)+(english()?"k":" tis."):"0"}</text></g>`).join("");
    const rows=visible.map((country,index)=>{const y=top+index*rowHeight+rowHeight/2,active=country.iso3==="CZE",name=english()?country.name_en:country.name_cs;return `<g class="municipal-size-row${active?" active":""}"><text class="municipal-size-rank" x="0" y="${y+4}">${String(index+1).padStart(2,"0")}</text><text class="municipal-size-name" x="30" y="${y+4}">${escapeHtml(name)}</text><rect class="municipal-size-track" x="${left}" y="${y-6}" width="${width-left-right}" height="12"/><rect class="municipal-size-mean" x="${left}" y="${y-6}" width="${Math.max(2,x(country.mean)-left)}" height="12"><title>${escapeHtml(name)} · ${integer(country.mean)} ${english()?"people per municipality":"obyvatel na obec"}</title></rect><circle class="municipal-size-median" cx="${x(country.median)}" cy="${y}" r="5"><title>${english()?"Median":"Medián"}: ${integer(country.median)}</title></circle><text class="municipal-size-value" x="${width-2}" y="${y+4}" text-anchor="end">${integer(country.mean)}</text></g>`;}).join("");
    const copy=english()?{kicker:`02 / European benchmark · OECD ${dataset.reference_year}`,title:"Czechia has Europe's smallest municipalities.",intro:"The average municipality has 1,741 people. The median is only 453 — a clearer picture of how fragmented the system really is.",mean:"People per municipality",median:"Median municipality",small:"Municipalities under 2,000",eu:"Of the EU27 average",meanLegend:"Average population",medianLegend:"Median",euLegend:"EU27 average",more:"Show all countries",less:"Show compact view",note:"A smaller value means a more fragmented municipal structure. This indicator does not measure staff numbers, service quality or administrative efficiency. Competences differ across countries.",source:"Source: OECD · Municipal level government by population size",outlier:"people per municipality · outside chart scale"}:{kicker:`02 / Evropský benchmark · OECD ${dataset.reference_year}`,title:"Česko má nejmenší obce v Evropě.",intro:"Průměrná obec má 1 741 obyvatel. Medián je jen 453 — a ukazuje ještě přesněji, jak roztříštěný český systém je.",mean:"Obyvatel na obec",median:"Medián obce",small:"Obcí pod 2 000 obyvatel",eu:"Průměru EU27",meanLegend:"Průměrný počet obyvatel",medianLegend:"Medián",euLegend:"Průměr EU27",more:"Zobrazit všechny země",less:"Zobrazit kratší výběr",note:"Nižší hodnota znamená roztříštěnější obecní strukturu. Ukazatel neměří počet úředníků, kvalitu služeb ani efektivitu správy. Kompetence obcí se mezi zeměmi liší.",source:"Zdroj: OECD · Municipal level government by population size",outlier:"obyvatel na obec · mimo měřítko grafu"};
    const cards=outliers.map((country)=>`<article><span>${escapeHtml(english()?country.name_en:country.name_cs)}</span><strong>${integer(country.mean)}</strong><small>${copy.outlier}</small></article>`).join("");
    document.querySelector("#municipality-size").innerHTML=`<div class="municipal-size-heading"><div><span class="kicker">${copy.kicker}</span><h2>${copy.title}</h2></div><p>${copy.intro}</p></div><div class="municipal-size-kpis"><article><span>${copy.mean}</span><strong>${integer(czech.mean)}</strong><small>№ 1 / ${dataset.countries.length}</small></article><article><span>${copy.median}</span><strong>${integer(czech.median)}</strong><small>${english()?"people":"obyvatel"}</small></article><article><span>${copy.small}</span><strong>${integer(czech.under_2000_pct)} %</strong><small>${english()?"of all municipalities":"všech obcí"}</small></article><article><span>${copy.eu}</span><strong>${integer(czech.mean/dataset.eu27_mean*100)} %</strong><small>EU27 · ${integer(dataset.eu27_mean)}</small></article></div><div class="municipal-size-chart-card"><div class="municipal-size-legend"><span><i class="mean-key"></i>${copy.meanLegend}</span><span><i class="median-key"></i>${copy.medianLegend}</span><span><i class="eu-key"></i>${copy.euLegend}</span></div><div class="municipal-size-chart-scroll" tabindex="0" role="region" aria-label="${escapeHtml(copy.title)}"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeHtml(copy.title)}"><g class="municipal-size-axis">${axis}</g><line class="municipal-size-eu" x1="${x(dataset.eu27_mean)}" x2="${x(dataset.eu27_mean)}" y1="${top-22}" y2="${height-bottom+4}"/>${rows}</svg></div><button class="municipal-size-toggle" type="button">${expanded?copy.less:copy.more}</button></div><div class="municipal-size-outliers">${cards}</div><div class="municipal-size-method"><p>${copy.note}</p><a href="${escapeHtml(dataset.source.explorer_url)}" target="_blank" rel="noopener">${copy.source} ↗</a></div>`;
    document.querySelector(".municipal-size-toggle")?.addEventListener("click",()=>{state.benchmarkExpanded=!state.benchmarkExpanded;renderMunicipalSizeBenchmark();});
  }

  document.querySelectorAll("[data-lang]").forEach((button)=>button.onclick=()=>{state.lang=button.dataset.lang;localStorage.setItem("psd-lang",state.lang);history.replaceState(null,"",`?lang=${state.lang}${location.hash}`);translate();});
  document.querySelector("#municipality-country-switch")?.addEventListener("change",(event)=>{if(event.target.value!=="czechia")location.href=`../${event.target.value}/?lang=${state.lang}`;});
  fetch(`${assetRoot}data/municipal-snapshot.v1.json`).then((response)=>response.json()).then((data)=>{state.data=data;translate();}).catch((error)=>{console.error(error);document.querySelector("#cz-insight-grid").innerHTML="<p>Data could not be loaded.</p>";});
  fetch(`${assetRoot}data/municipal-size-benchmark.v1.json`).then((response)=>{if(!response.ok)throw new Error(`Municipal size benchmark returned ${response.status}`);return response.json();}).then((data)=>{state.benchmark=data;renderMunicipalSizeBenchmark();}).catch((error)=>{console.error(error);document.querySelector("#municipality-size").innerHTML=`<p class="benchmark-loading">${english()?"European benchmark could not be loaded.":"Evropský benchmark se nepodařilo načíst."}</p>`;});
  translate();
})();
