(()=>{
  const assetRoot=document.currentScript?.src?new URL(".",document.currentScript.src).href:"../../";
  const pickerReady=window.PSDMunicipalityCountryPicker?Promise.resolve():new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=`${assetRoot}municipality-country-picker.js?v=20260902-searchable-picker`;script.onload=resolve;script.onerror=reject;document.head.append(script);});
  const requestedLanguage=new URLSearchParams(location.search).get("lang"), initialLanguage=["cs","en"].includes(requestedLanguage)?requestedLanguage:(document.documentElement.lang==="en"?"en":"cs");
  const state={lang:initialLanguage,data:null,country:null,structure:null,query:"",year:"all",balance:"all",sort:"expenditure",shown:48};
  const code=document.body.dataset.countryCode;
  const slug=document.body.dataset.countrySlug;
  const slugs={CZE:"czechia",DEU:"germany",POL:"poland",DNK:"denmark",FRA:"france",SWE:"sweden",GBR:"england",UKR:"ukraine",NOR:"norway",NLD:"netherlands",FIN:"finland",BRA:"brazil",ESP:"spain",JPN:"japan",COL:"colombia",GEO:"georgia",ITA:"italy",BOL:"bolivia",SLV:"el-salvador",MEX:"mexico",CRI:"costa-rica",GTM:"guatemala",PER:"peru",KOR:"south-korea",CHL:"chile"};
  const profiles={
    POL:{cs:{eyebrow:"Polsko · gminy",title:"Polské gminy.<br><em>Jeden celostátní adresář.</em>",intro:"Roční výkazy Rb-27S a Rb-28S drží místní příjmy a výdaje ve společném národním systému.",insights:"Co polská vrstva skutečně pokrývá.",copy:"Adresář je úplný; zveřejněná fáze a rozsah ukazují, které hodnoty lze později srovnávat.",note:"Polská jednotka",noteCopy:"Základní místní jednotkou je gmina. Tato vrstva drží všechny gminy z ročních výkazů."},en:{eyebrow:"Poland · gminas",title:"Polish gminas.<br><em>One national directory.</em>",intro:"Annual Rb-27S and Rb-28S returns keep local revenue and expenditure in one national system.",insights:"What the Polish layer actually covers.",copy:"The directory is complete; published stages and scope show which values can later be compared.",note:"The Polish unit",noteCopy:"The basic local unit is the gmina. This layer keeps every gmina from the annual returns."}},
    DNK:{cs:{eyebrow:"Dánsko · 98 obcí",title:"Dánské obce.<br><em>Rozpočet i závěrečný účet.</em>",intro:"Malý počet velkých obcí a jednotný StatBank dávají Dánsku mimořádně čitelnou místní vrstvu.",insights:"Celá země v 98 řádcích.",copy:"Rozpočty a skutečné účty jsou oddělené, takže plán nemusí předstírat výsledek.",note:"Dánský model",noteCopy:"Po reformě místní správy tvoří celou obecní úroveň 98 obcí; všechny jsou v adresáři."},en:{eyebrow:"Denmark · 98 municipalities",title:"Danish municipalities.<br><em>Budget and final accounts.</em>",intro:"A small number of large municipalities and one StatBank make Denmark's local layer unusually legible.",insights:"The whole country in 98 rows.",copy:"Budgets and actual accounts remain separate, so a plan never has to masquerade as an outcome.",note:"The Danish model",noteCopy:"After local-government reform, 98 municipalities form the entire municipal tier; all are in the directory."}},
    FRA:{cs:{eyebrow:"Francie · 34 875 communes",title:"Rozpočty francouzských obcí",intro:"OFGL převádí celostátní účetní výkazy do srovnatelných souhrnů hlavního rozpočtu každé současné obce.",insights:"Skutečné účty pro každou obec.",copy:"Příjmy, výdaje, saldo, provozní část, úspory a dluh jsou dostupné za roky 2024–2025; rok 2025 je předběžný a u 97 obcí zatím chybí.",note:"Francouzský rozsah",noteCopy:"Adresář drží všech 34 875 současných communes. Schválené rozpočty zůstávají oddělené a odkazujeme je jen u měst, která je strojově zveřejňují."},en:{eyebrow:"France · 34,875 communes",title:"Budgets of French municipalities",intro:"OFGL turns nationwide accounting returns into comparable main-budget aggregates for every current commune.",insights:"Actual accounts for every commune.",copy:"Revenue, expenditure, balance, operating accounts, savings and debt are available for 2024–2025; 2025 is provisional and still missing for 97 communes.",note:"French scope",noteCopy:"The directory holds all 34,875 current communes. Approved budgets remain separate and are linked only where a city publishes them in machine-readable form."}},
    SWE:{cs:{eyebrow:"Švédsko · 290 kommuner",title:"Švédské obce.<br><em>Náklady, výnosy, rozvaha.</em>",intro:"Všech 290 obcí je v jedné vrstvě postavené na obecních účtech švédské statistiky.",insights:"Účetní pohled na místní stát.",copy:"Švédská data přinášejí náklady, výnosy a rozvahu; pojmy proto nepřekládáme automaticky na rozpočtové příjmy a výdaje.",note:"Švédský rozsah",noteCopy:"Úplný census 290 kommuner vychází z národních obecních účtů SCB."},en:{eyebrow:"Sweden · 290 kommuner",title:"Swedish municipalities.<br><em>Costs, income, balance sheet.</em>",intro:"All 290 municipalities sit in one layer built from Statistics Sweden's municipal accounts.",insights:"An accounting view of local government.",copy:"Swedish data exposes costs, income and balance sheets; those terms are not silently relabelled as budget revenue and expenditure.",note:"Swedish scope",noteCopy:"The complete census of 290 kommuner comes from SCB's national municipal accounts."}},
    GBR:{cs:{eyebrow:"Anglie · councils",title:"Anglické místní úřady.<br><em>Výsledky bez skrytých sborů.</em>",intro:"Adresář spojuje odevzdané výkazy councils a GLA, ale vědomě odděluje policii a hasiče.",insights:"Jasná hranice anglické vrstvy.",copy:"Čísla jsou skutečné výsledky, nikoli schválené plány; rozsah místních orgánů zůstává explicitní.",note:"Co je vyloučeno",noteCopy:"Policejní a hasičské orgány nejsou obecní jednotky této vrstvy a nejsou započítané."},en:{eyebrow:"England · councils",title:"English local authorities.<br><em>Outturn without hidden bodies.</em>",intro:"The directory joins submitted council and GLA returns while deliberately separating police and fire bodies.",insights:"A clear boundary for the English layer.",copy:"The figures are actual outturns, not approved plans; the scope of local authorities remains explicit.",note:"What is excluded",noteCopy:"Police and fire authorities are outside this municipal layer and are not counted."}},
    UKR:{cs:{eyebrow:"Ukrajina · 1 467 územních komunit",title:"Ukrajinské komunity.<br><em>Dva kompletní roky.</em>",intro:"Rozpočty všech aktivních územních komunit včetně Kyjeva pocházejí z otevřeného rozpočtového API za roky 2024 a 2025.",insights:"4,12 milionu ověřených rozpočtových řádků.",copy:"Příjmy a výdaje zachovávají původní ukrajinskou programovou a ekonomickou klasifikaci i rozpočtovou fázi.",note:"Ukrajinská hranice",noteCopy:"Vrstva drží územní komunity včetně Kyjeva; oblasti a rajóny jsou mimo obecní úroveň."},en:{eyebrow:"Ukraine · 1,467 territorial communities",title:"Ukrainian communities.<br><em>Two complete years.</em>",intro:"Budgets for every active territorial community, including Kyiv, come from the open-budget API for 2024 and 2025.",insights:"4.12 million validated budget lines.",copy:"Revenue and expenditure preserve the original Ukrainian programme and economic classifications and budget stage.",note:"Ukrainian boundary",noteCopy:"The layer keeps territorial communities including Kyiv; oblast and district budgets sit outside the municipal tier."}}
  };
  profiles.NOR={cs:{eyebrow:"Norsko · obce",title:"Rozpočty norských obcí",intro:"Skutečné obecní účty KOSTRA za roky 2015–2025.",insights:"Celostátní účetní řada",copy:"Adresář zahrnuje všechny norské obce a Longyearbyen.",note:"Zdroj a rozsah",noteCopy:"Skutečné příjmy, výdaje a salda z norské statistiky SSB."},en:{eyebrow:"Norway · municipalities",title:"Budgets of Norwegian municipalities",intro:"Actual KOSTRA municipal accounts for 2015–2025.",insights:"National accounting series",copy:"The directory includes every Norwegian municipality and Longyearbyen.",note:"Source and scope",noteCopy:"Actual revenue, expenditure and balances from Statistics Norway."}};
  profiles.NLD={cs:{eyebrow:"Nizozemsko · obce",title:"Rozpočty nizozemských obcí",intro:"Roční obecní účty CBS Iv3 za roky 2024–2025.",insights:"Úplný obecní adresář",copy:"Původní funkční a ekonomické členění zůstává zachované.",note:"Zdroj a rozsah",noteCopy:"Skutečné obecní účty zveřejněné nizozemským CBS."},en:{eyebrow:"Netherlands · municipalities",title:"Budgets of Dutch municipalities",intro:"CBS Iv3 annual municipal accounts for 2024–2025.",insights:"Complete municipal directory",copy:"The original functional and economic classifications are retained.",note:"Source and scope",noteCopy:"Actual municipal accounts published by Statistics Netherlands."}};
  profiles.FIN={cs:{eyebrow:"Finsko · obce",title:"Rozpočty finských obcí",intro:"Účetní výkazy všech finských obcí za roky 2015–2020.",insights:"Šestiletá účetní řada",copy:"Adresář zahrnuje všech 310 obcí ve zdrojovém roce 2020.",note:"Zdroj a rozsah",noteCopy:"Skutečné účetní výkazy z finské statistiky."},en:{eyebrow:"Finland · municipalities",title:"Budgets of Finnish municipalities",intro:"Financial statements for every Finnish municipality from 2015–2020.",insights:"Six-year accounting series",copy:"The directory includes all 310 municipalities in the 2020 source year.",note:"Source and scope",noteCopy:"Actual financial statements from Statistics Finland."}};
  profiles.DEU={cs:{eyebrow:"Německo · obce",title:"Rozpočty německých obcí",intro:"Celostátní adresář obecních jádrových rozpočtů za rok 2025.",insights:"10 756 obcí v jednom přehledu",copy:"Očištěné příjmy, výdaje a saldo jsou dostupné pro každou obec; financování zůstává mimo tyto součty.",note:"Německý rozsah",noteCopy:"Vrstva vychází z tabulky 71717-Z-01 regionální databáze a zahrnuje obecní jádrové rozpočty."},en:{eyebrow:"Germany · municipalities",title:"Budgets of German municipalities",intro:"A nationwide directory of municipal core budgets for 2025.",insights:"10,756 municipalities in one directory",copy:"Adjusted receipts, payments and balance are available for every municipality; financing remains outside these totals.",note:"German scope",noteCopy:"The layer comes from Regional Database table 71717-Z-01 and covers municipal core budgets."}};
  profiles.BRA={cs:{eyebrow:"Brazílie · municípios",title:"Rozpočty brazilských obcí",intro:"SICONFI spojuje obecní rozpočty a jejich plnění v jednom národním systému.",insights:"Od rozpočtu po platbu",copy:"Fáze rozpočtu, závazku, likvidace a platby zůstávají oddělené.",note:"Brazilský rozsah",noteCopy:"Adresář vychází z celostátního registru obcí SICONFI."},en:{eyebrow:"Brazil · municípios",title:"Budgets of Brazilian municipalities",intro:"SICONFI joins municipal budgets and execution in one national system.",insights:"From appropriation to payment",copy:"Appropriation, commitment, liquidation and payment stages remain separate.",note:"Brazilian scope",noteCopy:"The directory follows SICONFI's national municipality register."}};
  profiles.ESP={cs:{eyebrow:"Španělsko · municipios",title:"Rozpočty španělských obcí",intro:"CONPREL zveřejňuje schválené rozpočty i jejich likvidaci v maximálním detailu za místní entity.",insights:"Plán a skutečnost",copy:"Schválený rozpočet 2026 a likvidace 2025 používají původní ekonomické kódy.",note:"Španělský rozsah",noteCopy:"Vrstva drží obecní úroveň z národního inventáře místních entit."},en:{eyebrow:"Spain · municipios",title:"Budgets of Spanish municipalities",intro:"CONPREL publishes adopted budgets and liquidations at maximum local-entity detail.",insights:"Plan and outcome",copy:"The 2026 adopted budget and 2025 liquidation retain native economic codes.",note:"Spanish scope",noteCopy:"The layer keeps the municipal tier from the national local-entity inventory."}};
  profiles.JPN={cs:{eyebrow:"Japonsko · 市町村",title:"Finance japonských obcí",intro:"e-Stat standardizuje závěrečné účty obcí včetně příjmů, výdajů, dluhu, fondů a výdajů spojených se stárnutím.",insights:"Detail skutečnosti, ne schváleného plánu",copy:"Národní vrstva obsahuje závěrečné účty; schválené rozpočty zůstávají v dokumentech jednotlivých obcí.",note:"Japonský rozsah",noteCopy:"Profily vycházejí z oficiálního Local Public Finance Survey."},en:{eyebrow:"Japan · municipalities",title:"Finances of Japanese municipalities",intro:"e-Stat standardizes municipal settlements including revenue, expenditure, debt, funds and ageing-related spending.",insights:"Deep actuals, not the adopted plan",copy:"The national layer contains settlements; adopted budgets remain in individual municipal documents.",note:"Japanese scope",noteCopy:"Profiles use the official Local Public Finance Survey."}};
  profiles.COL={cs:{eyebrow:"Kolumbie · municipios",title:"Rozpočty kolumbijských obcí",intro:"CUIPO zveřejňuje plánování i plnění příjmů a výdajů územních samospráv.",insights:"Plán, revize a skutečnost",copy:"Počáteční a konečný rozpočet zůstávají oddělené od skutečného plnění za rok 2025.",note:"Kolumbijský rozsah",noteCopy:"Adresář obsahuje všech 1 102 obcí vykazujících v národním systému CUIPO."},en:{eyebrow:"Colombia · municipios",title:"Budgets of Colombian municipalities",intro:"CUIPO publishes territorial-government revenue and expenditure planning and execution.",insights:"Plan, revision and actuals",copy:"Initial and definitive budgets remain separate from 2025 execution.",note:"Colombian scope",noteCopy:"The directory contains all 1,102 municipalities reporting in the national CUIPO system."}};
  profiles.GEO={cs:{eyebrow:"Gruzie · municipalities",title:"Rozpočty gruzínských obcí",intro:"Ministerstvo financí zveřejňuje jednotné sešity pro celou obecní úroveň.",insights:"Skutečnost i schválený plán",copy:"Skutečnost 2025 se páruje se schváleným plánem 2026 a funkčním detailem výdajů.",note:"Gruzínský rozsah",noteCopy:"Všech 69 obcí je ověřeno proti souhrnnému funkčnímu sešitu ministerstva."},en:{eyebrow:"Georgia · municipalities",title:"Budgets of Georgian municipalities",intro:"The Ministry of Finance publishes standardized workbooks for the full municipal tier.",insights:"Actuals and an approved plan",copy:"2025 actuals pair with the 2026 approved plan and functional expenditure detail.",note:"Georgian scope",noteCopy:"All 69 municipalities are reconciled to the ministry's national functional workbook."}};
  profiles.ITA={cs:{eyebrow:"Itálie · comuni",title:"Finance italských obcí",intro:"SIOPE zveřejňuje celostátní hotovostní příjmy a platby všech italských obcí.",insights:"Skutečné peněžní toky",copy:"Vrstva drží příjmy a platby roku 2025 podle původních účetních titulů.",note:"Italský rozsah",noteCopy:"Adresář obsahuje všech 7 896 obcí vykazujících v národním SIOPE."},en:{eyebrow:"Italy · comuni",title:"Finances of Italian municipalities",intro:"SIOPE publishes nationwide cash receipts and payments for every Italian municipality.",insights:"Observed cash flows",copy:"The layer keeps 2025 receipts and payments grouped by native accounting titles.",note:"Italian scope",noteCopy:"The directory contains all 7,896 municipalities reporting in national SIOPE."}};
  profiles.BOL={cs:{eyebrow:"Bolívie · gobiernos locales",title:"Rozpočty bolivijských samospráv",intro:"Presupuesto Abierto zveřejňuje plán i plnění aktivních obecních a domorodých autonomních vlád.",insights:"Celý rozpočtový cyklus",copy:"Počáteční a upravený rozpočet, závazky a hotovost zůstávají oddělené.",note:"Bolivijský rozsah",noteCopy:"Vrstva pokrývá 335 obecních a 8 domorodých autonomních vlád."},en:{eyebrow:"Bolivia · local governments",title:"Budgets of Bolivian local governments",intro:"Presupuesto Abierto publishes plans and execution for active municipal and Indigenous autonomous governments.",insights:"The full budget cycle",copy:"Initial and revised budgets, accruals and cash remain separate.",note:"Bolivian scope",noteCopy:"The layer covers 335 municipal and 8 Indigenous autonomous governments."}};
  profiles.SLV={cs:{eyebrow:"Salvador · municipalidades",title:"Rozpočty salvadorských obcí",intro:"SAFIM zveřejňuje schválené, upravené a skutečné obecní rozpočty.",insights:"Poslední srovnatelná celoroční vrstva",copy:"Rok 2023 pokrývá 259 z 262 tehdejších obcí; tři nevykázaly.",note:"Salvadorský rozsah",noteCopy:"Rozsah zůstává explicitně částečný a nepředstírá úplný census."},en:{eyebrow:"El Salvador · municipalidades",title:"Budgets of Salvadoran municipalities",intro:"SAFIM publishes enacted, revised and executed municipal budgets.",insights:"The last comparable full-year layer",copy:"2023 covers 259 of the 262 then-municipalities; three did not report.",note:"Salvadoran scope",noteCopy:"Coverage remains explicitly partial and is not presented as a complete census."}};
  profiles.MEX={cs:{eyebrow:"Mexiko · municipios",title:"Finance mexických obcí",intro:"INEGI zveřejňuje definitivní roční příjmy a výdaje vykazujících obecních vlád.",insights:"Definitivní účty, částečný census",copy:"Rok 2024 obsahuje 2 380 vykazujících vlád a původní rozpočtové kapitoly.",note:"Mexický rozsah",noteCopy:"Vrstva je výslovně částečná, protože soubor nezahrnuje všechny obce v zemi."},en:{eyebrow:"Mexico · municipios",title:"Finances of Mexican municipalities",intro:"INEGI publishes definitive annual revenue and expenditure for reporting municipal governments.",insights:"Definitive accounts, partial census",copy:"The 2024 layer contains 2,380 reporting governments and native budget chapters.",note:"Mexican scope",noteCopy:"The layer is explicitly partial because the file does not include every municipality in the country."}};
  profiles.CRI={cs:{eyebrow:"Kostarika · municipalidades",title:"Finance kostarických obcí",intro:"Contraloría zveřejňuje přijaté příjmy, výdaje a výsledky všech obcí v systému SIPP.",insights:"Úplná současná obecní vrstva",copy:"Rok 2025 pokrývá všech 84 obcí včetně nových kantonů Monteverde a Puerto Jiménez.",note:"Kostarický rozsah",noteCopy:"Hodnoty jsou skutečné přijaté příjmy a výdaje vykázané národnímu SIPP."},en:{eyebrow:"Costa Rica · municipalidades",title:"Finances of Costa Rican municipalities",intro:"The Comptroller publishes received revenue, spending and results for every municipality in SIPP.",insights:"The complete current municipal tier",copy:"The 2025 layer covers all 84 municipalities, including the newer Monteverde and Puerto Jiménez cantons.",note:"Costa Rican scope",noteCopy:"Values are actual received revenue and spending reported to the national SIPP."}};
  profiles.GTM={cs:{eyebrow:"Guatemala · municipalidades",title:"Rozpočty guatemalských obcí",intro:"MINFIN zveřejňuje plán i plnění příjmů a výdajů všech obcí v SICOINGL a SICOINDES.",insights:"Úplný rozpočtový cyklus",copy:"Rok 2025 odděluje schválený a upravený rozpočet, akruální plnění a hotovost.",note:"Guatemalský rozsah",noteCopy:"Národní příjmový sešit a osm regionálních výdajových sešitů společně pokrývají všech 340 obcí."},en:{eyebrow:"Guatemala · municipalidades",title:"Budgets of Guatemalan municipalities",intro:"MINFIN publishes revenue and expenditure plans and execution for every municipality in SICOINGL and SICOINDES.",insights:"The full budget cycle",copy:"The 2025 layer separates enacted and revised budgets, accrual execution and cash.",note:"Guatemalan scope",noteCopy:"One national revenue workbook and eight regional expenditure workbooks jointly cover all 340 municipalities."}};
  profiles.PER={cs:{eyebrow:"Peru · municipalidades",title:"Rozpočty peruánských obcí",intro:"MEF zveřejňuje rozpočet a plnění příjmů a výdajů všech provinčních a okresních místních vlád.",insights:"Celá místní úroveň",copy:"Rok 2024 odděluje počáteční a upravený rozpočet, skutečnost a platby.",note:"Peruánský rozsah",noteCopy:"Vrstva pokrývá 196 provinčních vlád včetně metropolitní Limy a 1 695 okresních obcí."},en:{eyebrow:"Peru · municipalidades",title:"Budgets of Peruvian municipalities",intro:"MEF publishes revenue and expenditure budgets and execution for every provincial and district local government.",insights:"The whole local tier",copy:"The 2024 layer separates initial and revised budgets, actuals and payments.",note:"Peruvian scope",noteCopy:"The layer covers 196 provincial governments including metropolitan Lima and 1,695 district municipalities."}};
  profiles.KOR={cs:{eyebrow:"Jižní Korea · 지방자치단체",title:"Finance jihokorejských samospráv",intro:"Local Finance 365 zveřejňuje závěrečné příjmy a výdaje všech místních vlád v jednom národním systému.",insights:"Dvě úrovně, jeden úplný census",copy:"Rok 2024 zahrnuje 17 vyšších a 226 základních místních vlád a odděluje obecný účet, zvláštní účty a fondy.",note:"Korejský rozsah",noteCopy:"Vrstva obsahuje všech 243 místních vlád; vyšší a základní úroveň jsou v profilech výslovně označené."},en:{eyebrow:"South Korea · 지방자치단체",title:"Finances of South Korean local governments",intro:"Local Finance 365 publishes final revenue and expenditure for every local government in one national system.",insights:"Two tiers, one complete census",copy:"The 2024 layer covers 17 upper-tier and 226 basic local governments, separating the general account, special accounts and funds.",note:"South Korean scope",noteCopy:"The layer contains all 243 local governments; upper-tier and basic governments are explicitly identified in their profiles."}};
  profiles.CHL={cs:{eyebrow:"Chile · municipalidades",title:"Finance chilských obcí",intro:"SUBDERE zveřejňuje v SINIM přijaté příjmy a akruální výdaje každé obce.",insights:"Všech 345 obcí",copy:"Rok 2025 používá příjmy bez počátečního zůstatku hotovosti a výdaje obecního sektoru v původním členění SINIM.",note:"Chilský rozsah",noteCopy:"Vrstva pokrývá úplný národní seznam 345 obcí a zachovává kódy i názvy indikátorů SINIM."},en:{eyebrow:"Chile · municipalidades",title:"Finances of Chilean municipalities",intro:"SUBDERE publishes perceived revenue and accrued expenditure for every municipality in SINIM.",insights:"All 345 municipalities",copy:"The 2025 layer uses revenue excluding opening cash and municipal-sector expenditure in SINIM's native classification.",note:"Chilean scope",noteCopy:"The layer covers the complete national list of 345 municipalities and retains SINIM's indicator codes and names."}};
  const simpleCountryTitles={DEU:["Rozpočty německých obcí","Budgets of German municipalities"],POL:["Rozpočty polských gmin","Budgets of Polish municipalities"],DNK:["Rozpočty dánských obcí","Budgets of Danish municipalities"],FRA:["Francouzské obce.<br><em>V jednom adresáři.</em>","French municipalities.<br><em>One complete directory.</em>"],SWE:["Rozpočty švédských obcí","Budgets of Swedish municipalities"],GBR:["Rozpočty anglických místních úřadů","Budgets of English local authorities"],UKR:["Rozpočty ukrajinských komunit","Budgets of Ukrainian communities"],NOR:["Rozpočty norských obcí","Budgets of Norwegian municipalities"],NLD:["Rozpočty nizozemských obcí","Budgets of Dutch municipalities"],FIN:["Rozpočty finských obcí","Budgets of Finnish municipalities"],BRA:["Rozpočty brazilských obcí","Budgets of Brazilian municipalities"],ESP:["Rozpočty španělských obcí","Budgets of Spanish municipalities"],JPN:["Finance japonských obcí","Finances of Japanese municipalities"],COL:["Rozpočty kolumbijských obcí","Budgets of Colombian municipalities"],GEO:["Rozpočty gruzínských obcí","Budgets of Georgian municipalities"],ITA:["Finance italských obcí","Finances of Italian municipalities"],BOL:["Rozpočty bolivijských samospráv","Budgets of Bolivian local governments"],SLV:["Rozpočty salvadorských obcí","Budgets of Salvadoran municipalities"],MEX:["Finance mexických obcí","Finances of Mexican municipalities"],CRI:["Finance kostarických obcí","Finances of Costa Rican municipalities"],GTM:["Rozpočty guatemalských obcí","Budgets of Guatemalan municipalities"],PER:["Rozpočty peruánských obcí","Budgets of Peruvian municipalities"],KOR:["Finance jihokorejských samospráv","Finances of South Korean local governments"],CHL:["Finance chilských obcí","Finances of Chilean municipalities"]};
  Object.entries(profiles).forEach(([countryCode,profile])=>{profile.cs.title=simpleCountryTitles[countryCode][0];profile.en.title=simpleCountryTitles[countryCode][1];});
  const copy={cs:{viewEurope:"Evropa",countryHomepage:"Stránka země",covered:"Pokryté místní jednotky",navInsights:"Co data říkají",navDirectory:"Adresář",navContext:"Kontext a zdroj",insightsKicker:"Datový profil",directoryKicker:"Místní úroveň",directoryTitle:"Najděte konkrétní obec.",search:"Hledat",searchPlaceholder:"Název nebo národní kód…",year:"Rok",reset:"Vymazat filtry",more:"Načíst další",contextKicker:"Co je uvnitř",contextTitle:"Rozsah zůstává viditelný.",contextCopy:"U každého čísla uvádíme národní zdroj a účetní hranici.",top:"Nahoru ↑",entities:"jednotek",shown:"zobrazeno",years:"dostupné roky",stages:"rozpočtové fáze",measures:"účetní oblasti",source:"Otevřít národní zdroj ↗",capital:"Hlavní město",capitalLink:"Otevřít fiskální profil →",noCapital:"Samostatný fiskální profil hlavního města zatím v evropské vrstvě není.",detail:"Detail →",complete:"Úplné pokrytí",partial:"Částečné pokrytí",downloading:"Probíhá import",aggregate_only:"Pouze adresář",actual:"skutečnost",enacted:"schválený",revised:"upravený",revenue:"příjmy",expenditure:"výdaje",balance:"saldo",cash:"stav účtů",financing:"financování"},en:{viewEurope:"Europe",countryHomepage:"Country homepage",covered:"Covered local units",navInsights:"What data says",navDirectory:"Directory",navContext:"Context and source",insightsKicker:"Data profile",directoryKicker:"Local tier",directoryTitle:"Find a specific municipality.",search:"Search",searchPlaceholder:"Name or national code…",year:"Year",reset:"Reset filters",more:"Load more",contextKicker:"What is inside",contextTitle:"Scope stays visible.",contextCopy:"Every figure carries its national source and accounting boundary.",top:"Back to top ↑",entities:"entities",shown:"shown",years:"available years",stages:"budget stages",measures:"accounting areas",source:"Open national source ↗",capital:"Capital city",capitalLink:"Open fiscal profile →",noCapital:"A separate fiscal profile for the capital is not yet in the European layer.",detail:"Detail →",complete:"Full coverage",partial:"Partial coverage",downloading:"Import running",aggregate_only:"Directory only",actual:"actual",enacted:"approved",revised:"revised",revenue:"revenue",expenditure:"expenditure",balance:"balance",cash:"cash",financing:"financing"}};
  Object.assign(copy.cs,{directoryTitle:"Najděte obec",contextTitle:"Zdroj a rozsah dat",result:"saldo",population:"obyvatelé",dataSource:"Zdroj dat ↗",regions:"Účty regionů",regionsCopy:"Regiony tvoří jinou úroveň samosprávy než obce. Jejich oficiální účetní data proto odkazujeme odděleně.",regionsLink:"Otevřít účty regionů ↗"});
  Object.assign(copy.en,{directoryTitle:"Find a municipality",contextTitle:"Data source and scope",result:"balance",population:"population",dataSource:"Data source ↗",regions:"Regional accounts",regionsCopy:"Regions are a different tier of government from communes, so their official accounting data are linked separately.",regionsLink:"Open regional accounts ↗"});
  Object.assign(copy.cs,{navStructure:"Struktura rozpočtu",structureKicker:"Průměrný místní rozpočet",structureTitle:"Složení průměrného místního rozpočtu",structureCopy:"Každý místní rozpočet má stejnou váhu, takže největší města nepřehluší okresní a menší obecní rozpočty.",averageBudget:"Průměrný místní rozpočet",ofFunctionalSpending:"ze 100 jednotek funkčních výdajů",budgetsIncluded:"zahrnutých rozpočtů",method:"Jak je průměr spočítaný",actualLabel:"skutečné výdaje",approvedLabel:"schválené výdaje"});
  Object.assign(copy.en,{navStructure:"Budget structure",structureKicker:"Average local budget",structureTitle:"What an average local budget contains",structureCopy:"Every local budget has equal weight, so the largest cities do not drown out district and smaller municipal budgets.",averageBudget:"Average local budget",ofFunctionalSpending:"out of 100 units of functional spending",budgetsIncluded:"budgets included",method:"How the average is calculated",actualLabel:"actual expenditure",approvedLabel:"approved expenditure"});
  Object.assign(copy.cs,{navRankings:"Rozpočtové žebříčky",taxAutonomy:"OECD · daňová pravomoc",rankingsKicker:"Rozpočtové žebříčky · předběžná skutečnost 2025",rankingsTitle:"Největší rozpočty, přebytky a schodky",rankingsCopy:"Skutečné výdaje ukazují velikost rozpočtu. Přebytek a schodek jsou příjmy minus výdaje za jediný rok, nikoli známka kvality vedení.",rankingsNote:"„Dobré“ a „špatné“ zde znamená pouze přebytek nebo schodek v jediném roce. Schodek může financovat plánovanou investici z dřívějších úspor.",searchLabel:"Hledat obec",franceSearchPlaceholder:"Název, region nebo kód INSEE…",resetShort:"Vymazat",profileYear:"Rok v profilu",balanceFilter:"Výsledek",allBalances:"Přebytky i schodky",surplusOnly:"Přebytky",deficitOnly:"Schodky",sort:"Řazení",sortBudget:"Podle velikosti rozpočtu",sortRevenue:"Podle příjmů",sortBalance:"Podle výsledku",sortPopulation:"Podle počtu obyvatel",sortName:"Podle názvu",directoryIntro:"Hledejte podle názvu, regionu nebo kódu INSEE. Každý výsledek vede na úplný finanční profil obce.",directoryOrderNote:"Výsledky začínají největšími rozpočty podle skutečných výdajů."});
  Object.assign(copy.en,{navRankings:"Budget rankings",taxAutonomy:"OECD · tax autonomy",rankingsKicker:"Budget rankings · provisional 2025 actuals",rankingsTitle:"Largest budgets, surpluses and deficits",rankingsCopy:"Actual expenditure shows budget size. Surplus and deficit are revenue minus expenditure for one year, not a score for the quality of local management.",rankingsNote:"“Good” and “bad” here mean only a surplus or deficit in one year. A deficit may fund planned investment from savings accumulated earlier.",searchLabel:"Find a municipality",franceSearchPlaceholder:"Name, region or INSEE code…",resetShort:"Clear",profileYear:"Year in profile",balanceFilter:"Balance",allBalances:"Surplus and deficit",surplusOnly:"Surplus",deficitOnly:"Deficit",sort:"Sort",sortBudget:"By budget size",sortRevenue:"By revenue",sortBalance:"By balance",sortPopulation:"By population",sortName:"By name",directoryIntro:"Search by name, region or INSEE code. Every result opens the municipality’s complete financial profile.",directoryOrderNote:"Results start with the largest budgets by actual expenditure."});
  const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const t=()=>copy[state.lang], p=()=>profiles[code][state.lang], fmt=n=>new Intl.NumberFormat(state.lang==="en"?"en-GB":"cs-CZ").format(n), money=n=>Number.isFinite(n)?new Intl.NumberFormat(state.lang==="en"?"en-GB":"cs-CZ",{style:"currency",currency:state.country.currency,notation:"compact",maximumFractionDigits:1}).format(n):"—";
  function translate(){
    document.documentElement.lang=state.lang;
    document.querySelectorAll("[data-copy]").forEach(el=>{if(t()[el.dataset.copy])el.textContent=t()[el.dataset.copy];});
    document.querySelectorAll("[data-placeholder]").forEach(el=>el.placeholder=t()[el.dataset.placeholder]);
    document.querySelectorAll("[data-lang]").forEach(el=>{const active=el.dataset.lang===state.lang;el.classList.toggle("active",active);el.setAttribute("aria-pressed",String(active));});
    $(".municipality-lang-switch")?.setAttribute("aria-label",state.lang==="en"?"Language":"Jazyk");
    $("#municipality-country-switch")?.setAttribute("aria-label",state.lang==="en"?"Municipality country page":"Stránka obcí podle země");
    $('[data-view-link="europe"]').href=`../?lang=${state.lang}`;
    if(state.data)render();
  }
  function renderSwitch(){
    const select=$("#municipality-country-switch"), country=state.country;
    if(!window.PSDMunicipalityCountryPicker){pickerReady.then(renderSwitch).catch(console.error);return;}
    window.PSDMunicipalityCountryPicker?.enhance(select,{
      label:state.lang==="en"?"Municipality country":"Obecní země",
      placeholder:state.lang==="en"?"Choose a country":"Vyberte zemi",
      hint:state.lang==="en"?"Search all municipality countries":"Prohledejte všechny obecní země",
      searchLabel:state.lang==="en"?"Search countries":"Hledat země",
      searchPlaceholder:state.lang==="en"?"Country name…":"Název země…",
      emptyLabel:state.lang==="en"?"No countries match.":"Žádná země neodpovídá.",
      resultSingular:state.lang==="en"?"country":"země",
      resultPlural:state.lang==="en"?"countries":"zemí",
      selected:slugs[code],
      options:state.data.countries.filter(c=>slugs[c.code]).map(c=>({value:slugs[c.code],label:c[`name_${state.lang}`],search:`${c.name_cs} ${c.name_en} ${c.code}`,meta:`${fmt(c.directory_count)} ${t().entities}`,flag:`${assetRoot}assets/flags/${c.alpha2.toLowerCase()}.svg`})),
    });
  }
  function render(){
    const c=state.country, profile=p();
    const plainTitle=profile.title.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
    document.title=`${plainTitle} — Public Spending Data`;
    document.querySelector('meta[name="description"]')?.setAttribute("content",profile.intro);
    renderSwitch(); $("#country-eyebrow").textContent=profile.eyebrow; $("#country-title").innerHTML=profile.title; $("#country-intro").textContent=profile.intro;
    $("#country-total").textContent=fmt(c.directory_count); $("#country-coverage").textContent=`${t()[c.status]} · ${c.years.join(" + ")}`;
    if(code==="FRA")document.querySelector(".municipal-hero-stat span").textContent=state.lang==="en"?"Municipalities":"Obce";
    $("#insights-title").textContent=profile.insights; $("#insights-copy").textContent=profile.copy;
    if(code==="FRA")renderFranceOverview();
    else $("#country-insight-grid").innerHTML=[{n:fmt(c.directory_count),h:t().entities,p:c[`coverage_${state.lang}`]},{n:c.years.join(" + "),h:t().years,p:c.years.length>1?`${c.years.length} ${t().years}`:t().years},{n:String(c.stages.length),h:t().stages,p:c.stages.map(x=>t()[x]).join(" · ")},{n:String(c.measures.length),h:t().measures,p:c.measures.map(x=>t()[x]).join(" · ")}].map(x=>`<article><strong>${esc(x.n)}</strong><h3>${esc(x.h)}</h3><p>${esc(x.p)}</p></article>`).join("");
    renderBudgetStructure();
    const years=[...c.years].sort((a,b)=>b-a); $("#country-year-filter").innerHTML=`<option value="all">${years.join(" + ")}</option>`+years.map(y=>`<option>${y}</option>`).join(""); $("#country-year-filter").value=state.year;
    const capitalIds={POL:"warsaw-pl",DNK:"copenhagen-dk",FRA:"paris-fr",SWE:"stockholm-se",GBR:"london-gb"}; const capital=state.capitals?.find(x=>x.city_id===capitalIds[code]);
    $("#country-context-grid").innerHTML=`<article><img class="country-flag" src="${assetRoot}assets/flags/${c.alpha2.toLowerCase()}.svg" alt=""><span class="kicker">${esc(c.code)} · ${esc(c.currency)}</span><h3>${esc(profile.note)}</h3><p>${esc(profile.noteCopy)}</p><a href="${esc(c.source)}" target="_blank" rel="noopener">${t().source}</a></article><article><span class="kicker">${t().capital}</span><h3>${esc(capital?.city||"—")}</h3><p>${esc(capital?capital.scope:t().noCapital)}</p>${capital?`<a href="${assetRoot}eu-capitals.html?lang=${state.lang}&city=${capital.city_id}#city-detail">${t().capitalLink}</a>`:""}</article>${code==="FRA"&&c.regional_source?`<article><span class="kicker">France · régions</span><h3>${t().regions}</h3><p>${t().regionsCopy}</p><a href="${esc(c.regional_source)}" target="_blank" rel="noopener">${t().regionsLink}</a></article>`:""}`;
    const countryFooter=$("#country-footer");if(countryFooter)countryFooter.textContent=`${c[`name_${state.lang}`]} · ${c[`coverage_${state.lang}`]}`;if(code==="FRA")renderFranceRankings();renderDirectory();
  }
  function franceRows(){return state.data.entities.filter(e=>e.country==="FRA"&&e.years.includes(2025)&&Number.isFinite(e.revenue)&&Number.isFinite(e.expenditure)&&Number.isFinite(e.balance));}
  function renderFranceOverview(){
    const rows=franceRows(),revenue=rows.reduce((sum,e)=>sum+e.revenue,0),expenditure=rows.reduce((sum,e)=>sum+e.expenditure,0),balance=rows.reduce((sum,e)=>sum+e.balance,0),surplus=rows.filter(e=>e.balance>=0).length;
    const labels=state.lang==="en"?{title:"The complete municipal result for 2025.",copy:"Every reporting commune is included in the totals and classified by its annual balance. The latest year is provisional; 97 current communes have not yet reported 2025.",revenue:"Total revenue",expenditure:"Total expenditure",balance:"Combined balance",reporting:"Reporting communes",actual:"provisional actuals",net:"revenue minus expenditure",share:"in surplus"}:{title:"Úplný výsledek obcí za rok 2025.",copy:"Součty zahrnují každou vykazující obec a všechny obce dělí podle ročního výsledku. Poslední rok je předběžný; u 97 současných obcí zatím rok 2025 chybí.",revenue:"Celkové příjmy",expenditure:"Celkové výdaje",balance:"Souhrnný výsledek",reporting:"Vykazující obce",actual:"předběžná skutečnost",net:"příjmy minus výdaje",share:"v přebytku"};
    $("#insights-title").textContent=labels.title;$("#insights-copy").textContent=labels.copy;
    $("#country-insight-grid").innerHTML=[{n:money(revenue),h:labels.revenue,p:`2025 · ${labels.actual}`},{n:money(expenditure),h:labels.expenditure,p:`2025 · ${labels.actual}`},{n:`${balance>0?"+":""}${money(balance)}`,h:labels.balance,p:labels.net,tone:balance>=0?"positive":"negative"},{n:fmt(rows.length),h:labels.reporting,p:`${(surplus/rows.length*100).toLocaleString(state.lang==="en"?"en-GB":"cs-CZ",{maximumFractionDigits:1})} % ${labels.share}`}].map(x=>`<article><strong class="${x.tone||""}">${esc(x.n)}</strong><h3>${esc(x.h)}</h3><p>${esc(x.p)}</p></article>`).join("");
  }
  function franceProfileHref(entity){return `${assetRoot}municipalities/france/profile/?code=${encodeURIComponent(entity.code)}&lang=${state.lang}`;}
  function franceRankedRows(title,subtitle,entities,field,tone){
    const maximum=Math.max(...entities.map(entity=>Math.abs(entity[field])),1);
    return `<article class="municipal-ranking-card ${tone}"><header><span>${esc(title)}</span><small>${esc(subtitle)}</small></header><ol>${entities.map((entity,index)=>`<li><a href="${esc(franceProfileHref(entity))}"><span class="municipal-rank-number">${String(index+1).padStart(2,"0")}</span><span class="municipal-rank-name"><strong>${esc(entity.name)}</strong><small>${esc(entity.region||"")}</small></span><i><b style="width:${(Math.abs(entity[field])/maximum*100).toFixed(2)}%"></b></i><em>${field==="balance"&&entity[field]>0?"+":""}${money(entity[field])}</em></a></li>`).join("")}</ol></article>`;
  }
  function renderFranceRankings(){
    const rows=franceRows(),surplusRows=rows.filter(e=>e.balance>=0),deficitRows=rows.filter(e=>e.balance<0),totalBalance=rows.reduce((sum,e)=>sum+e.balance,0);
    const largest=[...rows].sort((a,b)=>b.expenditure-a.expenditure).slice(0,8),surplus=[...surplusRows].sort((a,b)=>b.balance-a.balance).slice(0,8),deficit=[...deficitRows].sort((a,b)=>a.balance-b.balance).slice(0,8);
    const labels=state.lang==="en"?{surplus:"Communes in surplus",deficit:"Communes in deficit",together:"Together, reporting communes finished 2025 at",largest:"Largest budgets",largestSub:"Actual expenditure · provisional 2025",best:"Largest surpluses",bestSub:"Revenue minus expenditure · provisional 2025",worst:"Largest deficits",worstSub:"Revenue minus expenditure · provisional 2025"}:{surplus:"Obce v přebytku",deficit:"Obce ve schodku",together:"Vykazující obce dohromady uzavřely rok 2025 výsledkem",largest:"Největší rozpočty",largestSub:"Skutečné výdaje · předběžně 2025",best:"Největší přebytky",bestSub:"Příjmy minus výdaje · předběžně 2025",worst:"Největší schodky",worstSub:"Příjmy minus výdaje · předběžně 2025"};
    const share=count=>`${(count/rows.length*100).toLocaleString(state.lang==="en"?"en-GB":"cs-CZ",{maximumFractionDigits:1})} %`;
    $("#municipal-balance-split").innerHTML=`<article><span>${esc(labels.surplus)}</span><strong>${fmt(surplusRows.length)}</strong><small>${share(surplusRows.length)}</small></article><article><span>${esc(labels.deficit)}</span><strong>${fmt(deficitRows.length)}</strong><small>${share(deficitRows.length)}</small></article><p>${esc(labels.together)} <strong class="${totalBalance>=0?"positive":"negative"}">${totalBalance>0?"+":""}${money(totalBalance)}</strong>.</p>`;
    $("#municipal-ranking-grid").innerHTML=franceRankedRows(labels.largest,labels.largestSub,largest,"expenditure","scale")+franceRankedRows(labels.best,labels.bestSub,surplus,"balance","surplus")+franceRankedRows(labels.worst,labels.worstSub,deficit,"balance","deficit");
  }
  function renderBudgetStructure(){
    const section=$("#budget-structure"), nav=$("#budget-structure-nav"), content=$("#budget-structure-content");
    if(!section||!nav||!content)return;
    const structure=state.structure?.countries?.find(country=>country.code===code);
    section.hidden=!structure;nav.hidden=!structure;
    const directoryKicker=$("#directory [data-copy='directoryKicker']"), contextKicker=$("#context [data-copy='contextKicker']");
    if(directoryKicker)directoryKicker.textContent=t().directoryKicker.replace(/^\d+/,structure?"03":"02");
    if(contextKicker)contextKicker.textContent=t().contextKicker.replace(/^\d+/,structure?"04":"03");
    if(!structure)return;
    const palette={administration:"#5c6661",safety:"#9a5b5e",economy:"#b18a64",transport:"#c74c2f",environment:"#727b2b",housing:"#8e7d68",health:"#a8b63f",education:"#b59f32",culture:"#826b8f",social:"#287158",other:"#8b8d83"};
    const rows=structure.categories.filter(category=>category.average_share_pct>=.05);
    const top=rows[0], definition=state.structure[`definition_${state.lang}`], scope=structure[`scope_${state.lang}`], basis=structure[`source_basis_${state.lang}`];
    const stageLabel=structure.stage==="actual"?t().actualLabel:t().approvedLabel;
    const stackLabel=rows.map(category=>`${category[`label_${state.lang}`]} ${category.average_share_pct.toLocaleString(state.lang==="en"?"en-GB":"cs-CZ",{maximumFractionDigits:1})}%`).join(", ");
    content.innerHTML=`<div class="municipal-structure-layout"><article class="municipal-structure-summary"><span class="kicker">${esc(t().averageBudget)}</span><strong>${top.average_share_pct.toLocaleString(state.lang==="en"?"en-GB":"cs-CZ",{maximumFractionDigits:1})}</strong><h3>${esc(top[`label_${state.lang}`])}</h3><p>${esc(t().ofFunctionalSpending)}</p><dl><div><dt>${esc(t().budgetsIncluded)}</dt><dd>${fmt(structure.included_profile_count)}</dd></div><div><dt>${esc(t().year)}</dt><dd>${esc(structure.year)} · ${esc(stageLabel)}</dd></div></dl></article><div class="municipal-structure-chart"><div class="municipal-structure-stack" role="img" aria-label="${esc(stackLabel)}">${rows.map(category=>`<i style="width:${category.average_share_pct}%;background:${palette[category.id]||palette.other}" title="${esc(category[`label_${state.lang}`])}: ${category.average_share_pct.toFixed(1)}%"></i>`).join("")}</div><ol>${rows.map(category=>`<li><span><i style="background:${palette[category.id]||palette.other}"></i>${esc(category[`label_${state.lang}`])}</span><b>${category.average_share_pct.toLocaleString(state.lang==="en"?"en-GB":"cs-CZ",{minimumFractionDigits:1,maximumFractionDigits:1})} %</b><div><i style="width:${Math.min(100,category.average_share_pct)}%;background:${palette[category.id]||palette.other}"></i></div></li>`).join("")}</ol></div></div><aside class="municipal-structure-method"><strong>${esc(scope)}</strong><p><b>${esc(t().method)}:</b> ${esc(definition)} ${esc(basis)}.</p></aside>`;
  }
  function filtered(){
    const q=state.query.trim().toLocaleLowerCase();
    const rows=state.data.entities.filter(e=>e.country===code&&(state.year==="all"||e.years.includes(Number(state.year)))&&(state.balance==="all"||(state.balance==="surplus"?e.balance>=0:e.balance<0))&&(!q||`${e.name} ${e.code} ${e.region||""}`.toLocaleLowerCase().includes(q)));
    const descending={expenditure:"expenditure",revenue:"revenue",balance:"balance",population:"population"}[state.sort];
    return rows.sort((a,b)=>descending?(Number(b[descending])||0)-(Number(a[descending])||0)||a.name.localeCompare(b.name,state.lang):a.name.localeCompare(b.name,state.lang));
  }
  function renderDirectory(){const result=filtered();$("#country-directory-count").textContent=code==="FRA"?(state.query?`${fmt(result.length)} ${state.lang==="en"?"matches":"výsledků"}`:`${fmt(result.length)} ${state.lang==="en"?"searchable municipalities":"obcí k prohledání"}`):`${fmt(Math.min(result.length,state.shown))} ${t().shown} · ${fmt(result.length)} ${t().entities}`;$("#country-municipality-grid").innerHTML=result.slice(0,state.shown).map(e=>{const href=e.url?`${e.url}?lang=${state.lang}`:(["DEU","FRA"].includes(code)?`${assetRoot}municipalities/${slug}/profile/?code=${encodeURIComponent(e.code)}&lang=${state.lang}`:"");return `<article class="municipality-card"${href?` data-href="${esc(href)}"`:""}><header><img src="${assetRoot}assets/flags/${state.country.alpha2.toLowerCase()}.svg" alt=""><span>${esc(state.country[`name_${state.lang}`])}</span><small>${esc(e.code)}</small></header><h3>${esc(e.name)}</h3><p>${esc(e.region||state.country[`coverage_${state.lang}`])}</p><dl><div><dt>${t().revenue}</dt><dd>${money(e.revenue)}</dd></div><div><dt>${t().expenditure}</dt><dd>${money(e.expenditure)}</dd></div><div><dt>${t().result}</dt><dd class="${Number.isFinite(e.balance)?e.balance>=0?"positive":"negative":""}">${e.balance>0?"+":""}${money(e.balance)}</dd></div><div><dt>${t().population}</dt><dd>${Number.isFinite(e.population)?fmt(e.population):"—"}</dd></div></dl><footer>${e.years.map(y=>`<b>${y}</b>`).join("")}<a class="card-source" href="${esc(e.source_url||state.country.source)}" target="_blank" rel="noopener">${t().dataSource}</a>${href?`<a href="${esc(href)}">${t().detail}</a>`:""}</footer></article>`;}).join("");$("#country-load-more").hidden=state.shown>=result.length;}
  function bind(){
    document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;history.replaceState(null,"",`?lang=${state.lang}${location.hash}`);translate();});
    $("#municipality-country-switch").onchange=e=>location.href=`../${e.target.value}/?lang=${state.lang}`;
    $("#country-municipality-search").oninput=e=>{state.query=e.target.value;state.shown=48;renderDirectory();};
    $("#country-year-filter").onchange=e=>{state.year=e.target.value;state.shown=48;renderDirectory();};
    if($("#country-balance-filter"))$("#country-balance-filter").onchange=e=>{state.balance=e.target.value;state.shown=48;renderDirectory();};
    if($("#country-sort"))$("#country-sort").onchange=e=>{state.sort=e.target.value;state.shown=48;renderDirectory();};
    $("#country-reset").onclick=()=>{state.query="";state.year="all";state.balance="all";state.sort="expenditure";state.shown=48;$("#country-municipality-search").value="";$("#country-year-filter").value="all";if($("#country-balance-filter"))$("#country-balance-filter").value="all";if($("#country-sort"))$("#country-sort").value="expenditure";renderDirectory();};
    $("#country-load-more").onclick=()=>{state.shown+=48;renderDirectory();};
  }
  // One country hub loads one country shard. The index carries only country metadata,
  // which is all the picker and the coverage panels need; the 21 MB monolith is never
  // touched here. Shards drop what the country already states, so rehydrate to the shape
  // the directory renders from.
  const hydrate=shard=>{const d=shard.defaults,c=shard.country.code;return shard.entities.map(e=>({id:e.id||`${d.id_prefix}:${e.code}`,country:c,code:e.code,name:e.name,region:e.region??null,currency:e.currency||d.currency,years:e.years||d.years,revenue:e.revenue??null,expenditure:e.expenditure??null,balance:e.balance??null,population:e.population??null,source_url:e.source_url||(d.source_url_prefix?`${d.source_url_prefix}${e.code}`:null),url:e.url||(e.slug?`${d.url_prefix}${e.slug}/`:null)}));};
  const load=(path,optional=false)=>fetch(`${assetRoot}${path}`).then(r=>{if(!r.ok){if(optional)return null;throw new Error(`${path}: ${r.status}`)}return r.json()}).catch(error=>{if(!optional)throw error;console.error(error);return null});
  Promise.all([load("data/international-municipalities/index.v1.json"),load(`data/international-municipalities/${code}.v1.json`),load("data/eu-capital-budgets.v1.json"),load("data/municipal-budget-structure.v1.json",true)]).then(([index,shard,capitals,structure])=>{state.data={countries:index.countries,entities:hydrate(shard)};state.capitals=capitals.cities;state.structure=structure;state.country=index.countries.find(c=>c.code===code);if(!state.country||!profiles[code])throw new Error(`Unknown municipality country ${code}`);translate();bind();}).catch(error=>{console.error(error);$("#country-title").textContent="Data could not be loaded.";});
})();
