/* Observed payments and household-income benchmarks are deliberately separate. */
(() => {
  "use strict";
  const root = document.querySelector("#pensions-today-root");
  if (!root) return;
  const params = new URLSearchParams(location.search);
  const state = {code: (params.get("code") || "CZE").toUpperCase(), sex: params.get("pensionSex") || "total", kind: params.get("pensionType") || "all", metric:params.get("pensionMetric") === "poverty" ? "poverty" : "income", population:params.get("pensionPopulation") === "new" ? "new" : "paid", awardYear:params.get("pensionYear") || "2025", detail:params.get("pensionDetail") === "native" ? "native" : "summary", scope:params.get("pensionScope") === "all" ? "all" : "report", data: null};
  const reportCodes = ["CZE","DEU","DNK","FIN","FRA","GBR","POL","SWE","CHE","UKR","USA","BRA","ESP","JPN","NLD","NOR","GRC"];
  if (!["total", "male", "female"].includes(state.sex)) state.sex = "total";
  if (!["all", "regular", "early"].includes(state.kind)) state.kind = "all";
  const lang = () => document.documentElement.lang === "en" ? "en" : "cs";
  const tr = (en, cs) => lang() === "en" ? en : cs;
  const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;"}[c]));
  const fmt = (v, digits = 0) => Number.isFinite(v) ? v.toLocaleString(lang() === "en" ? "en-GB" : "cs-CZ", {minimumFractionDigits: digits, maximumFractionDigits: digits}) : "—";
  const name = code => state.data.countries[code]?.name[lang()] || code;
  const sexes = () => ({total:tr("All", "Celkem"), male:tr("Men", "Muži"), female:tr("Women", "Ženy")});
  const kinds = () => ({all:tr("All old-age pensions", "Všechny starobní důchody"), regular:tr("Regular pension (S)", "Řádný důchod (S)"), early:tr("Early pension (ST)", "Předčasný důchod (ST)")});
  const bandLabel = b => b.upper === null ? `${fmt(b.lower)}+` : `${fmt(b.lower)}–${fmt(b.upper)}`;
  const select = (id, label, options, value) => `<label for="${id}">${label}<select id="${id}" aria-label="${esc(label)}">${Object.entries(options).map(([v, text]) => `<option value="${v}" ${v === value ? "selected" : ""}>${text}</option>`).join("")}</select></label>`;
  const sourceLine = id => {const s = state.data.sources[id]; return `<p class="pension-source">${tr("Source", "Zdroj")}: <a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.table)}</a> · ${tr("Extracted", "Staženo")} ${s.extracted_at}</p>`;};
  const kpi = (label, value, note) => `<article><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`;
  function chart(title, rows, unit, max = null) {
    const W = 860, left = 150, right = 135, top = 42, rowH = 42, H = top + rows.length * rowH + 36;
    const ceiling = max || Math.ceil(Math.max(...rows.map(r => r.value), 1) / 10) * 10;
    const scale = v => v / ceiling * (W - left - right);
    const grid = [0, .25, .5, .75, 1].map(f => `<line x1="${left + scale(ceiling*f)}" x2="${left + scale(ceiling*f)}" y1="${top-8}" y2="${H-30}" stroke="#d2ccc1"/><text x="${left + scale(ceiling*f)}" y="${H-10}" text-anchor="middle" font-size="12">${fmt(ceiling*f, Number.isInteger(ceiling*f) ? 0 : 1)}</text>`).join("");
    return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(title)}" style="font-family:Arial,Helvetica,sans-serif;fill:#171918"><title>${esc(title)} · ${esc(unit)}</title><text x="${left}" y="18" font-size="12">${esc(unit)}</text>${grid}${rows.map((r,i) => `<g><text x="${left-12}" y="${top+i*rowH+18}" text-anchor="end" font-size="14">${esc(r.label)}</text><rect x="${left}" y="${top+i*rowH}" width="${scale(r.value)}" height="25" fill="${r.selected ? '#c93237' : '#a8b63f'}"/><text x="${W-right+12}" y="${top+i*rowH+18}" font-size="14">${esc(r.display || fmt(r.value,1))}</text><title>${esc(r.label)}: ${esc(r.display || fmt(r.value,1))}</title></g>`).join("")}</svg>`;
  }
  function register(el, slug, title, rows, columns, sourceId, definition, caveat, excludes) {
    const s = state.data.sources[sourceId];
    window.PSDChart.register({el, slug, title, rows: () => rows.map(row => Object.fromEntries(Object.entries(row).map(([key, value]) => [key, typeof value === "number" ? Math.round(value * 100) / 100 : value]))), columns, embeddable:false, exports:["csv", "png"],
      source:{name:({cssz:"ČSSZ",ssa:"Social Security Administration",dwp:"Department for Work and Pensions",drees_level:"DREES",drees_cohort:"DREES"})[sourceId] || (sourceId.startsWith("cssz") ? "ČSSZ" : "OECD"), url:s.url, table:s.table, edition:String(s.year || 2025), extracted:s.extracted_at, vintage:"outturn", definition, caveat, excludes}});
  }
  function czechBands(d) {
    if (state.detail === "native" || (state.population === "new" && Number(state.awardYear) < 2025)) return d.bands.map(b=>({...b,value:b.count/d.count*100,label:bandLabel(b),display:`${fmt(b.count/d.count*100,1)} %`}));
    const groups = [[1,14999],[15000,17999],[18000,20999],[21000,23999],[24000,26999],[27000,29999],[30000,null]];
    return groups.map(([lower, upper]) => {
      const count = d.bands.filter(b => b.lower >= lower && (upper === null || (b.upper !== null && b.upper <= upper))).reduce((sum,b) => sum+b.count,0);
      const value = count/d.count*100;
      return {lower, upper, count, value, label:bandLabel({lower,upper}), display:`${fmt(value,1)} %`};
    });
  }
  const selectedCzech = p => state.population === "new" ? p.awards_by_year[state.awardYear][state.sex][state.kind] : p.distribution[state.sex][state.kind];
  const awardDefinition = () => tr("Newly awarded old-age pensions in Czechia, at their award-year amounts. This is a flow of awards during the year, not current payments to surviving members of that cohort. Coverage differs from the standalone pensions paid at year-end.", "Nově přiznané starobní důchody v ČR v částkách roku přiznání. Jde o přiznání během roku, nikoli o dnešní výplaty žijícím příjemcům daného ročníku. Pokrytí se liší od sólo důchodů vyplácených na konci roku.");
  const awardCaveat = () => tr("Nominal CZK at award, without inflation or subsequent pension increases. A higher starting amount is not evidence that earlier retirees receive less today. Year-end recipients include recent awards; subtracting the two populations would not yield older retirees.", "Nominální Kč při přiznání, bez očištění o inflaci a následné valorizace. Vyšší nástupní částka nedokazuje, že dřívější důchodci dnes dostávají méně. Stav na konci roku zahrnuje i nové důchodce; odečtením těchto dvou skupin nelze získat starší důchodce.");
  function bandTable(d) {
    return `<div class="pension-chart-scroll" tabindex="0" role="region" aria-label="${esc(tr("Pension chart and data", "Důchodový graf a data"))}"><table class="pension-data-table"><thead><tr><th>${tr("CZK / month","Kč / měsíc")}</th><th>${tr("Count","Počet")}</th><th>%</th></tr></thead><tbody>${d.bands.map(b=>`<tr><th scope="row">${bandLabel(b)}</th><td>${fmt(b.count)}</td><td>${fmt(b.count/d.count*100,2)}</td></tr>`).join("")}${d.unknown_count ? `<tr><th>${tr("Unknown amount","Neudaná částka")}</th><td>${fmt(d.unknown_count)}</td><td>${fmt(d.unknown_count/d.count*100,2)}</td></tr>` : ""}</tbody><tfoot><tr><th>${tr("Total","Celkem")}</th><td>${fmt(d.count)}</td><td>100</td></tr></tfoot></table></div>`;
  }
  function awardRows(p) {
    return Object.entries(p.awards_by_year).map(([year,sexes])=>({year:Number(year),mean:sexes[state.sex][state.kind].mean,count:sexes[state.sex][state.kind].count}));
  }
  function awardAnalysis(p) {
    const rows=awardRows(p), latest=rows.at(-1), previous=rows.at(-2), paid=p.distribution[state.sex][state.kind];
    const difference=latest.mean-paid.mean, change=latest.mean-previous.mean;
    const signed=(v,digits=0)=>`${v>0?"+":""}${fmt(v,digits)}`;
    const title=tr("How much did each new retirement cohort start with?","S jakým důchodem začínaly jednotlivé ročníky?");
    return `<figure class="pension-figure" id="pension-award-history"><h3>${title}</h3><p>${sexes()[state.sex]} · ${kinds()[state.kind]} · ${tr("Mean monthly amount at award, 2008–2025. These are not today's payments.","Průměrná měsíční částka při přiznání, 2008–2025. Nejde o dnešní výplaty.")}</p><div class="pension-chart-scroll" tabindex="0" role="region" aria-label="${esc(tr("Pension chart and data", "Důchodový graf a data"))}">${chart(title,rows.map(r=>({label:String(r.year),value:r.mean,display:`${fmt(r.mean)} Kč`,selected:r.year===Number(state.awardYear)})),tr("CZK/month at award","Kč/měsíc při přiznání"))}</div>${sourceLine("cssz_award_means")}<p>${awardCaveat()}</p></figure><aside class="pension-question"><h3>${tr("Do newer retirees receive more?","Dostávají noví důchodci více?")}</h3><p>${tr("For the selected sex and pension type, the 2025 award mean is","Pro vybrané pohlaví a druh důchodu činí průměr při přiznání v roce 2025")} <strong>${fmt(latest.mean)} Kč</strong> (${signed(change)} Kč ${tr("versus awards in 2024","oproti přiznáním v roce 2024")}). ${tr("The mean standalone payment at end-2025 is","Průměrná sólo výplata ke konci roku 2025 činí")} <strong>${fmt(paid.mean)} Kč</strong>. ${tr("The descriptive difference is","Popisný rozdíl činí")} <strong>${signed(difference)} Kč (${signed(difference/paid.mean*100,1)} %)</strong>.</p><p>${awardDefinition()} ${awardCaveat()}</p><p>${tr("The overall distribution also depends on the mix of regular and early pensions and recipients' sex, earnings and contribution years. Use the filters to inspect this composition. These aggregate tables cannot isolate the effect of retirement timing or judge fairness: that requires current payments at one common date linked to award year and comparable contribution and earnings histories.","Celkové rozdělení závisí také na poměru řádných a předčasných důchodů, pohlaví, výdělcích a délce pojištění příjemců. Složení si lze prohlédnout pomocí filtrů. Souhrnné tabulky neumožňují oddělit vliv načasování odchodu ani posoudit spravedlnost: k tomu jsou potřeba výplaty ke stejnému datu propojené s rokem přiznání a srovnatelnou historií pojištění a výdělků.")}</p></aside>`;
  }
  function national() {
    const p = state.data.countries[state.code]?.national;
    if (p?.payment_by_age || p?.payment_by_scheme || p?.payment_by_birth_year) return extendedNational(p);
    if (!p?.distribution) return `<p class="pension-note">${tr("A national payment distribution has not been loaded for this country. The international income and poverty comparison is shown below where available. Missing values are not zero.", "Pro tuto zemi není načteno národní rozdělení vyplácených částek. Mezinárodní srovnání příjmů a chudoby je níže, pokud jsou údaje dostupné. Chybějící hodnoty nejsou nula.")}</p><p class="pension-note">${tr("Explore national detail:", "Prohlédnout národní detail:")} ${["CZE","USA","GBR","FRA"].map(code=>`<a href="?code=${code}&lang=${lang()}#pensions-today">${esc(name(code))}</a>`).join(" · ")}</p>`;
    if (!p.awards_by_year[state.awardYear]) state.awardYear = "2025";
    const d = selectedCzech(p);
    const thresholdKnown = !d.bands.some(b=>b.lower < 15000 && (b.upper === null || b.upper >= 15000));
    const under = d.bands.filter(b => b.upper !== null && b.upper < 15000).reduce((sum,b) => sum+b.count,0);
    const rows = czechBands(d);
    const scope = state.population === "new" ? awardDefinition() : tr("Standalone old-age pensions paid by ČSSZ in Czechia. Excludes pensions paid together with a survivor pension and payments abroad. All ages of recipients are included.", "Sólo starobní důchody vyplácené ČSSZ v ČR. Bez souběhu s pozůstalostním důchodem a bez výplat do zahraničí. Zahrnuje všechny věkové skupiny příjemců.");
    const title = tr("Who receives how much?", "Kdo dostává kolik?");
    return `<div class="pension-controls">${select("pension-sex", tr("Recipients", "Příjemci"), sexes(), state.sex)}${select("pension-type", tr("Pension type", "Druh důchodu"), kinds(), state.kind)}${select("pension-population",tr("Population","Skupina"),{paid:tr("Paid at end-2025","Vyplácené ke konci 2025"),new:tr("Newly awarded","Nově přiznané")},state.population)}${state.population === "new" ? select("pension-year",tr("Award year","Rok přiznání"),Object.fromEntries(Object.keys(p.awards_by_year).reverse().map(y=>[y,y])),state.awardYear) : ""}${select("pension-detail",tr("Amount bands","Pásma částek"),{summary:tr("Overview","Přehled"),native:tr("Detailed source bands","Podrobná zdrojová pásma")},state.detail)}<p>${tr("Period", "Období")} <strong>${state.population === "new" ? state.awardYear : p.date}</strong><br>CZK / ${tr("month", "měsíc")}</p></div>
      <p class="pension-note">${scope}</p>
      <div class="aging-kpis pension-kpis">${kpi(tr("Average pension", "Průměrný důchod"),`${fmt(d.mean)} Kč`,tr("Published mean", "Publikovaný průměr"))}${kpi(tr("Median payment band", "Pásmo mediánu"),bandLabel(d.median_band),tr("CZK/month · exact median unavailable", "Kč/měsíc · přesný medián není dostupný"))}${kpi(tr("Below CZK 15,000", "Pod 15 000 Kč"),thresholdKnown ? `${fmt(under/d.count*100,1)} %` : "—",thresholdKnown ? `${fmt(under)} ${tr("recipients", "příjemců")}` : tr("Source band crosses the threshold", "Zdrojové pásmo překračuje hranici"))}${kpi(tr("Recipients covered", "Pokrytí příjemci"),fmt(d.count),`${sexes()[state.sex]} · ${kinds()[state.kind]}`)}</div>
      <figure class="pension-figure" id="pension-distribution"><h3>${title}</h3><p>${tr("Monthly pension bands in CZK. Bars show the share of the selected group; the table gives exact counts. Historical years retain their original bands.", "Pásma měsíčního důchodu v Kč. Sloupce ukazují podíl vybrané skupiny; tabulka obsahuje přesné počty. Historické roky zachovávají původní pásma.")}</p><div class="pension-chart-scroll" tabindex="0" role="region" aria-label="${esc(tr("Pension chart and data", "Důchodový graf a data"))}">${chart(title,rows,tr("% of recipients", "% příjemců"))}</div>${sourceLine(state.population === "new" ? "cssz_awards" : "cssz")}${state.population === "new" ? sourceLine("cssz_award_means") : ""}<details class="pension-method"><summary>${tr("Exact counts by amount band", "Přesné počty podle částky")}</summary>${bandTable(d)}</details></figure>
      ${awardAnalysis(p)}`;
  }

  const usDefinition = () => tr("Average monthly Social Security retired-worker benefit by current age and sex, December 2025. All beneficiaries in this SSA category, including those living abroad. It excludes private pensions, earnings and other income.", "Průměrná měsíční dávka Social Security pro starobní důchodce podle současného věku a pohlaví, prosinec 2025. Všichni příjemci v této kategorii SSA, včetně žijících v zahraničí. Bez soukromých penzí, výdělků a dalších příjmů.");
  const ukDefinition = () => tr("Mean weekly State Pension paid under the pre-2016 and new systems, August 2025. DWP coverage: Great Britain and overseas recipients, excluding separately administered Northern Ireland cases. New-system amounts include protected payments.", "Průměrný týdenní státní důchod podle systému před rokem 2016 a nového systému, srpen 2025. Pokrytí DWP: Velká Británie a příjemci v zahraničí, bez samostatně spravovaných případů v Severním Irsku. Nový systém zahrnuje chráněné doplatky.");
  const frDefinition = () => tr("Gross monthly direct pension, including the supplement for three or more children, for recipients resident in France. Birth cohorts 1930–1953 from DREES EIR 2020, at 31 December 2020. Full-career recipients are a separate subset. Birth year is not retirement year.", "Hrubý měsíční přímý důchod včetně příplatku za tři a více dětí, příjemci žijící ve Francii. Ročníky narození 1930–1953 ze šetření DREES EIR 2020, stav k 31. prosinci 2020. Příjemci s úplnou kariérou jsou samostatnou podskupinou. Rok narození není rok přiznání důchodu.");
  function cohortChart(rows) {
    const W=860,H=330,L=65,R=30,T=32,B=44,max=2500;
    const x=y=>L+(y-1930)/23*(W-L-R), y=v=>T+(max-v)/max*(H-T-B);
    return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(tr("Pension by birth year, 2020", "Důchod podle roku narození, 2020"))}" style="font-family:Arial,Helvetica,sans-serif;fill:#171918"><title>${esc(frDefinition())}</title>${[0,500,1000,1500,2000,2500].map(v=>`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#d2ccc1"/><text x="${L-10}" y="${y(v)+4}" text-anchor="end" font-size="12">${fmt(v)}</text>`).join("")}${[["mean","#a8b63f"],["full_career_mean","#8b8d83"]].map(([key,color])=>`<polyline points="${rows.map(r=>`${x(r.birth_year)},${y(r[key])}`).join(" ")}" fill="none" stroke="${color}" stroke-width="3"/>`).join("")}${[1930,1935,1940,1945,1950,1953].map(v=>`<text x="${x(v)}" y="${H-20}" font-size="12" text-anchor="middle">${v}</text>`).join("")}<text x="${L}" y="17" font-size="12">EUR / ${tr("month · 2020", "měsíc · 2020")}</text></svg>`;
  }
  function franceBands(p) {
    return [[0,500],[500,1000],[1000,1500],[1500,2000],[2000,2500],[2500,3000],[3000,4500],[4500,null]].map(([lo,hi])=>({
      label:lo===0?`≤ ${fmt(hi)}`:hi===null?`> ${fmt(lo)}`:`> ${fmt(lo)}–${fmt(hi)}`,
      value:p.distribution_pct[state.sex].filter(b=>hi===null?b.upper===null:b.upper!==null&&b.upper>lo&&b.upper<=hi).reduce((sum,b)=>sum+b.share,0)
    }));
  }
  function extendedNational(p) {
    const controls=`<div class="pension-controls">${select("pension-sex",tr("Recipients", "Příjemci"),sexes(),state.sex)}<p>${tr("Latest payment snapshot", "Poslední načtený stav výplat")}: <strong>${p.date}</strong></p></div>`;
    if (p.payment_by_age) {
      const d=p.payment_by_age[state.sex], younger=d.ages.find(r=>r.age==="70–74"),older=d.ages.find(r=>r.age==="85–89"),gap=(older.mean/younger.mean-1)*100;
      const title=tr("Social Security payments by age", "Výplaty Social Security podle věku");
      return `${controls}<p class="pension-note">${usDefinition()}</p><div class="aging-kpis pension-kpis">${kpi(tr("Average monthly benefit", "Průměrná měsíční dávka"),`$${fmt(d.mean,2)}`,`${sexes()[state.sex]} · ${p.date}`)}${kpi(tr("Ages 70–74", "Věk 70–74"),`$${fmt(younger.mean,2)}`,tr("mean per month", "průměr za měsíc"))}${kpi(tr("85–89 versus 70–74", "85–89 vůči 70–74"),`${gap>0?"+":""}${fmt(gap,1)} %`,tr("relative difference in benefits", "relativní rozdíl dávek"))}${kpi(tr("Recipients covered", "Pokrytí příjemci"),fmt(d.count),tr("retired-worker benefits", "starobní dávky pracovníků"))}</div><figure class="pension-figure" id="pension-national-detail"><h3>${title}</h3><p>${tr("Current age, not age when benefits were first claimed.", "Současný věk, nikoli věk při prvním přiznání dávky.")}</p><div class="pension-chart-scroll" tabindex="0" role="region" aria-label="${esc(title)}">${chart(title,d.ages.map(r=>({label:r.age,value:r.mean,display:`$${fmt(r.mean,2)}`})),tr("USD/month", "USD/měsíc"))}</div>${sourceLine("ssa")}</figure><aside class="pension-question"><h3>${tr("Payments do not simply fall with age", "Výplaty s věkem neklesají rovnoměrně")}</h3><p>${tr("The age profile also reflects early-claim reductions, delayed-claim credits, lifetime earnings, survivor patterns and different generations. This is a snapshot of different people, not a forecast of one person’s future benefit.", "Věkový profil odráží také krácení za předčasné čerpání, zvýšení za odklad, celoživotní výdělky, strukturu přeživších a různé generace. Jde o pohled na různé lidi v jednom okamžiku, nikoli předpověď budoucí dávky jednotlivce.")}</p></aside>`;
    }
    if (p.payment_by_scheme) {
      const d=p.payment_by_scheme[state.sex],gap=(d.new/d.pre_2016-1)*100;
      const title=tr("Old and new State Pension systems", "Starý a nový systém státního důchodu");
      return `${controls}<p class="pension-note">${ukDefinition()}</p><div class="aging-kpis pension-kpis">${kpi(tr("Pre-2016 system", "Systém před rokem 2016"),`£${fmt(d.pre_2016,2)}`,tr("mean per week", "průměr za týden"))}${kpi(tr("New system", "Nový systém"),`£${fmt(d.new,2)}`,tr("mean per week", "průměr za týden"))}${kpi(tr("New versus old", "Nový vůči starému"),`${gap>0?"+":""}${fmt(gap,1)} %`,tr("observed difference", "pozorovaný rozdíl"))}${kpi(tr("Scheme boundary", "Hranice systémů"),tr("6 Apr 2016","6. 4. 2016"),tr("date of reaching State Pension age", "datum dosažení státního důchodového věku"))}</div><figure class="pension-figure" id="pension-national-detail"><h3>${title}</h3>${chart(title,[{label:tr("Pre-2016", "Před 2016"),value:d.pre_2016,display:`£${fmt(d.pre_2016,2)}`},{label:tr("New system", "Nový systém"),value:d.new,display:`£${fmt(d.new,2)}`}],tr("GBP/week", "GBP/týden"))}${sourceLine("dwp")}</figure><aside class="pension-question"><h3>${tr("The answer differs for men and women", "Výsledek se liší u mužů a žen")}</h3><p>${tr("In this snapshot, women receive more on average under the new system, while men receive more under the old system. Use the recipient filter to see the difference. These are different groups of people; contribution records, additional pensions and overseas residence also matter.", "V tomto období mají ženy vyšší průměr v novém systému, muži ve starém. Rozdíl zobrazí filtr příjemců. Jde o různé skupiny lidí; záleží také na historii pojištění, dodatečných nárocích a pobytu v zahraničí.")}</p></aside>`;
    }
    const m=p.means[state.sex],cohorts=p.payment_by_birth_year[state.sex],title=tr("Pension payments by birth year", "Vyplácené důchody podle roku narození");
    return `${controls}<p class="pension-note">${tr("Gross monthly pensions for direct-pension recipients resident in France. Includes the supplement for three or more children. DREES estimates, 2023.", "Hrubé měsíční důchody příjemců přímého důchodu žijících ve Francii. Včetně příplatku za tři a více dětí. Odhady DREES, 2023.")}</p><div class="aging-kpis pension-kpis">${kpi(tr("Own pension", "Vlastní důchod"),`${fmt(m.direct)} €`,tr("gross/month · 2023", "hrubého/měsíc · 2023"))}${kpi(tr("Including survivor rights", "Včetně pozůstalostních nároků"),`${fmt(m.combined)} €`,tr("gross/month · 2023", "hrubého/měsíc · 2023"))}${kpi(tr("Distribution snapshot", "Rozdělení částek k roku"),"2020",tr("latest loaded detailed survey", "poslední načtené detailní šetření"))}${kpi(tr("Birth cohorts", "Ročníky narození"),"1930–1953",tr("common observation date: end-2020", "společné datum: konec 2020"))}</div>${sourceLine("drees_level")}<figure class="pension-figure" id="pension-france-distribution"><h3>${tr("Monthly pension distribution · 2020", "Rozdělení měsíčních důchodů · 2020")}</h3><p>${tr("Gross direct pensions in EUR. Shares are rounded by the source and may not sum to exactly 100%.", "Hrubé přímé důchody v EUR. Podíly jsou zaokrouhlené zdrojem a jejich součet nemusí být přesně 100 %.")}</p><div class="pension-chart-scroll" tabindex="0" role="region" aria-label="${esc(title)}">${chart(tr("Pension distribution", "Rozdělení důchodů"),franceBands(p),tr("% of recipients", "% příjemců"))}</div>${sourceLine("drees_level")}</figure><figure class="pension-figure" id="pension-national-detail"><h3>${title} · 2020</h3><p>${frDefinition()}</p><div class="pension-cohort-legend"><span><i></i>${sexes()[state.sex]} · ${tr("all careers", "všechny kariéry")}</span><span><i></i>${tr("Full careers only", "Pouze úplné kariéry")}</span></div><div class="pension-chart-scroll" tabindex="0" role="region" aria-label="${esc(title)}">${cohortChart(cohorts)}</div><p class="pension-note">${tr("All plotted cohorts use the common end-2020 observation. More recent cohorts measured in later years are excluded. A full career does not mean identical earnings or identical pension rules.", "Všechny zobrazené ročníky používají společné pozorování ke konci roku 2020. Novější ročníky měřené v pozdějších letech jsou vynechány. Úplná kariéra neznamená stejné výdělky ani stejná důchodová pravidla.")}</p>${sourceLine("drees_cohort")}</figure>`;
  }
  const incomeDefinition = () => tr("Average disposable household income per person, adjusted for household size, relative to the average for the whole population. Includes pensions, earnings, investments and other transfers, after taxes. Housing wealth and public services are excluded.", "Průměrný disponibilní příjem domácnosti na osobu, upravený o velikost domácnosti, vůči průměru celé populace. Zahrnuje důchody, výdělky, investice a ostatní transfery po zdanění. Nezahrnuje hodnotu bydlení ani veřejné služby.");
  const povertyDefinition = () => tr("Share of people below 50% of their country’s median equivalised disposable household income. This relative threshold differs by country and year.", "Podíl osob pod 50 % národního mediánu ekvivalizovaného disponibilního příjmu domácnosti. Tato relativní hranice se liší podle země a roku.");
  const benchmarkCaveat = () => tr("Age groups observed in the same year within each country, not the same people followed over time. Countries use different observation years. Work, household composition, earnings histories and survivor benefits can affect the gap; it does not establish unequal treatment by pension rules.", "Věkové skupiny pozorované ve stejném roce v rámci země, nikoli stejní lidé sledovaní v čase. Země mají různé referenční roky. Rozdíl může ovlivňovat práce, složení domácnosti, výdělková historie a pozůstalostní důchody; sám nedokazuje nerovné zacházení důchodových pravidel.");
  function benchmarkRows() {
    return Object.entries(state.data.countries).filter(([code,p]) => p[state.metric] && code !== "OECD" && (state.scope === "all" || reportCodes.includes(code))).map(([code,p]) => {
      const m=p[state.metric];
      return {code, label:name(code), younger:m.age_66_75, older:m.age_76_plus, year:m.year, selected:code===state.code, value:state.metric === "income" ? m.age_76_plus/m.age_66_75*100 : m.age_76_plus, gap:m.age_76_plus-m.age_66_75};
    }).sort((a,b)=>a.value-b.value || a.label.localeCompare(b.label));
  }
  function benchmark() {
    if (!state.data.sources.income) return "";
    const p=state.data.countries[state.code], inc=p?.income, pov=p?.poverty;
    const income=state.metric === "income";
    const rows=benchmarkRows();
    const oecd=state.data.countries.OECD[state.metric];
    const oecdValue=income ? oecd.age_76_plus/oecd.age_66_75*100 : oecd.age_76_plus;
    const title=income ? tr("Income after 75 relative to ages 66–75", "Příjem po 75 letech vůči věku 66–75") : tr("Poverty after age 75", "Chudoba po 75 letech");
    const unit=income ? tr("Ages 66–75 = 100 within each country", "Věk 66–75 = 100 v každé zemi") : tr("% of people aged 76+", "% osob ve věku 76+");
    const gap=inc ? (inc.age_76_plus/inc.age_66_75-1)*100 : null;
    return `<section class="aging-section pension-section" id="pension-benchmark"><div class="aging-heading"><div><span class="kicker">OECD · ${tr("37 countries", "37 zemí")}</span><h2>${tr("Older people, benchmarked", "Senioři v mezinárodním srovnání")}</h2></div><p>${tr("Comparable household income and poverty by age. These measure living standards, not the pension cheque alone. OECD’s 2025 edition uses observations from 2017–2023.", "Srovnatelný příjem domácností a chudoba podle věku. Měří životní úroveň, nikoli samotný důchod. Vydání OECD 2025 používá pozorování z let 2017–2023.")}</p></div>
      ${inc ? `<h3 class="pension-country-heading">${esc(name(state.code))} · ${inc.year}</h3><div class="aging-kpis pension-kpis">${kpi(tr("Income, ages 66–75", "Příjem ve věku 66–75"),`${fmt(inc.age_66_75,1)} %`,tr("of whole-population average", "průměru celé populace"))}${kpi(tr("Income, ages 76+", "Příjem ve věku 76+"),`${fmt(inc.age_76_plus,1)} %`,tr("of whole-population average", "průměru celé populace"))}${kpi(tr("76+ versus 66–75", "76+ vůči 66–75"),`${gap>0?"+":""}${fmt(gap,1)} %`,tr("relative difference in income", "relativní rozdíl příjmů"))}${kpi(tr("Poverty, ages 76+", "Chudoba ve věku 76+"),`${fmt(pov.age_76_plus,1)} %`,`${tr("Ages 66–75", "Věk 66–75")}: ${fmt(pov.age_66_75,1)} %`)}</div>` : `<p class="pension-note">${tr("This OECD edition has no comparable age-income observation for", "Toto vydání OECD nemá srovnatelné údaje o příjmu podle věku pro")} ${esc(name(state.code))}. ${tr("Other countries remain available below.", "Ostatní země jsou dostupné níže.")}</p>`}
      <div class="pension-controls">${select("pension-metric",tr("Compare", "Porovnat"),{income:tr("Income difference by age", "Rozdíl příjmů podle věku"),poverty:tr("Poverty by age", "Chudoba podle věku")},state.metric)}${select("pension-scope",tr("Countries", "Země"),{report:tr("Report countries", "Země reportu"),all:tr("All 37 countries", "Všech 37 zemí")},state.scope)}</div>
      <figure class="pension-figure" id="pension-benchmark-chart"><h3>${title}</h3><p>${income ? incomeDefinition() : povertyDefinition()}</p><div class="pension-chart-scroll" tabindex="0" role="region" aria-label="${esc(title)}">${chart(title,[...rows,{label:tr("OECD average", "Průměr OECD"),value:oecdValue}],unit,income?120:60)}</div><p class="pension-note">${income ? tr("Below 100 means lower income after 75. Calculated as (income at 76+ ÷ income at 66–75) × 100. The OECD reference is the ratio of the published age-group averages.", "Pod 100 znamená nižší příjem po 75 letech. Výpočet: (příjem 76+ ÷ příjem 66–75) × 100. Referenční hodnota OECD je poměr publikovaných průměrů věkových skupin.") : povertyDefinition()} ${tr("The red bar marks the selected country. See the table for source years and both age groups.", "Červený sloupec označuje vybranou zemi. Tabulka uvádí referenční roky i obě věkové skupiny.")}</p>${sourceLine(state.metric)}</figure>
      <aside class="pension-question"><h3>${tr("An age gap is not a verdict on fairness", "Věkový rozdíl není verdikt o spravedlnosti")}</h3><p>${benchmarkCaveat()}</p><p>${tr("To test whether earlier retirees are disadvantaged, we need current payments by retirement year and comparable earnings and contribution histories. We do not substitute these age groups for retirement cohorts.", "Pro ověření znevýhodnění dřívějších důchodců potřebujeme současné výplaty podle roku přiznání a srovnatelnou historii výdělků a pojištění. Věkové skupiny nenahrazují skupiny podle roku přiznání.")}</p></aside>
      <details class="pension-method"><summary>${tr("Coverage, definitions and downloadable data", "Pokrytí, definice a data ke stažení")}</summary><p>${incomeDefinition()}</p><p>${povertyDefinition()}</p><p>${tr("The international age and sex splits are separate; an age × sex cross-tabulation is not supplied. Colombia has no observation in these tables. Brazil and Ukraine are outside their coverage.", "Mezinárodní členění podle věku a pohlaví je oddělené; kombinace věk × pohlaví není k dispozici. Kolumbie nemá v tabulkách pozorování. Brazílie a Ukrajina jsou mimo jejich pokrytí.")}</p><p>${tr("Source edition: OECD Pensions at a Glance 2025, Income Distribution Database, June 2025 vintage. Most observations are 2022; individual source years are preserved in every downloaded row.", "Vydání zdroje: OECD Pensions at a Glance 2025, Income Distribution Database, verze červen 2025. Většina pozorování je za rok 2022; každý stažený řádek zachovává svůj referenční rok.")}</p><a href="../../data/pensions-today.v1.json">${tr("Download the complete dataset (JSON)", "Stáhnout celý datový soubor (JSON)")}</a></details></section>`;
  }
  function render() {
    if (!state.data) return;
    root.innerHTML = `<section class="aging-section pension-section" id="pensions-today"><div class="aging-heading"><div><span class="kicker">${tr("Observed pensions", "Vyplácené důchody")} · ${esc(name(state.code))}</span><h2>${tr("Pensions today", "Důchody dnes")}</h2></div><p>${tr("What people actually receive, how payments are distributed, and what the data can tell us about older and newer retirees. Latest loaded observations, with their dates shown.", "Kolik lidé skutečně dostávají, jak jsou částky rozdělené a co data říkají o dřívějších a novějších důchodcích. Nejnovější načtené údaje s uvedeným obdobím.")}</p></div>${national()}</section>${benchmark()}`;
    [ ["pension-population","population","pensionPopulation"], ["pension-year","awardYear","pensionYear"], ["pension-detail","detail","pensionDetail"], ["pension-sex","sex","pensionSex"], ["pension-type","kind","pensionType"], ["pension-metric","metric","pensionMetric"], ["pension-scope","scope","pensionScope"] ].forEach(([id,key,param]) => document.getElementById(id)?.addEventListener("change", event => {
      state[key] = event.target.value;
      const url = new URL(location.href); url.searchParams.set(param,state[key]); history.replaceState({},"",url); render(); document.getElementById(id)?.focus();
    }));
    if (state.data.sources.income) {
      const income=state.metric === "income";
      const oecd=state.data.countries.OECD[state.metric];
      const rows=[...benchmarkRows(),{label:name("OECD"),younger:oecd.age_66_75,older:oecd.age_76_plus,year:tr("Mixed years", "Různé roky"),gap:oecd.age_76_plus-oecd.age_66_75}];
      register(document.getElementById("pension-benchmark-chart"), "ageing-older-income-benchmark",tr("Older people, benchmarked", "Senioři v mezinárodním srovnání") + " · " + (income ? tr("Income", "Příjem") : tr("Poverty", "Chudoba")),
        rows.map(r=>({...r,index:r.older/r.younger*100,unit:income?tr("% of population average income", "% průměrného příjmu populace"):tr("% below poverty threshold", "% pod hranicí chudoby")})),
        [{key:"label",label:tr("Country","Země")},{key:"year",label:tr("Source year","Referenční rok")},{key:"younger",label:"66–75",numeric:true},{key:"older",label:"76+",numeric:true},{key:"gap",label:tr("Difference (percentage points)","Rozdíl (procentní body)"),numeric:true},...(income?[{key:"index",label:tr("Index: 66–75 = 100","Index: 66–75 = 100"),numeric:true}]:[]),{key:"unit",label:tr("Unit","Jednotka")}],state.metric,income?incomeDefinition():povertyDefinition(),benchmarkCaveat(),tr("Individual pension payment amounts and retirement-year cohorts.","Jednotlivé vyplácené důchody a skupiny podle roku přiznání."));
    }
    const p = state.data.countries[state.code]?.national;
    if (p?.payment_by_age || p?.payment_by_scheme || p?.payment_by_birth_year) {
      let rows, columns, definition, sourceId=p.source_id;
      const groupColumn={key:"group",label:tr("Group", "Skupina")};
      const meanColumn={key:"mean",label:tr("Mean payment", "Průměrná výplata"),numeric:true};
      if (p.payment_by_age) {
        rows=p.payment_by_age[state.sex].ages.map(r=>({group:r.age,mean:r.mean,count:r.count}));
        columns=[groupColumn,meanColumn,{key:"count",label:tr("Recipients","Příjemci"),numeric:true}];definition=usDefinition();
      } else if (p.payment_by_scheme) {
        const d=p.payment_by_scheme[state.sex];
        rows=[{group:tr("Pre-2016", "Před 2016"),mean:d.pre_2016},{group:tr("New system", "Nový systém"),mean:d.new}];
        columns=[groupColumn,meanColumn];definition=ukDefinition();
      } else {
        rows=p.payment_by_birth_year[state.sex].map(r=>({group:r.birth_year,mean:r.mean,full_career_mean:r.full_career_mean}));
        columns=[{key:"group",label:tr("Birth year","Rok narození")},meanColumn,{key:"full_career_mean",label:tr("Full-career mean", "Průměr za úplné kariéry"),numeric:true}];definition=frDefinition();sourceId="drees_cohort";
        register(document.getElementById("pension-france-distribution"), "ageing-france-pension-distribution",`France · ${tr("Monthly pension distribution", "Rozdělení měsíčních důchodů")} · 2020 · ${sexes()[state.sex]}`,
          franceBands(p).map(r=>({band:r.label,share:r.value,date:p.distribution_date,sex:state.sex})),[{key:"band",label:tr("Monthly pension (EUR)","Měsíční důchod (EUR)")},{key:"share",label:"%",numeric:true},{key:"date",label:tr("Date","Datum")},{key:"sex",label:tr("Sex","Pohlaví")}],"drees_level",tr("Gross direct pension amounts among residents of France, including child supplements. DREES EIR 2020.","Hrubé přímé důchody rezidentů Francie včetně příplatků za děti. DREES EIR 2020."),tr("Rounded published shares; not comparable to Czech standalone-pension coverage.","Zaokrouhlené publikované podíly; odlišné pokrytí od českých sólo důchodů."),tr("Survivor rights, other income and non-residents.","Pozůstalostní nároky, ostatní příjmy a nerezidenti."));
      }
      const date=p.birth_year_date || p.date;
      register(document.getElementById("pension-national-detail"), "ageing-national-pension-payments",`${name(state.code)} · ${tr("Pension payments", "Vyplácené důchody")} · ${date} · ${sexes()[state.sex]}`,
        rows.map(r=>({...r,date,currency:p.currency,frequency:p.frequency,sex:state.sex})),[...columns,{key:"date",label:tr("Date","Datum")},{key:"currency",label:tr("Currency","Měna")},{key:"frequency",label:tr("Payment period","Období platby")},{key:"sex",label:tr("Sex","Pohlaví")}],sourceId,definition,benchmarkCaveat(),tr("Other income and an adjusted causal estimate of pension-rule fairness.","Ostatní příjmy a očištěný kauzální odhad spravedlnosti důchodových pravidel."));
    }
    if (p?.distribution) {
      const d=selectedCzech(p);
      register(document.getElementById("pension-award-history"), "ageing-czech-pension-award-history", tr("Pensions by award year","Důchody podle roku přiznání"), awardRows(p).map(r=>({...r,sex:state.sex,type:state.kind})), [{key:"year",label:tr("Award year","Rok přiznání")},{key:"mean",label:"CZK",numeric:true},{key:"count",label:tr("Awards","Přiznání"),numeric:true},{key:"sex",label:tr("Sex","Pohlaví")},{key:"type",label:tr("Type","Druh")}], "cssz_award_means", awardDefinition(), awardCaveat(), tr("Current cohort payments","Dnešní výplaty podle ročníku přiznání"));
      register(document.getElementById("pension-distribution"), "ageing-pension-payment-distribution", `${name(state.code)} · ${tr("Monthly pension distribution", "Rozdělení měsíčních důchodů")} · ${state.population === "new" ? state.awardYear : p.date} · ${state.population === "new" ? tr("New awards","Nová přiznání") : tr("Paid","Vyplácené")} · ${sexes()[state.sex]} · ${kinds()[state.kind]}`,
        czechBands(d).map(b=>({band:b.label,count:b.count,share:b.value,date:state.population === "new" ? state.awardYear : p.date,population:state.population,currency:p.currency,sex:state.sex,type:state.kind})),
        [{key:"band",label:tr("Monthly pension (CZK)","Měsíční důchod (Kč)")},{key:"count",label:tr("Recipients","Příjemci"),numeric:true},{key:"share",label:"%",numeric:true},{key:"population",label:tr("Population","Skupina")},{key:"date",label:tr("Date","Datum")},{key:"sex",label:tr("Sex","Pohlaví")},{key:"type",label:tr("Pension type","Druh důchodu")}], state.population === "new" ? "cssz_awards" : "cssz",
        state.population === "new" ? awardDefinition() : tr("Monthly standalone old-age pensions. Published mean; the median is reported only as a source band.","Měsíční sólo starobní důchody. Publikovaný průměr; medián je uveden pouze jako zdrojové pásmo."),
        tr("No age × amount or retirement-year × current-payment cross-tabulation is available in these tables.","Tabulky neobsahují propojení věku ani roku přiznání s dnešní částkou."),
        state.population === "new" ? tr("Current payments to historical award cohorts and other income.","Současné výplaty historickým ročníkům přiznání a ostatní příjmy.") : tr("Survivor-pension combinations, payments abroad, other income and pensions administered outside ČSSZ.","Souběhy s pozůstalostními důchody, výplaty do zahraničí, ostatní příjmy a důchody mimo správu ČSSZ."));
    }
  }
  addEventListener("countryprofilechange", event => {state.code=event.detail.code; render();});
  fetch("../../data/pensions-today.v1.json?v=20260909-awards").then(r=>{if(!r.ok)throw new Error(r.status);return r.json();}).then(data=>{state.data=data;render();if (["#pensions-today","#pension-benchmark"].includes(location.hash)) document.querySelector(location.hash)?.scrollIntoView();}).catch(error=>{console.error("Pensions data",error);root.innerHTML=`<p class="aging-loading">${tr("Pension data could not be loaded. Please reload the page.","Důchodová data se nepodařilo načíst. Obnovte stránku.")}</p>`;});
})();
