(async function () {
  'use strict';
  const app = document.querySelector('#praha-app');
  const query = new URLSearchParams(location.search);
  const lang = ['en', 'cs'].includes(query.get('lang')) ? query.get('lang') : document.documentElement.lang === 'cs' ? 'cs' : 'en';
  document.documentElement.lang = lang;
  window.addEventListener('psdlanguagechange', event => { const nextLang = event.detail?.lang; if (['en', 'cs'].includes(nextLang) && nextLang !== lang) { const next = new URL(location.href); next.searchParams.set('lang', nextLang); location.href = next.href; } });
  const T = (en, cs) => lang === 'cs' ? cs : en;
  document.title = T('Praha · The open budget — Public Spending Data', 'Praha · Otevřený rozpočet — Public Spending Data');
  document.addEventListener('click', event => { const control = event.target.closest('[data-lang]'); if (control && ['en', 'cs'].includes(control.dataset.lang) && control.dataset.lang !== lang) { const next = new URL(location.href); next.searchParams.set('lang', control.dataset.lang); location.href = next.href; } });
  const locale = lang === 'cs' ? 'cs-CZ' : 'en-GB';
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const $ = selector => app.querySelector(selector);
  const number = (value, digits = 0) => Number.isFinite(value) ? new Intl.NumberFormat(locale, { maximumFractionDigits: digits }).format(value) : '—';
  const exact = value => Number.isFinite(value) ? `${new Intl.NumberFormat(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value)} ${T('CZK', 'Kč')}` : '—';
  const short = value => !Number.isFinite(value) ? '—' : Math.abs(value) >= 1e9 ? `${number(value / 1e9, 2)} ${T('bn', 'mld.')}` : Math.abs(value) >= 1e6 ? `${number(value / 1e6, 1)} ${T('m', 'mil.')}` : number(value, Math.abs(value) < 100 ? 1 : 0);
  const money = value => `${short(value)} ${T('CZK', 'Kč')}`;
  const displayedExact = value => `${exact(value)}${state.unit === 'per-capita' ? T(' / resident', ' / obyv.') : ''}`;
  const signed = value => `${value > 0 ? '+' : ''}${money(value)}`;
  const percent = value => Number.isFinite(value) ? `${number(value, 1)}%` : '—';
  const safeLink = value => { try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) ? esc(url.href) : ''; } catch { return ''; } };
  const link = (url, label) => safeLink(url) ? `<a href="${safeLink(url)}" target="_blank" rel="noreferrer">${esc(label)} ↗</a>` : esc(label);
  const monitor = year => `https://monitor.statnipokladna.gov.cz/ucetni-jednotka/00064581/rozpocet/souhrnny?obdobi=${String(year).slice(-2)}12&rad=t`;
  const state = { year: Number(query.get('year')) || 2025, unit: query.get('unit') === 'per-capita' ? 'per-capita' : 'total', stage: 'actual', dimension: 'purpose', ledgerKind: 'payments', ledgerPage: 0, detail: null, payments: null, context: null, overview: null, request: 0 };
  const chartControllers = new Map();
  let chartReady = false;
  const name = row => lang === 'cs' ? row.name_cs || row.name || row.code : row.name_en || row.name_cs || row.name || row.code;
  const yearRow = () => state.overview.history.find(row => row.year === state.year);
  const shownValue = (value, row = yearRow()) => state.unit === 'per-capita' ? Number.isFinite(value) && row?.population_mid_year > 0 ? value / row.population_mid_year : null : value;
  const unit = () => state.unit === 'per-capita' ? T('CZK / resident', 'Kč / obyvatele') : T('CZK · nominal', 'Kč · běžné ceny');
  function writeURL() { const url = new URL(location.href); url.searchParams.set('year', state.year); url.searchParams.set('unit', state.unit); url.searchParams.set('lang', lang); history.replaceState(null, '', url); }
  const heading = (id, title, explanation) => `<div class="pb-heading"><div><span class="pb-section-no">${id}</span><h2>${title}</h2></div><p>${explanation}</p></div>`;

  function shell() {
    app.innerHTML = `
      <header class="pb-hero"><div class="pb-shell">
        <div class="pb-eyebrow"><span>${T('Czechia / Capital city / IČO 00064581', 'Česko / Hlavní město / IČO 00064581')}</span><span class="pb-tag">${T('Local research preview', 'Místní výzkumný náhled')}</span></div>
        <div class="pb-hero-grid"><div><h1 class="pb-city">Praha<span>.</span></h1><h2>${T('A city. Every crown.<br>A longer view.', 'Jedno město. Každá koruna.<br>V delším pohledu.')}</h2><p>${T('Follow the public money: what was planned, what was spent, what changed — and how much of the story the evidence can actually tell.', 'Sledujte veřejné peníze: co se plánovalo, co se utratilo, co se změnilo — a co lze skutečně doložit.')}</p></div>
        <div class="pb-hero-stat"><span class="pb-label" id="hero-label"></span><strong class="pb-hero-number" id="hero-amount">—</strong><div class="pb-hero-foot"><div><strong id="hero-person">—</strong>${T('per resident · actual expenditure', 'na obyvatele · skutečné výdaje')}</div><div><strong id="hero-change">—</strong>${T('year-on-year · nominal', 'meziročně · běžné ceny')}</div></div></div></div>
      </div></header>
      <div class="pb-control-bar"><div class="pb-shell pb-controls">
        <label class="pb-control"><span>${T('Financial year', 'Rozpočtový rok')}</span><select id="budget-year">${state.overview.history.map(row => `<option value="${row.year}">${row.year}</option>`).join('')}</select></label>
        <label class="pb-control"><span>${T('Display', 'Zobrazení')}</span><select id="budget-unit"><option value="total">${T('Total crowns', 'Celkem v korunách')}</option><option value="per-capita">${T('Per resident', 'Na obyvatele')}</option></select></label>
        <div class="pb-scope"><strong>${T('Whole-city budget · consolidated', 'Rozpočet celé Prahy · po konsolidaci')}</strong>${T('City and districts. Internal transfers eliminated. City companies are not a consolidated corporate group.', 'Město a městské části. Vnitřní převody vyloučeny. Nejde o konsolidovanou skupinu městských firem.')}</div>
      </div></div>
      <div class="pb-shell"><nav class="pb-nav" aria-label="${T('Budget chapters', 'Části rozpočtu')}"><a href="#trajectory"><span>01</span>${T('The long view', 'Dlouhodobý vývoj')}</a><a href="#spending"><span>02</span>${T('Where it goes', 'Kam peníze jdou')}</a><a href="#records"><span>03</span>${T('Follow a record', 'Podrobné záznamy')}</a><a href="#outcomes"><span>04</span>${T('What changes', 'Co se mění')}</a><a href="#evidence"><span>05</span>${T('The evidence', 'Důkazy a pokrytí')}</a></nav>
      <section class="pb-section" id="trajectory">${heading('01 / 2010—2025', T('Sixteen years.<br>One public balance.', 'Šestnáct let.<br>Jeden veřejný rozpočet.'), T('A budget is a promise. The accounts show execution. Compare both over time, with the same geography and accounting stage kept in view.', 'Rozpočet je plán. Účetní výkazy ukazují jeho plnění. Porovnejte je v čase při stejném územním a účetním vymezení.'))}
        <div class="pb-metrics" id="headline-metrics"></div>
        <div class="pb-chart-card"><div class="pb-chart-top"><h3 class="pb-chart-title">${T('Revenue, spending and the revised spending plan', 'Příjmy, výdaje a upravený plán výdajů')}</h3><div class="pb-legend"><span style="--series-color:#a8b63f">${T('Revenue', 'Příjmy')}</span><span style="--series-color:#c93237">${T('Spending', 'Výdaje')}</span><span style="--series-color:#8b8d83">${T('Revised plan', 'Upravený plán')}</span></div></div><div id="trajectory-chart"></div></div>
        <p class="pb-note" id="trajectory-note"></p>
        <div class="pb-insight"><div><span class="pb-tag">${T('Calculated · accounting explanation', 'Výpočet · účetní vysvětlení')}</span><h3 id="change-title"></h3><p id="change-story"></p><p class="pb-note">${T('This decomposes the change in spending. It does not identify what caused an outcome in the city.', 'Jde o rozklad změny výdajů. Neurčuje příčinu změny životních podmínek ve městě.')}</p></div><div class="pb-bridge" id="change-bridge"></div></div>
      </section>
      <section class="pb-section" id="spending">${heading('02 / '+T('THE BUDGET', 'ROZPOČET'), T('From billions<br>to a budget line.', 'Od miliard<br>k rozpočtovému řádku.'), T('Open every reported classification. Purpose answers “for what?” Economic items answer “what kind of spending?” These are alternative views of the same money.', 'Projděte všechny vykázané kategorie. Paragraf říká „na co“, položka „jaký druh výdaje“. Jde o různé pohledy na stejné peníze.'))}
        <div class="pb-toolbar"><div class="pb-field"><label for="budget-dimension">${T('View', 'Pohled')}</label><select id="budget-dimension"><option value="purpose">${T('Spending · purpose', 'Výdaje · paragrafy')}</option><option value="economic">${T('Spending · economic item', 'Výdaje · položky')}</option><option value="revenue">${T('Revenue · economic item', 'Příjmy · položky')}</option></select></div><div class="pb-field"><label for="budget-stage">${T('Accounting stage', 'Fáze rozpočtu')}</label><select id="budget-stage"><option value="actual">${T('Actual', 'Skutečnost')}</option><option value="approved">${T('Approved budget', 'Schválený rozpočet')}</option><option value="adjusted">${T('Revised budget', 'Upravený rozpočet')}</option></select></div><div class="pb-field pb-field-grow"><label for="budget-search">${T('Find a code or classification', 'Hledat kód nebo název')}</label><input id="budget-search" type="search" placeholder="${T('Transport, schools, 3113…', 'Doprava, školy, 3113…')}"></div></div>
        <div id="budget-status" class="pb-status" role="status"></div><div class="pb-detail-layout"><div class="pb-chart-card"><div class="pb-chart-top"><h3 class="pb-chart-title" id="breakdown-title"></h3></div><div id="breakdown-chart"></div></div><div><div class="pb-table-wrap pb-native"><table class="pb-table" id="budget-table"><thead><tr><th>${T('Code / classification', 'Kód / kategorie')}</th><th>${T('Amount', 'Částka')}</th></tr></thead><tbody></tbody></table></div><p class="pb-note" id="budget-count"></p></div></div>
        <p class="pb-note">${T('Native classification labels are retained when an English translation is unavailable. Click a row to inspect exact values and all three budget stages. Purpose and economic categories are never added together.', 'Pokud chybí překlad, zachováváme původní název. Kliknutím na řádek otevřete přesné částky ve všech třech fázích. Paragrafy a položky nikdy nesčítáme.')}</p>
      </section>
      <section class="pb-section" id="records">${heading('03 / '+T('THE PAPER TRAIL', 'STOPA PENĚZ'), T('Follow the detail.<br>Keep the boundary.', 'Sledujte detail.<br>Vnímejte hranice dat.'), T('Investigate invoice allocations, accounting rows and named projects in one place. These records cover the magistrate publication, not every crown in the whole-city budget.', 'Prozkoumejte fakturační alokace, účetní řádky a pojmenované akce na jednom místě. Jde o publikované záznamy magistrátu, nikoli o veškeré výdaje celé Prahy.'))}
        <div class="pb-toolbar"><div class="pb-field"><label for="ledger-kind">${T('Record type', 'Typ záznamu')}</label><select id="ledger-kind"><option value="payments">${T('Invoice allocations', 'Fakturační alokace')}</option><option value="accounting">${T('Accounting rows', 'Účetní řádky')}</option><option value="projects">${T('Named projects / events', 'Pojmenované akce')}</option></select></div><div class="pb-field pb-field-grow"><label for="ledger-search">${T('Search across the record', 'Hledat v záznamu')}</label><input id="ledger-search" type="search" placeholder="${T('Supplier, IČO, project, paragraph…', 'Dodavatel, IČO, akce, paragraf…')}"></div><button id="ledger-load" class="pb-button" type="button">${T('Open invoice records', 'Otevřít fakturační záznamy')} ↗</button></div>
        <div class="pb-status warning" id="ledger-status" role="status"></div><div class="pb-table-wrap"><table id="ledger-table" class="pb-table"><thead></thead><tbody></tbody></table></div><div class="pb-pagination" id="ledger-pagination"></div>
        <div class="pb-insight"><div><span class="pb-tag">${T('Contract connection · pending', 'Napojení smluv · čeká')}</span><h3>${T('The next missing link.', 'Další chybějící spojení.')}</h3></div><div><p>${T('Praha’s Hlídač contract snapshot is held privately. It has not passed a published contract-to-payment join. A shared supplier or amount alone is not sufficient to claim that a payment fulfils a contract.', 'Snímek pražských smluv z Hlídače je uložen neveřejně. Vazby smluv na faktury dosud nemají ověřenou publikaci. Shodný dodavatel nebo částka samy o sobě nedokládají plnění konkrétní smlouvy.')}</p><a href="#evidence" class="pb-note">${T('Inspect the coverage boundary', 'Prozkoumat hranice pokrytí')} →</a></div></div>
      </section>
      <section class="pb-section" id="outcomes">${heading('04 / '+T('LIFE IN THE CITY', 'ŽIVOT VE MĚSTĚ'), T('What changed<br>alongside the money?', 'Co se měnilo<br>spolu s penězi?'), T('Put observed local conditions beside the budget. Compare annual changes and time lags. An association is a question to investigate, not proof that spending caused the change.', 'Srovnejte místní podmínky s rozpočtem. Sledujte meziroční změny a zpoždění. Souvislost je otázkou pro další výzkum, nikoli důkazem účinku výdajů.'))}
        <div class="pb-toolbar"><div class="pb-field pb-field-grow"><label for="context-series">${T('Observed Praha indicator', 'Pozorovaný ukazatel Prahy')}</label><select id="context-series"><option>${T('Loading observations…', 'Načítání pozorování…')}</option></select></div><div class="pb-field"><label for="context-budget">${T('Compare with', 'Porovnat s')}</label><select id="context-budget"><option value="expense_actual">${T('Total expenditure', 'Celkové výdaje')}</option><option value="capital_expense">${T('Capital expenditure', 'Kapitálové výdaje')}</option><option value="current_expense">${T('Current expenditure', 'Běžné výdaje')}</option></select></div><div class="pb-field"><label for="context-lag">${T('Outcome lag', 'Zpoždění ukazatele')}</label><select id="context-lag"><option value="0">${T('Same year', 'Stejný rok')}</option><option value="1">${T('One year later', 'O rok později')}</option></select></div></div>
        <div class="pb-outcome-grid"><div class="pb-chart-card"><div class="pb-chart-top"><h3 class="pb-chart-title" id="context-title"></h3></div><div id="context-chart"></div></div><aside class="pb-context-detail" id="context-detail"><p role="status">${T('Loading published observations…', 'Načítání publikovaných pozorování…')}</p></aside></div>
        <div class="pb-insight"><div><span class="pb-tag">${T('Causal evidence · not established', 'Příčinný účinek · neprokázán')}</span><h3>${T('What would it take<br>to say “because”?', 'Co je třeba pro tvrzení<br>„díky těmto výdajům“?')}</h3></div><div><ol class="pb-causal-list"><li>${T('Identify an intervention, its delivery date, actual cost and the people or places exposed to it.', 'Určit opatření, datum realizace, skutečnou cenu a zasažené obyvatele či území.')}</li><li>${T('Find comparable places and credible pre-intervention trends; measure population, inflation and other changes.', 'Najít srovnatelná území a doložit vývoj před opatřením; měřit změny populace, cen i dalších vlivů.')}</li><li>${T('Test an explicit counterfactual and report uncertainty. Publish the evaluation and its limitations.', 'Testovat vývoj bez opatření a vyčíslit nejistotu. Zveřejnit hodnocení i jeho omezení.')}</li></ol><p class="pb-note">${T('The current view establishes budget arithmetic and exploratory associations. It does not yet estimate causal effects.', 'Současný pohled dokládá rozpočtovou aritmetiku a průzkumné souvislosti. Zatím neodhaduje příčinné účinky.')}</p></div></div>
      </section>
      <section class="pb-section" id="evidence">${heading('05 / '+T('RESEARCHER EVIDENCE', 'VÝZKUMNÉ PODKLADY'), T('Trust the number.<br>Inspect its limits.', 'Důvěra v čísla.<br>S viditelnými limity.'), T('Read-only provenance stays attached to the observation. A publication date, an accounting year and the extent of coverage answer different questions.', 'Původ dat zůstává spojen s pozorováním. Datum publikace, účetní rok a rozsah pokrytí odpovídají na odlišné otázky.'))}
        <div class="pb-evidence-grid" id="evidence-cards"></div>
      </section><div class="pb-bottom"><p>${T('One city, several accounting boundaries. Amounts are nominal CZK; “per resident” uses the reported mid-year population. Missing values remain missing. The public budget is not a balance sheet of the entire city economy.', 'Jedno město, několik účetních hranic. Částky jsou v běžných Kč; přepočet na obyvatele používá vykázanou populaci v polovině roku. Chybějící hodnoty zůstávají chybějícími. Veřejný rozpočet není rozvahou celé městské ekonomiky.')}</p><a id="language-link" href="?lang=${lang === 'cs' ? 'en' : 'cs'}&year=${state.year}">${lang === 'cs' ? 'English →' : 'Česky →'}</a></div>
      </div><dialog id="record-dialog" class="pb-dialog"><div class="pb-dialog-head"><div><span class="pb-label">${T('Read-only evidence', 'Podklady pouze ke čtení')}</span><h2 id="record-title"></h2></div><button type="button" id="record-close" aria-label="${T('Close details', 'Zavřít detail')}">×</button></div><div class="pb-dialog-body" id="record-body"></div></dialog>`;
    $('#budget-year').value = state.year; $('#budget-unit').value = state.unit;
    $('#language-link').addEventListener('click', event => { event.preventDefault(); const next = new URL(location.href); next.searchParams.set('lang', lang === 'cs' ? 'en' : 'cs'); location.href = next.href; });
    $('#budget-year').addEventListener('change', event => selectYear(Number(event.target.value)));
    $('#budget-unit').addEventListener('change', event => { state.unit = event.target.value; writeURL(); renderOverview(); renderBudget(); renderContext(); });
    $('#budget-stage').addEventListener('change', event => { state.stage = event.target.value; renderBudget(); });
    $('#budget-dimension').addEventListener('change', event => { state.dimension = event.target.value; renderBudget(); });
    $('#budget-search').addEventListener('input', renderBudget);
    $('#ledger-kind').addEventListener('change', event => { state.ledgerKind = event.target.value; state.ledgerPage = 0; renderLedger(); });
    $('#ledger-search').addEventListener('input', () => { state.ledgerPage = 0; renderLedger(); });
    $('#ledger-load').addEventListener('click', loadPayments);
    ['#context-series', '#context-budget', '#context-lag'].forEach(id => $(id).addEventListener('change', renderContext));
    $('#record-close').addEventListener('click', () => $('#record-dialog').close());
    $('#record-dialog').addEventListener('click', event => { if (event.target === $('#record-dialog')) { const r = event.target.getBoundingClientRect(); if (event.clientX < r.left || event.clientX > r.right || event.clientY < r.top || event.clientY > r.bottom) event.target.close(); } });
    $('#budget-table').addEventListener('click', event => { const row = event.target.closest('[data-budget-code]'); if (row) budgetRecord(row.dataset.budgetCode); });
    $('#ledger-table').addEventListener('click', event => { const row = event.target.closest('[data-record]'); if (row) ledgerRecord(Number(row.dataset.record)); });
  }

  function plot(id, spec, source) {
    const host = $(id); if (!chartReady || !host) return;
    chartControllers.get(id)?.destroy?.();
    host.replaceChildren(); const plotHost = document.createElement('div'); plotHost.className = 'pb-plot'; host.append(plotHost);
    const controller = window.PSDPlot.render(plotHost, { locale, animate: false, ...spec });
    chartControllers.set(id, controller);
    window.PSDChart.register({ el: host, slug: id.slice(1), title: spec.title, accessor: controller.accessor, exports: [], embeddable: false, source });
    // This investigation view offers tables and provenance, without raw-download controls.
    host.querySelector('[data-action="csv"]')?.remove();
  }
  function metric(label, value, note) { return `<div class="pb-metric"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`; }
  function renderOverview() {
    const row = yearRow(), previous = state.overview.history.find(item => item.year === state.year - 1);
    $('#hero-label').textContent = `${T('Actual public expenditure', 'Skutečné veřejné výdaje')} / ${state.year}`;
    $('#hero-amount').innerHTML = `${number(row.expense_actual / 1e9, 2)}<small>${T('billion CZK', 'miliard Kč')}</small>`;
    $('#hero-person').textContent = money(row.expense_actual / row.population_mid_year);
    $('#hero-change').textContent = previous ? `${row.expense_actual >= previous.expense_actual ? '+' : ''}${percent((row.expense_actual / previous.expense_actual - 1) * 100)}` : '—';
    $('#headline-metrics').innerHTML = metric(T('Revenue', 'Příjmy'), money(shownValue(row.revenue_actual)), `${state.year} · ${unit()}`) + metric(T('Expenditure', 'Výdaje'), money(shownValue(row.expense_actual)), `${percent(row.expense_actual / row.expense_adjusted * 100)} ${T('of revised plan', 'upraveného plánu')} · ${unit()}`) + metric(T('Budget balance', 'Saldo rozpočtu'), signed(shownValue(row.budget_balance)), T('Revenue minus expenditure · flow', 'Příjmy minus výdaje · tok') + ' · ' + unit()) + metric(T('Capital investment', 'Kapitálové výdaje'), money(shownValue(row.capital_expense)), `${percent(row.capital_expense / row.expense_actual * 100)} ${T('of expenditure', 'výdajů')} · ${unit()}`);
    plot('#trajectory-chart', { type: 'line', rows: state.overview.history, fields: [{ key: 'revenue_actual', label: T('Actual revenue', 'Skutečné příjmy'), color: '#a8b63f', value: item => shownValue(item.revenue_actual, item) }, { key: 'expense_actual', label: T('Actual expenditure', 'Skutečné výdaje'), color: '#c93237', value: item => shownValue(item.expense_actual, item) }, { key: 'expense_adjusted', label: T('Revised expenditure', 'Upravené výdaje'), color: '#8b8d83', value: item => shownValue(item.expense_adjusted, item) }], title: `${T('Praha budget', 'Rozpočet Prahy')} · 2010–2025 · ${unit()}`, unit: unit(), height: 360, endLabels: false, selectedLabel: String(state.year), format: displayedExact, axisFormat: short, onSelect: row => selectYear(row.year) }, { name: 'Ministerstvo financí · MONITOR · FIN 2-12 M', url: monitor(state.year), table: state.overview.evidence[0]?.datasetId, edition: state.overview.evidence[0]?.generatedAt, definition: T('Annual consolidated revenue and expenditure. Nominal CZK; per-resident values divide each year by its reported mid-year population.', 'Roční příjmy a výdaje po konsolidaci. Běžné Kč; hodnoty na obyvatele dělí každý rok vykázanou populací k polovině roku.'), caveat: T('No inflation adjustment. Cash stocks are excluded from flow comparisons. Companies are outside the consolidated city budget boundary.', 'Bez očištění o inflaci. Stavy peněz nejsou přičítány k ročním tokům. Městské firmy nejsou součástí konsolidované skupinové rozvahy.') });
    $('#trajectory-note').innerHTML = `${T('Select a year in the chart or above. Read the exact values in the table.', 'Rok vyberte v grafu nebo nahoře. Přesné hodnoty najdete v tabulce.')} ${link(monitor(state.year), 'MONITOR · FIN 2-12 M')} · ${state.year} · ${T('Population denominator', 'Populační jmenovatel')}: ${number(row.population_mid_year)}.`;
    $('#change-title').textContent = previous ? `${T('What explains the change in', 'Co vysvětluje změnu v roce')} ${state.year}?` : T('The starting point.', 'Výchozí rok.');
    if (previous) {
      const current = row.current_expense - previous.current_expense, capital = row.capital_expense - previous.capital_expense, total = row.expense_actual - previous.expense_actual, residual = total - current - capital;
      $('#change-story').textContent = T(`Expenditure changed by ${signed(total)}. Current operations contributed ${signed(current)}, and capital expenditure ${signed(capital)}. These are nominal annual differences, not changes in service quality.`, `Výdaje se změnily o ${signed(total)}. Běžné výdaje přispěly ${signed(current)}, kapitálové ${signed(capital)}. Jde o nominální meziroční rozdíly, nikoli o změny kvality služeb.`);
      $('#change-bridge').innerHTML = [[`${previous.year} · ${T('actual expenditure', 'skutečné výdaje')}`, money(previous.expense_actual)], [T('Change in current expenditure', 'Změna běžných výdajů'), signed(current)], [T('Change in capital expenditure', 'Změna kapitálových výdajů'), signed(capital)], ...(Math.abs(residual) > .02 ? [[T('Other / reconciliation difference', 'Ostatní / rozdíl odsouhlasení'), signed(residual)]] : []), [`${state.year} · ${T('actual expenditure', 'skutečné výdaje')}`, money(row.expense_actual)]].map(([label, value]) => `<div class="pb-bridge-row"><span>${label}</span><strong>${value}</strong></div>`).join('');
    } else { $('#change-story').textContent = T('The previous year is outside this published history. A year-on-year change is unavailable.', 'Předchozí rok není v publikované historii. Meziroční změna není dostupná.'); $('#change-bridge').textContent = ''; }
    $('#language-link').href = `?lang=${lang === 'cs' ? 'en' : 'cs'}&year=${state.year}&unit=${state.unit}`;
  }
  async function selectYear(year) {
    if (!state.overview.history.some(row => row.year === year)) return;
    state.year = year; $('#budget-year').value = year; $('#budget-year').dispatchEvent(new Event('input', { bubbles: true })); state.detail = null; state.payments = null; state.ledgerPage = 0;
    writeURL(); renderOverview(); renderBudget(); renderLedger(); renderContext(); renderEvidence();
    const token = ++state.request;
    try { const detail = await window.PrahaBudgetData.loadYearDetail(year); if (token !== state.request) return; state.detail = detail; }
    catch (error) { if (token !== state.request) return; state.detail = { year, rows: [], accountingRows: [], events: [], error: error.message, coverage: {} }; }
    renderBudget(); renderLedger(); renderEvidence();
  }
  function budgetRows() { const dimension = state.dimension === 'purpose' ? 'functional' : 'economic', side = state.dimension === 'revenue' ? 'revenue' : 'expenditure'; return (state.detail?.rows || []).filter(row => row.dimension === dimension && row.side === side && row.stage === state.stage); }
  function renderBudget() {
    const status = $('#budget-status'), all = budgetRows(), term = $('#budget-search').value.trim().toLocaleLowerCase(locale), rows = all.filter(row => `${row.code} ${row.name} ${row.name_en || ''}`.toLocaleLowerCase(locale).includes(term)).sort((a, b) => Math.abs(b.amount) - Math.abs(a.amount));
    $('#budget-table tbody').innerHTML = rows.map(row => `<tr data-budget-code="${esc(row.code)}"><td><button type="button"><code>${esc(row.code)}</code> ${esc(name(row))}</button></td><td>${money(shownValue(row.amount))}</td></tr>`).join('');
    $('#budget-count').textContent = `${number(rows.length)} / ${number(all.length)} ${T('native rows · exact values in the row detail', 'původních řádků · přesné částky v detailu řádku')}`;
    $('#breakdown-title').textContent = `${T('Largest reported categories', 'Největší vykázané kategorie')} · ${state.year}`;
    if (!all.length) {
      status.className = 'pb-status warning'; status.textContent = !state.detail ? T('Loading the selected year…', 'Načítání vybraného roku…') : state.detail.error ? T('The budget detail service is unavailable. Retry the selected year; missing values have not been replaced.', 'Služba detailu rozpočtu není dostupná. Vyberte rok znovu; chybějící hodnoty nebyly nahrazeny.') : T(`Full classification detail is not published here for ${state.year}. The 2025 whole-city breakdown is available. Magistrate records below remain a separate, partial scope.`, `Úplný detail kategorií pro rok ${state.year} zde není publikován. K dispozici je rozpad rozpočtu celé Prahy za rok 2025. Níže uvedené záznamy magistrátu mají samostatný, dílčí rozsah.`);
      chartControllers.get('#breakdown-chart')?.destroy?.(); $('#breakdown-chart').innerHTML = `<p class="pb-empty">${T('No substitute values. Select 2025 for the reconciled budget detail.', 'Bez náhradních hodnot. Pro odsouhlasený detail rozpočtu vyberte rok 2025.')}</p>`; return;
    }
    const complete = all.every(row => Number.isFinite(row.amount)), total = complete ? all.reduce((sum, row) => sum + row.amount, 0) : null, target = yearRow()[`${state.dimension === 'revenue' ? 'revenue' : 'expense'}_${state.stage}`], difference = complete && Number.isFinite(target) ? total - target : null, reconciles = complete && Number.isFinite(difference) && Math.abs(difference) < .02;
    status.className = `pb-status${reconciles ? '' : ' warning'}`;
    status.innerHTML = `<strong>${reconciles ? T('Reconciled to the whole-city total.', 'Odsouhlaseno na součet celé Prahy.') : T('Reconciliation difference is visible.', 'Rozdíl odsouhlasení je viditelný.')}</strong> ${T('Sum of', 'Součet')} ${number(all.length)} ${T('native rows', 'původních řádků')}: ${exact(total)}. ${!reconciles ? `${T('Headline', 'Souhrn')}: ${exact(target)}; ${T('difference', 'rozdíl')}: ${exact(difference)}.` : ''} ${T('Selected stage', 'Vybraná fáze')}: ${esc($('#budget-stage option:checked').textContent)}.`;
    plot('#breakdown-chart', { type: 'bar', rows: rows.slice(0, 8).map(row => ({ ...row, label: `${row.code} ${name(row)}` })), fields: [{ key: 'amount', label: $('#budget-stage option:checked').textContent, color: '#a8b63f', value: row => shownValue(row.amount) }], title: `${$('#budget-dimension option:checked').textContent} · ${state.year} · ${unit()}`, unit: unit(), height: 480, valueLabels: true, format: displayedExact, axisFormat: short, onSelect: row => budgetRecord(row.code) }, { name: 'MONITOR · FIN 2-12 M', url: monitor(state.year), table: `${state.dimension} · ${state.stage}`, definition: T('Native reported budget classification. Top eight matching rows shown in the chart; all matching rows appear alongside.', 'Původní rozpočtová klasifikace. Graf obsahuje osm největších odpovídajících řádků; tabulka všechny nalezené řádky.'), caveat: T('Functional and economic views overlap. Do not add their totals or infer unreported cross-classification links.', 'Odvětvový a druhový pohled se překrývají. Jejich součty nesčítejte ani z nich neodvozujte nepublikované vazby.') });
  }
  function openRecord(title, pairs, note, source) {
    $('#record-title').textContent = title;
    $('#record-body').innerHTML = `<dl>${pairs.map(([key, value]) => `<dt>${esc(key)}</dt><dd>${esc(value ?? '—')}</dd>`).join('')}</dl><p class="pb-status warning">${esc(note)}</p><p class="pb-note">${source || ''}</p>`;
    $('#record-dialog').showModal();
  }
  function budgetRecord(code) {
    const row = budgetRows().find(item => item.code === code); if (!row) return;
    const related = state.detail.rows.filter(item => item.code === code && item.dimension === row.dimension && item.side === row.side);
    const pairs = [[T('Year / scope', 'Rok / rozsah'), `${state.year} · ${T('whole city, consolidated', 'celá Praha po konsolidaci')}`], [T('Native code', 'Původní kód'), code], [T('Classification', 'Klasifikace'), row.dimension], ...['approved', 'adjusted', 'actual'].map((stage, index) => [T(['Approved budget', 'Revised budget', 'Actual'][index], ['Schválený rozpočet', 'Upravený rozpočet', 'Skutečnost'][index]), exact(related.find(item => item.stage === stage)?.amount)]), [T('Source', 'Zdroj'), 'MONITOR · FIN 2-12 M']];
    openRecord(`${code} · ${name(row)}`, pairs, T('The magistrate records may share this classification code but do not represent a complete allocation of this consolidated total. No one-to-one contract join has been verified.', 'Záznamy magistrátu mohou sdílet stejný kód, ale netvoří úplný rozpad tohoto konsolidovaného součtu. Vazba na konkrétní smlouvu nebyla ověřena.'), link(monitor(state.year), T('Inspect official accounts', 'Otevřít oficiální výkaz')));
  }
  async function loadPayments() {
    const year = state.year, token = state.request, button = $('#ledger-load'); button.disabled = true; button.textContent = T('Loading records…', 'Načítání záznamů…');
    try { const payments = await window.PrahaBudgetData.loadPayments(year); if (token !== state.request) return; state.payments = payments; }
    catch (error) { if (token !== state.request) return; state.payments = { rows: [], error: error.message }; }
    if (token === state.request) { renderLedger(); renderEvidence(); }
  }
  function ledgerRows() { return state.ledgerKind === 'payments' ? state.payments?.rows || [] : state.ledgerKind === 'projects' ? state.detail?.events || [] : state.detail?.accountingRows || []; }
  function renderLedger() {
    const status = $('#ledger-status'), button = $('#ledger-load'), isPayments = state.ledgerKind === 'payments', projects = state.ledgerKind === 'projects';
    button.hidden = !isPayments || !!state.payments && !state.payments.error; button.disabled = !state.detail; button.textContent = state.payments?.error ? T('Retry invoice records', 'Zkusit načíst znovu') : T('Open invoice records', 'Otevřít fakturační záznamy');
    const all = ledgerRows(), term = $('#ledger-search').value.trim().toLocaleLowerCase(locale), rows = all.map((row, index) => ({ row, index })).filter(({ row }) => Object.values(row).join(' ').toLocaleLowerCase(locale).includes(term)).sort((a, b) => (b.row.expenditure || 0) - (a.row.expenditure || 0)), pages = Math.max(1, Math.ceil(rows.length / 25));
    state.ledgerPage = Math.min(state.ledgerPage, pages - 1);
    const descriptions = isPayments ? all.filter(row => !row.description).length : 0;
    if (!state.detail) status.textContent = T('Checking record coverage for this year…', 'Ověřování pokrytí záznamů pro tento rok…');
    else if (!isPayments && (state.detail.error || state.detail.coverage.accounting?.status === 'unavailable')) status.textContent = T('The magistrate accounting layer is unavailable for this year. No zero or substitute records are implied.', 'Účetní vrstva magistrátu pro tento rok není dostupná. Nejde o nulový počet záznamů ani náhradní hodnoty.');
    else if (isPayments && !state.payments) { const count = state.detail.invoiceSummary?.rows; status.textContent = T(`Magistrate publication only. ${Number.isFinite(count) ? number(count) + ' invoice allocations are reported for the selected year.' : 'Invoice availability has not been verified for this year.'} Open the records to investigate coverage. They are not a complete payment ledger for the consolidated city budget.`, `Pouze publikace magistrátu. ${Number.isFinite(count) ? 'Pro vybraný rok je vykázáno ' + number(count) + ' fakturačních alokací.' : 'Dostupnost faktur v tomto roce nebyla ověřena.'} Otevřete záznamy pro průzkum pokrytí. Nejde o úplnou knihu plateb konsolidovaného rozpočtu.`); }
    else if (state.payments?.error && isPayments) status.textContent = T('Invoice records could not be loaded. No records have been substituted. Retry when the published service is available.', 'Fakturační záznamy se nepodařilo načíst. Nenahrazujeme je jinými daty. Zkuste znovu po obnovení publikované služby.');
    else { const dates = isPayments ? all.map(row => row.date).filter(Boolean).sort() : []; status.textContent = `${T('Partial magistrate scope', 'Dílčí rozsah magistrátu')} · ${number(all.length)} ${T('records', 'záznamů')} · ${T('source validity', 'platnost zdroje')}: ${state.detail.sourceValidity || '—'}. ${isPayments ? T(`${number(descriptions)} records have no description. Observed dates: ${dates[0] || '—'}–${dates.at(-1) || '—'}. Invoice allocations are not proof of bank payment; fiscal year and record date may differ.`, `${number(descriptions)} záznamů nemá popis. Pozorovaná data: ${dates[0] || '—'}–${dates.at(-1) || '—'}. Alokace nejsou dokladem bankovní platby; účetní rok a datum záznamu se mohou lišit.`) : T('These rows do not reconcile to the whole-city headline and must not be added to it.', 'Tyto řádky neodpovídají součtu celé Prahy a nesmějí se k němu přičítat.')}`; }
    $('#ledger-table thead').innerHTML = `<tr><th>${isPayments ? T('Date', 'Datum') : T('Code', 'Kód')}</th><th>${isPayments ? T('Supplier / description', 'Dodavatel / popis') : projects ? T('Project / event', 'Akce') : T('Classification / event', 'Klasifikace / akce')}</th><th>${T('Expenditure · CZK', 'Výdaje · Kč')}</th></tr>`;
    $('#ledger-table tbody').innerHTML = rows.slice(state.ledgerPage * 25, state.ledgerPage * 25 + 25).map(({ row, index }) => `<tr data-record="${index}"><td>${esc(isPayments ? row.date || '—' : projects ? row.code : `${row.paragraphCode} / ${row.itemCode}`)}</td><td><button type="button">${esc(isPayments ? row.counterparty || T('Supplier not reported', 'Dodavatel neuveden') : projects ? row.name || row.code : row.eventName || row.paragraphName)}</button><small>${esc(isPayments ? `${row.counterpartyId || ''} · ${row.description || T('Description missing', 'Popis chybí')}` : projects ? T('Reported event; delivery status not available', 'Vykázaná akce; stav realizace není dostupný') : `${row.paragraphName} · ${row.itemName}`)}</small></td><td>${exact(row.expenditure)}</td></tr>`).join('');
    $('#ledger-pagination').innerHTML = `<span>${number(rows.length)} / ${number(all.length)} ${T('matching records', 'odpovídajících záznamů')} · ${T('page', 'strana')} ${state.ledgerPage + 1}/${pages}</span><div><button type="button" data-page="-1" ${state.ledgerPage === 0 ? 'disabled' : ''}>← ${T('Previous', 'Předchozí')}</button> <button type="button" data-page="1" ${state.ledgerPage >= pages - 1 ? 'disabled' : ''}>${T('Next', 'Další')} →</button></div>`;
    $('#ledger-pagination').querySelectorAll('[data-page]').forEach(item => item.addEventListener('click', () => { state.ledgerPage += Number(item.dataset.page); renderLedger(); }));
  }
  function ledgerRecord(index) {
    const row = ledgerRows()[index]; if (!row) return;
    const keys = state.ledgerKind === 'payments' ? ['id', 'year', 'date', 'counterparty', 'counterpartyId', 'description', 'paragraphCode', 'paragraphName', 'itemCode', 'itemName', 'event', 'eventName', 'income', 'expenditure'] : state.ledgerKind === 'projects' ? ['code', 'name', 'income', 'expenditure', 'budgetIncome', 'budgetExpenditure'] : ['id', 'year', 'type', 'paragraphCode', 'paragraphName', 'itemCode', 'itemName', 'event', 'eventName', 'organizationUnit', 'income', 'expenditure', 'budgetIncome', 'budgetExpenditure'];
    const evidence = state.ledgerKind === 'payments' ? state.payments.evidence : state.detail.evidence?.cityvizor;
    openRecord(row.counterparty || row.name || row.eventName || row.id, [...keys.map(key => [key, ['income', 'expenditure', 'budgetIncome', 'budgetExpenditure'].includes(key) ? exact(row[key]) : row[key] === '' || row[key] == null ? T('Not reported', 'Neuvedeno') : row[key]]), [T('Published release', 'Publikované vydání'), evidence?.releaseId], [T('Source SHA-256', 'SHA-256 zdroje'), evidence?.sourceSha256], [T('Source validity', 'Platnost zdroje'), state.detail.sourceValidity]], T('Partial magistrate publication. The accounting year may differ from the document date. A project label does not establish completion. No contract or bank-payment match is inferred.', 'Dílčí publikace magistrátu. Účetní rok se může lišit od data dokladu. Název akce nedokládá její dokončení. Neodvozujeme vazbu na smlouvu ani bankovní platbu.'), link('https://cityvizor.praha.eu/magistrat', 'CityVizor · Magistrát hl. m. Prahy'));
  }

  function association(series) {
    return window.PrahaBudgetMath.associateAnnualChanges(state.overview.history, series.points, {budgetKey: $('#context-budget').value, lag: Number($('#context-lag').value), endYear: state.year, perCapita: state.unit === 'per-capita'});
  }
  function renderContext() {
    if (!state.context?.series?.length) return;
    const series = state.context.series.find(item => item.id === $('#context-series').value) || state.context.series[0], points = series.points.filter(row => row.year <= state.year), latest = points.filter(row => row.value !== null).at(-1), title = name(series), nativeUnit = series.unit || T('source units', 'jednotky zdroje');
    $('#context-title').textContent = `${title} · ${nativeUnit}`;
    plot('#context-chart', { type: 'line', rows: points, fields: [{ key: 'value', label: title, color: '#a8b63f' }], title: `${title} · Praha · ${nativeUnit}`, unit: nativeUnit, height: 330, format: value => `${number(value, series.decimals ?? 2)} ${nativeUnit}`, axisFormat: value => number(value, 1), selectedLabel: String(state.year), includeZero: true }, { name: 'PAQ Research · DataPAQ', url: latest?.sourceUrl || state.context.evidence.sourceUrl, edition: state.context.snapshot, table: series.id, definition: series.definition, caveat: T('Municipality 554782 only. Missing years are not interpolated. Source methods and units remain native; these are contextual observations, not causal effects.', 'Pouze obec 554782. Chybějící roky nejsou dopočítávány. Zachováváme původní metodiku a jednotky; jde o kontextová pozorování, nikoli příčinný účinek.') });
    const result = association(series);
    $('#context-detail').innerHTML = `<span class="pb-tag">${T('Observed · Praha / municipality', 'Pozorování · Praha / obec')}</span><h3>${esc(title)}</h3><div class="pb-outcome-value">${latest ? number(latest.value, series.decimals ?? 2) : '—'} <span class="pb-label">${esc(nativeUnit)}</span></div><p>${latest ? `${latest.year} · ${T('latest observation through selected year', 'nejnovější pozorování do vybraného roku')}` : T('No observation through the selected year.', 'Do vybraného roku není dostupné pozorování.')}</p><details><summary>${T('Definition and denominator', 'Definice a jmenovatel')}</summary><p>${esc(series.definition)}</p><p>${link(latest?.sourceUrl, T('Inspect the observation', 'Prozkoumat pozorování'))}</p></details><div class="pb-association" id="association-status"><span class="pb-label">${T('Exploratory association · annual changes', 'Průzkumná souvislost · meziroční změny')}</span><p><strong>${result.r !== null ? `r = ${number(result.r, 2)}` : T('Insufficient evidence', 'Nedostatek podkladů')}</strong></p><p>${result.r !== null ? T(`Pearson correlation across ${result.pairs.length} matched annual changes. This is not an estimate of a causal effect.`, `Pearsonova korelace z ${result.pairs.length} párových meziročních změn. Nejde o odhad příčinného účinku.`) : T(`${result.pairs.length} matched annual changes; at least five and non-zero variation are required. No coefficient is shown.`, `${result.pairs.length} párových meziročních změn; je třeba alespoň pět a nenulová variabilita. Koeficient nezobrazujeme.`)}</p><details><summary>${T('Inspect calculation', 'Prozkoumat výpočet')}</summary><p>${T('Each change = 100 × (value / previous calendar year − 1). Match budget year t to outcome year t + lag. Use only observed, consecutive years and positive prior values, through the selected year. No inflation, confounder or multiple-testing adjustment. Small samples and serial dependence limit interpretation.', 'Každá změna = 100 × (hodnota / předchozí kalendářní rok − 1). Spojujeme rozpočtový rok t s ukazatelem t + zpoždění. Pouze pozorované navazující roky s kladným základem do vybraného roku. Bez očištění o inflaci, další vlivy a vícenásobné testování. Malý vzorek a časová závislost omezují interpretaci.')}</p><div class="pb-table-wrap"><table class="pb-table"><thead><tr><th>${T('Years', 'Roky')}</th><th>${T('Budget Δ', 'Rozpočet Δ')}</th><th>${T('Outcome Δ', 'Ukazatel Δ')}</th></tr></thead><tbody>${result.pairs.map(row => `<tr><td>${row.year} → ${row.outcomeYear}</td><td>${percent(row.budgetChange)}</td><td>${percent(row.outcomeChange)}</td></tr>`).join('')}</tbody></table></div></details></div>`;
  }
  function renderEvidence() {
    const overview = state.overview, detail = state.detail, receipt = overview.evidence[0];
    const card = (status, title, body, pairs, source) => `<article class="pb-evidence-card"><span class="pb-tag">${status}</span><h3>${title}</h3><p>${body}</p><dl>${pairs.map(([key, value]) => `<dt>${key}</dt><dd>${esc(value ?? '—')}</dd>`).join('')}</dl><p>${source}</p></article>`;
    $('#evidence-cards').innerHTML = card(T('Published / reconciled', 'Publikováno / odsouhlaseno'), T('Whole-city budget', 'Rozpočet celé Prahy'), T('Annual history is available for 2010–2025. Native 2025 purpose and economic totals independently reconcile to the consolidated headline. Earlier detailed years are not published in this view.', 'Roční historie pokrývá 2010–2025. Součty paragrafů a položek pro rok 2025 samostatně odpovídají konsolidovanému souhrnu. Detail dřívějších let zde není publikován.'), [[T('Dataset', 'Datová sada'), receipt?.datasetId], [T('Snapshot generated', 'Snímek vytvořen'), receipt?.generatedAt], [T('Unit / scope', 'Jednotka / rozsah'), 'CZK · FIN 2-12 M · 00064581']], link(monitor(state.year), T('Official financial statement', 'Oficiální finanční výkaz')) + ' · ' + link('https://www.praha.eu/documents/d/praha/rozpocet-2024-plneni', T('City / districts consolidation · 2024, pp. 2–4', 'Konsolidace města a městských částí · 2024, s. 2–4'))) +
      card(T('Published / partial', 'Publikováno / dílčí'), T('Magistrate detail', 'Detail magistrátu'), T('Accounting rows, projects and invoice allocations retain their native codes and original source fingerprint. Availability does not establish full-year completeness or a bank-payment trail.', 'Účetní řádky, akce a fakturační alokace zachovávají původní kódy i otisk zdroje. Dostupnost nedokládá úplnost roku ani bankovní platbu.'), [[T('Release', 'Vydání'), detail?.evidence?.cityvizor?.releaseId || overview.coverage.cityvizor.release], [T('Source validity / year', 'Platnost zdroje / rok'), `${detail?.sourceValidity || '—'} / ${state.year}`], [T('Accounting rows / selected year', 'Účetní řádky / vybraný rok'), detail?.accountingRows?.length ?? '—'], [T('Source SHA-256', 'SHA-256 zdroje'), detail?.evidence?.cityvizor?.sourceSha256]], link('https://cityvizor.praha.eu/magistrat', 'CityVizor · Praha')) +
      card(T('Held / not published', 'Uloženo / nepublikováno'), T('Contracts and local outcomes', 'Smlouvy a místní podmínky'), T('The private Hlídač snapshot has not been published as a reconciled contract layer. Local PAQ observations are published separately and joined here only by verified municipality identity and year.', 'Neveřejný snímek Hlídače dosud nemá publikovanou odsouhlasenou vrstvu smluv. Místní pozorování PAQ jsou publikována samostatně a zde spojena pouze podle ověřené obce a roku.'), [[T('Privately held contract records', 'Neveřejně uložené záznamy smluv'), `${number(overview.coverage.contracts.acceptedRows)} · ${overview.coverage.contracts.completedAt.slice(0, 10)} · ${overview.coverage.contracts.sourceQuery}`], [T('Contract snapshot fingerprint', 'Otisk snímku smluv'), overview.coverage.contracts.normalizedSha256], [T('Contract-to-payment matches', 'Vazby smlouva–faktura'), T('Not verified; not counted', 'Neověřeno; nezapočítáno')], [T('Outcome series / exact territory', 'Řady ukazatelů / přesné území'), state.context?.series ? `${state.context.series.length} · obec:554782` : state.context?.unavailable ? T('Unavailable', 'Nedostupné') : T('Loading', 'Načítání')], [T('PAQ snapshot', 'Snímek PAQ'), state.context?.snapshot], [T('PAQ licence', 'Licence PAQ'), state.context?.license || 'CC BY-NC 4.0']], link('https://datapaq.cz/?g=obec&vis=table', 'PAQ Research · DataPAQ'));
  }
  try {
    const overview = await window.PrahaBudgetData.loadOverview(); state.overview = overview;
    if (!overview.history.some(row => row.year === state.year)) state.year = overview.latest.year;
    await window.PSDPlotReady; chartReady = true; shell(); renderOverview(); writeURL();
    app.setAttribute('aria-busy', 'false'); app.dataset.ready = 'true';
    const detail = selectYear(state.year);
    const context = window.PrahaBudgetData.loadContext().then(value => { state.context = value; $('#context-series').innerHTML = value.series.map(series => `<option value="${esc(series.id)}">${esc(name(series))}</option>`).join(''); renderContext(); renderEvidence(); }).catch(() => { $('#context-series').innerHTML = `<option>${T('Context unavailable', 'Kontext není dostupný')}</option>`; state.context = { unavailable: true }; $('#context-detail').innerHTML = `<p id="association-status" role="status">${T('The published outcome service is unavailable. No substitute geography or estimated values are shown.', 'Publikovaná služba ukazatelů není dostupná. Nezobrazujeme náhradní území ani odhadované hodnoty.')}</p>`; renderEvidence(); });
    await Promise.allSettled([detail, context]); app.dataset.loaded = 'true';
    let resizeTimer; window.addEventListener('resize', () => { clearTimeout(resizeTimer); resizeTimer = setTimeout(() => { renderOverview(); renderBudget(); renderContext(); }, 160); });
  } catch (error) {
    app.setAttribute('aria-busy', 'false'); app.innerHTML = `<div class="pb-fatal"><span class="pb-tag">${T('Published data unavailable', 'Publikovaná data nejsou dostupná')}</span><h1>${T('Praha’s budget could not be opened.', 'Rozpočet Prahy se nepodařilo otevřít.')}</h1><p>${T('The viewer has not substituted old, partial or invented values. Retry when the published service is available.', 'Prohlížeč nenahradil hodnoty staršími, neúplnými ani vymyšlenými údaji. Zkuste to znovu po obnovení publikované služby.')}</p><button class="pb-button" type="button" onclick="location.reload()">${T('Try again', 'Zkusit znovu')}</button><p>${link(monitor(state.year), T('Official accounts', 'Oficiální výkazy'))}</p></div>`;
  }
}());
