const LANG = () => window.PSDLanguage?.current?.() ?? (document.documentElement.lang === 'en' ? 'en' : 'cs');
const PAGE = 40;
const COPY = {
  en: {
    title: 'Data processing and release log', lede: 'A public provenance ledger: what PSD received, what it processed, and where the result is published.',
    method: 'Coverage, sources and architecture →', type: 'Event', all: 'All events', ingestion: 'Source intake', data_release: 'Data release', deployment: 'Application deployment',
    source: 'Upstream source', dataset: 'PSD dataset / project', sourceFilter: 'Dataset', allSources: 'All datasets', country: 'Country', allCountries: 'All countries', noCountry: 'No country', search: 'Search', searchPh: 'source, dataset, build or SHA…',
    count: (n, total) => `${n} of ${total} events`, empty: 'No event matches.', more: 'Load more', loading: 'Loading the public ledger…', failed: 'The process log could not be loaded.',
    evidence: 'Evidence basis', volume: 'Processed volume', git: 'Git SHA', pr: 'Pull request', build: 'Cloud Build ID', digest: 'Image digest', releases: 'Data-release IDs', checker: 'Automated checker', approver: 'Human approval', notRecorded: 'not recorded',
    destinations: 'Published on the website', noDestination: 'No public destination is mapped for this event.', sourceEvidence: 'Original source links', artifact: 'Processed artifacts', permalink: 'Permanent event link',
    deployed: 'deployed', skipped: 'skipped', received: 'received', processed: 'processed', published: 'published', notPublished: 'not mapped to a public page',
    reconstructed: 'reconstructed from existing evidence', native: 'recorded when it happened', multiplePublishers: (n) => `${n} source organisations`, limitsTitle: 'How to read this ledger',
    limits: ['Received means PSD recorded a retrieval or warehouse load. Processed means that event produced an artifact, fact, entity or release record. Published requires a mapped public page; it is not inferred from processing alone.','Historical source events were reconstructed from committed load and provenance records. Missing source organisations, checks, approvals and URLs remain explicitly unrecorded.','Application deployments are separate from data releases. A skipped deployment built an image but did not change production.'],
  },
  cs: {
    title: 'Deník zpracování a vydávání dat', lede: 'Veřejný registr původu: co PSD přijalo, co zpracovalo a kde je výsledek publikovaný.',
    method: 'Pokrytí, zdroje a architektura →', type: 'Událost', all: 'Všechny události', ingestion: 'Příjem zdroje', data_release: 'Datové vydání', deployment: 'Nasazení aplikace',
    source: 'Původní zdroj', dataset: 'Datová sada / projekt PSD', sourceFilter: 'Datová sada', allSources: 'Všechny datové sady', country: 'Země', allCountries: 'Všechny země', noCountry: 'Bez země', search: 'Hledat', searchPh: 'zdroj, sada, build nebo SHA…',
    count: (n, total) => `${n} z ${total} událostí`, empty: 'Žádná událost neodpovídá.', more: 'Načíst další', loading: 'Načítám veřejný registr…', failed: 'Provozní deník se nepodařilo načíst.',
    evidence: 'Podklad záznamu', volume: 'Zpracovaný objem', git: 'Git SHA', pr: 'Pull request', build: 'Cloud Build ID', digest: 'Otisk obrazu', releases: 'ID datových vydání', checker: 'Automatická kontrola', approver: 'Lidské schválení', notRecorded: 'nezaznamenáno',
    destinations: 'Publikováno na webu', noDestination: 'K této události není přiřazená veřejná stránka.', sourceEvidence: 'Odkazy na původní zdroje', artifact: 'Zpracované artefakty', permalink: 'Trvalý odkaz na událost',
    deployed: 'nasazeno', skipped: 'přeskočeno', received: 'přijato', processed: 'zpracováno', published: 'publikováno', notPublished: 'bez přiřazené veřejné stránky',
    reconstructed: 'zpětně sestaveno z existujících podkladů', native: 'zaznamenáno při události', multiplePublishers: (n) => `${n} zdrojových organizací`, limitsTitle: 'Jak registr číst',
    limits: ['Přijato znamená evidované stažení nebo načtení do skladu. Zpracováno znamená vznik artefaktu, faktu, jednotky nebo vydání. Publikováno vyžaduje přiřazenou veřejnou stránku; ze samotného zpracování se neodvozuje.','Historické události jsou zpětně sestavené z uložených záznamů o načtení a původu. Chybějící organizace, kontroly, schválení a URL zůstávají výslovně nezaznamenané.','Nasazení aplikace je oddělené od datového vydání. Přeskočené nasazení vytvořilo obraz, ale nezměnilo produkci.'],
  },
};

const ROUTES = {'/':['Domovská stránka','Homepage'],'/country.html':['Profily zemí','Country profiles'],'/comparison.html':['Srovnání zemí','Country comparison'],'/methodology.html':['Pokrytí a zdroje','Coverage and sources'],'/process/log/':['Provozní deník','Process log'],'/money-flow.html':['Tok veřejných peněz','Public money flow'],'/czech-sources.html':['Registr českých zdrojů','Czech source registry'],'/cz/municipalities/':['České obce','Czech municipalities'],'/deep-dives/funding/':['Financování','Funding'],'/deep-dives/industry/diagnostics/':['Průmysl','Industry'],'/deep-dives/european-politics/':['Evropská politika','European politics'],'/about.html':['O projektu','About the project']};
const MUNICIPAL = {france:['Francie','France'],germany:['Německo','Germany'],england:['Anglie','England'],poland:['Polsko','Poland'],ukraine:['Ukrajina','Ukraine'],brazil:['Brazílie','Brazil'],denmark:['Dánsko','Denmark'],sweden:['Švédsko','Sweden'],japan:['Japonsko','Japan'],bolivia:['Bolívie','Bolivia'],chile:['Chile','Chile'],colombia:['Kolumbie','Colombia'],'costa-rica':['Kostarika','Costa Rica'],spain:['Španělsko','Spain'],georgia:['Gruzie','Georgia'],guatemala:['Guatemala','Guatemala'],italy:['Itálie','Italy'],'south-korea':['Jižní Korea','South Korea'],mexico:['Mexiko','Mexico'],peru:['Peru','Peru'],'el-salvador':['Salvador','El Salvador'],czechia:['Česko','Czechia']};
const el = (tag, attrs = {}, ...children) => { const node=document.createElement(tag); for(const [key,value] of Object.entries(attrs)){if(value==null||value===false)continue;if(key==='class')node.className=value;else if(key==='text')node.textContent=value;else node.setAttribute(key,value===true?'':String(value));} node.append(...children.filter(Boolean)); return node; };
const fmt = new Intl.NumberFormat('en-GB');
const volume = (value={}) => Object.entries(value).map(([key,amount])=>`${fmt.format(amount)} ${key.replaceAll('_',' ')}`).join(' · ');
const date = (event,lang) => new Date(event.timestamp||`${event.date}T00:00:00Z`).toLocaleDateString(lang==='en'?'en-GB':'cs-CZ',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
const absent = (value,t) => value==null||value===''?t.notRecorded:String(value);
const sourceHost = event => { try { return new URL(event.source_urls?.[0]).hostname.replace(/^www\./,''); } catch { return null; } };
const destinationLabel = (href,lang) => { const fixed=ROUTES[href]; if(fixed)return fixed[lang==='en'?1:0]; const slug=href.match(/^\/municipalities\/([^/]+)\/$/)?.[1]; if(slug&&MUNICIPAL[slug])return `${lang==='en'?'Municipal finance':'Obecní finance'} · ${MUNICIPAL[slug][lang==='en'?1:0]}`; return href; };
const lifecycle = event => event.lifecycle||{received:event.event_type==='ingestion'?true:null,processed:event.event_type!=='deployment',published:event.event_type==='deployment'?event.outcome==='deployed':Boolean(event.sections?.length)};
const deploymentToEvent = event => ({...event,run_id:event.event_id,date:event.timestamp.slice(0,10),record_kind:'native',evidence:'Cloud Build deployment receipt',source_id:'czbudget-public web application',publisher:'Public Spending Data',country_codes:[],sections:['/'],artifacts:[],source_urls:[],volume:{},lifecycle:{received:null,processed:true,published:event.outcome==='deployed'}});

const mount=document.querySelector('[data-run-log]');
let payload={runs:[],facets:{countries:[],sources:[]}},shown=PAGE,open=new URLSearchParams(location.search).get('event');
const filters={type:'',country:'',source:'',query:''};
const textOf=event=>[event.source_id,event.publisher,event.git_sha,event.cloud_build_id,event.image_digest,...(event.data_release_ids||[]),...(event.source_urls||[])].filter(Boolean).join(' ').toLowerCase();
const matches=event=>(!filters.type||event.event_type===filters.type)&&(!filters.country||(filters.country==='__none'?!event.country_codes.length:event.country_codes.includes(filters.country)))&&(!filters.source||event.source_id===filters.source)&&(!filters.query||textOf(event).includes(filters.query.toLowerCase()));

function statusStrip(event,t){if(event.event_type==='deployment')return el('div',{class:'run-log__lifecycle'},el('span',{class:`is-${event.outcome==='deployed'?'yes':'no'}`,text:t[event.outcome]||event.outcome}));const state=lifecycle(event);return el('div',{class:'run-log__lifecycle'},state.received!=null?el('span',{class:state.received?'is-yes':'is-no',text:t.received}):null,el('span',{class:state.processed?'is-yes':'is-no',text:t.processed}),el('span',{class:state.published?'is-yes':'is-no',text:state.published?t.published:t.notPublished}));}
function detail(event,t,lang){
  const cell=(label,value,isAbsent=false)=>el('div',{},el('dt',{text:label}),el('dd',{class:isAbsent?'is-absent':'',text:value}));
  const cells=[cell(t.evidence,`${event.evidence} · ${event.record_kind==='backfilled'?t.reconstructed:t.native}`),cell(t.volume,volume(event.volume)||'—')];
  if(event.event_type==='deployment'||event.event_type==='data_release')cells.push(cell(t.git,absent(event.git_sha,t),!event.git_sha),cell(t.pr,absent(event.pr_number,t),!event.pr_number),cell(t.build,absent(event.cloud_build_id,t),!event.cloud_build_id),cell(t.digest,absent(event.image_digest,t),!event.image_digest),cell(t.releases,event.data_release_ids?.join(' · ')||t.notRecorded,!event.data_release_ids?.length));else cells.push(cell(t.checker,t.notRecorded,true),cell(t.approver,t.notRecorded,true));
  const destinations=event.sections?.length?el('ul',{},...event.sections.map(href=>el('li',{},el('a',{href},el('strong',{text:destinationLabel(href,lang)}),el('code',{text:href}))))):el('p',{class:'run-log__empty-note',text:t.noDestination});
  const sources=event.source_urls?.length?el('ul',{},...event.source_urls.map(href=>el('li',{},el('a',{href,target:'_blank',rel:'noreferrer',text:href})))):el('p',{class:'run-log__empty-note',text:t.notRecorded});
  const artifacts=event.artifacts?.length?el('ul',{},...event.artifacts.map(href=>el('li',{},el('a',{href:`/${href}`},el('code',{text:href}))))):el('p',{class:'run-log__empty-note',text:t.notRecorded});
  return el('div',{class:'run-log__detail'},statusStrip(event,t),el('dl',{class:'run-log__kv'},...cells),el('div',{class:'run-log__wiki'},el('section',{},el('h3',{text:t.destinations}),destinations),el('section',{},el('h3',{text:t.sourceEvidence}),sources),el('section',{},el('h3',{text:t.artifact}),artifacts)),el('p',{class:'run-log__links'},el('a',{href:`?lang=${lang}&event=${encodeURIComponent(event.run_id)}`,text:t.permalink})));
}
function render(){
  const lang=LANG(),t=COPY[lang],all=payload.runs,list=all.filter(matches),page=list.slice(0,shown);document.title=`${t.title} — Public Spending Data`;
  const select=(label,value,options,change)=>{const node=el('select',{'aria-label':label},...options);node.value=value;node.onchange=()=>change(node.value);return node;};
  const type=select(t.type,filters.type,[el('option',{value:'',text:t.all}),...['ingestion','data_release','deployment'].map(value=>el('option',{value,text:t[value]}))],value=>{filters.type=value;shown=PAGE;render();});
  const source=select(t.sourceFilter,filters.source,[el('option',{value:'',text:t.allSources}),...payload.facets.sources.map(item=>el('option',{value:item.value,text:`${item.value} (${item.runs})`}))],value=>{filters.source=value;shown=PAGE;render();});
  const country=select(t.country,filters.country,[el('option',{value:'',text:t.allCountries}),...payload.facets.countries.map(item=>el('option',{value:item.value,text:`${item.value} (${item.runs})`})),el('option',{value:'__none',text:t.noCountry})],value=>{filters.country=value;shown=PAGE;render();});
  const search=el('input',{type:'search',value:filters.query,placeholder:t.searchPh,'aria-label':t.search});search.oninput=()=>{filters.query=search.value;shown=PAGE;render();};
  const ledger=el('div',{class:'run-log__ledger'});
  for(const event of page){const isOpen=open===event.run_id,host=sourceHost(event),publisher=event.publisher||host||(event.publisher_count>1?t.multiplePublishers(event.publisher_count):t.notRecorded);const row=el('button',{class:'run-log__row',type:'button','aria-expanded':String(isOpen)},el('span',{class:'run-log__d',text:date(event,lang)}),el('span',{class:`run-log__badge run-log__badge--${event.event_type}`,text:t[event.event_type]}),el('span',{class:`run-log__publisher${event.publisher||host?'':' is-absent'}`,text:publisher}),el('span',{class:'run-log__dataset',text:event.source_id}),statusStrip(event,t),el('span',{class:event.country_codes.length?'run-log__cc':'run-log__cc run-log__cc--none',text:event.country_codes.join(' ')||'—'}));row.onclick=()=>{open=isOpen?null:event.run_id;const url=new URL(location.href);open?url.searchParams.set('event',open):url.searchParams.delete('event');history.replaceState(null,'',url);render();};ledger.append(row);if(isOpen)ledger.append(detail(event,t,lang));}
  if(!page.length)ledger.append(el('p',{class:'run-log__empty',text:t.empty}));const more=shown<list.length?el('button',{class:'run-log__more',type:'button',text:t.more}):null;if(more)more.onclick=()=>{shown+=PAGE;render();};const totals=['ingestion','data_release','deployment'].map(kind=>[kind,all.filter(event=>event.event_type===kind).length]);
  mount.replaceChildren(el('header',{class:'run-log__head'},el('span',{class:'run-log__kicker',text:'PUBLICSPENDINGDATA.ORG / DATA PROVENANCE'}),el('h1',{text:t.title}),el('p',{class:'run-log__lede'},document.createTextNode(`${t.lede} `),el('a',{href:`/methodology.html?lang=${lang}#release-architecture`,text:t.method})),el('div',{class:'run-log__types'},...totals.map(([kind,count])=>el('div',{},el('b',{text:fmt.format(count)}),el('span',{text:t[kind]}))))),el('div',{class:'run-log__filters'},el('label',{text:t.type}),type,el('label',{text:t.sourceFilter}),source,el('label',{text:t.country}),country,el('label',{text:t.search}),search,el('span',{class:'run-log__spacer'}),el('span',{class:'run-log__count',text:t.count(list.length,all.length)})),el('div',{class:'run-log__column-heads'},...['Date','Event',t.source,t.dataset,'Status',t.country].map(text=>el('span',{text}))),ledger,more||document.createTextNode(''),el('section',{class:'run-log__limits'},el('h2',{text:t.limitsTitle}),...t.limits.map(value=>el('p',{text:value}))));
}

mount.innerHTML=`<p class="run-log__loading">${COPY[LANG()].loading}</p>`;
try{payload=await(await fetch('/data/registry/run-log.v1.json')).json();render();fetch('/api/v1/process-log/deployments').then(response=>response.ok?response.json():null).then(live=>{if(!live)return;payload.runs.push(...(live.data?.events||[]).map(deploymentToEvent));payload.runs.sort((a,b)=>String(b.timestamp||b.date).localeCompare(String(a.timestamp||a.date)));render();}).catch(()=>{});}catch{mount.innerHTML=`<p class="run-log__loading run-log__loading--error">${COPY[LANG()].failed}</p>`;}
addEventListener('psdlanguagechange',render);
