import {readRussiaAggregate,aggregateModel,supplierComparisons,categoryGrowth,supplierHistory,RESEARCH_SUPPLIERS,HUBS} from './lib/russia-trade-model.mjs';
const $=s=>document.querySelector(s),lang=document.documentElement.lang==='cs'?'cs':'en',tr=(cs,en)=>lang==='cs'?cs:en;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const locale=lang==='cs'?'cs-CZ':'en-GB',money=v=>v==null?'—':new Intl.NumberFormat(locale,{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(v),exact=v=>v==null?'—':new Intl.NumberFormat(locale,{maximumFractionDigits:9}).format(v),pct=v=>v==null?'—':new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:1}).format(v);
const names={KAZ:tr('Kazachstán','Kazakhstan'),KGZ:tr('Kyrgyzstán','Kyrgyzstan'),RUS:tr('Rusko','Russia')},colors={KAZ:'#a8b63f',KGZ:'#83abb2',RUS:'#c93237'};
const chapters={'01':['Živá zvířata','Live animals'],'02':['Maso','Meat'],'03':['Ryby','Fish'],'04':['Mléčné výrobky','Dairy'],'08':['Ovoce a ořechy','Fruit & nuts'],'10':['Obiloviny','Cereals'],'15':['Tuky a oleje','Fats & oils'],'22':['Nápoje','Beverages'],'25':['Sůl a minerály','Salt & minerals'],'26':['Rudy','Ores'],'27':['Minerální paliva','Mineral fuels'],'28':['Anorganické chemikálie','Inorganic chemicals'],'29':['Organické chemikálie','Organic chemicals'],'30':['Léčiva','Pharmaceuticals'],'31':['Hnojiva','Fertilizers'],'33':['Kosmetika','Cosmetics'],'38':['Chemické výrobky','Chemical products'],'39':['Plasty','Plastics'],'40':['Kaučuk','Rubber'],'44':['Dřevo','Wood'],'48':['Papír','Paper'],'61':['Pletené oděvy','Knitted apparel'],'62':['Oděvy','Apparel'],'64':['Obuv','Footwear'],'70':['Sklo','Glass'],'71':['Drahé kovy a kameny','Precious metals & stones'],'72':['Železo a ocel','Iron & steel'],'73':['Výrobky ze železa','Iron & steel articles'],'74':['Měď','Copper'],'76':['Hliník','Aluminium'],'82':['Nástroje','Tools'],'84':['Stroje','Machinery'],'85':['Elektrická zařízení','Electrical equipment'],'86':['Železniční zařízení','Rail equipment'],'87':['Vozidla','Vehicles'],'88':['Letadla','Aircraft'],'89':['Lodě','Ships'],'90':['Optické a zdravotnické přístroje','Optical & medical instruments'],'94':['Nábytek','Furniture'],'95':['Hračky a sport','Toys & sports'],'99':['Zvláštní obchod','Special trade']};
const detailed={'854231':['Procesory a řadiče','Processors & controllers'],'847130':['Přenosné počítače','Portable computers'],'845710':['Obráběcí centra','Machining centres'],'848210':['Kuličková ložiska','Ball bearings']};
const productName=code=>code==='TOTAL'?tr('Veškeré vykázané zboží','All observed goods'):(detailed[code]||chapters[code])?.[lang==='cs'?0:1]||`HS ${code}`;
const params=new URLSearchParams(location.search),legacy=params.has('exporter')||params.has('via');
const validProduct=p=>p==='TOTAL'||/^(0[1-9]|[1-8][0-9]|9[0-9])$/.test(p)||Object.hasOwn(detailed,p);
const state={frequency:params.get('frequency')==='M'?'M':'A',product:!legacy&&validProduct(params.get('product'))?params.get('product'):'TOTAL',period:legacy?null:params.get('period'),data:null,model:null,geometry:null,plot:null,charts:[],map:null,playing:false,timer:null,loading:true,request:0,leadChart:null,growthData:null,growthCharts:[],growthYear:null,growthBase:'2019',growthFlow:'M',growthRequest:null};
const label=p=>p?.length===4?p:p?new Intl.DateTimeFormat(locale,{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${p.slice(0,4)}-${p.slice(4)}-01T00:00:00Z`)):'—';
const country=code=>names[code]||state.data?.countries?.find(c=>c.iso3===code)?.name||code;
const source=(data=state.data)=>({name:'UN Comtrade',url:data.source.url,table:data.source.table,extracted:data.source.retrieved_at||'—',vintage:'outturn',definition:tr('Vypočtený součet dostupných původních HS6; běžné USD.','Calculated sum of available original HS6 records; current USD.'),caveat:tr('Dostupné detaily, ne oficiální TOTAL. Chybějící není nula.','Available detail, not official TOTAL. Missing is not zero.')});
function sync(){const u=new URL(location.href);for(const k of ['exporter','via'])u.searchParams.delete(k);for(const k of ['frequency','product','period'])if(state[k])u.searchParams.set(k,state[k]);u.searchParams.set('lang',lang);history.replaceState(null,'',u);}
function playback(){const rows=state.model?.rows||[],i=rows.findIndex(r=>r.period===state.period),ready=rows.length>0&&!state.loading;$('#rt-play').disabled=!ready;$('#rt-play').textContent=state.playing?tr('Ⅱ Pauza','Ⅱ Pause'):tr('▶ Přehrát','▶ Play');$('#rt-play').setAttribute('aria-pressed',String(state.playing));$('#rt-prev').disabled=!ready||i<=0;$('#rt-next').disabled=!ready||i>=rows.length-1;const slider=$('#rt-timeline');slider.disabled=!ready;slider.max=Math.max(0,rows.length-1);slider.value=Math.max(0,i);slider.setAttribute('aria-valuetext',label(state.period));$('.rt-stage').classList.toggle('routes-playing',state.playing);document.querySelectorAll('[data-chapter]').forEach(b=>b.disabled=!ready);}
function pause(){state.playing=false;clearTimeout(state.timer);playback();}
function tick(){state.timer=setTimeout(()=>{if(!state.playing)return;const i=state.model.rows.findIndex(r=>r.period===state.period);if(i>=state.model.rows.length-1)return pause();select(state.model.rows[i+1].period,false);tick();},1500);}
function select(period,stop=true){if(stop)pause();if(!state.model?.periods.includes(period))return;state.period=period;sync();renderPeriod();}
function table(heads,rows){return `<table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(cells=>`<tr>${cells.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
const cell=v=>`<span title="${esc(exact(v))} USD">${money(v)}</span>`;
function renderLeads(){
 const model=supplierHistory(state.data,state.period.slice(0,4)),wrapper=$('#rt-lead-chart');state.leadChart?.destroy();state.leadChart=null;wrapper.replaceChildren();
 const labels={KOR:tr('Jižní Korea','South Korea'),GEO:tr('Gruzie','Georgia'),DEU:tr('Německo','Germany'),TUR:tr('Turecko','Türkiye'),ITA:tr('Itálie','Italy')},palette=['#427c68','#bd923f','#c93237','#537b84','#89738b'];
 $('#rt-lead-legend').innerHTML=RESEARCH_SUPPLIERS.map((code,i)=>`<span><i style="background:${palette[i]}"></i>${esc(labels[code])}</span>`).join('');
 $('#rt-lead-status').textContent=tr(`Roční hlášení vývozců → Kyrgyzstán · ${productName(state.product)}. Tabulka: ${model.year} proti 2019${model.year!==model.requestedYear?` (poslední dostupný roční údaj do ${model.requestedYear})`:""}. Měsíční data před 2024 zde chybí; zlomy z článku v roce 2022 nejsou nezávisle ověřeny.`,`Annual exporter declarations → Kyrgyzstan · ${productName(state.product)}. Table: ${model.year} against 2019${model.year!==model.requestedYear?` (latest available annual year at or before ${model.requestedYear})`:""}. Monthly data before 2024 is unavailable here; the article’s 2022 breakpoints have not been independently reproduced.`);
 if(model.rows.length){const host=document.createElement('div');wrapper.append(host);const title=tr('Pět dodavatelů do Kyrgyzstánu','Five suppliers to Kyrgyzstan');state.leadChart=state.plot.render(host,{type:'line',rows:model.rows,fields:RESEARCH_SUPPLIERS.map((key,i)=>({key,label:labels[key],color:palette[i],format:v=>`${exact(v)} USD`})),title,unit:tr('Běžné USD / rok','Current USD / year'),height:350,locale});window.PSDChart.register({slug:'russia-research-suppliers',el:wrapper,title,accessor:state.leadChart.accessor,exports:['csv','png'],embeddable:false,source:{...source(),definition:tr('Samostatná roční hlášení vývozců: dostupné součty HS6 do Kyrgyzstánu.','Separate annual exporter declarations: available HS6 subtotals to Kyrgyzstan.')}});}
 $('#rt-lead-values').innerHTML=table([tr('Vývozce','Exporter'),'2019 USD',`${esc(model.year)} USD`,'Δ USD',tr('Změna','Change')],model.comparisons.map(r=>[`${esc(labels[r.reporter])} <small>${r.reporter}</small>`,cell(r.base),cell(r.value),cell(r.delta),r.ratio===null?'—':pct(r.ratio-1)]));
}
function renderSuppliers(){
 const q=$('#rt-search').value.toLowerCase(),all=state.model.suppliers(state.period),mirrors=state.frequency==='A'?(state.data.suppliers||[]).filter(o=>o.period===state.period&&HUBS.includes(o.partner_iso3)):[];
 const codes=[...new Set([...all.map(o=>o.partner_iso3||String(o.partner_area_code)),...mirrors.map(o=>o.reporter_iso3)])];
 const ranked=codes.map(code=>{const records=HUBS.map(h=>all.find(o=>o.reporter_iso3===h&&(o.partner_iso3||String(o.partner_area_code))===code));return {code,records,total:records.reduce((s,o)=>s+(o?.value_usd||0),0)};}).sort((a,b)=>b.total-a.total).filter(r=>`${country(r.code)} ${r.code}`.toLowerCase().includes(q));
 const heads=[tr('Původ','Origin'),...HUBS.flatMap(h=>[country(h)+' · '+tr('dovoz USD','imports USD'),...(state.frequency==='A'?[tr('Hlášení dodavatele USD','Supplier report USD'),tr('Rozdíl hlášení USD','Mirror gap USD')]:[]),tr('Podíl dovozu','Import share')])];
 $('#rt-suppliers').innerHTML=table(heads,ranked.map(r=>[`${esc(country(r.code))} <small>${esc(r.code)}</small>`,...r.records.flatMap((o,i)=>{const denom=state.model.get(state.period,HUBS[i],'M'),mirror=mirrors.find(m=>m.reporter_iso3===r.code&&m.partner_iso3===HUBS[i])?.value_usd??null,value=o?.value_usd??null;return [cell(value),...(state.frequency==='A'?[cell(mirror),cell(mirror!==null&&value!==null?mirror-value:null)]:[]),pct(denom>0&&value!==null?value/denom:null)];})]));
}
function renderPeriod(){const m=state.model,p=state.period;$('#rt-month').textContent=label(p);$('#rt-period-label').textContent=label(p);$('#rt-era').textContent=p<'2022'?tr('Před plnou invazí','Before the full-scale invasion'):p.slice(0,4)==='2022'?tr('Rok invaze · 24. února 2022','Invasion year · 24 February 2022'):tr('Po plné invazi','After the full-scale invasion');$('#rt-product-tag').textContent=productName(state.product);
 const imports=m.suppliers(p),lookup=new Map((state.data.countries||[]).map(c=>[c.iso3,c.iso2]));lookup.set('KAZ','kz');lookup.set('KGZ','kg');lookup.set('RUS','ru');
 const mapped=imports.filter(o=>lookup.get(o.partner_iso3)&&state.geometry.locations.some(l=>l.id===lookup.get(o.partner_iso3)));
 const edges=[...mapped].sort((a,b)=>(a.value_usd||0)-(b.value_usd||0)).map(o=>({from:o.partner_iso3,to:o.reporter_iso3,value:o.value_usd,color:colors[o.reporter_iso3],label:`${country(o.partner_iso3)} → ${country(o.reporter_iso3)} · ${label(p)} · ${exact(o.value_usd)} USD · ${tr('dovozní hlášení uzlu','hub-reported imports')}`}));
 for(const hub of HUBS)edges.push({from:hub,to:'RUS',value:m.get(p,hub,'X','RUS'),color:colors.RUS,label:`${country(hub)} → ${country('RUS')} · ${label(p)} · ${exact(m.get(p,hub,'X','RUS'))} USD · ${tr('vývozní hlášení uzlu','hub-reported exports')}`});
 const originTotals=new Map();for(const o of imports)originTotals.set(o.partner_iso3,(originTotals.get(o.partner_iso3)||0)+(o.value_usd||0));const labelled=new Set(['KAZ','KGZ','RUS',...[...originTotals].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([code])=>code)]);
 const nodes=[...new Set(edges.flatMap(e=>[e.from,e.to]))].map(id=>({id,iso2:lookup.get(id),label:country(id),quiet:!labelled.has(id)}));
 const max=Math.max(1,...state.data.observations.filter(o=>o.product_code===state.product&&Number(o.partner_area_code)!==0).map(o=>o.value_usd||0));state.map?.destroy();state.map=state.plot.render($('#rt-map'),{type:'route-map',geometry:state.geometry,nodes,edges,maxValue:max,worldView:true,title:`${productName(state.product)} · ${label(p)}`,note:tr('Vyberte spoj. Samostatná hlášení, nikoli sledované zásilky.','Select a route. Separate declarations, not tracked shipments.')});
 $('#rt-map-coverage').textContent=tr(`${mapped.length} z ${imports.length} vykázaných vazeb na mapě. Všechny jsou v tabulce. Tloušťka roste s odmocninou USD; škála je pevná v celé časové řadě. Červené spoje jsou nezávislé vývozy do Ruska.`,`${mapped.length} of ${imports.length} reported links mapped. Every link remains in the table. Width scales with the square root of USD, fixed across the timeline. Red connections are independent exports to Russia.`);
 $('#rt-legs').innerHTML=HUBS.map(h=>{const a=m.compare(p,h,'M'),b=m.compare(p,h,'X','RUS');return `<article class="rt-leg" style="--leg-color:${colors[h]}"><small>${esc(country(h))}</small><div class="rt-leg-pair"><div><h3>${tr('Dovoz ze světa','Imports from the world')}</h3><strong>${money(a.value)}</strong><p>${tr('Proti 2019','Against 2019')}: ${a.ratio===null?'—':a.ratio.toFixed(2)+'×'}</p></div><div><h3>${tr('Vývoz do Ruska','Exports to Russia')}</h3><strong>${money(b.value)}</strong><p>${tr('Proti 2019','Against 2019')}: ${b.ratio===null?'—':b.ratio.toFixed(2)+'×'}</p></div></div></article>`;}).join('');
 $('#rt-status').textContent=state.frequency==='A'?tr('Roční pohled · všechny vykázané země původu · referenční rok 2019. Kazachstán 2020–2022: dostupný detail je pod národními součty; viz metodika.','Annual view · all reported origins · reference year 2019. Kazakhstan 2020–2022: available detail is below national totals; see methodology.'):tr('Měsíční detail je dostupný od roku 2024; předválečné měsíce chybí. Roční historie zůstává dostupná přepínačem. Mezery nejsou nuly.','Monthly detail is available from 2024; pre-war months are missing. Switch to Annual for the historical comparison. Gaps are not zeros.');
 const deps=m.dependencies(p),leading=deps.find(r=>r.jointGrowth!==null);$('#rt-findings').textContent=leading?tr(`${country(leading.hub)} · ${productName(leading.product)}: dovoz +${money(leading.inbound.delta)}, vývoz do Ruska +${money(leading.onward.delta)} proti roku 2019. Rusko odebírá ${pct(leading.russiaShare)} vykázaného vývozu této kapitoly.`,`${country(leading.hub)} · ${productName(leading.product)}: imports +${money(leading.inbound.delta)}, exports to Russia +${money(leading.onward.delta)} against 2019. Russia takes ${pct(leading.russiaShare)} of observed exports in this chapter.`):tr('Bez předválečného základu pořadí souběžného růstu nelze určit. Zde jsou dostupné hodnoty.','Without a pre-war baseline, simultaneous growth cannot be ranked. Available values are shown below.');
 $('#rt-dependencies').innerHTML=table([tr('Uzel / kapitola','Hub / chapter'),tr('Dovoz USD','Imports USD'),tr('Změna od 2019','Change since 2019'),tr('Do Ruska USD','To Russia USD'),tr('Změna od 2019','Change since 2019'),tr('Rusko / veškerý vývoz','Russia / all exports')],deps.map(r=>[`${esc(country(r.hub))}<br><button class="rt-chapter-link" data-product="${r.product}">${esc(productName(r.product))} · ${r.product}</button>`,cell(r.inbound.value),cell(r.inbound.delta),cell(r.onward.value),cell(r.onward.delta),pct(r.russiaShare)]));
 renderSuppliers();renderLeads();renderDirect();playback();
}
function renderDirect(){const year=state.period.slice(0,4),all=supplierComparisons(state.data,year),rows=all.filter(r=>r.eligible),sum=key=>rows.reduce((s,r)=>s+r[key].delta,0),direct=sum('direct'),hubs=sum('kaz')+sum('kgz');$('#rt-direct-summary').textContent=rows.length?tr(`${year} proti 2019 · společný panel ${rows.length} z ${all.length} dodavatelů. Změna vývozu přímo do Ruska: ${money(direct)}; do obou uzlů: ${money(hubs)}. Tyto částky se nepovažují za vzájemnou náhradu.`,`${year} against 2019 · matched panel of ${rows.length} of ${all.length} suppliers. Change in direct exports to Russia: ${money(direct)}; to both hubs: ${money(hubs)}. These amounts are not assumed to offset each other.`):tr(`Pro rok ${year} chybí úplný společný roční panel.`, `A complete matched annual panel is unavailable for ${year}.`);
 const excluded=all.filter(r=>!r.eligible),major=excluded.filter(r=>['CHN','USA','DEU','TUR','IND','KOR','GBR','JPN'].includes(r.reporter));
 $('#rt-direct-coverage').textContent=tr('Panel není globální součet a jeho složení se mezi roky mění.','This panel is not a global total, and its composition changes between years.')+(major.length?' '+tr('Chybí mimo jiné: ','Excluded major suppliers: ')+major.map(r=>country(r.reporter)).join(', ')+'.':'');
 $('#rt-exclusions').textContent=excluded.map(r=>country(r.reporter)).join(' · ')||'—';
 $('#rt-direct').innerHTML=table([tr('Vývozce','Exporter'),tr('Do Ruska: změna','To Russia: change'),tr('Do Kazachstánu: změna','To Kazakhstan: change'),tr('Do Kyrgyzstánu: změna','To Kyrgyzstan: change'),tr('Vzor','Pattern')],rows.map(r=>[esc(country(r.reporter)),cell(r.direct.delta),cell(r.kaz.delta),cell(r.kgz.delta),r.direct.delta<0&&r.hubDelta>0?tr('Přímo ↓ · uzly ↑','Direct ↓ · hubs ↑'):'—']));
}
function renderHistory(){state.charts.forEach(c=>c?.destroy());state.charts=[];for(const [id,keys,title] of [['rt-trend-wrapper',['KAZ','KGZ'],tr('Dovoz ze světa','World imports')],['rt-onward-wrapper',['KAZ_RUS','KGZ_RUS'],tr('Vývoz do Ruska','Exports to Russia')]]){const wrapper=$('#'+id);wrapper.replaceChildren();const host=document.createElement('div');wrapper.append(host);const chart=state.plot.render(host,{type:'line',rows:state.model.rows,fields:keys.map(key=>({key,label:country(key.slice(0,3)),color:colors[key.slice(0,3)],format:v=>`${exact(v)} USD`})),title,unit:`USD / ${state.frequency==='A'?tr('rok','year'):tr('měsíc','month')}`,height:310,locale,onSelect:r=>select(r.period)});state.charts.push(chart);window.PSDChart.register({slug:id,el:wrapper,title,accessor:chart.accessor,exports:['csv','png'],embeddable:false,source:source()});}
 $('#rt-source').textContent=`UN Comtrade · ${productName(state.product)} · ${state.frequency} · ${state.data.source.table} · ${tr('Staženo','Retrieved')}: ${state.data.source.retrieved_at||'—'}`;
 const world=state.data.observations.filter(o=>o.product_code===state.product&&Number(o.partner_area_code)===0&&o.flow_code==='M');$('#rt-provenance').innerHTML=`<p>${esc(state.data.source.method)} ${esc(state.data.source.release_note)}</p><div class="rt-table-scroll">${table([tr('Období / uzel','Period / hub'),'USD',tr('Počet HS6','HS6 count'),'HS',tr('Vydání načtení','Ingestion release')],world.map(o=>[`${esc(o.period)} · ${esc(o.reporter_iso3)}`,esc(o.reported_value_usd),esc(o.product_count),esc(o.classifications),`<code>${esc(o.release_ids)}</code>`]))}</div>`;
}
async function loadCategories(){
 $('#rt-growth-retry').hidden=true;
 try{
  if(state.data?.frequency==='A')state.growthData=state.data;
  if(!state.growthData){
   $('#rt-growth-status').textContent=tr('Načítáme roční kategorie…','Loading annual categories…');
   state.growthRequest ||= readRussiaAggregate('A','TOTAL').finally(()=>{state.growthRequest=null;});
   state.growthData=await state.growthRequest;
  }
  const allYears=[...new Set(state.growthData.observations.filter(o=>o.product_code==='TOTAL').map(o=>o.period))].sort();
  if(!allYears.includes(state.growthBase))state.growthBase=allYears[0]||'2019';
  const bases=allYears.filter(y=>y<'2022');
  $('#rt-growth-base').innerHTML=bases.map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join('');$('#rt-growth-base').value=state.growthBase;
  const years=allYears.filter(y=>y>state.growthBase);
  if(!years.includes(state.growthYear))state.growthYear=years.at(-1)||'2019';
  $('#rt-growth-year').innerHTML=(years.length?years:['2019']).map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join('');$('#rt-growth-year').value=state.growthYear;
  renderCategories();
 }catch(error){console.error('Russia trade category chart failed',error);$('#rt-growth-status').textContent=tr('Roční kategorie se nepodařilo načíst.','Annual category data could not be loaded.');$('#rt-growth-retry').hidden=false;}
}
function renderCategories(){
 if(!state.growthData)return;
 const models=HUBS.map(hub=>categoryGrowth(state.growthData,{hub,flow:state.growthFlow,baseYear:state.growthBase,endYear:state.growthYear}));
 const palette=['#809027','#c93237','#537b84','#bd923f','#89738b','#427c68','#d37d56','#53615e','#ab6380','#7b673f'];
 const codes=[...new Set(models.flatMap(m=>m.categories.map(c=>c.code)))].sort(),paint=new Map(codes.map((code,i)=>[code,palette[i%palette.length]]));
 state.growthCharts.forEach(c=>c.destroy());state.growthCharts=[];
 $('#rt-growth-status').textContent=tr(`Pořadí podle absolutního růstu v USD: ${state.growthBase} → ${state.growthYear}. Každý uzel má vlastní svislou škálu; hodnoty lze porovnat v tabulce.`, `Ranked by absolute USD growth: ${state.growthBase} → ${state.growthYear}. Each hub has its own vertical scale; compare exact values in the tables.`);
 for(const model of models){
  const wrapper=$('#rt-growth-'+model.hub);wrapper.replaceChildren();const host=document.createElement('div');wrapper.append(host);
  const fields=[{key:'other',label:tr('Ostatní kategorie','Other categories'),color:'#d2ccc1'},...model.categories.map(c=>({key:c.code,label:`${productName(c.code)} · HS ${c.code}`,color:paint.get(c.code)}))].map(f=>({...f,format:v=>`${exact(v)} USD`}));
  const title=`${country(model.hub)} · ${state.growthFlow==='M'?tr('dovoz ze světa','World imports'):tr('vývoz do Ruska','exports to Russia')}`;
  const chart=state.plot.render(host,{type:'stacked',stackMode:'absolute',rows:model.rows,fields,title,unit:tr('Běžné USD / rok','Current USD / year'),height:350,locale});state.growthCharts.push(chart);
  window.PSDChart.register({slug:({KAZ:'russia-category-growth-kaz',KGZ:'russia-category-growth-kgz'})[model.hub],el:wrapper,title,accessor:chart.accessor,exports:['csv','png'],embeddable:false,source:{...source(state.growthData),definition:tr('Roční HS2 složení dostupných HS6 součtů; pět největších přírůstků od vybraného základu a zbytek.','Annual HS2 composition of observed HS6 subtotals; five largest increases from the selected baseline and the remainder.')}});
  $('#rt-growth-key-'+model.hub).innerHTML=model.categories.length?`<table class="rt-growth-key"><caption>${tr(`Zvýrazněné přírůstky proti ${state.growthBase}`,`Highlighted increases against ${state.growthBase}`)}</caption><thead><tr><th>${tr('Kategorie','Category')}</th><th>Δ USD</th><th>${tr('Změna','Change')}</th></tr></thead><tbody>${model.categories.map(c=>`<tr><td><i style="background:${paint.get(c.code)}"></i>${esc(productName(c.code))} <small>HS ${c.code}</small></td><td>${cell(c.delta)}</td><td>${c.ratio===null?'—':pct(c.ratio-1)}</td></tr>`).join('')}</tbody></table>`:`<p class="rt-note">${tr(`Není doložen kladný růst proti roku ${state.growthBase}.`,`No positive growth against ${state.growthBase} is established.`)}</p>`;
 }
}
function latestShared(){return state.model?.rows.filter(r=>[r.KAZ,r.KGZ,r.KAZ_RUS,r.KGZ_RUS].every(Number.isFinite)).at(-1)?.period||state.model?.periods.at(-1);}
async function load(){pause();const request=++state.request;state.loading=true;state.data=null;state.model=null;state.map?.destroy();state.charts.forEach(c=>c?.destroy());state.leadChart?.destroy();state.leadChart=null;playback();$('#rt-status').textContent=tr('Načítáme všechny dodavatele a obě země…','Loading all suppliers and both hubs…');$('#rt-retry').hidden=true;$('#rt-map').setAttribute('aria-busy','true');for(const id of ['rt-lead-chart','rt-lead-legend','rt-lead-values','rt-lead-status','rt-map','rt-legs','rt-trend-wrapper','rt-onward-wrapper','rt-suppliers','rt-dependencies','rt-direct','rt-direct-summary','rt-direct-coverage','rt-exclusions','rt-findings','rt-provenance','rt-source','rt-map-coverage'])$('#'+id).replaceChildren();
 try{const data=await readRussiaAggregate(state.frequency,state.product);if(request!==state.request)return;state.data=data;state.model=aggregateModel(data);if(!state.model.rows.length)throw new Error('empty');if(!state.model.periods.includes(state.period))state.period=latestShared();state.loading=false;sync();renderHistory();renderPeriod();loadCategories();}
 catch(e){if(request!==state.request)return;console.error('Russia trade view failed',e);state.loading=false;state.model=null;playback();$('#rt-status').textContent=tr('Souhrnná data se nepodařilo načíst. Zkuste to znovu.','Aggregate data could not be loaded. Please retry.');$('#rt-retry').hidden=false;playback();}finally{if(request===state.request)$('#rt-map').setAttribute('aria-busy','false');}}
function controls(){document.querySelectorAll('[data-frequency]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.frequency===state.frequency)));$('#rt-product').value=state.product;}
document.querySelectorAll('[data-cs][data-en]').forEach(n=>n.innerHTML=n.dataset[lang]);document.title=tr('Obchod kolem Ruska','The trade around Russia')+' — Public Spending Data';$('#rt-back').href=`/deep-dives/?lang=${lang}`;
$('#rt-product').innerHTML=['TOTAL',...Array.from({length:97},(_,i)=>String(i+1).padStart(2,'0')), '99',...Object.keys(detailed)].map(code=>`<option value="${code}">${esc(productName(code))}${code==='TOTAL'?'':` · HS ${code}`}</option>`).join('');controls();
for(const b of document.querySelectorAll('[data-frequency]'))b.addEventListener('click',()=>{if(state.frequency===b.dataset.frequency)return;state.frequency=b.dataset.frequency;state.period=null;controls();load();});
$('#rt-product').addEventListener('change',e=>{state.product=e.target.value;load();});$('#rt-dependencies').addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(b){state.product=b.dataset.product;controls();load();$('#routes').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}});
$('#rt-growth-flow').addEventListener('change',e=>{state.growthFlow=e.target.value;renderCategories();});
$('#rt-growth-base').addEventListener('change',e=>{state.growthBase=e.target.value;loadCategories();});
$('#rt-growth-year').addEventListener('change',e=>{state.growthYear=e.target.value;renderCategories();});
$('#rt-growth-retry').addEventListener('click',loadCategories);
document.querySelectorAll('[data-supplier]').forEach(b=>b.addEventListener('click',()=>{if(!state.model)return;$('#rt-search').value=b.dataset.supplier;renderSuppliers();$('#rt-search').focus();}));
$('#rt-search').addEventListener('input',()=>{if(state.model)renderSuppliers();});$('#rt-retry').addEventListener('click',()=>state.plot&&state.geometry?load():start());
$('#rt-play').addEventListener('click',()=>{if(state.playing)return pause();if(state.period===state.model.periods.at(-1))select(state.model.periods[0]);state.playing=true;playback();tick();});$('#rt-timeline').addEventListener('input',e=>select(state.model.periods[Number(e.target.value)]));
for(const [id,step] of [['rt-prev',-1],['rt-next',1]])$('#'+id).addEventListener('click',()=>{const p=state.model.periods[state.model.periods.indexOf(state.period)+step];if(p)select(p);});
document.querySelectorAll('[data-chapter]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.chapter==='before'?'2019':b.dataset.chapter==='break'?'2022':latestShared();if(state.frequency==='M'&&b.dataset.chapter!=='after'){state.frequency='A';state.period=p;controls();load();}else select(p);}));
$('#rt-download').addEventListener('click',()=>{if(!state.data)return;const columns=['reporting_basis','frequency','period','reporter_iso3','flow_code','partner_iso3','partner_area_code','product_code','reported_value_usd','product_count','classifications','source_last_released','retrieved_at','release_ids','source_hashes'];const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const exportRows=[...state.data.observations.map(o=>({...o,frequency:state.frequency,reporting_basis:'HUB_REPORTED'})),...state.data.suppliers.map(o=>({...o,frequency:'A',flow_code:'X',product_code:state.product,reporting_basis:'SUPPLIER_REPORTED'}))];const csv=[columns,...exportRows.map(o=>columns.map(k=>o[k]))].map(r=>r.map(quote).join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`russia-trade-${state.frequency}-${state.product}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});addEventListener('pagehide',pause);
async function start(){try{state.plot=await window.PSDPlotReady;const r=await fetch('/data/world-map.v1.json');if(!r.ok)throw new Error('map');state.geometry=await r.json();await load();}catch(e){$('#rt-status').textContent=tr('Mapu se nepodařilo načíst. Zkuste to znovu.','The map could not be loaded. Please retry.');$('#rt-retry').hidden=false;}}
start();
