import {deltaAuditRows,deltaBasket,bilateralDelta,supplierDelta,hubDelta,deltaSlices,chooseStoryYear,bilateralHistory,directSupplierGrowth,largestMapSuppliers,readRussiaAggregate,aggregateModel,supplierComparisons,categoryGrowth,supplierHistory,RESEARCH_SUPPLIERS,HUBS} from './lib/russia-trade-model.mjs';
const $=s=>document.querySelector(s),lang=document.documentElement.lang==='cs'?'cs':'en',tr=(cs,en)=>lang==='cs'?cs:en;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const locale=lang==='cs'?'cs-CZ':'en-GB',money=v=>v==null?'—':new Intl.NumberFormat(locale,{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(v),exact=v=>v==null?'—':new Intl.NumberFormat(locale,{maximumFractionDigits:9}).format(v),pct=v=>v==null?'—':new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:1}).format(v);
const names={CHN:tr('Čína','China'),KOR:tr('Jižní Korea','South Korea'),PRK:tr('Severní Korea','North Korea'),KAZ:tr('Kazachstán','Kazakhstan'),KGZ:tr('Kyrgyzstán','Kyrgyzstan'),RUS:tr('Rusko','Russia'),TUR:tr('Turecko','Türkiye'),ARM:tr('Arménie','Armenia'),GEO:tr('Gruzie','Georgia'),UZB:tr('Uzbekistán','Uzbekistan'),IND:tr('Indie','India'),BLR:tr('Bělorusko','Belarus')},colors={KAZ:'#a8b63f',KGZ:'#83abb2',RUS:'#c93237'};
const chapters={'01':['Živá zvířata','Live animals'],'02':['Maso','Meat'],'03':['Ryby','Fish'],'04':['Mléčné výrobky','Dairy'],'08':['Ovoce a ořechy','Fruit & nuts'],'10':['Obiloviny','Cereals'],'15':['Tuky a oleje','Fats & oils'],'22':['Nápoje','Beverages'],'25':['Sůl a minerály','Salt & minerals'],'26':['Rudy','Ores'],'27':['Minerální paliva','Mineral fuels'],'28':['Anorganické chemikálie','Inorganic chemicals'],'29':['Organické chemikálie','Organic chemicals'],'30':['Léčiva','Pharmaceuticals'],'31':['Hnojiva','Fertilizers'],'33':['Kosmetika','Cosmetics'],'38':['Chemické výrobky','Chemical products'],'39':['Plasty','Plastics'],'40':['Kaučuk','Rubber'],'44':['Dřevo','Wood'],'48':['Papír','Paper'],'61':['Pletené oděvy','Knitted apparel'],'62':['Oděvy','Apparel'],'64':['Obuv','Footwear'],'70':['Sklo','Glass'],'71':['Drahé kovy a kameny','Precious metals & stones'],'72':['Železo a ocel','Iron & steel'],'73':['Výrobky ze železa','Iron & steel articles'],'74':['Měď','Copper'],'76':['Hliník','Aluminium'],'82':['Nástroje','Tools'],'84':['Stroje','Machinery'],'85':['Elektrická zařízení','Electrical equipment'],'86':['Železniční zařízení','Rail equipment'],'87':['Vozidla','Vehicles'],'88':['Letadla','Aircraft'],'89':['Lodě','Ships'],'90':['Optické a zdravotnické přístroje','Optical & medical instruments'],'94':['Nábytek','Furniture'],'95':['Hračky a sport','Toys & sports'],'99':['Zvláštní obchod','Special trade']};
// Compact chapter labels follow the UN Comtrade HS2 catalogue; the HS code remains visible.
Object.assign(chapters,{'05':['Ostatní živočišné výrobky','Other animal products'],'06':['Živé rostliny a květiny','Live plants & flowers'],'07':['Zelenina','Vegetables'],'09':['Káva, čaj a koření','Coffee, tea & spices'],'11':['Mlýnské výrobky','Milling products'],'12':['Olejnatá semena a rostliny','Oil seeds & plants'],'13':['Pryskyřice a rostlinné výtažky','Gums, resins & plant extracts'],'14':['Rostlinné pletací materiály','Vegetable plaiting materials'],'16':['Masné a rybí přípravky','Meat & fish preparations'],'17':['Cukr a cukrovinky','Sugar & confectionery'],'18':['Kakao','Cocoa'],'19':['Obilné a mléčné přípravky','Cereal & milk preparations'],'20':['Ovocné a zeleninové přípravky','Fruit & vegetable preparations'],'21':['Ostatní potravinové přípravky','Other food preparations'],'23':['Krmiva a potravinářské zbytky','Animal feed & food residues'],'24':['Tabák a nikotinové výrobky','Tobacco & nicotine products'],'32':['Barviva, barvy a inkousty','Dyes, paints & inks'],'34':['Mýdla, vosky a prací přípravky','Soap, waxes & washing preparations'],'35':['Bílkoviny, lepidla a enzymy','Proteins, glues & enzymes'],'36':['Výbušniny a pyrotechnika','Explosives & pyrotechnics'],'37':['Fotografické výrobky','Photographic goods'],'41':['Kůže a usně','Hides & leather'],'42':['Kožené výrobky a zavazadla','Leather articles & luggage'],'43':['Kožešiny a kožešinové výrobky','Furskins & fur articles'],'45':['Korek','Cork'],'46':['Pletací a košíkářské výrobky','Plaiting articles & basketware'],'47':['Buničina a papírový odpad','Pulp & recovered paper'],'49':['Tiskoviny','Printed matter'],'50':['Hedvábí','Silk'],'51':['Vlna a zvířecí srst','Wool & animal hair'],'52':['Bavlna','Cotton'],'53':['Rostlinná textilní vlákna','Vegetable textile fibres'],'54':['Chemická nekonečná vlákna','Man-made filaments'],'55':['Chemická střižová vlákna','Man-made staple fibres'],'56':['Vata, plsti a netkané textilie','Wadding, felt & nonwovens'],'57':['Koberce','Carpets'],'58':['Speciální tkaniny a krajky','Special fabrics & lace'],'59':['Povrstvené a průmyslové textilie','Coated & industrial textiles'],'60':['Pletené textilie','Knitted fabrics'],'63':['Ostatní textilní výrobky','Other made-up textiles'],'65':['Pokrývky hlavy','Headgear'],'66':['Deštníky a hole','Umbrellas & walking sticks'],'67':['Peří a umělé květiny','Feathers & artificial flowers'],'68':['Výrobky z kamene a cementu','Stone & cement articles'],'69':['Keramika','Ceramics'],'75':['Nikl','Nickel'],'78':['Olovo','Lead'],'79':['Zinek','Zinc'],'80':['Cín','Tin'],'81':['Ostatní základní kovy a cermety','Other base metals & cermets'],'83':['Ostatní výrobky ze základních kovů','Other base-metal articles'],'91':['Hodiny a hodinky','Clocks & watches'],'92':['Hudební nástroje','Musical instruments'],'93':['Zbraně a střelivo','Arms & ammunition'],'96':['Různé zpracované výrobky','Miscellaneous manufactured articles'],'97':['Umění a starožitnosti','Art & antiques']});
const detailed={'854231':['Procesory a řadiče','Processors & controllers'],'847130':['Přenosné počítače','Portable computers'],'845710':['Obráběcí centra','Machining centres'],'848210':['Kuličková ložiska','Ball bearings']};
const productName=code=>code==='TOTAL'?tr('Veškeré vykázané zboží','All observed goods'):(detailed[code]||chapters[code])?.[lang==='cs'?0:1]||`HS ${code}`;
const params=new URLSearchParams(location.search),legacy=params.has('exporter')||params.has('via');
const validProduct=p=>p==='TOTAL'||/^(0[1-9]|[1-8][0-9]|9[0-9])$/.test(p)||Object.hasOwn(detailed,p);
const state={mapDetail:params.get('map')==='all'?'all':'major',frequency:params.get('frequency')==='M'?'M':'A',product:!legacy&&validProduct(params.get('product'))?params.get('product'):'TOTAL',period:legacy?null:params.get('period'),data:null,model:null,geometry:null,plot:null,charts:[],map:null,playing:false,timer:null,loading:true,request:0,leadChart:null,growthData:null,growthCharts:[],growthYear:null,growthBase:'2019',growthFlow:'M',growthRequest:null};
const label=p=>p?.length===4?p:p?new Intl.DateTimeFormat(locale,{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${p.slice(0,4)}-${p.slice(4)}-01T00:00:00Z`)):'—';
const country=code=>names[code]||state.data?.countries?.find(c=>c.iso3===code)?.name||code;
const source=(data=state.data)=>({name:'UN Comtrade',url:data.source.url,table:data.source.table,extracted:data.source.retrieved_at||'—',vintage:'outturn',definition:tr('Vypočtený součet dostupných původních HS6; běžné USD.','Calculated sum of available original HS6 records; current USD.'),caveat:tr('Dostupné detaily, ne oficiální TOTAL. Chybějící není nula.','Available detail, not official TOTAL. Missing is not zero.')});
function sync(){const u=new URL(location.href);for(const k of ['exporter','via'])u.searchParams.delete(k);for(const k of ['frequency','product','period'])if(state[k])u.searchParams.set(k,state[k]);if(state.mapDetail==='all')u.searchParams.set('map','all');else u.searchParams.delete('map');u.searchParams.set('lang',lang);history.replaceState(null,'',u);}
function playback(){const rows=state.model?.rows||[],i=rows.findIndex(r=>r.period===state.period),ready=rows.length>0&&!state.loading;$('#rt-play').disabled=!ready;$('#rt-play').textContent=state.playing?tr('Ⅱ Pauza','Ⅱ Pause'):tr('▶ Přehrát','▶ Play');$('#rt-play').setAttribute('aria-pressed',String(state.playing));$('#rt-prev').disabled=!ready||i<=0;$('#rt-next').disabled=!ready||i>=rows.length-1;const slider=$('#rt-timeline');slider.disabled=!ready;slider.max=Math.max(0,rows.length-1);slider.value=Math.max(0,i);slider.setAttribute('aria-valuetext',label(state.period));$('.rt-stage').classList.toggle('routes-playing',state.playing);document.querySelectorAll('[data-chapter]').forEach(b=>b.disabled=!ready);}
function pause(){state.playing=false;clearTimeout(state.timer);playback();}
function tick(){state.timer=setTimeout(()=>{if(!state.playing)return;const i=state.model.rows.findIndex(r=>r.period===state.period);if(i>=state.model.rows.length-1)return pause();select(state.model.rows[i+1].period,false);tick();},1500);}
function select(period,stop=true){if(stop)pause();if(!state.model?.periods.includes(period))return;state.period=period;sync();renderPeriod();}
function table(heads,rows){return `<table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(cells=>`<tr>${cells.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
const cell=v=>`<span title="${esc(exact(v))} USD">${money(v)}</span>`;
function renderLeads(){
 const model=supplierHistory(state.data,state.period.slice(0,4)),wrapper=$('#rt-lead-chart');state.leadChart?.destroy();state.leadChart=null;wrapper.replaceChildren();
 const labels={KOR:tr('Jižní Korea','South Korea'),GEO:tr('Gruzie','Georgia'),DEU:tr('Německo','Germany'),TUR:tr('Turecko','Türkiye'),ITA:tr('Itálie','Italy')},palette=['#427c68','#bd923f','#c93237','#537b84','#89738b'];
 $('#rt-lead-legend').innerHTML=RESEARCH_SUPPLIERS.map((code,i)=>`<span><i style="background:${palette[i]}"></i>${esc(labels[code])}</span>`).join('');
 $('#rt-lead-status').textContent=tr(`Roční hlášení vývozců → Kyrgyzstán · ${productName(state.product)}. Tabulka: ${model.year} proti 2019${model.year!==model.requestedYear?` (poslední dostupný roční údaj do ${model.requestedYear})`:""}. Měsíční data před 2024 zde chybí; zlomy z článku v roce 2022 nejsou nezávisle ověřeny.`,`Annual exporter declarations → Kyrgyzstan · ${productName(state.product)}. Table: ${model.year} against 2019${model.year!==model.requestedYear?` (latest available annual year at or before ${model.requestedYear})`:""}. Monthly data before 2024 is unavailable here; the article’s 2022 breakpoints have not been independently reproduced.`);
 if(model.rows.length){const host=document.createElement('div');wrapper.append(host);const title=tr('Pět dodavatelů do Kyrgyzstánu','Five suppliers to Kyrgyzstan');state.leadChart=state.plot.render(host,{type:'line',inspectionPlacement:'below',rows:model.rows,fields:RESEARCH_SUPPLIERS.map((key,i)=>({key,label:labels[key],color:palette[i],format:v=>`${exact(v)} USD`})),title,unit:tr('Běžné USD / rok','Current USD / year'),height:350,locale});window.PSDChart.register({slug:'russia-research-suppliers',el:wrapper,title,accessor:state.leadChart.accessor,exports:['csv','png'],embeddable:false,source:{...source(),definition:tr('Samostatná roční hlášení vývozců: dostupné součty HS6 do Kyrgyzstánu.','Separate annual exporter declarations: available HS6 subtotals to Kyrgyzstan.')}});}
 $('#rt-lead-values').innerHTML=table([tr('Vývozce','Exporter'),'2019 USD',`${esc(model.year)} USD`,'Δ USD',tr('Změna','Change')],model.comparisons.map(r=>[`${esc(labels[r.reporter])} <small>${r.reporter}</small>`,cell(r.base),cell(r.value),cell(r.delta),r.ratio===null?'—':pct(r.ratio-1)]));
}
function renderSuppliers(){
 const q=$('#rt-search').value.toLowerCase(),all=state.model.suppliers(state.period),mirrors=state.frequency==='A'?(state.data.suppliers||[]).filter(o=>o.period===state.period&&HUBS.includes(o.partner_iso3)):[];
 const codes=[...new Set([...all.map(o=>o.partner_iso3||String(o.partner_area_code)),...mirrors.map(o=>o.reporter_iso3)])];
 const ranked=codes.map(code=>{const records=HUBS.map(h=>all.find(o=>o.reporter_iso3===h&&(o.partner_iso3||String(o.partner_area_code))===code));return {code,records,total:records.reduce((s,o)=>s+(o?.value_usd||0),0)};}).sort((a,b)=>b.total-a.total).filter(r=>`${country(r.code)} ${r.code}`.toLowerCase().includes(q));
 const heads=[tr('Původ','Origin'),...HUBS.flatMap(h=>[country(h)+' · '+tr('dovoz USD','imports USD'),...(state.frequency==='A'?[tr('Hlášení dodavatele USD','Supplier report USD'),tr('Rozdíl hlášení USD','Mirror gap USD')]:[]),tr('Podíl dovozu','Import share')])];
 $('#rt-suppliers').innerHTML=table(heads,ranked.map(r=>[`${esc(country(r.code))} <small>${esc(r.code)}</small>`,...r.records.flatMap((o,i)=>{const denom=state.model.get(state.period,HUBS[i],'M'),mirror=mirrors.find(m=>m.reporter_iso3===r.code&&m.partner_iso3===HUBS[i])?.value_usd??null,value=o?.value_usd??null;return [cell(value),...(state.frequency==='A'?[cell(mirror),cell(mirror!==null&&value!==null?mirror-value:null)]:[]),pct(denom>0&&value!==null?value/denom:null)];})]));
}
function renderPeriod(){const m=state.model,p=state.period;$('#rt-month').textContent=label(p);$('#rt-period-label').textContent=label(p);$('#rt-era').textContent=p<'2022'?tr('Před plnou invazí','Before the full-scale invasion'):p.slice(0,4)==='2022'?tr('Rok invaze · 24. února 2022','Invasion year · 24 February 2022'):tr('Po plné invazi','After the full-scale invasion');$('#rt-product-tag').textContent=productName(state.product);
 const imports=m.suppliers(p),lookup=new Map((state.data.countries||[]).map(c=>[c.iso3,c.iso2]));lookup.set('KAZ','kz');lookup.set('KGZ','kg');lookup.set('RUS','ru');
 const mapped=imports.filter(o=>lookup.get(o.partner_iso3)&&state.geometry.locations.some(l=>l.id===lookup.get(o.partner_iso3)));
 const visible=state.mapDetail==='all'?mapped:largestMapSuppliers(mapped);
 const edges=[...visible].sort((a,b)=>(a.value_usd||0)-(b.value_usd||0)).map(o=>({from:o.partner_iso3,to:o.reporter_iso3,value:o.value_usd,color:colors[o.reporter_iso3],label:`${country(o.partner_iso3)} → ${country(o.reporter_iso3)} · ${label(p)} · ${exact(o.value_usd)} USD · ${tr('dovozní hlášení uzlu','hub-reported imports')}`}));
 for(const hub of HUBS)edges.push({from:hub,to:'RUS',value:m.get(p,hub,'X','RUS'),color:colors.RUS,label:`${country(hub)} → ${country('RUS')} · ${label(p)} · ${exact(m.get(p,hub,'X','RUS'))} USD · ${tr('vývozní hlášení uzlu','hub-reported exports')}`});
 const originTotals=new Map();for(const o of imports)originTotals.set(o.partner_iso3,(originTotals.get(o.partner_iso3)||0)+(o.value_usd||0));const labelled=new Set(['KAZ','KGZ','RUS',...[...originTotals].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([code])=>code)]);
 const nodes=[...new Set(edges.flatMap(e=>[e.from,e.to]))].map(id=>({id,iso2:lookup.get(id),label:country(id),quiet:!labelled.has(id)}));
 const max=Math.max(1,...state.data.observations.filter(o=>o.product_code===state.product&&Number(o.partner_area_code)!==0).map(o=>o.value_usd||0));state.map?.destroy();state.map=state.plot.render($('#rt-map'),{type:'route-map',geometry:state.geometry,nodes,edges,maxValue:max,worldView:true,title:`${productName(state.product)} · ${label(p)}`,note:tr('Vyberte spoj. Samostatná hlášení, nikoli sledované zásilky.','Select a route. Separate declarations, not tracked shipments.')});
 const coverage=HUBS.map(h=>{const total=imports.filter(o=>o.reporter_iso3===h&&Number.isFinite(o.value_usd)).reduce((sum,o)=>sum+o.value_usd,0),shown=visible.filter(o=>o.reporter_iso3===h).reduce((sum,o)=>sum+o.value_usd,0);return `${country(h)}: ${total>0?pct(shown/total):'—'}`;}).join(' · ');
 $('#rt-map-detail').value=state.mapDetail;
 $('#rt-map-coverage').textContent=tr(`${state.mapDetail==='all'?'Všechny mapovatelné dodavatele':'Nejvýše 8 největších mapovatelných dodavatelů pro každý uzel'} · ${visible.length} z ${imports.length} vykázaných dovozních vazeb. Podíl z hodnoty vykázaného bilaterálního dovozu: ${coverage}. Všechny země zůstávají v tabulce. Škála tloušťky je pevná v celé časové řadě; červené spoje jsou samostatné vývozy do Ruska.`,`${state.mapDetail==='all'?'All mappable suppliers':'Up to 8 largest mappable suppliers per hub'} · ${visible.length} of ${imports.length} reported import links. Share of reported bilateral import value: ${coverage}. Every country remains in the table. Width scale is fixed across the timeline; red routes are separate exports to Russia.`);

 $('#rt-legs').innerHTML=HUBS.map(h=>{const a=m.compare(p,h,'M'),b=m.compare(p,h,'X','RUS');return `<article class="rt-leg" style="--leg-color:${colors[h]}"><small>${esc(country(h))}</small><div class="rt-leg-pair"><div><h3>${tr('Dovoz ze světa','Imports from the world')}</h3><strong>${money(a.value)}</strong><p>${tr('Proti 2019','Against 2019')}: ${a.ratio===null?'—':a.ratio.toFixed(2)+'×'}</p></div><div><h3>${tr('Vývoz do Ruska','Exports to Russia')}</h3><strong>${money(b.value)}</strong><p>${tr('Proti 2019','Against 2019')}: ${b.ratio===null?'—':b.ratio.toFixed(2)+'×'}</p></div></div></article>`;}).join('');
 $('#rt-status').textContent=state.frequency==='A'?tr('Roční pohled · všechny vykázané země původu · referenční rok 2019. Kazachstán 2020–2022: dostupný detail je pod národními součty; viz metodika.','Annual view · all reported origins · reference year 2019. Kazakhstan 2020–2022: available detail is below national totals; see methodology.'):tr('Měsíční detail je dostupný od roku 2024; předválečné měsíce chybí. Roční historie zůstává dostupná přepínačem. Mezery nejsou nuly.','Monthly detail is available from 2024; pre-war months are missing. Switch to Annual for the historical comparison. Gaps are not zeros.');
 const deps=m.dependencies(p),leading=deps.find(r=>r.jointGrowth!==null);$('#rt-findings').textContent=leading?tr(`${country(leading.hub)} · ${productName(leading.product)}: dovoz +${money(leading.inbound.delta)}, vývoz do Ruska +${money(leading.onward.delta)} proti roku 2019. Rusko odebírá ${pct(leading.russiaShare)} vykázaného vývozu této kapitoly.`,`${country(leading.hub)} · ${productName(leading.product)}: imports +${money(leading.inbound.delta)}, exports to Russia +${money(leading.onward.delta)} against 2019. Russia takes ${pct(leading.russiaShare)} of observed exports in this chapter.`):tr('Bez předválečného základu pořadí souběžného růstu nelze určit. Zde jsou dostupné hodnoty.','Without a pre-war baseline, simultaneous growth cannot be ranked. Available values are shown below.');
 $('#rt-dependencies').innerHTML=table([tr('Uzel / kapitola','Hub / chapter'),tr('Dovoz USD','Imports USD'),tr('Změna od 2019','Change since 2019'),tr('Do Ruska USD','To Russia USD'),tr('Změna od 2019','Change since 2019'),tr('Rusko / veškerý vývoz','Russia / all exports')],deps.map(r=>[`${esc(country(r.hub))}<br><button class="rt-chapter-link" data-product="${r.product}">${esc(productName(r.product))} · ${r.product}</button>`,cell(r.inbound.value),cell(r.inbound.delta),cell(r.onward.value),cell(r.onward.delta),pct(r.russiaShare)]));
 renderSuppliers();renderLeads();renderDirect();playback();
}
function renderDirect(){const year=state.period.slice(0,4),all=supplierComparisons(state.data,year),rows=all.filter(r=>r.eligible),sum=key=>rows.reduce((s,r)=>s+r[key].delta,0),direct=sum('direct'),hubs=sum('kaz')+sum('kgz');$('#rt-direct-summary').textContent=rows.length?tr(`${year} proti 2019 · společný panel ${rows.length} z ${all.length} dodavatelů. Změna vývozu přímo do Ruska: ${money(direct)}; do obou uzlů: ${money(hubs)}. Tyto částky se nepovažují za vzájemnou náhradu.`,`${year} against 2019 · matched panel of ${rows.length} of ${all.length} suppliers. Change in direct exports to Russia: ${money(direct)}; to both hubs: ${money(hubs)}. These amounts are not assumed to offset each other.`):tr(`Pro rok ${year} chybí úplný společný roční panel.`, `A complete matched annual panel is unavailable for ${year}.`);
 const excluded=all.filter(r=>!r.eligible),major=excluded.filter(r=>['CHN','USA','DEU','TUR','IND','KOR','GBR','JPN'].includes(r.reporter));
 $('#rt-direct-coverage').textContent=tr('Panel není globální součet a jeho složení se mezi roky mění.','This panel is not a global total, and its composition changes between years.')+(major.length?' '+tr('Chybí mimo jiné: ','Excluded major suppliers: ')+major.map(r=>country(r.reporter)).join(', ')+'.':'');
 $('#rt-exclusions').textContent=excluded.map(r=>country(r.reporter)).join(' · ')||'—';
 $('#rt-direct').innerHTML=table([tr('Vývozce','Exporter'),tr('Do Ruska: změna','To Russia: change'),tr('Do Kazachstánu: změna','To Kazakhstan: change'),tr('Do Kyrgyzstánu: změna','To Kyrgyzstan: change'),tr('Vzor','Pattern')],rows.map(r=>[esc(country(r.reporter)),cell(r.direct.delta),cell(r.kaz.delta),cell(r.kgz.delta),r.direct.delta<0&&r.hubDelta>0?tr('Přímo ↓ · uzly ↑','Direct ↓ · hubs ↑'):'—']));
}
function renderHistory(){state.charts.forEach(c=>c?.destroy());state.charts=[];for(const [id,keys,title] of [['rt-trend-wrapper',['KAZ','KGZ'],tr('Dovoz ze světa','World imports')],['rt-onward-wrapper',['KAZ_RUS','KGZ_RUS'],tr('Vývoz do Ruska','Exports to Russia')]]){const wrapper=$('#'+id);wrapper.replaceChildren();const host=document.createElement('div');wrapper.append(host);const chart=state.plot.render(host,{type:'line',inspectionPlacement:'below',rows:state.model.rows,fields:keys.map(key=>({key,label:country(key.slice(0,3)),color:colors[key.slice(0,3)],format:v=>`${exact(v)} USD`})),title,unit:`USD / ${state.frequency==='A'?tr('rok','year'):tr('měsíc','month')}`,height:310,locale,onSelect:r=>select(r.period)});state.charts.push(chart);window.PSDChart.register({slug:id,el:wrapper,title,accessor:chart.accessor,exports:['csv','png'],embeddable:false,source:source()});}
 $('#rt-source').textContent=`UN Comtrade · ${productName(state.product)} · ${state.frequency} · ${state.data.source.table} · ${tr('Staženo','Retrieved')}: ${state.data.source.retrieved_at||'—'}`;
 const world=state.data.observations.filter(o=>o.product_code===state.product&&Number(o.partner_area_code)===0&&o.flow_code==='M');$('#rt-provenance').innerHTML=`<p>${esc(state.data.source.method)} ${esc(state.data.source.release_note)}</p><div class="rt-table-scroll">${table([tr('Období / uzel','Period / hub'),'USD',tr('Počet HS6','HS6 count'),'HS',tr('Vydání načtení','Ingestion release')],world.map(o=>[`${esc(o.period)} · ${esc(o.reporter_iso3)}`,esc(o.reported_value_usd),esc(o.product_count),esc(o.classifications),`<code>${esc(o.release_ids)}</code>`]))}</div>`;
}
async function loadCategories(){
 $('#rt-growth-retry').hidden=true;
 try{
  if(state.data?.frequency==='A')state.growthData=state.data;
  if(!state.growthData){
   $('#rt-growth-status').textContent=tr('Načítáme roční kategorie…','Loading annual categories…');
   state.growthRequest ||= readRussiaAggregate('A','TOTAL').finally(()=>{state.growthRequest=null;});
   state.growthData=await state.growthRequest;
  }
  const allYears=[...new Set(state.growthData.observations.filter(o=>o.product_code==='TOTAL').map(o=>o.period))].sort();
  if(!allYears.includes(state.growthBase))state.growthBase=allYears[0]||'2019';
  const bases=allYears.filter(y=>y<'2022');
  $('#rt-growth-base').innerHTML=bases.map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join('');$('#rt-growth-base').value=state.growthBase;
  const years=allYears.filter(y=>y>state.growthBase);
  if(!years.includes(state.growthYear))state.growthYear=years.at(-1)||'2019';
  $('#rt-growth-year').innerHTML=(years.length?years:['2019']).map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join('');$('#rt-growth-year').value=state.growthYear;
  renderCategories();
 }catch(error){console.error('Russia trade category chart failed',error);$('#rt-growth-status').textContent=tr('Roční kategorie se nepodařilo načíst.','Annual category data could not be loaded.');$('#rt-growth-retry').hidden=false;}
}
function renderCategories(){
 if(!state.growthData)return;
 const models=HUBS.map(hub=>categoryGrowth(state.growthData,{hub,flow:state.growthFlow,baseYear:state.growthBase,endYear:state.growthYear}));
 const palette=['#809027','#c93237','#537b84','#bd923f','#89738b','#427c68','#d37d56','#53615e','#ab6380','#7b673f'];
 const codes=[...new Set(models.flatMap(m=>m.categories.map(c=>c.code)))].sort(),paint=new Map(codes.map((code,i)=>[code,palette[i%palette.length]]));
 state.growthCharts.forEach(c=>c.destroy());state.growthCharts=[];
 $('#rt-growth-status').textContent=tr(`Pořadí podle absolutního růstu v USD: ${state.growthBase} → ${state.growthYear}. Každý uzel má vlastní svislou škálu; hodnoty lze porovnat v tabulce.`, `Ranked by absolute USD growth: ${state.growthBase} → ${state.growthYear}. Each hub has its own vertical scale; compare exact values in the tables.`);
 for(const model of models){
  const wrapper=$('#rt-growth-'+model.hub);wrapper.replaceChildren();const host=document.createElement('div');wrapper.append(host);
  const fields=[{key:'other',label:tr('Ostatní kategorie','Other categories'),color:'#d2ccc1'},...model.categories.map(c=>({key:c.code,label:`${productName(c.code)} · HS ${c.code}`,color:paint.get(c.code)}))].map(f=>({...f,format:v=>`${exact(v)} USD`}));
  const title=`${country(model.hub)} · ${state.growthFlow==='M'?tr('dovoz ze světa','World imports'):tr('vývoz do Ruska','exports to Russia')}`;
  const chart=state.plot.render(host,{type:'stacked',inspectionPlacement:'below',stackMode:'absolute',rows:model.rows,fields,title,unit:tr('Běžné USD / rok','Current USD / year'),height:350,locale});state.growthCharts.push(chart);
  window.PSDChart.register({slug:({KAZ:'russia-category-growth-kaz',KGZ:'russia-category-growth-kgz'})[model.hub],el:wrapper,title,accessor:chart.accessor,exports:['csv','png'],embeddable:false,source:{...source(state.growthData),definition:tr('Roční HS2 složení dostupných HS6 součtů; pět největších přírůstků od vybraného základu a zbytek.','Annual HS2 composition of observed HS6 subtotals; five largest increases from the selected baseline and the remainder.')}});
  $('#rt-growth-key-'+model.hub).innerHTML=model.categories.length?`<table class="rt-growth-key"><caption>${tr(`Zvýrazněné přírůstky proti ${state.growthBase}`,`Highlighted increases against ${state.growthBase}`)}</caption><thead><tr><th>${tr('Kategorie','Category')}</th><th>Δ USD</th><th>${tr('Změna','Change')}</th></tr></thead><tbody>${model.categories.map(c=>`<tr><td><i style="background:${paint.get(c.code)}"></i>${esc(productName(c.code))} <small>HS ${c.code}</small></td><td>${cell(c.delta)}</td><td>${c.ratio===null?'—':pct(c.ratio-1)}</td></tr>`).join('')}</tbody></table>`:`<p class="rt-note">${tr(`Není doložen kladný růst proti roku ${state.growthBase}.`,`No positive growth against ${state.growthBase} is established.`)}</p>`;
 }
}
function latestShared(){return state.model?.rows.filter(r=>[r.KAZ,r.KGZ,r.KAZ_RUS,r.KGZ_RUS].every(Number.isFinite)).at(-1)?.period||state.model?.periods.at(-1);}
async function load(){pause();const request=++state.request;state.loading=true;state.data=null;state.model=null;state.map?.destroy();state.charts.forEach(c=>c?.destroy());state.leadChart?.destroy();state.leadChart=null;playback();$('#rt-status').textContent=tr('Načítáme všechny dodavatele a obě země…','Loading all suppliers and both hubs…');$('#rt-retry').hidden=true;$('#rt-map').setAttribute('aria-busy','true');for(const id of ['rt-lead-chart','rt-lead-legend','rt-lead-values','rt-lead-status','rt-map','rt-legs','rt-trend-wrapper','rt-onward-wrapper','rt-suppliers','rt-dependencies','rt-direct','rt-direct-summary','rt-direct-coverage','rt-exclusions','rt-findings','rt-provenance','rt-source','rt-map-coverage'])$('#'+id).replaceChildren();
 try{const data=await readRussiaAggregate(state.frequency,state.product);if(request!==state.request)return;state.data=data;state.model=aggregateModel(data);if(!state.model.rows.length)throw new Error('empty');if(!state.model.periods.includes(state.period))state.period=latestShared();state.loading=false;sync();renderHistory();renderPeriod();renderDirectRanking();loadCategories();}
 catch(e){if(request!==state.request)return;console.error('Russia trade view failed',e);state.loading=false;state.model=null;playback();$('#rt-status').textContent=tr('Souhrnná data se nepodařilo načíst. Zkuste to znovu.','Aggregate data could not be loaded. Please retry.');$('#rt-retry').hidden=false;playback();}finally{if(request===state.request)$('#rt-map').setAttribute('aria-busy','false');}}
function controls(){document.querySelectorAll('[data-frequency]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.frequency===state.frequency)));$('#rt-product').value=state.product;}
document.querySelectorAll('[data-cs][data-en]').forEach(n=>n.innerHTML=n.dataset[lang]);document.title=tr('Obchod kolem Ruska','The trade around Russia')+' — Public Spending Data';$('#rt-back').href=`/deep-dives/?lang=${lang}`;
$('#rt-product').innerHTML=['TOTAL',...Array.from({length:97},(_,i)=>String(i+1).padStart(2,'0')), '99',...Object.keys(detailed)].map(code=>`<option value="${code}">${esc(productName(code))}${code==='TOTAL'?'':` · HS ${code}`}</option>`).join('');controls();
for(const b of document.querySelectorAll('[data-frequency]'))b.addEventListener('click',()=>{if(state.frequency===b.dataset.frequency)return;state.frequency=b.dataset.frequency;state.period=null;controls();load();});
$('#rt-map-detail').addEventListener('change',e=>{state.mapDetail=e.target.value;sync();if(state.model)renderPeriod();});
$('#rt-product').addEventListener('change',e=>{state.product=e.target.value;load();});$('#rt-dependencies').addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(b){state.product=b.dataset.product;controls();load();$('#routes').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}});
$('#rt-growth-flow').addEventListener('change',e=>{state.growthFlow=e.target.value;renderCategories();});
$('#rt-growth-base').addEventListener('change',e=>{state.growthBase=e.target.value;loadCategories();});
$('#rt-growth-year').addEventListener('change',e=>{state.growthYear=e.target.value;renderCategories();});
$('#rt-growth-retry').addEventListener('click',loadCategories);
document.querySelectorAll('[data-supplier]').forEach(b=>b.addEventListener('click',()=>{if(!state.model)return;$('#rt-search').value=b.dataset.supplier;renderSuppliers();$('#rt-search').focus();}));
$('#rt-search').addEventListener('input',()=>{if(state.model)renderSuppliers();});$('#rt-retry').addEventListener('click',()=>state.plot&&state.geometry?load():start());
$('#rt-play').addEventListener('click',()=>{if(state.playing)return pause();if(state.period===state.model.periods.at(-1))select(state.model.periods[0]);state.playing=true;playback();tick();});$('#rt-timeline').addEventListener('input',e=>select(state.model.periods[Number(e.target.value)]));
for(const [id,step] of [['rt-prev',-1],['rt-next',1]])$('#'+id).addEventListener('click',()=>{const p=state.model.periods[state.model.periods.indexOf(state.period)+step];if(p)select(p);});
document.querySelectorAll('[data-chapter]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.chapter==='before'?'2019':b.dataset.chapter==='break'?'2022':latestShared();if(state.frequency==='M'&&b.dataset.chapter!=='after'){state.frequency='A';state.period=p;controls();load();}else select(p);}));
$('#rt-download').addEventListener('click',()=>{if(!state.data)return;const columns=['reporting_basis','frequency','period','reporter_iso3','flow_code','partner_iso3','partner_area_code','product_code','reported_value_usd','product_count','classifications','source_last_released','retrieved_at','release_ids','source_hashes'];const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const exportRows=[...state.data.observations.map(o=>({...o,frequency:state.frequency,reporting_basis:'HUB_REPORTED'})),...state.data.suppliers.map(o=>({...o,frequency:'A',flow_code:'X',product_code:state.product,reporting_basis:'SUPPLIER_REPORTED'}))];const csv=[columns,...exportRows.map(o=>columns.map(k=>o[k]))].map(r=>r.map(quote).join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`russia-trade-${state.frequency}-${state.product}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});addEventListener('pagehide',pause);
async function start(){try{state.plot=await window.PSDPlotReady;const r=await fetch('/data/world-map.v1.json');if(!r.ok)throw new Error('map');state.geometry=await r.json();await load();loadBilateral();loadStory();}catch(e){$('#rt-status').textContent=tr('Mapu se nepodařilo načíst. Zkuste to znovu.','The map could not be loaded. Please retry.');$('#rt-retry').hidden=false;}}
const requestedCountry=params.get('bilateral');
const bilateral={country:/^[A-Z]{3}$/.test(requestedCountry||'')&&requestedCountry!=='RUS'?requestedCountry:'CHN',data:null,charts:[],request:0,base:params.get('bilateral_base')||'2019',year:params.get('bilateral_year'),flow:params.get('bilateral_flow')==='M'?'M':'X'};
for(const option of $('#rt-bilateral-country').options)option.textContent=`${country(option.value)} · ${option.value}`;
if(![...$('#rt-bilateral-country').options].some(o=>o.value===bilateral.country)){const option=document.createElement('option');option.value=bilateral.country;option.textContent=country(bilateral.country);$('#rt-bilateral-country').append(option);}
function bilateralURL(){const u=new URL(location.href);u.searchParams.set('bilateral',bilateral.country);u.searchParams.set('bilateral_base',bilateral.base);if(bilateral.year)u.searchParams.set('bilateral_year',bilateral.year);else u.searchParams.delete('bilateral_year');u.searchParams.set('bilateral_flow',bilateral.flow);history.replaceState(null,'',u);}
function renderDirectRanking(){
 if(!state.data)return;
 const years=[...new Set(state.data.suppliers.filter(o=>o.partner_iso3==='RUS').map(o=>o.period))].sort(),selected=(years.includes($('#rt-direct-year').value)?$('#rt-direct-year').value:null)||years.filter(y=>state.data.suppliers.some(o=>o.reporter_iso3==='CHN'&&o.partner_iso3==='RUS'&&o.period===y)).at(-1)||years.at(-1);
 if(!years.length){$('#rt-direct-rank-status').textContent=tr('Chybí roční hlášení dodavatelů pro tuto volbu.','No available annual supplier declarations for this selection.');$('#rt-direct-rank').replaceChildren();return;}
 $('#rt-direct-year').innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('');$('#rt-direct-year').value=selected;
 const rows=directSupplierGrowth(state.data,'2019',selected),eligible=rows.filter(r=>r.delta!==null),missing=rows.filter(r=>r.delta===null);
 $('#rt-direct-rank-status').textContent=tr(`Roční hlášení vývozců · ${productName(state.product)} · 2019 → ${selected}. Seřazeno podle změny v USD; nejde o hodnocení porušování sankcí. Chybějící základ nebo konec: ${missing.map(r=>r.reporter).join(', ')||'žádný'}.`,`Annual exporter declarations · ${productName(state.product)} · 2019 → ${selected}. Ranked by USD change; this is not a sanctions-violation score. Missing baseline or endpoint: ${missing.map(r=>r.reporter).join(', ')||'none'}.`);
 $('#rt-direct-rank').innerHTML=table([tr('Vývozce','Exporter'),'2019 USD',`${selected} USD`,'Δ USD',tr('Změna','Change')],eligible.map(r=>[`<button data-bilateral="${esc(r.reporter)}">${esc(country(r.reporter))} · ${esc(r.reporter)}</button>`,cell(r.base),cell(r.value),cell(r.delta),r.ratio===null?'—':pct(r.ratio-1)]));
 const countrySelect=$('#rt-bilateral-country'),known=new Set([...countrySelect.options].map(o=>o.value));
 for(const r of rows)if(!known.has(r.reporter)&&r.reporter!=='RUS'){const option=document.createElement('option');option.value=r.reporter;option.textContent=`${country(r.reporter)} · ${r.reporter}`;countrySelect.append(option);known.add(r.reporter);}
}
async function loadBilateral(){
 const request=++bilateral.request;bilateral.data=null;bilateral.charts.forEach(c=>c.destroy());bilateral.charts=[];
 for(const id of ['rt-bilateral-history','rt-bilateral-stack','rt-bilateral-values','rt-bilateral-provenance','rt-bilateral-history-title','rt-bilateral-stack-title'])$('#'+id).replaceChildren();
 $('#rt-bilateral-title').textContent=tr(`${country(bilateral.country)} a Rusko. Co se změnilo?`,`${country(bilateral.country)} and Russia. What changed?`);
 $('#rt-bilateral-base').disabled=true;$('#rt-bilateral-year').disabled=true;
 $('#rt-bilateral-retry').hidden=true;$('#rt-bilateral-status').textContent=tr('Načítáme přímý obchod s Ruskem…','Loading direct trade with Russia…');$('#rt-bilateral-country').value=bilateral.country;bilateralURL();
 try{
  const data=await readRussiaAggregate('A','TOTAL',fetch,`/api/v1/trade/russia-bilateral?country=${encodeURIComponent(bilateral.country)}`);if(request!==bilateral.request)return;bilateral.data=data;
  const years=bilateralHistory(data).map(r=>r.period),bases=years.filter(y=>y<'2022');
  $('#rt-bilateral-base').disabled=!bases.length;$('#rt-bilateral-year').disabled=!years.length;
  if(!bases.includes(bilateral.base))bilateral.base=bases.includes('2019')?'2019':bases.at(-1)||'2019';
  if(!years.includes(bilateral.year)||bilateral.year<bilateral.base)bilateral.year=years.at(-1);
  $('#rt-bilateral-base').innerHTML=bases.map(y=>`<option value="${y}">${y}</option>`).join('');$('#rt-bilateral-base').value=bilateral.base;
  $('#rt-bilateral-year').innerHTML=years.filter(y=>y>=bilateral.base).map(y=>`<option value="${y}">${y}</option>`).join('');$('#rt-bilateral-year').value=bilateral.year||'';
  renderBilateral();
 }catch(error){if(request!==bilateral.request)return;console.error('Direct Russia trade failed',error);$('#rt-bilateral-status').textContent=tr('Přímé obchodní údaje se nepodařilo načíst.','Direct trade observations could not be loaded.');$('#rt-bilateral-retry').hidden=false;}
}
function renderBilateral(){
 if(!bilateral.data)return;bilateralURL();$('#rt-bilateral-flow').value=bilateral.flow;
 const data=bilateral.data,rows=bilateralHistory(data),who=country(bilateral.country),unit=tr('Běžné USD / rok','Current USD / year');bilateral.charts.forEach(c=>c.destroy());bilateral.charts=[];
 for(const id of ['rt-bilateral-history','rt-bilateral-stack','rt-bilateral-values','rt-bilateral-provenance','rt-bilateral-history-title','rt-bilateral-stack-title'])$('#'+id).replaceChildren();
 if(!rows.length){$('#rt-bilateral-status').textContent=tr(`${who}: žádná dostupná roční hlášení v tomto pohledu. Chybějící data nejsou nula.`,`${who}: no available annual declarations in this view. Missing data is not zero.`);return;}
 $('#rt-bilateral-status').textContent=tr(`Oba směry používají hlášení země ${who}. Dostupná roční historie: ${rows[0].period}–${rows.at(-1).period}; základ ${bilateral.base} → ${bilateral.year}. Rok 2022 je přechodový.`,`Both directions use declarations from ${who}. Available annual history: ${rows[0].period}–${rows.at(-1).period}; baseline ${bilateral.base} → ${bilateral.year}. 2022 is a transition year.`);
 $('#rt-bilateral-provenance').innerHTML=`<p>${esc(data.source.table)} · ${esc(data.source.method)} ${esc(data.source.release_note)}</p><div class="rt-table-scroll">${table([tr('Rok / směr','Year / direction'),'USD',tr('Počet HS6','HS6 count'),'HS',tr('Vydání načtení','Ingestion release')],data.observations.filter(o=>o.product_code==='TOTAL').map(o=>[`${esc(o.period)} · ${esc(o.flow_code)}`,esc(o.reported_value_usd),esc(o.product_count),esc(o.classifications),`<code>${esc(o.release_ids)}</code>`]))}</div>`;
 const lineWrapper=$('#rt-bilateral-history'),lineHost=document.createElement('div');lineWrapper.append(lineHost);
 const title=`${who} ↔ ${country('RUS')}`;$('#rt-bilateral-history-title').textContent=title;
 const line=state.plot.render(lineHost,{type:'line',inspectionPlacement:'below',rows,fields:[{key:'X',label:`${who} → ${country('RUS')}`,color:'#a8b63f'},{key:'M',label:`${country('RUS')} → ${who}`,color:'#537b84'}].map(f=>({...f,format:v=>`${exact(v)} USD`})),title,unit,height:350,locale});bilateral.charts.push(line);
 window.PSDChart.register({slug:'russia-bilateral-history',el:lineWrapper,title,accessor:line.accessor,exports:['csv','png'],embeddable:false,source:source(data)});
 const model=categoryGrowth(data,{hub:bilateral.country,flow:bilateral.flow,partner:'RUS',baseYear:bilateral.base,endYear:bilateral.year,continuousYears:true}),palette=['#a8b63f','#c93237','#537b84','#bd923f','#89738b'];
 const fields=[{key:'other',label:tr('Ostatní','Other'),color:'#d2ccc1'},...model.categories.map((c,i)=>({key:c.code,label:`${productName(c.code)} · HS ${c.code}`,color:palette[i]}))].map(f=>({...f,format:v=>`${exact(v)} USD`}));
 const stackWrapper=$('#rt-bilateral-stack'),stackHost=document.createElement('div');stackWrapper.append(stackHost);const stackTitle=`${bilateral.flow==='X'?`${who} → ${country('RUS')}`:`${country('RUS')} → ${who}`} · ${tr('největší přírůstky kategorií','largest category increases')}`;
 $('#rt-bilateral-stack-title').textContent=stackTitle;
 const stack=state.plot.render(stackHost,{type:'stacked',stackMode:'absolute',inspectionPlacement:'below',rows:model.rows,fields,title:stackTitle,unit,height:350,locale});bilateral.charts.push(stack);
 window.PSDChart.register({slug:'russia-bilateral-categories',el:stackWrapper,title:stackTitle,accessor:stack.accessor,exports:['csv','png'],embeddable:false,source:source(data)});
 const scoped=data.observations.filter(o=>o.flow_code===bilateral.flow&&/^\d{2}$/.test(o.product_code)),codes=[...new Set(scoped.map(o=>o.product_code))];
 const comparisons=codes.map(code=>{const get=year=>scoped.find(o=>o.period===year&&o.product_code===code)?.value_usd??null,before=get(bilateral.base),after=get(bilateral.year);return {code,before,after,delta:before!==null&&after!==null?after-before:null};}).sort((a,b)=>(b.delta??-Infinity)-(a.delta??-Infinity));
 $('#rt-bilateral-values').innerHTML=table([tr('Všechny kategorie','All categories'),`${bilateral.base} USD`,`${bilateral.year} USD`,'Δ USD'],comparisons.map(c=>[`${esc(productName(c.code))} · HS ${c.code}`,cell(c.before),cell(c.after),cell(c.delta)]));
}
$('#rt-direct-year').addEventListener('change',renderDirectRanking);
$('#rt-direct-rank').addEventListener('click',e=>{const button=e.target.closest('[data-bilateral]');if(button){bilateral.country=button.dataset.bilateral;bilateral.year=$('#rt-direct-year').value;loadBilateral();$('#bilateral').scrollIntoView({behavior:'smooth'});}});
$('#rt-bilateral-country').addEventListener('change',e=>{bilateral.country=e.target.value;bilateral.year=null;loadBilateral();});
$('#rt-bilateral-base').addEventListener('change',e=>{bilateral.base=e.target.value;const years=bilateralHistory(bilateral.data).map(r=>r.period).filter(y=>y>=bilateral.base);if(!years.includes(bilateral.year)||bilateral.year<bilateral.base)bilateral.year=years.at(-1);$('#rt-bilateral-year').innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('');$('#rt-bilateral-year').value=bilateral.year;renderBilateral();});$('#rt-bilateral-year').addEventListener('change',e=>{bilateral.year=e.target.value;renderBilateral();});$('#rt-bilateral-flow').addEventListener('change',e=>{bilateral.flow=e.target.value;renderBilateral();});$('#rt-bilateral-retry').addEventListener('click',loadBilateral);

// Authored annual delta layer. Its all-goods accounting is independent of explorer filters.
const story={country:/^[A-Z]{3}$/.test(params.get('story_country')||'')&&params.get('story_country')!=='RUS'?params.get('story_country'):'CHN',year:/^20\d{2}$/.test(params.get('story_year')||'')&&params.get('story_year')>'2019'?params.get('story_year'):null,data:null,bilateral:null,cache:new Map(),charts:[],request:0};
const storyPalette=['#a8b63f','#537b84','#bd923f','#89738b','#427c68','#d2ccc1'];
const decimal=v=>{if(v===null||v===undefined)return '—';const [whole,fraction]=String(v).split('.');return (whole==='-0'?'-':'')+new Intl.NumberFormat(locale).format(BigInt(whole))+(fraction?(lang==='cs'?',':'.')+fraction:'');},exactUSD=v=>`${decimal(v)} USD`;
const deltaColumns=[{key:'label',label:tr('Kategorie / země','Category / country')},{key:'baseExact',label:'2019 USD'},{key:'valueExact',label:tr('Srovnávací rok USD','Comparison year USD')},{key:'deltaExact',label:'Δ USD'},{key:'sharePositiveExact',label:tr('Podíl kladných změn %','Share of positive changes %')},{key:'memberCodes',label:tr('Zahrnuté kódy','Included codes')}];
function clearStory(){$('#rt-story-download').disabled=true;story.charts.forEach(c=>c.destroy());story.charts=[];for(const id of ['rt-story-suppliers','rt-story-supplier-declines','rt-story-supplier-copy','rt-story-supplier-balance','rt-story-supplier-table','rt-story-hubs','rt-story-provenance',...['X','M'].flatMap(f=>['copy','takeaway','balance','donut','legend','declines','table'].map(part=>`rt-story-${f}-${part}`))])$('#'+id).replaceChildren();}
function storyURL(){const u=new URL(location.href);u.searchParams.set('story_country',story.country);if(story.year)u.searchParams.set('story_year',story.year);history.replaceState(null,'',u);}
function storyTable(basket,labels){return table([tr('Kategorie / země','Category / country'),'2019 USD',`${story.year} USD`,'Δ USD',tr('Podíl kladných změn','Share of positive changes')],basket.rows.map(r=>[esc(labels(r.code)),esc(decimal(r.baseExact)),esc(decimal(r.valueExact)),esc(decimal(r.deltaExact)),r.sharePositiveExact===null?'—':esc(r.sharePositiveExact)+'%']));}
function balance(basket,total=basket.netExact,fullBasket=false){return [[tr('Kladné změny','Positive changes'),basket.positiveExact],[tr('Poklesy','Declines'),basket.negativeExact],[fullBasket?tr('Čistá změna vykázaného koše','Net change in observed basket'):tr('Čistá změna společného panelu','Matched-panel net change'),total]].map(([label,value])=>`<div><small>${esc(label)}</small><strong>${esc(exactUSD(value))}</strong></div>`).join('');}
function storyPlot(id,slug,rows,{type='bar',title,color='#a8b63f',donut=false,denominator,axis}={}){
 const wrapper=$('#'+id);if(!rows.length){wrapper.innerHTML=`<p class="rt-note">${tr('Žádné doložené změny tohoto znaménka.','No observed changes of this sign.')}</p>`;return;}
 const host=document.createElement('div');wrapper.append(host);
 const supplier=id==='rt-story-suppliers'||id==='rt-story-supplier-declines',flow=id.includes('-M-')?'M':'X',sourceData=supplier?story.data:story.bilateral;
 const plotRows=rows.map(r=>({...r,reporter:supplier?r.code:story.country,flow,baselineYear:'2019',comparisonYear:story.year,denominatorExact:donut?denominator:null,baseLoadIds:r.baseLoadIds??r.baseObservation?.release_ids??null,valueLoadIds:r.valueLoadIds??r.valueObservation?.release_ids??null}));
 const columns=[...deltaColumns.map(c=>({...c,...(c.key==='valueExact'?{label:`${story.year} USD`}:{} )})),{key:'reporter',label:'Reporter ISO3'},{key:'flow',label:'Flow'},{key:'baselineYear',label:'Baseline year'},{key:'comparisonYear',label:'Comparison year'},{key:'denominatorExact',label:'Positive-change denominator USD'},{key:'baseLoadIds',label:'Baseline ingestion IDs'},{key:'valueLoadIds',label:'Endpoint ingestion IDs'}];
 const spec={type,rows:plotRows,fields:[{key:'delta',label:tr('Vypočtená změna','Calculated change'),format:(v,row)=>exactUSD(row.deltaExact)}],tableColumns:columns,yDomain:axis,title,unit:tr('Δ běžné USD','Δ current USD'),locale,inspectionPlacement:'below',height:donut?280:Math.max(180,rows.length*42+95),rowColor:row=>donut?row.color:color,...(donut?{shareFormat:(v,row)=>`${row.sharePositiveExact}%`,centerLabel:'≈ '+money(Number(denominator)),centerSubLabel:title.split(' · ')[0]}:{valueLabels:true,valueLabelFormat:v=>money(v)})};
 const chart=state.plot.render(host,spec);story.charts.push(chart);window.PSDChart.register({slug,el:wrapper,title,accessor:chart.accessor,exports:['csv','png'],embeddable:false,exportCaption:`${title} · 2019 → ${story.year} · current USD\n${donut?`Positive-change denominator: ${denominator} USD\n`:''}${rows.map(r=>`${r.label}: ${r.deltaExact} USD${donut?` (${r.sharePositiveExact}%)`:''}`).join('\n')}\nUN Comtrade · ${sourceData.source.table} · available original HS6 subtotals`,source:{...source(sourceData),definition:tr('Změna koncového roku proti 2019; přesná desetinná aritmetika.','Endpoint minus 2019; exact decimal arithmetic.'),caveat:tr('Podíl používá součet pouze kladných změn; chybějící konce jsou vynechány a pojmenovány.','Share uses the sum of positive changes only; missing endpoints are excluded and named.')}});
}
async function loadStory(){
 const request=++story.request;clearStory();$('#rt-story-retry').hidden=true;$('#rt-story-status').textContent=tr('Načítáme společný roční příběh…','Loading the shared annual story…');$('#rt-story-year').disabled=true;
 try{
  const aggregate=story.data?Promise.resolve(story.data):state.data?.frequency==='A'&&state.data.product==='TOTAL'?Promise.resolve(state.data):readRussiaAggregate('A','TOTAL');
  const bilateralData=story.cache.has(story.country)?Promise.resolve(story.cache.get(story.country)):bilateral.country===story.country&&bilateral.data?Promise.resolve(bilateral.data):readRussiaAggregate('A','TOTAL',fetch,`/api/v1/trade/russia-bilateral?country=${encodeURIComponent(story.country)}`);
  const [data,direct]=await Promise.all([aggregate,bilateralData]);if(request!==story.request)return;story.data=data;story.bilateral=direct;story.cache.set(story.country,direct);story.year=chooseStoryYear(data,direct,story.year)||'2024';
  const years=[...new Set([...data.suppliers.map(o=>o.period),story.year])].filter(y=>/^\d{4}$/.test(y)&&y>'2019').sort();$('#rt-story-year').innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('');$('#rt-story-year').value=story.year;$('#rt-story-year').disabled=false;
  const select=$('#rt-story-country'),known=new Set([...select.options].map(o=>o.value));for(const code of [story.country,...new Set(data.suppliers.map(o=>o.reporter_iso3))])if(code!=='RUS'&&!known.has(code)){const option=document.createElement('option');option.value=code;select.append(option);known.add(code);}for(const option of select.options)option.textContent=`${country(option.value)} · ${option.value}`;select.value=story.country;
  renderStory();
 }catch(error){if(request!==story.request)return;clearStory();$('#rt-story-status').textContent=tr('Roční příběh se nepodařilo načíst.','The annual story could not be loaded.');$('#rt-story-retry').hidden=false;console.error('Russia delta story failed',error);}
}
function renderStory(){
 if(!story.data||!story.bilateral)return;clearStory();$('#rt-story-download').disabled=false;storyURL();const year=story.year,who=country(story.country),suppliers=supplierDelta(story.data,'2019',year),growth=suppliers.positives.slice(0,10).map(r=>({...r,label:country(r.code)}));
 $('#rt-story-status').textContent=tr(`Všechny panely: 2019 → ${year} · veškeré dostupné zboží · ročně · běžné USD. Nezávislé na měsíčních filtrech průzkumníku.`,`Every panel: 2019 → ${year} · all available goods · annual · current USD. Independent of the explorer’s monthly filters.`);
 const missing=suppliers.missing.map(r=>r.code).join(', ')||tr('žádné','none');$('#rt-story-supplier-copy').textContent=tr(`Deset největších přírůstků a poklesů se stejnou dolarovou škálou. Společný panel ${suppliers.knownCount} z ${suppliers.totalCount} pozorovaných dodavatelů; chybějící základ nebo konec: ${missing}. Nejde o úplný světový součet.`,`The ten largest observed dollar increases and declines, with equal dollar scales. Matched panel: ${suppliers.knownCount} of ${suppliers.totalCount} observed suppliers; missing baseline or endpoint: ${missing}. This is not a complete global total.`);
 const span=state.plot.domain(suppliers.rows.map(r=>Math.abs(r.delta??0))).max,ticks=state.plot.domain([span]).ticks;storyPlot('rt-story-suppliers','russia-story-supplier-increases',growth,{title:tr('Největší přírůstky dodávek do Ruska','Largest increases in supplies to Russia'),axis:{min:0,max:span,ticks}});storyPlot('rt-story-supplier-declines','russia-story-supplier-declines',suppliers.negatives.slice().sort((a,b)=>a.delta-b.delta).slice(0,10).map(r=>({...r,label:country(r.code)})),{title:tr('Největší poklesy dodávek do Ruska','Largest declines in supplies to Russia'),color:'#c93237',axis:{min:-span,max:0,ticks:ticks.map(v=>v===0?0:-v).reverse()}});$('#rt-story-supplier-balance').innerHTML=balance(suppliers);$('#rt-story-supplier-table').innerHTML=storyTable(suppliers,country);
 $('#rt-story-country-title').textContent=tr(`${who}: rozložte změnu na zboží.`,`${who}: take the change apart.`);
 for(const flow of ['X','M']){
  const basket=bilateralDelta(story.bilateral,{country:story.country,flow,baseYear:'2019',endYear:year}),direction=flow==='X'?`${who} → ${country('RUS')}`:`${country('RUS')} → ${who}`,label=code=>code==='OTHER'?tr('Ostatní rostoucí kategorie','Other growing categories'):`${productName(code)} · HS ${code}`,slices=deltaSlices(basket).map((r,i)=>({...r,label:label(r.code),color:storyPalette[i],memberCodes:r.members.join('|')}));
  $('#rt-story-'+flow+'-title').textContent=direction;const top=basket.positives[0];$('#rt-story-'+flow+'-takeaway').textContent=top?tr(`${productName(top.code)} představují největší doložený přírůstek: +${exactUSD(top.deltaExact)}.`,`${productName(top.code)} contributed the largest observed increase: +${exactUSD(top.deltaExact)}.`):tr('Pro tento rok chybí srovnatelný kladný přírůstek.','No paired positive category increase is available for this year.');const diff=basket.coverageDifferenceExact,missing=basket.missing.map(r=>r.code).join(', ')||tr('žádné','none');
  $('#rt-story-'+flow+'-copy').textContent=tr(`Koš: ${exactUSD(basket.total?.baseExact)} → ${exactUSD(basket.total?.valueExact)}. Podíl kruhu = přírůstek kategorie / ${exactUSD(basket.positiveExact)} kladných změn. Srovnatelné kategorie ${basket.knownCount}/${basket.totalCount}; chybějící: ${missing}. Čistá změna srovnatelných kategorií: ${exactUSD(basket.netExact)}. Rozdíl mezi čistou změnou koše a srovnatelnými kategoriemi: ${exactUSD(diff)}.`,`Observed basket: ${exactUSD(basket.total?.baseExact)} → ${exactUSD(basket.total?.valueExact)}. Donut share = category increase / ${exactUSD(basket.positiveExact)} of positive changes. Paired categories ${basket.knownCount}/${basket.totalCount}; missing: ${missing}. Paired-category net change: ${exactUSD(basket.netExact)}. Difference between full-basket net change and paired-category net change: ${exactUSD(diff)}.`);
  $('#rt-story-'+flow+'-balance').innerHTML=balance(basket,basket.total?.deltaExact??null,true);
  storyPlot('rt-story-'+flow+'-donut',({X:'russia-story-exports-growth',M:'russia-story-imports-growth'})[flow],slices,{type:'donut',donut:true,title:`${direction} · ${tr('podíl kladných změn','share of positive changes')}`,denominator:basket.positiveExact});
  $('#rt-story-'+flow+'-legend').innerHTML=table([tr('Rostoucí kategorie','Growing category'),'Δ USD',tr('Podíl kladných změn','Share of positive changes')],slices.map(r=>[`<i style="background:${r.color}"></i>${esc(r.label)}`,esc(decimal(r.deltaExact)),esc(decimal(r.sharePositiveExact))+'%']));
  storyPlot('rt-story-'+flow+'-declines',({X:'russia-story-exports-declines',M:'russia-story-imports-declines'})[flow],basket.negatives.slice().sort((a,b)=>a.delta-b.delta).slice(0,5).map(r=>({...r,label:label(r.code)})),{title:`${direction} · ${tr('pět největších poklesů','five largest declines')}`,color:'#c93237'});
  $('#rt-story-'+flow+'-table').innerHTML=storyTable(basket,label);
 }
 $('#rt-story-hubs').innerHTML=HUBS.map(hub=>{const basket=hubDelta(story.data,hub,'2019',year);return `<section><h4>${esc(country(hub))}</h4>${table([tr('Samostatný tok','Separate flow'),'2019 USD',`${year} USD`,'Δ USD'],basket.rows.map(r=>[r.code==='WORLD_IMPORTS'?tr('Dovoz ze světa','World imports'):tr('Vývoz do Ruska','Exports to Russia'),esc(decimal(r.baseExact)),esc(decimal(r.valueExact)),esc(decimal(r.deltaExact))]))}</section>`;}).join('');
 const ids=[...new Set([...(story.data.source.release_ids||[]),...(story.bilateral.source.release_ids||[])])];$('#rt-story-provenance').textContent=`${story.data.source.table}. ${story.bilateral.source.method||''} ${story.bilateral.source.release_note||''} ${tr('Vydání načtení','Ingestion IDs')}: ${ids.join(' | ')}. ${tr('Každá změna je konec minus základ. Součty a rozdíly používají původní desetinné řetězce, nikoli zaokrouhlené popisky grafu. Podíly jsou vypočtené a zobrazené nejvýše na devět desetinných míst.','Every change is endpoint minus baseline. Sums and differences use original decimal strings, never rounded chart labels. Shares are calculated and displayed to at most nine decimal places.')}`;
}
$('#rt-story-country').addEventListener('change',e=>{story.country=e.target.value;loadStory();});$('#rt-story-year').addEventListener('change',e=>{story.year=e.target.value;renderStory();});$('#rt-story-retry').addEventListener('click',loadStory);
$('#rt-story-download').addEventListener('click',()=>{
 if(!story.data||!story.bilateral)return;const year=story.year;
 const rows=deltaAuditRows(supplierDelta(story.data,'2019',year),{kind:'direct_supplier',flow:'X'});
 for(const flow of ['X','M']){const basket=bilateralDelta(story.bilateral,{country:story.country,flow,endYear:year});rows.push(...deltaAuditRows(basket,{reporter:story.country,flow}));const total=deltaBasket(story.bilateral.observations.filter(o=>o.reporter_iso3===story.country&&o.partner_iso3==='RUS'&&o.flow_code===flow&&o.product_code==='TOTAL'),{endYear:year});rows.push(...deltaAuditRows(total,{kind:'observed_basket',reporter:story.country,flow}));}
 for(const hub of HUBS)for(const row of deltaAuditRows(hubDelta(story.data,hub,'2019',year),{kind:'hub_route',reporter:hub}))rows.push({...row,flow_code:row.code==='WORLD_IMPORTS'?'M':'X',positive_denominator_usd:null,declines_usd:null,paired_net_usd:null,share_positive_pct:null});
 const csv=window.PSDChart.toCSV(Object.keys(rows[0]||{}).map(key=>({key,label:key})),rows),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`russia-delta-2019-${year}-${story.country}.csv`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
});
$('#rt-story-explore').addEventListener('click',()=>{if(!state.model)return;state.frequency='A';state.product='TOTAL';state.period=story.year;controls();load();});

start();
