(() => {
  const lang = new URLSearchParams(location.search).get("lang") || localStorage.getItem("psd-lang") || "cs";
  const copy = {
    cs: {
      methodEyebrow:"Metodika · datová smlouva",methodTitle:"Srovnávat ano.<br><em>Zjednodušovat ne.</em>",methodLead:"Každé číslo držíme u jeho definice, období a původního zdroje. Metodika vysvětluje společný rámec i místa, kde se země a města rozcházejí.",
      m1:"Stejný sektor",m1c:"Mezinárodní srovnání používá sektor vládních institucí: ústřední, regionální a místní vlády plus sociální fondy.",m2:"Stejná jednotka",m2c:"Příjmy, výdaje, saldo a dluh vyjadřujeme jako podíl HDP. Nominální částky nepoužíváme jako žebříček velikosti státu.",m3:"Viditelný rok",m3c:"Rok, rozpočtová fáze a datum zdroje jsou součástí každé hodnoty. Plán a skutečnost zůstávají oddělené.",m4:"Měny bez iluze",m4c:"Přepočty používají uvedený kurz ECB. Originální místní částka zůstává uložená a dohledatelná.",m5:"Účetní hranice",m5c:"Obce, regiony, státní rozpočet a veřejné korporace nesčítáme, pokud nejsou konsolidované ve společné definici.",m6:"Zdroj až k řádku",m6c:"Profil odkazuje na primární publikaci a uchovává zdrojový kód. Chybějící údaj není nula.",methodSource:"Hlavní harmonizovaný zdroj",methodSourceValue:"IMF World Economic Outlook · duben 2026",methodCta:"Otevřít srovnání →",
      aboutEyebrow:"O projektu",aboutTitle:"Data pro veřejnou<br><em>kontrolu.</em>",aboutLead:"Public Spending Data dává veřejné rozpočty do souvislostí. Spojuje oficiální data, dlouhé časové řady a trvalé odkazy, aby se k číslům dalo vracet, ověřovat je a rozumně je porovnávat.",aboutMission:"Proč projekt vznikl",aboutMissionCopy:"Rozpočtová data jsou veřejná, ale často roztříštěná mezi portály, soubory a rozdílné účetní definice. Projekt je převádí do čitelné vrstvy bez ztráty původu a bez předstírání přesnosti tam, kde srovnání přesné není.",aboutPrinciples:"Co slibujeme",p1:"Oficiální zdroj u každé hodnoty",p2:"Viditelné účetní hranice",p3:"Otevřená data a trvalé odkazy",p4:"Žádné skryté hodnocení ani falešný žebříček",makerKicker:"Projekt připravuje",makerTitle:"Hlídač státu, z.ú.",makerCopy:"Nezávislá česká nezisková watchdog organizace. Propojuje a analyzuje veřejná data, sleduje smlouvy, zakázky, dotace a další veřejné výdaje a pomáhá občanům, novinářům i úřadům kontrolovat hospodaření státu.",legal:"zapsaný ústav · nezisková organizace",office:"Velenovského 648, 251 64 Mnichovice",official:"Oficiální web ↗",impact:"Výsledky a dopad ↗",support:"Podpořit Hlídač státu ↗"
    },
    en: {
      methodEyebrow:"Methodology · data contract",methodTitle:"Compare carefully.<br><em>Never oversimplify.</em>",methodLead:"Every number stays attached to its definition, period and original source. The methodology explains the common framework and the points where countries and cities diverge.",
      m1:"The same sector",m1c:"International comparisons use general government: central, regional and local government plus social-security funds.",m2:"The same unit",m2c:"Revenue, expenditure, balance and debt are expressed as a share of GDP. Nominal amounts are not used as a ranking of government size.",m3:"A visible year",m3c:"The year, budget stage and source date travel with every value. Plans and actual accounts remain separate.",m4:"Currencies without illusion",m4c:"Conversions use the stated ECB rate. The original local-currency amount remains stored and traceable.",m5:"Accounting boundaries",m5c:"Municipalities, regions, state budgets and public corporations are not added together unless a common definition consolidates them.",m6:"Source to the row",m6c:"Profiles link to the primary publication and retain source codes. A missing value is never treated as zero.",methodSource:"Primary harmonised source",methodSourceValue:"IMF World Economic Outlook · April 2026",methodCta:"Open comparison →",
      aboutEyebrow:"About the project",aboutTitle:"Data for public<br><em>scrutiny.</em>",aboutLead:"Public Spending Data puts public budgets in context. It combines official data, long time series and permanent links so figures can be revisited, verified and compared responsibly.",aboutMission:"Why the project exists",aboutMissionCopy:"Budget data is public, yet often fragmented across portals, files and incompatible accounting definitions. The project turns it into a readable layer without losing provenance or pretending that imperfect comparisons are exact.",aboutPrinciples:"What we promise",p1:"An official source for every value",p2:"Visible accounting boundaries",p3:"Open data and permanent links",p4:"No hidden scoring or false league tables",makerKicker:"Created by",makerTitle:"Hlídač státu, z.ú.",makerCopy:"An independent Czech nonprofit watchdog organisation. It connects and analyses public data, monitors contracts, procurement, subsidies and other public spending, and helps citizens, journalists and public bodies scrutinise how the state manages money.",legal:"registered institute · nonprofit organisation",office:"Velenovského 648, 251 64 Mnichovice, Czechia",official:"Official website ↗",impact:"Results and impact ↗",support:"Support Hlídač státu ↗"
    }
  };
  let current = lang === "en" ? "en" : "cs";
  function render() {
    document.documentElement.lang = current;
    document.querySelectorAll("[data-page-copy]").forEach(node => { const value=copy[current][node.dataset.pageCopy]; if(value)node.innerHTML=value; });
    document.querySelectorAll("[data-lang]").forEach(button => { const active=button.dataset.lang===current; button.classList.toggle("active",active); button.setAttribute("aria-pressed",String(active)); });
    document.querySelectorAll("[data-language-link]").forEach(link => { const url=new URL(link.getAttribute("href"),location.href); url.searchParams.set("lang",current); link.href=url.pathname+url.search+url.hash; });
    localStorage.setItem("psd-lang",current);
    history.replaceState(null,"",`${location.pathname}?lang=${current}${location.hash}`);
  }
  document.querySelectorAll("[data-lang]").forEach(button => button.addEventListener("click",()=>{current=button.dataset.lang;render();}));
  render();
})();
