(() => {
  const lang = new URLSearchParams(location.search).get("lang") || localStorage.getItem("psd-lang") || "cs";
  const copy = {
    cs: {
      methodEyebrow:"Metodika",methodTitle:"Jak data srovnáváme.",methodLead:"U každého čísla uvádíme definici, období a původní zdroj. Tady jsou pravidla, která používáme.",methodAside:"6 pravidel pro srovnání",
      m1:"Rozsah institucí",m1c:"Mezinárodní srovnání používá sektor vládních institucí: ústřední, regionální a místní vlády plus sociální fondy.",m2:"Jednotky",m2c:"Příjmy, výdaje, saldo a dluh vyjadřujeme jako podíl HDP. Nominální částky nepoužíváme jako žebříček velikosti státu.",m3:"Rok a fáze",m3c:"U každé hodnoty uvádíme rok, rozpočtovou fázi a datum zdroje. Plán a skutečnost zůstávají oddělené.",m4:"Přepočet měn",m4c:"Přepočty používají uvedený kurz ECB. Původní částka v místní měně zůstává dohledatelná.",m5:"Účetní hranice",m5c:"Obce, regiony, státní rozpočet a veřejné korporace nesčítáme, pokud nejsou konsolidované ve společné definici.",m6:"Původ dat",m6c:"Profily odkazují na primární publikaci a uchovávají zdrojový kód. Chybějící údaj není nula.",methodSource:"Hlavní srovnávací zdroj",methodSourceValue:"IMF World Economic Outlook · duben 2026",methodCta:"Otevřít srovnání →",
      aboutEyebrow:"O projektu",aboutTitle:"O Public Spending Data",aboutLead:"Na jednom místě zveřejňujeme rozpočtová data, dlouhé časové řady a odkazy na původní zdroje.",aboutAside:"data · zdroje · metodika",aboutMission:"Co děláme",aboutMissionCopy:"Rozpočtová data jsou často rozdělená mezi portály, soubory a různé účetní definice. Převádíme je do čitelné podoby a zachováváme odkaz na jejich původ.",aboutPrinciples:"Naše pravidla",p1:"Oficiální zdroj u každé hodnoty",p2:"Jasně uvedený rozsah dat",p3:"Otevřená data a trvalé odkazy",p4:"Bez skrytého hodnocení a falešných žebříčků",makerKicker:"Projekt připravuje",makerTitle:"Hlidac statu, z.u.",makerCopy:"Nezávislá česká nezisková organizace, která propojuje veřejná data a sleduje smlouvy, zakázky, dotace a další veřejné výdaje.",legal:"zapsaný ústav · nezisková organizace",office:"Velenovského 648, 251 64 Mnichovice",official:"Oficiální web ↗",impact:"Výsledky a dopad ↗",support:"Podpořit Hlidac statu, z.u. ↗"
    },
    en: {
      methodEyebrow:"Methodology",methodTitle:"How we compare the data.",methodLead:"Every figure includes its definition, period and original source. These are the rules we use.",methodAside:"6 comparison rules",
      m1:"Institutional scope",m1c:"International comparisons use general government: central, regional and local government plus social-security funds.",m2:"Units",m2c:"Revenue, expenditure, balance and debt are expressed as a share of GDP. Nominal amounts are not used to rank government size.",m3:"Year and stage",m3c:"Each value states its year, budget stage and source date. Plans and actual accounts remain separate.",m4:"Currency conversion",m4c:"Conversions use the stated ECB rate. The original amount in local currency remains traceable.",m5:"Accounting boundaries",m5c:"Municipalities, regions, state budgets and public corporations are not added together unless a common definition consolidates them.",m6:"Data provenance",m6c:"Profiles link to the primary publication and retain source codes. A missing value is never treated as zero.",methodSource:"Main comparison source",methodSourceValue:"IMF World Economic Outlook · April 2026",methodCta:"Open comparison →",
      aboutEyebrow:"About",aboutTitle:"About Public Spending Data",aboutLead:"We publish budget data, long time series and links to original sources in one place.",aboutAside:"data · sources · methods",aboutMission:"What we do",aboutMissionCopy:"Budget data is often split across portals, files and accounting definitions. We make it easier to read while preserving a clear link to the original source.",aboutPrinciples:"Our rules",p1:"An official source for every value",p2:"A clear scope for every dataset",p3:"Open data and permanent links",p4:"No hidden scoring or false league tables",makerKicker:"Created by",makerTitle:"Hlidac statu, z.u.",makerCopy:"An independent Czech nonprofit organisation that connects public data and monitors contracts, procurement, subsidies and other public spending.",legal:"registered institute · nonprofit organisation",office:"Velenovského 648, 251 64 Mnichovice, Czechia",official:"Official website ↗",impact:"Results and impact ↗",support:"Support Hlidac statu, z.u. ↗"
    }
  };
  let current = lang === "en" ? "en" : "cs";
  function render() {
    document.documentElement.lang = current;
    document.querySelectorAll("[data-page-copy]").forEach(node => { const value=copy[current][node.dataset.pageCopy]; if(value)node.innerHTML=value; });
    document.querySelectorAll("[data-lang]").forEach(button => { const active=button.dataset.lang===current; button.classList.toggle("active",active); button.setAttribute("aria-pressed",String(active)); });
    document.querySelectorAll("[data-language-link]").forEach(link => { const url=new URL(link.getAttribute("href"),location.href); url.searchParams.set("lang",current); link.href=url.pathname+url.search+url.hash; });
    localStorage.setItem("psd-lang",current);
    history.replaceState(null,"",`${location.pathname}?lang=${current}${location.hash}`);
  }
  document.querySelectorAll("[data-lang]").forEach(button => button.addEventListener("click",()=>{current=button.dataset.lang;render();}));
  render();
})();
