(() => {
  const lang = new URLSearchParams(location.search).get("lang") || localStorage.getItem("psd-lang") || "cs";
  const copy = {
    cs: {
      methodEyebrow:"Metodika",methodTitle:"Jak data srovnáváme.",methodLead:"U každého čísla uvádíme definici, období a původní zdroj. Tady jsou pravidla, která používáme.",methodAside:"6 pravidel pro srovnání",
      m1:"Rozsah institucí",m1c:"Mezinárodní srovnání používá sektor vládních institucí: ústřední, regionální a místní vlády plus sociální fondy.",m2:"Jednotky",m2c:"Příjmy, výdaje, saldo a dluh vyjadřujeme jako podíl HDP. Nominální částky nepoužíváme jako žebříček velikosti státu.",m3:"Rok a fáze",m3c:"U každé hodnoty uvádíme rok, rozpočtovou fázi a datum zdroje. Plán a skutečnost zůstávají oddělené.",m4:"Přepočet měn",m4c:"Přepočty používají uvedený kurz ECB. Původní částka v místní měně zůstává dohledatelná.",m5:"Účetní hranice",m5c:"Obce, regiony, státní rozpočet a veřejné korporace nesčítáme, pokud nejsou konsolidované ve společné definici.",m6:"Původ dat",m6c:"Profily odkazují na primární publikaci a uchovávají zdrojový kód. Chybějící údaj není nula.",methodSource:"Hlavní srovnávací zdroj",methodSourceValue:"IMF World Economic Outlook · duben 2026",methodCta:"Otevřít srovnání →",healthEyebrow:"Kontrola vydání",healthTitle:"Co je úplné. Co chybí. Co prověřujeme.",healthLead:"Strojově čitelná kontrola každého vydání zpřístupňuje pokrytí, výslovně chybějící data a prověřované anomálie.",ledgerEyebrow:"Datová linie · 110 záznamů",ledgerTitle:"Úplná tabulka zdrojů",ledgerLead:"Každá země a každý modul: rozsah, období, artefakt, primární zdroj, přesné místo výběru, transformace a známé mezery.",ledgerJson:"Stáhnout JSON ↓",ledgerCsv:"Stáhnout CSV ↓",ledgerCountry:"Země",ledgerModule:"Modul",ledgerStatus:"Pokrytí",ledgerSearch:"Hledat",ledgerSearchPlaceholder:"zdroj, tabulka, soubor…",ledgerHave:"Co máme",ledgerPeriodScope:"Období · rozsah",ledgerSourceExact:"Zdroj · přesné místo",ledgerTransform:"Artefakt · transformace",ledgerLimits:"Mezery a hranice",ledgerAllCountries:"Všechny země",ledgerAllModules:"Všechny moduly",ledgerAllStatuses:"Všechny stavy",ledgerFull:"Plné",ledgerPartial:"Částečné",ledgerAggregate:"Agregát",ledgerRows:"záznamů z",
      aboutEyebrow:"O projektu",aboutTitle:"O Public Spending Data",aboutLead:"Na jednom místě zveřejňujeme rozpočtová data, dlouhé časové řady a odkazy na původní zdroje.",aboutAside:"data · zdroje · metodika",aboutMission:"Co děláme",aboutMissionCopy:"Rozpočtová data jsou často rozdělená mezi portály, soubory a různé účetní definice. Převádíme je do čitelné podoby a zachováváme odkaz na jejich původ.",aboutPrinciples:"Naše pravidla",p1:"Oficiální zdroj u každé hodnoty",p2:"Jasně uvedený rozsah dat",p3:"Otevřená data a trvalé odkazy",p4:"Bez skrytého hodnocení a falešných žebříčků",makerKicker:"Projekt připravuje",makerTitle:"Hlidac statu, z.u.",makerCopy:"Nezávislá česká nezisková organizace, která propojuje veřejná data a sleduje smlouvy, zakázky, dotace a další veřejné výdaje.",legal:"zapsaný ústav · nezisková organizace",office:"Velenovského 648, 251 64 Mnichovice",official:"Oficiální web ↗",impact:"Výsledky a dopad ↗",support:"Podpořit Hlidac statu, z.u. ↗"
    },
    en: {
      methodEyebrow:"Methodology",methodTitle:"How we compare the data.",methodLead:"Every figure includes its definition, period and original source. These are the rules we use.",methodAside:"6 comparison rules",
      m1:"Institutional scope",m1c:"International comparisons use general government: central, regional and local government plus social-security funds.",m2:"Units",m2c:"Revenue, expenditure, balance and debt are expressed as a share of GDP. Nominal amounts are not used to rank government size.",m3:"Year and stage",m3c:"Each value states its year, budget stage and source date. Plans and actual accounts remain separate.",m4:"Currency conversion",m4c:"Conversions use the stated ECB rate. The original amount in local currency remains traceable.",m5:"Accounting boundaries",m5c:"Municipalities, regions, state budgets and public corporations are not added together unless a common definition consolidates them.",m6:"Data provenance",m6c:"Profiles link to the primary publication and retain source codes. A missing value is never treated as zero.",methodSource:"Main comparison source",methodSourceValue:"IMF World Economic Outlook · April 2026",methodCta:"Open comparison →",healthEyebrow:"Release health",healthTitle:"What is complete. What is missing. What we review.",healthLead:"A machine-readable check for every release exposes coverage, explicitly missing data and anomalies under review.",ledgerEyebrow:"Data lineage · 110 records",ledgerTitle:"Complete source table",ledgerLead:"Every country and every module: coverage, period, artifact, primary source, exact extraction point, transformation and known gaps.",ledgerJson:"Download JSON ↓",ledgerCsv:"Download CSV ↓",ledgerCountry:"Country",ledgerModule:"Module",ledgerStatus:"Coverage",ledgerSearch:"Search",ledgerSearchPlaceholder:"source, table, file…",ledgerHave:"What we have",ledgerPeriodScope:"Period · scope",ledgerSourceExact:"Source · exact location",ledgerTransform:"Artifact · transformation",ledgerLimits:"Gaps and boundaries",ledgerAllCountries:"All countries",ledgerAllModules:"All modules",ledgerAllStatuses:"All statuses",ledgerFull:"Full",ledgerPartial:"Partial",ledgerAggregate:"Aggregate",ledgerRows:"records of",
      aboutEyebrow:"About",aboutTitle:"About Public Spending Data",aboutLead:"We publish budget data, long time series and links to original sources in one place.",aboutAside:"data · sources · methods",aboutMission:"What we do",aboutMissionCopy:"Budget data is often split across portals, files and accounting definitions. We make it easier to read while preserving a clear link to the original source.",aboutPrinciples:"Our rules",p1:"An official source for every value",p2:"A clear scope for every dataset",p3:"Open data and permanent links",p4:"No hidden scoring or false league tables",makerKicker:"Created by",makerTitle:"Hlidac statu, z.u.",makerCopy:"An independent Czech nonprofit organisation that connects public data and monitors contracts, procurement, subsidies and other public spending.",legal:"registered institute · nonprofit organisation",office:"Velenovského 648, 251 64 Mnichovice, Czechia",official:"Official website ↗",impact:"Results and impact ↗",support:"Support Hlidac statu, z.u. ↗"
    }
  };
  let current = lang === "en" ? "en" : "cs";
  let methodologyData=null,qualityData=null,releaseData=null;
  const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  const statusLabel=status=>copy[current][status==="full"?"ledgerFull":status==="partial"?"ledgerPartial":"ledgerAggregate"];
  function methodFilters(){return {country:document.querySelector("#method-country-filter")?.value||"",module:document.querySelector("#method-module-filter")?.value||"",status:document.querySelector("#method-status-filter")?.value||"",search:(document.querySelector("#method-source-search")?.value||"").trim().toLocaleLowerCase(current==="cs"?"cs":"en")};}
  function filteredMethodRows(){
    if(!methodologyData)return [];
    const filters=methodFilters();
    return methodologyData.rows.filter(row=>{
      if(filters.country&&row.country_code!==filters.country)return false;
      if(filters.module&&row.module!==filters.module)return false;
      if(filters.status&&row.status!==filters.status)return false;
      if(filters.search&&!JSON.stringify(row).toLocaleLowerCase(current==="cs"?"cs":"en").includes(filters.search))return false;
      return true;
    });
  }
  function fillSelect(selector,items,allLabel,label){
    const select=document.querySelector(selector); if(!select)return;
    const selected=select.value;
    select.innerHTML=`<option value="">${esc(allLabel)}</option>${items.map(item=>`<option value="${esc(item.value)}">${esc(item[label])}</option>`).join("")}`;
    if([...select.options].some(option=>option.value===selected))select.value=selected;
  }
  function renderMethodology(){
    if(!methodologyData)return;
    fillSelect("#method-country-filter",methodologyData.countries.map(item=>({value:item.code,cs:item.name_cs,en:item.name_en})),copy[current].ledgerAllCountries,current);
    fillSelect("#method-module-filter",methodologyData.modules.map(item=>({value:item.id,cs:item.label_cs,en:item.label_en})),copy[current].ledgerAllModules,current);
    fillSelect("#method-status-filter",[{value:"full",cs:"Plné",en:"Full"},{value:"partial",cs:"Částečné",en:"Partial"},{value:"aggregate",cs:"Agregát",en:"Aggregate"}],copy[current].ledgerAllStatuses,current);
    const rows=filteredMethodRows(),body=document.querySelector("#method-source-rows");
    if(body)body.innerHTML=rows.map(row=>`<tr><td><b>${esc(current==="cs"?row.country_name_cs:row.country_name_en)}</b><small>${esc(row.country_code)}</small></td><td><b>${esc(current==="cs"?row.module_label_cs:row.module_label_en)}</b><code>${esc(row.module)}</code></td><td><span class="method-status method-status-${esc(row.status)}">${esc(statusLabel(row.status))}</span><p>${esc(row.coverage)}</p></td><td><b>${esc(row.period)}</b><p>${esc(row.scope)}</p></td><td>${row.sources.map(item=>`<a href="${esc(item.url)}" target="_blank" rel="noreferrer">${esc(item.title)} ↗</a>`).join("")}<p>${esc(row.exact_extraction)}</p></td><td><code>${esc(row.artifact)}</code><p>${esc(row.transformation)}</p></td><td>${row.limitations?`<p>${esc(row.limitations)}</p>`:"—"}</td></tr>`).join("");
    const summary=document.querySelector("#method-ledger-summary"); if(summary)summary.textContent=`${rows.length} ${copy[current].ledgerRows} ${methodologyData.row_count}`;
  }
  function downloadMethodCsv(){
    const headings=["country_code","country","module","status","coverage","period","scope","sources","exact_extraction","artifact","transformation","limitations"],quote=value=>`"${String(value??"").replaceAll('"','""')}"`;
    const lines=[headings.join(","),...filteredMethodRows().map(row=>[row.country_code,current==="cs"?row.country_name_cs:row.country_name_en,current==="cs"?row.module_label_cs:row.module_label_en,row.status,row.coverage,row.period,row.scope,row.sources.map(item=>`${item.title}: ${item.url}`).join(" | "),row.exact_extraction,row.artifact,row.transformation,row.limitations].map(quote).join(","))];
    const link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8"}));link.download=`public-spending-data-methodology-${current}.csv`;link.click();URL.revokeObjectURL(link.href);
  }
  function renderDataHealth(){
    const root=document.querySelector("#data-health-root");if(!root||!qualityData)return;
    const c=qualityData.counts||{},missing=qualityData.explicit_missing_data?.cash_balance_sheet_rows_missing||[],anomalies=qualityData.reviewed_anomalies||{};
    const anomalyCount=Object.values(anomalies).reduce((sum,rows)=>sum+(Array.isArray(rows)?rows.length:0),0);
    const completePct=c.municipalities?c.complete_municipal_histories/c.municipalities*100:0;
    const financePct=c.public_entity_registry?c.public_entity_financial_statements/c.public_entity_registry*100:0;
    const generated=releaseData?.data_generated_at?new Intl.DateTimeFormat(current==="cs"?"cs-CZ":"en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(releaseData.data_generated_at)):"—";
    const labels=current==="cs"?{
      passed:"Kontrola prošla",generated:"Data vytvořena",municipalities:"Obcí",history:"Historických záznamů",complete:"Úplné obecní historie",registry:"Veřejné subjekty",finance:"S dostupnou účetní závěrkou",missing:"Výslovně chybějící data",missingCopy:`Rozvaha a peněžní zůstatky chybí u ${missing.length} obcí. Hodnota zůstává prázdná, nikdy není nahrazena nulou.`,review:"Prověřované anomálie",reviewCopy:`${anomalyCount} extrémních nebo záporných hodnot je zachováno a označeno k revizi, nikoli automaticky smazáno.`,build:"Detailní rozpočtové členění obcí",buildCopy:"Souhrny a úplné položkové členění se slučují z BigQuery během produkčního buildu. Nulový počet v lokálním předprodukčním reportu proto není chybějící veřejný dataset.",downloads:"Strojově čitelné podklady",quality:"Kontrola kvality JSON ↓",manifest:"Manifest vydání JSON ↓",warning:"Známá mezera"}:{
      passed:"Checks passed",generated:"Data generated",municipalities:"Municipalities",history:"Historical records",complete:"Complete municipal histories",registry:"Public entities",finance:"With a comparable financial statement",missing:"Explicitly missing data",missingCopy:`Balance-sheet cash data are missing for ${missing.length} municipalities. The value remains null and is never replaced with zero.`,review:"Anomalies under review",reviewCopy:`${anomalyCount} extreme or negative observations are retained and flagged for review, not silently deleted.`,build:"Detailed municipal budget lines",buildCopy:"Headlines and complete line-item breakdowns are merged from BigQuery during the production build. A zero in the local pre-build report therefore does not mean the public dataset is missing.",downloads:"Machine-readable evidence",quality:"Quality report JSON ↓",manifest:"Release manifest JSON ↓",warning:"Known gap"};
    const cards=[[labels.municipalities,c.municipalities,"100 %"],[labels.history,c.municipal_history_records,`${completePct.toFixed(1)} % ${labels.complete.toLocaleLowerCase()}`],[labels.registry,c.public_entity_registry,`${financePct.toFixed(1)} % ${labels.finance.toLocaleLowerCase()}`],[current==="cs"?"Produkční JSON":"Production JSON",c.production_json_files,`${c.html_files||0} HTML`]];
    root.innerHTML=`<div class="data-health-status"><span class="data-health-pass">● ${labels.passed}</span><span>${labels.generated}: <b>${esc(generated)}</b></span></div><div class="data-health-kpis">${cards.map(([label,value,note])=>`<article><span>${esc(label)}</span><strong>${new Intl.NumberFormat(current==="cs"?"cs-CZ":"en-GB").format(value||0)}</strong><small>${esc(note)}</small></article>`).join("")}</div><div class="data-health-notes"><article><b>${labels.missing}</b><strong>${missing.length}</strong><p>${labels.missingCopy}</p><details><summary>${current==="cs"?"Zobrazit obce":"Show municipalities"}</summary><ul>${missing.map(item=>`<li>${esc(item.name)} <code>${esc(item.national_id)}</code></li>`).join("")}</ul></details></article><article><b>${labels.review}</b><strong>${anomalyCount}</strong><p>${labels.reviewCopy}</p><ul>${Object.entries(anomalies).map(([key,rows])=>`<li><code>${esc(key)}</code> · ${rows.length}</li>`).join("")}</ul></article><article><b>${labels.build}</b><strong>BigQuery → UI</strong><p>${labels.buildCopy}</p></article></div>${(qualityData.warnings||[]).map(warning=>`<p class="data-health-warning"><b>${labels.warning}:</b> ${esc(warning)}</p>`).join("")}<div class="data-health-downloads"><b>${labels.downloads}</b><a href="data/data-quality-report.v1.json" download>${labels.quality}</a><a href="data/release-manifest.v1.json" download>${labels.manifest}</a></div>`;
  }
  function render() {
    document.documentElement.lang = current;
    document.querySelectorAll("[data-page-copy]").forEach(node => { const value=copy[current][node.dataset.pageCopy]; if(value)node.innerHTML=value; });
    document.querySelectorAll("[data-lang]").forEach(button => { const active=button.dataset.lang===current; button.classList.toggle("active",active); button.setAttribute("aria-pressed",String(active)); });
    document.querySelectorAll("[data-language-link]").forEach(link => { const url=new URL(link.getAttribute("href"),location.href); url.searchParams.set("lang",current); link.href=url.pathname+url.search+url.hash; });
    document.querySelectorAll("[data-page-placeholder]").forEach(node=>{const value=copy[current][node.dataset.pagePlaceholder];if(value)node.placeholder=value;});
    renderMethodology();
    renderDataHealth();
    localStorage.setItem("psd-lang",current);
    history.replaceState(null,"",`${location.pathname}?lang=${current}${location.hash}`);
  }
  document.querySelectorAll("[data-lang]").forEach(button => button.addEventListener("click",()=>{current=button.dataset.lang;render();}));
  ["#method-country-filter","#method-module-filter","#method-status-filter","#method-source-search"].forEach(selector=>document.querySelector(selector)?.addEventListener("input",renderMethodology));
  document.querySelector("#method-download-csv")?.addEventListener("click",downloadMethodCsv);
  render();
  if(document.body.dataset.page==="methodology")Promise.all([
    fetch("data/methodology-sources.v1.json").then(response=>{if(!response.ok)throw new Error(response.status);return response.json();}),
    fetch("data/data-quality-report.v1.json").then(response=>{if(!response.ok)throw new Error(response.status);return response.json();}),
    fetch("data/release-manifest.v1.json").then(response=>response.ok?response.json():null)
  ]).then(([methodology,quality,release])=>{methodologyData=methodology;qualityData=quality;releaseData=release;renderMethodology();renderDataHealth();}).catch(error=>{const summary=document.querySelector("#method-ledger-summary");if(summary)summary.textContent=`Methodology data: ${error}`;const health=document.querySelector("#data-health-root");if(health)health.textContent=`Data health: ${error}`;});
})();
