const {test}=require('node:test');const assert=require('node:assert/strict');const D=require('../industrial-data.js');
test('zero is observed; missing/confidential and flags survive',()=>{assert.deepEqual(D.cell('0 p'),{value:0,flag:'p',raw:'0 p'});assert.equal(D.cell(': c').value,null);assert.equal(D.cell(':C').flag,'C');assert.equal(D.cell('NaN').value,null);assert.equal(D.cell('-2.3e2 r').value,-230);});
test('lines do not cross missing periods, source breaks or quantity unit changes',()=>{const p=(period,value,unit='kg',flag='')=>({period,value,unit,flag});assert.equal(D.segments([p('2010',1),p('2011',null),p('2012',2)]).length,2);assert.equal(D.segments([p('2010-01',1),p('2010-03',2)]).length,2);assert.equal(D.segments([p('2010',1),p('2011',2,'items')]).length,2);assert.equal(D.segments([p('2010',1),p('2011',2,'kg','b')]).length,2);assert.equal(D.segments([p('2010-Q1',1),p('2010-Q2',2)]).length,1);});
test('PRODCOM joins quantity units and confidentiality flags; metadata is not charted as output',()=>{const meta={dimension_order:['freq','reporter','product','indicators'],periods:['2010','2011']};const rows=[[['A','CZ','1234','PRODQNT'],['0','99']],[['A','CZ','1234','PQNTFLAG'],['',':C']],[['A','CZ','1234','QNTUNIT'],['1500','2600']]];const p=D.series(rows[0],meta,rows);assert.equal(p[0].value,0);assert.equal(p[0].unit,'kg');assert.equal(p[1].value,null);assert.equal(p[1].unit,'items');assert.equal(D.series(rows[2],meta,rows)[0].value,null);});

test('quantity unit aliases agree and national currencies are not compared',()=>{assert.equal(D.normalizeUnit('M2'),D.normalizeUnit('m2'));assert.equal(D.normalizeUnit('KG'),'kg');assert.equal(D.comparableCurrency('CP_MNAC'),false);assert.equal(D.comparableCurrency('MIO_EUR'),true);});

test('PRODCOM preserves rounding bounds alongside observed quantities',()=>{const meta={dimension_order:['reporter','product','indicators'],periods:['2024']};const rows=[[['CZ','1234','PRODQNT'],['100']],[['CZ','1234','PQNTFLAG'],[':R']],[['CZ','1234','PQNTBASE'],['10']],[['CZ','1234','QNTUNIT'],['KG']]];const p=D.series(rows[0],meta,rows)[0];assert.equal(p.value,100);assert.equal(p.roundingBase,10);assert.equal(p.flag,':R');assert.equal(p.unit,'kg');});

test('invalid deep-linked date ranges reset together',()=>{assert.deepEqual(D.yearRange('2020','2024',2026),{from:2020,to:2024});assert.deepEqual(D.yearRange('2024','2020',2026),{from:2010,to:2026});assert.deepEqual(D.yearRange('NaN','2024',2026),{from:2010,to:2026});});
