(()=>{
 const root=document.getElementById('psd-learn-concept');
 const $=s=>root.querySelector(s), $$=s=>Array.from(root.querySelectorAll(s));
 const lessons=[
 {title:'Na všechno nestačí',icon:'blocks',goal:'Vyber, co městečku přidáš.',skill:'Volby a omezené zdroje',time:'8 minut',copy:'Vyzkoušej, jak rozhodujeme, když máme omezený rozpočet.',tags:['Počítání','Rozhodování','Společné služby']},
 {title:'Kdo platí naši školu?',icon:'school',goal:'Sleduj cestu společných peněz.',skill:'Veřejné služby',time:'6 minut',copy:'Příští aktivita: rozsvítíš postupně cestu od společných příjmů přes rozpočet ke škole. Objevíš, že provoz školy něco stojí, i když se neplatí u dveří.',tags:['Společné peníze','Škola','Lidé a firmy']},
 {title:'Co opravdu potřebuji?',icon:'shopping-basket',goal:'Naplň košík a vysvětli proč.',skill:'Potřeby a přání',time:'7 minut',copy:'Příští aktivita: pro různé postavy vybíráš věci do košíku. Zjistíš, že potřeby závisí na situaci a že každý může mít jiné priority.',tags:['Potřeby','Přání','Porovnávání']},
 {title:'Malé peníze, velký plán',icon:'piggy-bank',goal:'Slož si cestu ke svému cíli.',skill:'Spoření a plánování',time:'8 minut',copy:'Příští aktivita: po týdnech přidáváš žetony k vybranému cíli. Porovnáš, co můžeš mít hned a na co potřebuješ počkat.',tags:['Spoření','Čas','Sčítání']},
 {title:'Stejné peníze. Jiný nákup.',icon:'apple',goal:'Co se změní, když stoupne cena?',skill:'Ceny a množství',time:'6 minut',copy:'Příští aktivita: dvě nákupní tašky a stejný počet mincí. Změníš cenu jedné věci a uvidíš, kolik si jí můžeš dovolit.',tags:['Cena','Množství','Porovnávání']},
 {title:'Moje město doopravdy',icon:'map-pinned',goal:'Najdi společné služby kolem sebe.',skill:'První setkání s daty PSD',time:'10 minut',copy:'Příští aktivita: vybereš obec z ověřeného pokrytí PSD a objevíš několik skutečných výdajů. Každé číslo bude mít rok a zdroj; chybějící data nepředstavujeme jako nulu.',tags:['Obec','Skutečná data','Zdroje']}
 ];
 const future={explore:{name:'Explore · 11–14 let',copy:'Od osobního rozhodnutí k tomu, jak spolu souvisí domácnosti, město a stát.',items:[['Kam jde 100 liber','Rozpočtové podíly a veřejné služby.'],['Peníze v čase','Úspory, úroky a měnící se ceny.'],['Moje obec a stát','Kdo za co odpovídá a kdo co platí.']]},explain:{name:'Explain · 14–16 let',copy:'Pochop základní ekonomické vztahy a najdi pro své vysvětlení důkazy. Návaznost na GCSE Economics.',items:[['Ekonomika v pohybu','HDP, inflace a nezaměstnanost.'],['Jak funguje trh','Nabídka, poptávka a cena.'],['Svět propojený obchodem','Vývoz, dovoz a obchodní partneři.']]},evaluate:{name:'Evaluate · 16–18 let',copy:'Porovnávej možnosti hospodářské politiky, jejich předpoklady a rozdílné dopady. Návaznost na A-level Economics.',items:[['Rozpočtová laboratoř','Příjmy, výdaje a fiskální rozhodnutí.'],['Kdo získá a kdo platí','Daně, transfery a nerovnost.'],['Důkazy a argumenty','Výsledky služeb a limity srovnání.']]},research:{name:'Research · 18+ let',copy:'Od otázky k reprodukovatelné analýze. Datová výuka pro univerzitní semináře a samostatné projekty.',items:[['Datová laboratoř','Definice, řady a srovnatelné vzorky.'],['Prověř tvrzení','Souvislost, kauzalita a nejistota.'],['Zopakuj analýzu','Verzovaná data a výzkumné postupy.']]}};
 const upgrades=[{id:'books',name:'Knížky do školní knihovny',description:'Další příběhy pro malé čtenáře.',cost:3,icon:'book-open'},{id:'park',name:'Nové hřiště v parku',description:'Místo na hraní a setkávání.',cost:4,icon:'trees'},{id:'bus',name:'Další autobusový spoj',description:'Další možnost, jak se dostat do města.',cost:5,icon:'bus'}];
 let state={page:'home',age:'young',selected:[],phase:'choose',answer:null,percent:false,updatedAt:0,level:'discover',detail:0,view:'town'};
 const options={corners:24,scene:'paper'};
 const growingQuestion={
   explore:['Co se vejde do městského rozpočtu?','Porovnej dva rozpočty a spočítej podíl dopravy, školy a parku.'],
   explain:['Proč se město nemůže rozhodovat jen podle ceny?','Vysvětli náklady obětované příležitosti a přínosy pro různé obyvatele.'],
   evaluate:['Komu pomůže nový autobusový spoj?','Porovnej dva scénáře. Co předpokládáš a které dopady ještě neumíš doložit?'],
   research:['Zlepšuje dostupná doprava pracovní příležitosti?','Navrhni analýzu skutečných dat. Odděl souvislost od příčiny a popiš nejistotu.']
 };
 function icon(name){return '<i data-lucide="'+name+'" aria-hidden="true"></i>'}
 // Standalone preview needs no icon dependency. Inline previews use host Lucide.
 function icons(){
   if(window.lucide){window.lucide.createIcons({attrs:{width:18,height:18}});return}
   const symbols={'sprout':'🌱','compass':'◉','chart-no-axes-combined':'↗','scale':'⚖','microscope':'⌕','blocks':'🏘','school':'🏫','shopping-basket':'🧺','piggy-bank':'🐷','apple':'🍎','map-pinned':'🌍','book-open':'📚','trees':'🌳','bus':'🚌','lightbulb':'💡','check':'✓'};
   $$('[data-lucide]').forEach(el=>{el.textContent=symbols[el.dataset.lucide]||'→';el.classList.add('lp-fallback-icon')});
 }
 function applySaved(saved){const s=saved?.modelContent;if(!s||((s.updatedAt||0)<state.updatedAt))return;state.updatedAt=s.updatedAt||0;state.percent=s.percent===true;state.view=s.view==='numbers'?'numbers':'town';state.age=s.age==='older'?'older':'young';state.selected=Array.isArray(s.selected)?[...new Set(s.selected.filter(id=>upgrades.some(u=>u.id===id)))]:[];if(cost()>10)state.selected=[];state.page=['home','discover','lesson','teacher','future','detail'].includes(s.page)?s.page:'home';state.level=future[s.level]?s.level:'discover';state.phase=['choose','reflect','complete'].includes(s.phase)?s.phase:'choose';state.answer=['finite','wrong'].includes(s.answer)?s.answer:null;state.detail=Number.isInteger(s.detail)&&s.detail>=0&&s.detail<lessons.length?s.detail:0;if(!state.selected.length)state.phase='choose'}
 function save(){state.updatedAt=Date.now();const snapshot={modelContent:{...state},privateContent:null};if(window.openai?.setWidgetState)window.openai.setWidgetState(snapshot).catch(()=>{});else{try{sessionStorage.setItem('psd-learn-preview-v2',JSON.stringify(snapshot))}catch{/* A preview remains usable when storage is blocked. */}}}
 function cost(){return upgrades.filter(u=>state.selected.includes(u.id)).reduce((a,u)=>a+u.cost,0)}
 function go(page){state.page=page;if(page==='lesson'){state.phase='choose';state.answer=null}render();save()}
 function setLevel(level){if(level==='discover'){go('discover');return}state.level=level;state.page='future';render();save()}
 function render(){const focusedUpgrade=root.contains(document.activeElement)?document.activeElement.dataset.upgrade:null;root.dataset.page=state.page;root.dataset.age=state.age;root.style.setProperty('--lp-radius',(state.page==='future'?10:options.corners)+'px');$$('[data-screen]').forEach(n=>n.hidden=n.dataset.screen!==state.page);$$('.lp-level').forEach(n=>n.setAttribute('aria-pressed',state.page==='home'?'false':String(n.dataset.level===(state.page==='future'?state.level:'discover'))));$$('[data-age]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.age===state.age)));
 if(state.page==='future'){const f=future[state.level]||future.explore;$('#lp-future-title').textContent=f.name;$('#lp-future-copy').textContent=f.copy;$('#lp-future-list').innerHTML=f.items.map(i=>'<div><strong>'+i[0]+'</strong><p>'+i[1]+'</p></div>').join('')}
 if(state.page==='detail'){const l=lessons[state.detail];$('#lp-detail-title').textContent=l.title;$('#lp-detail-copy').textContent=l.copy;$('#lp-detail-visual').innerHTML='<span class="lp-card-icon">'+icon(l.icon)+'</span><span>→</span><span class="lp-card-icon">'+icon('lightbulb')+'</span>';$('#lp-detail-tags').innerHTML=l.tags.map(t=>'<span>'+t+'</span>').join('')}
 const m=state.age==='older'?10:1,remaining=(10-cost())*m;
 $('#lp-discover-intro').textContent='Knížky? Hřiště? Ještě jeden autobus? Máme městečko, '+(state.age==='older'?'sto':'deset')+' žetonů a spoustu nápadů.';
 if(state.page==='future'){
   const example=growingQuestion[state.level]||growingQuestion.explore;
   $('#lp-growing-question').textContent=example[0];
   $('#lp-growing-task').textContent=example[1];
 }
 $('#lp-remaining').textContent=remaining;
 $('#lp-lesson-intro').textContent='Na zlepšení městečka máš '+10*m+' žetonů. Co vybereš?';
 $('#lp-coins').innerHTML=Array.from({length:10},(_,i)=>'<span class="lp-coin '+(i<cost()?'spent':'')+'">'+m+'</span>').join('');
 $$('[data-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===state.view)));
 $('#lp-town-view').hidden=state.view!=='town';
 $('#lp-numbers-view').hidden=state.view!=='numbers';
 $('#lp-budget-rows').innerHTML=upgrades.map(u=>'<tr class="'+(state.selected.includes(u.id)?'is-chosen':'')+'"><th scope="row">'+u.name+'</th><td>'+u.cost*m+(state.age==='older'&&state.percent?' · '+u.cost*10+' %':'')+'</td><td>'+(state.selected.includes(u.id)?'✓ Vybráno':'Zatím ne')+'</td></tr>').join('');
 $('#lp-budget-total').textContent=cost()*m+' z '+10*m+' žetonů';
 $('#lp-guide-message').textContent=state.phase==='complete'?'Aha! Stejné žetony, různé možnosti.':state.selected.length===2?'Dva nápady jsou v plánu! Co necháme na příště?':state.selected.length===1?'První nápad je v plánu. Co se ještě vejde?':'Jaký nápad vyzkoušíme jako první?';
 const sceneLabel=state.selected.length?'Vybraná vylepšení: '+upgrades.filter(u=>state.selected.includes(u.id)).map(u=>u.name).join(', ')+'. Zbývá '+remaining+' žetonů.':'Městečko se základními službami. Zatím není vybráno žádné vylepšení.';
 $('[data-scene="lesson"]').setAttribute('aria-label',sceneLabel);
 $('#lp-options').innerHTML=upgrades.map(u=>{const chosen=state.selected.includes(u.id),unavailable=!chosen&&cost()+u.cost>10;return '<button class="lp-option" type="button" data-upgrade="'+u.id+'" aria-pressed="'+chosen+'" '+(unavailable?'disabled':'')+'><span class="lp-card-icon">'+icon(chosen?'check':u.icon)+'</span><span class="lp-option-text"><strong>'+u.name+'</strong><small>'+(state.age==='older'&&state.percent?u.cost*10+' % celého rozpočtu':u.description)+'</small></span><span class="lp-price">'+u.cost*m+'<span aria-hidden="true">●</span></span></button>'}).join('');
 $('#lp-choice-state').textContent=state.selected.length?'Vybráno za '+cost()*m+' žetonů. Zbývá '+remaining+'.'+(state.selected.length===2?' Třetí vylepšení už se nevejde.':''):'Vyber, co chceš městečku přidat.';$('#lp-confirm').disabled=!state.selected.length;
 $('#lp-percent-control').hidden=state.age!=='older';$('#lp-percent').checked=state.percent;$('#lp-choice-panel').hidden=state.phase!=='choose';$('#lp-reflection').hidden=state.phase!=='reflect';$('#lp-complete').hidden=state.phase!=='complete';$('#lp-step-label').innerHTML=['Vyber','Vysvětli','Objev'].map((s,i)=>(i?'<span>→</span>':'')+(i===['choose','reflect','complete'].indexOf(state.phase)?'<strong>':'<span>')+'0'+(i+1)+' '+s+(i===['choose','reflect','complete'].indexOf(state.phase)?'</strong>':'</span>')).join('');
 $('#lp-reflection-summary').textContent='Všechna tři vylepšení stojí '+12*m+' žetonů. Městečko má '+10*m+'.';$('#lp-takeaway').textContent='Tvoje volba stála '+cost()*m+' žetonů. Zbývajících '+remaining+' může městečko ponechat na později. Někdo jiný by mohl vybrat jinak. Dokážeš vysvětlit, komu tvoje volba pomůže?';
 $$('[data-answer]').forEach(n=>n.setAttribute('aria-pressed',String(state.answer===n.dataset.answer)));$('#lp-feedback').textContent=state.answer==='finite'?'Přesně. Když máme omezené prostředky, vybíráme, co uděláme teď a co odložíme.':state.answer==='wrong'?'Jiné priority nejsou chyba. Podívej se na počet žetonů: stačí na všechna tři vylepšení?':'';$('#lp-finish').hidden=state.answer!=='finite';icons();drawAll();if(focusedUpgrade)$$('[data-upgrade]').find(button=>button.dataset.upgrade===focusedUpgrade)?.focus();}
 $('#lp-lesson-cards').innerHTML=lessons.map((l,i)=>'<button class="lp-lesson-card" type="button" data-lesson="'+i+'"><span class="lp-card-top"><span class="lp-card-icon">'+icon(l.icon)+'</span><span>0'+(i+1)+'</span></span><strong>'+l.title+'</strong><p>'+l.goal+'</p><footer><span>'+l.skill+'</span><span>'+(i===0?'Vyzkoušet ↗':'Návrh →')+'</span></footer></button>').join('');
 $('#lp-percent').addEventListener('change',e=>{state.percent=e.target.checked;render();save()});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.go){go(b.dataset.go);return}if(b.dataset.level){setLevel(b.dataset.level);return}if(b.dataset.view){state.view=b.dataset.view;render();save();return}if(b.dataset.age){state.age=b.dataset.age;render();save();return}if(b.dataset.lesson){state.detail=Number(b.dataset.lesson);go(state.detail===0?'lesson':'detail');return}if(b.dataset.upgrade){const id=b.dataset.upgrade;state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):[...state.selected,id];render();save();const scene=$('#lp-town-view');scene.classList.remove('lp-town-pop');void scene.offsetWidth;scene.classList.add('lp-town-pop');return}if(b.dataset.answer){state.answer=b.dataset.answer;render();save();return}if(b.id==='lp-confirm')state.phase='reflect';if(b.id==='lp-finish')state.phase='complete';if(b.id==='lp-rethink'||b.id==='lp-again'){state.phase='choose';state.answer=null}render();save()});
 function drawAll(){ $$('.lp-town').forEach(canvas=>{if(canvas.closest('[hidden]'))return;drawTown(canvas)}) }
 function drawTown(canvas){const r=canvas.getBoundingClientRect();if(!r.width)return;const d=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);const ctx=canvas.getContext('2d');ctx.scale(d,d);const w=r.width,h=r.height,s=Math.min(w/650,h/490);ctx.translate(w/2,h*.44);ctx.scale(s,s);const css=getComputedStyle(root),dark=matchMedia('(prefers-color-scheme:dark)').matches;const P={ink:dark?'#e8ecdb':'#343d26',roof:dark?'#b6ce74':'#a8c468',roofSide:dark?'#859e55':'#809e50',coral:dark?'#e59d8e':'#e58d7d',lilac:dark?'#b4a3db':'#b5a4db',blue:dark?'#8db9d0':'#83b8d2',honey:dark?'#eec366':'#ffd875',wall:dark?'#ccc5b0':'#fffbef',side:dark?'#9b9685':'#d5cfbc',ground:dark?'#667451':'#dce4ba',edge:dark?'#455436':'#b5c78c',road:dark?'#40484b':'#f9efd8',window:dark?'#4b5e64':'#56777f',muted:dark?'#59634b':'#ccd0bf',line:dark?'#778266':'#b4bb9f',accent:'#a8b63f'};const chosen=canvas.dataset.scene==='lesson'?state.selected:['books','park','bus'];const flat=options.scene==='quiet';
 const iso=(x,y,z=0)=>[(x-y)*.88,(x+y)*.45-z];
 function poly(points,color){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=color;ctx.fill()}
 function line(points,color,width=1){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineJoin='round';ctx.stroke()}
 function tile(x,y,a,b,color,z=0){poly([iso(x,y,z),iso(x+a,y,z),iso(x+a,y+b,z),iso(x,y+b,z)],color)}
 function box(x,y,a,b,z,color=P.wall,top=P.roof){const pts=[iso(x,y),iso(x+a,y),iso(x+a,y+b),iso(x,y+b)],tops=[iso(x,y,z),iso(x+a,y,z),iso(x+a,y+b,z),iso(x,y+b,z)];poly([pts[1],pts[2],tops[2],tops[1]],P.side);poly([pts[2],pts[3],tops[3],tops[2]],color);poly(tops,top)}
 function disk(x,y,z,rad,color){const p=iso(x,y,z);ctx.beginPath();ctx.ellipse(p[0],p[1],rad,rad*.62,0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill()}
 function sphere(x,y,z,rad,color){const p=iso(x,y,z);ctx.beginPath();ctx.ellipse(p[0],p[1],rad,rad,0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill()}
 function tree(x,y,size=1){disk(x+8,y+4,0,15*size,P.edge);box(x-2,y-2,4,4,22*size,P.side,P.side);sphere(x,y,31*size,15*size,P.roofSide);sphere(x-4,y-2,37*size,12*size,P.roof)}
 function building(x,y,a,b,z,active=true,type='home'){tile(x+9,y+10,a+7,b+4,P.edge);box(x,y,a,b,z,P.wall,active?(type==='school'?P.coral:type==='library'?P.lilac:P.blue):P.muted);box(x+3,y+3,a-6,b-6,4,P.side,active?P.roof:P.muted);for(let col=0;col<Math.floor(a/19);col++){let xx=x+8+col*18;poly([iso(xx,y+b+.3,z-13),iso(xx+8,y+b+.3,z-13),iso(xx+8,y+b+.3,z-23),iso(xx,y+b+.3,z-23)],P.window);if(z>57)poly([iso(xx,y+b+.3,z-34),iso(xx+8,y+b+.3,z-34),iso(xx+8,y+b+.3,z-44),iso(xx,y+b+.3,z-44)],P.window)}for(let col=0;col<Math.floor(b/20);col++){let yy=y+7+col*20;poly([iso(x+a+.3,yy,z-13),iso(x+a+.3,yy+8,z-13),iso(x+a+.3,yy+8,z-23),iso(x+a+.3,yy,z-23)],P.window)}poly([iso(x+a*.43,y+b+.6,0),iso(x+a*.6,y+b+.6,0),iso(x+a*.6,y+b+.6,23),iso(x+a*.43,y+b+.6,23)],P.ink);if(type==='school'){box(x+a*.38,y+b*.15,a*.27,b*.3,z+27,P.wall,active?P.coral:P.muted);let c=iso(x+a*.52,y+b*.46,z+15);ctx.beginPath();ctx.arc(c[0],c[1],6,0,Math.PI*2);ctx.fillStyle=P.wall;ctx.fill();line([[c[0],c[1]-4],[c[0],c[1]],[c[0]+3,c[1]]],P.ink,1.3)}if(type==='library'&&active){for(let i=0;i<5;i++)box(x+10+i*10,y+b+7,6,9,9+i%2*3,P.wall,P.roof)} }
 ctx.save();ctx.shadowColor='rgba(23,25,24,.13)';ctx.shadowBlur=20;ctx.shadowOffsetY=18;tile(-170,-118,330,316,P.ground);ctx.restore();poly([iso(-170,198),iso(160,198),iso(160,198,-12),iso(-170,198,-12)],P.edge);poly([iso(160,-118),iso(160,198),iso(160,198,-12),iso(160,-118,-12)],P.line);
 tile(-170,18,330,36,P.road);tile(-22,-118,35,316,P.road);for(let i=-152;i<140;i+=25)tile(i,34,10,2,P.line);for(let i=-107;i<180;i+=25)tile(-6,i,2,10,P.line);
 tile(-151,-95,106,95,P.edge);tile(30,-99,109,95,P.edge);tile(-148,72,109,100,P.edge);tile(35,76,103,105,P.edge);
 if(!flat){tree(-153,-106,.95);tree(133,-111,.8);tree(-164,6,.65)}building(-134,-92,70,65,72,true,'school');building(43,-95,70,60,55,chosen.includes('books'),'library');
 tree(125,-42,.75);tree(141,13,.65);tree(-144,66,.75);building(-130,89,61,60,46,true);building(-156,148,29,26,39,false);
 const parkActive=chosen.includes('park');tile(37,77,101,103,parkActive?P.roof:P.ground);tile(81,77,12,103,P.road);tile(37,122,101,9,P.road);tree(54,95,parkActive?1.05:.8);tree(122,91,parkActive?1:.7);tree(119,157,parkActive?.9:.65);if(parkActive){box(49,143,28,5,10,P.wall,P.wall);box(55,139,3,4,26,P.ink,P.ink);box(75,139,3,4,26,P.ink,P.ink);line([iso(57,141,26),iso(78,141,26)],P.ink,3);line([iso(66,141,25),iso(66,141,10)],P.ink,1.3);box(58,155,19,6,4,P.wall,P.wall)}
 const busX=chosen.includes('bus')?48:89;box(busX,22,44,21,22,P.wall,chosen.includes('bus')?P.honey:P.muted);for(let i=0;i<4;i++)poly([iso(busX+4+i*10,43.2,17),iso(busX+11+i*10,43.2,17),iso(busX+11+i*10,43.2,9),iso(busX+4+i*10,43.2,9)],P.window);for(const off of [9,35]){let p=iso(busX+off,43,1);ctx.beginPath();ctx.ellipse(p[0],p[1],5,6,0,0,Math.PI*2);ctx.fillStyle=P.ink;ctx.fill();}
 if(!flat){for(const p of [[-40,51],[-28,76],[20,82],[19,-36],[-106,60]]){sphere(p[0],p[1],10,3,P.ink);const q=iso(p[0],p[1],6);line([[q[0],q[1]],[q[0],q[1]+7]],P.ink,3)}}
 function sign(text,x,y,z,active){if(w<390)return;const p=iso(x,y,z),fs=Math.max(12,11/s),hs=Math.max(25,24/s);ctx.font='600 '+fs+'px "DM Sans", sans-serif';const sw=ctx.measureText(text).width+18/s;ctx.fillStyle=active?P.ink:getComputedStyle($('.lp-header')).backgroundColor;if(ctx.fillStyle.includes('light-dark'))ctx.fillStyle=dark?'#292d27':'#faf7ef';ctx.beginPath();ctx.roundRect(p[0]-sw/2,p[1]-hs/2,sw,hs,hs/2);ctx.fill();ctx.fillStyle=active?(dark?'#171918':'#faf7ef'):P.ink;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,p[0],p[1]);}
 sign('ŠKOLA',-94,-69,112,false);sign(chosen.includes('books')?'NOVÉ KNÍŽKY':'KNIHOVNA',78,-67,88,chosen.includes('books'));sign(chosen.includes('park')?'NOVÉ HŘIŠTĚ':'PARK',103,146,-15,chosen.includes('park'));if(chosen.includes('bus'))sign('DALŠÍ SPOJ',75,34,48,true);
 }
 let restored=window.openai?.widgetState;if(!restored){try{restored=JSON.parse(sessionStorage.getItem('psd-learn-preview-v2'))}catch{/* Storage is optional. */}}applySaved(restored);render();const ro=new ResizeObserver(drawAll);ro.observe(root);matchMedia('(prefers-color-scheme:dark)').addEventListener('change',drawAll);document.fonts?.ready.then(drawAll);window.addEventListener('openai:set_globals',event=>{if(event.detail?.globals?.widgetState){applySaved(event.detail.globals.widgetState);render()}});
 if(window.Tweak){const tweak=new window.Tweak({container:root,onChange:render});tweak.addSlider(options,'corners',{label:'Zaoblení panelů',min:8,max:32,step:4,unit:'px'});tweak.addSelect(options,'scene',{label:'Detail městečka',options:[{label:'Papírové městečko',value:'paper'},{label:'Klidnější scéna',value:'quiet'}]})}
})();
