// Editorial institutional maps, not measured flows. Each route has its own evidence.
export const reviewed = '2026-09-19';
export const tr = (en, cs) => ({ en, cs });
const route = (id, label, nodes, note, sources, partial = false) => ({ id, label, nodes, note, sources, partial });
const n = (en, cs) => tr(en, cs);
export const sources = {
  czSchool: { title: 'MŠMT · school operating finance from 2026', url: 'https://edu.gov.cz/pro-zrizovatele/provoz-skol/nepedagogicka-cinnost/', vintage: '2026' },
  czTeaching: { title: 'MŠMT · regional school funding', url: 'https://msmt.gov.cz/fin-leg/financovani-regionalniho-skolstvi/reforma-financovani-regionalniho-skolstvi', vintage: '2026' },
  czPool: { title: 'VZP · collection and risk redistribution', url: 'https://www.vzp.cz/platci/informace/stat/splatnost-a-prerozdelovani-pojistneho', vintage: 'Web guidance' },
  czHealth: { title: 'WHO / European Observatory · Czechia', url: 'https://eurohealthobservatory.who.int/publications/i/czechia-health-system-summary-2024', vintage: '2024 review' },
  czBudget: { title: 'MF ČR · state budget and local accounts', url: 'https://monitor.statnipokladna.gov.cz/metodika', vintage: 'Methodology' },
  usSchool: { title: 'US Department of Education · federal role', url: 'https://www.ed.gov/about/ed-overview/federal-role-in-education', vintage: 'Institutional guidance; historical figures not used' },
  usMedicare: { title: 'Medicare · trust funds and funding sources', url: 'https://www.medicare.gov/about-us/how-is-medicare-funded', vintage: '2024 accounts / web guidance' },
  usMedicaid: { title: 'CMS · Medicaid managed care', url: 'https://www.medicaid.gov/medicaid/managed-care', vintage: 'Web guidance' },
  usBudget: { title: 'US Treasury · federal revenue', url: 'https://fiscaldata.treasury.gov/americas-finance-guide/government-revenue/', vintage: 'Web guidance' },
  usHealth: { title: 'WHO / European Observatory · United States', url: 'https://eurohealthobservatory.who.int/countries/united-states-of-america', vintage: 'Country overview' },
  frSchool: { title: 'Education nationale · state and local responsibilities', url: 'https://www.education.gouv.fr/le-role-des-collectivites-territoriales-dans-le-service-public-de-l-education-et-le-partenariat-avec-8138', vintage: '2026 guidance' },
  frCollection: { title: 'Urssaf · CSG and social protection', url: 'https://www.urssaf.fr/accueil/employeur/cotisations/liste-cotisations/csg-crds.html', vintage: '2026-02-12' },
  frHealth: { title: 'WHO / European Observatory · France', url: 'https://eurohealthobservatory.who.int/publications/i/france-health-system-summary-2024-%28updated%29', vintage: '2024 review' },
  frBudget: { title: 'French Ministry of Economy · public budgets', url: 'https://www.economie.gouv.fr/dette-publique-budget-impot?language=fr', vintage: 'Web guidance' },
  ruSchool: { title: 'Russian government · regional education subventions', url: 'https://government.ru/docs/all/138399/?page=9', vintage: 'Legal framework; current implementation not independently verified' },
  ruInsurance: { title: 'Russian government · compulsory insurance law 326-FZ', url: 'https://government.ru/docs/all/99737/', vintage: 'Legal framework; amendments and regional practice may differ' },
  ruHealth: { title: 'WHO / European Observatory · Russian Federation', url: 'https://eurohealthobservatory.who.int/countries/russian-federation', vintage: 'Country overview; underlying full review 2011' },
  ruBudget: { title: 'Russian government · federal budget execution 2024', url: 'https://government.ru/docs/all/160232/', vintage: '2024 outturn, published 2025' },
  uaSchool: { title: 'Ukraine Ministry of Education · 2026 teacher funding', url: 'https://mon.gov.ua/news/zapuskaiemo-hariachu-liniiu-dlia-konsultatsii-hromad-shchodo-vyplaty-zarplat-pedahoham-u-shkolakh-u-2026-rotsi', vintage: '2026-01-26' },
  uaHealth: { title: 'WHO / European Observatory · Ukraine', url: 'https://eurohealthobservatory.who.int/publications/i/health-systems-in-action-ukraine-2024', vintage: '2024 review' },
  uaSupport: { title: 'Ukraine Ministry of Finance · external support', url: 'https://mof.gov.ua/en/news/the_ministry_of_finance_of_ukraine_attracted_417_billion_in_external_financing_including_30_in_the_form_of_grants-4972', vintage: '2024 outturn' },
  uaLocal: { title: 'Ukraine Ministry of Finance · local budgets', url: 'https://openbudget.gov.ua/en/local-budget', vintage: 'Budget portal' },
};
const taxes = n('People & businesses', 'Lidé a firmy');
const providers = n('Hospitals, doctors & pharmacies', 'Nemocnice, lékaři a lékárny');
const schoolEnd = n('School → teachers & pupils', 'Škola → učitelé a žáci');
const patient = n('Households', 'Domácnosti');
const lenders = n('Bond buyers & lenders', 'Kupci dluhopisů a věřitelé');
export const countries = [
  {
    code: 'CZE', flag: 'cz', name: n('Czechia', 'Česko'),
    headline: n('The state pays for teaching. The founder keeps the school running.', 'Stát platí výuku. Zřizovatel zajišťuje chod školy.'),
    summary: n('National taxes, local budgets and public health insurance are separate pools linked by transfers.', 'Státní daně, místní rozpočty a veřejné zdravotní pojištění tvoří oddělené rozpočty propojené transfery.'),
    gap: n('Routes are mapped; the amounts at each hand-off are not reconciled. The 2026 school reform is included.', 'Cesty jsou zmapovány; částky při každém převodu nejsou účetně sladěny. Mapa zahrnuje změnu financování škol od roku 2026.'),
    compare: {
      funding: [n('Taxes + compulsory contributions', 'Daně + povinné pojistné'), n('State, municipalities, regions, insurance funds', 'Stát, obce, kraje, pojišťovny'), n('Shared taxes + transfers', 'Sdílené daně + transfery')],
      schools: [n('MŠMT → regional offices → schools', 'MŠMT → krajské úřady → školy'), n('Municipality / region as founder', 'Obec / kraj jako zřizovatel'), n('Teaching allocation + founder contribution', 'Rozpis na výuku + příspěvek zřizovatele')],
      health: [n('Compulsory health insurance', 'Veřejné zdravotní pojištění'), n('Risk redistribution → health insurers', 'Přerozdělení rizik → zdravotní pojišťovny'), n('Provider contracts; owner investment separately', 'Smluvní úhrady; investice vlastníka zvlášť')],
    },
    routes: {
      funding: [
        route('tax', n('Taxes become budgets', 'Daně se mění v rozpočty'), [taxes, n('Tax & customs authorities', 'Finanční a celní správa'), n('State / regional / municipal budgets', 'Státní / krajské / obecní rozpočty'), n('Services & transfers', 'Služby a transfery')], n('VAT and income taxes are shared under tax-allocation rules. Local own revenue does not first become state-budget spending.', 'DPH a daně z příjmů se dělí podle rozpočtového určení daní. Vlastní místní příjmy nejsou nejprve výdajem státního rozpočtu.'), ['czBudget']),
        route('insurance', n('A separate route for insurance', 'Samostatná cesta pojistného'), [n('Workers, employers & self-employed', 'Zaměstnanci, zaměstnavatelé a OSVČ'), n('Social insurance / health insurance', 'Sociální / zdravotní pojištění'), n('State budget / health insurers', 'Státní rozpočet / zdravotní pojišťovny'), n('Pensions & care', 'Důchody a péče')], n('These are two different channels: social insurance enters the state budget; health contributions enter public health insurance.', 'Jde o dva různé kanály: sociální pojistné vstupuje do státního rozpočtu, zdravotní pojistné do veřejného zdravotního pojištění.'), ['czBudget', 'czPool']),
        route('finance', n('Covering the gap', 'Pokrytí schodku'), [lenders, n('Ministry of Finance / Treasury', 'Ministerstvo financí / pokladna'), n('Budget financing', 'Financování rozpočtu')], n('Borrowing finances a deficit and refinancing replaces maturing debt. Neither is tax revenue. EU grants and other receipts also support the budget.', 'Půjčky financují schodek a refinancování nahrazuje splatný dluh. Nejde o daňové příjmy. Rozpočet podporují i dotace EU a další příjmy.'), ['czBudget']),
      ],
      schools: [
        route('teaching', n('Teaching & teacher pay', 'Výuka a platy učitelů'), [n('State budget', 'Státní rozpočet'), n('Education ministry · MŠMT', 'Ministerstvo školství · MŠMT'), n('Regional office · allocation', 'Krajský úřad · rozpis'), schoolEnd], n('For ordinary municipal and regional schools, the ministry sets teaching funding and regional offices distribute it. The school pays its staff.', 'U běžných obecních a krajských škol stanovuje financování výuky ministerstvo a krajské úřady je rozepisují. Škola vyplácí zaměstnance.'), ['czTeaching']),
        route('operations', n('Buildings, support staff & daily operation', 'Budovy, nepedagogové a provoz'), [n('Shared taxes & local revenue', 'Sdílené daně a místní příjmy'), n('Municipality / region · founder', 'Obec / kraj · zřizovatel'), n('School budget / shared services', 'Rozpočet školy / sdílené služby'), n('Support staff, heating & buildings', 'Nepedagogové, vytápění a budovy')], n('From January 2026, founders fund non-teaching work and most other non-investment costs, alongside operations and investment. Municipalities usually found primary schools; regions usually found secondary schools.', 'Od ledna 2026 financují zřizovatelé nepedagogickou práci a většinu ONIV vedle provozu a investic. Obce obvykle zřizují základní školy, kraje střední školy.'), ['czSchool']),
      ],
      health: [
        route('care', n('The main care-payment route', 'Hlavní cesta úhrad péče'), [n('Health contributions + state payments', 'Zdravotní pojistné + platby státu'), n('Risk redistribution pool', 'Přerozdělení podle rizika'), n('Health insurers · VZP and others', 'Zdravotní pojišťovny · VZP a další'), providers], n('The state pays contributions for eligible groups such as children and pensioners. Redistribution reflects insured risks; insurers contract and reimburse care. The Ministry of Health is not the routine payer of every hospital bill.', 'Stát platí za vymezené skupiny, například děti a důchodce. Přerozdělení zohledňuje rizika pojištěnců; pojišťovny sjednávají a hradí péči. Ministerstvo zdravotnictví běžně neplatí každou fakturu nemocnice.'), ['czPool', 'czHealth']),
        route('capital', n('Buildings & equipment', 'Budovy a vybavení'), [n('State, region, municipality / EU grants', 'Stát, kraj, obec / dotace EU'), n('Owner / investment programme', 'Vlastník / investiční program'), n('Hospital investment', 'Investice nemocnice')], n('Ownership and payment for treatment are separate roles. Grants and owner contributions can support investment in addition to provider resources.', 'Vlastnictví a placení léčby jsou různé role. Dotace a příspěvky vlastníků mohou doplňovat vlastní zdroje poskytovatele na investice.'), ['czHealth']),
        route('private', n('Direct household spending', 'Přímé výdaje domácností'), [patient, n('Co-payments & uncovered services', 'Doplatky a nehrazené služby'), providers], n('Households also pay directly, including for medicines and some dental services. This is outside the state budget.', 'Domácnosti platí i přímo, například za léky a některé zubní služby. Tyto platby jsou mimo státní rozpočet.'), ['czHealth']),
      ],
    },
  },
  {
    code: 'USA', flag: 'us', name: n('United States', 'USA'),
    headline: n('A school district pools the money. Healthcare has several payers.', 'Peníze škol sdružuje školský obvod. Zdravotnictví má více plátců.'),
    summary: n('Federal, state and local governments raise their own revenue. A federal budget alone misses much of school funding.', 'Federace, státy a samosprávy vybírají vlastní příjmy. Samotný federální rozpočet velkou část financování škol nezachycuje.'),
    gap: n('A typical public K–12 route is shown. State formulas, districts, charter schools and insurance contracts vary; no single national flow split is assumed.', 'Zobrazena je typická cesta veřejných škol K–12. Pravidla států, obvodů, charterových škol i pojistné smlouvy se liší; jednotné celostátní podíly nepředpokládáme.'),
    compare: {
      funding: [n('Federal + state + local taxes', 'Federální, státní a místní daně'), n('Separate budgets and programme funds', 'Samostatné rozpočty a programové fondy'), n('Federal grants + state equalisation', 'Federální dotace + vyrovnávání mezi obvody')],
      schools: [n('State aid + local taxes + federal grants', 'Státní podpora + místní daně + federální dotace'), n('Local school district', 'Místní školský obvod'), n('District payroll, allocations & procurement', 'Mzdy, příděly a nákupy školského obvodu')],
      health: [n('Taxes, premiums & household payments', 'Daně, pojistné a platby domácností'), n('CMS, state Medicaid agencies, private plans', 'CMS, státní agentury Medicaid, soukromé plány'), n('Mixed public and private contracts', 'Veřejné i soukromé smluvní úhrady')],
    },
    routes: {
      funding: [
        route('tax', n('Several governments collect revenue', 'Příjmy vybírá více úrovní vlády'), [taxes, n('IRS / state & local tax authorities', 'IRS / státní a místní daňové úřady'), n('Federal / state / local budgets', 'Federální / státní / místní rozpočty'), n('Programmes & intergovernmental grants', 'Programy a mezivládní dotace')], n('Income and payroll taxes are major federal sources. State and local systems also use sales, income and property taxes, with different mixes across states.', 'Hlavní federální zdroje zahrnují daně z příjmů a mzdové odvody. Státy a samosprávy využívají i daně z prodeje, příjmů a nemovitostí; jejich mix se liší.'), ['usBudget', 'usSchool']),
        route('finance', n('Federal borrowing', 'Federální půjčky'), [lenders, n('US Treasury · securities', 'Ministerstvo financí · dluhopisy'), n('Federal financing', 'Federální financování')], n('Treasury borrowing covers financing needs, including deficits and maturing debt. It is separate from revenue; state and local borrowing has its own rules.', 'Půjčky ministerstva financí pokrývají financování včetně schodků a splatného dluhu. Jsou oddělené od příjmů; dluh států a samospráv má vlastní pravidla.'), ['usBudget']),
      ],
      schools: [
        route('state', n('State education aid', 'Podpora školství ze států'), [n('State taxes', 'Daně členského státu'), n('State budget / education agency', 'Státní rozpočet / školská agentura'), n('School district', 'Školský obvod'), schoolEnd], n('States allocate aid using their own formulas. Districts pay teachers, buy services and allocate resources among schools.', 'Státy rozdělují podporu podle vlastních vzorců. Obvody platí učitele, nakupují služby a rozdělují zdroje mezi školy.'), ['usSchool']),
        route('local', n('Locally raised money', 'Místně vybrané peníze'), [n('Local taxpayers · often property tax', 'Místní poplatníci · často daň z nemovitostí'), n('Local government / school district', 'Samospráva / školský obvod'), n('School services & facilities', 'Školní služby a budovy')], n('Local revenue joins state aid in district budgets. A district can pay costs centrally, so money need not pass through a separate school bank account.', 'Místní příjmy doplňují státní podporu v rozpočtu obvodu. Obvod může platit náklady centrálně; peníze tedy nemusí projít samostatným účtem školy.'), ['usSchool']),
        route('federal', n('Targeted federal support', 'Cílená federální podpora'), [n('Federal budget', 'Federální rozpočet'), n('Federal programme → state agency', 'Federální program → státní agentura'), n('District / eligible recipient', 'Obvod / oprávněný příjemce'), n('Targeted pupil support', 'Cílená podpora žáků')], n('Examples include Title I and special-education grants. This is a common grant route, not a claim that every federal education programme follows it.', 'Příklady zahrnují Title I a dotace na speciální vzdělávání. Jde o obvyklou cestu dotací, nikoli pravidlo pro každý federální vzdělávací program.'), ['usSchool']),
      ],
      health: [
        route('medicare', n('Medicare · federal programme', 'Medicare · federální program'), [n('Payroll taxes, general revenue & premiums', 'Mzdové odvody, obecné příjmy a pojistné'), n('Treasury trust funds / CMS', 'Svěřenské fondy / CMS'), n('Claims contractors / Medicare plans', 'Správci úhrad / plány Medicare'), providers], n('Part A relies mainly on payroll taxes; Parts B and D use general revenue and premiums. Original Medicare and private Medicare plans use different payment channels.', 'Část A se opírá hlavně o mzdové odvody; části B a D o obecné příjmy a pojistné. Original Medicare a soukromé plány Medicare mají různé platební cesty.'), ['usMedicare']),
        route('medicaid', n('Medicaid · federal + state', 'Medicaid · federace + stát'), [n('Federal match + state funds', 'Federální spoluúčast + zdroje státu'), n('State Medicaid agency', 'Státní agentura Medicaid'), n('Managed-care plan / direct payment', 'Plán řízené péče / přímá úhrada'), providers], n('States can pay providers directly or pay managed-care organisations per enrolled member; those organisations then pay providers.', 'Státy mohou hradit poskytovatele přímo nebo platit organizacím řízené péče za pojištěnce; ty pak platí poskytovatelům.'), ['usMedicaid']),
        route('private', n('Employment & individual coverage', 'Zaměstnanecké a individuální krytí'), [n('Employers & households', 'Zaměstnavatelé a domácnosti'), n('Insurer / self-funded employer plan', 'Pojišťovna / samofinancovaný plán zaměstnavatele'), n('Provider payments + patient cost sharing', 'Úhrady poskytovatelům + spoluúčast pacienta')], n('Private coverage is a major parallel route. Households also pay deductibles and co-payments. Separate public systems, including veterans’ care, are outside these simplified lanes.', 'Soukromé krytí je významnou souběžnou cestou. Domácnosti hradí i spoluúčast. Další veřejné systémy včetně péče o veterány tyto zjednodušené cesty nezobrazují.'), ['usHealth']),
      ],
    },
  },
  {
    code: 'FRA', flag: 'fr', name: n('France', 'Francie'),
    headline: n('The teacher and the school building have different payers.', 'Učitele a školní budovu platí různí plátci.'),
    summary: n('State, social-security and local budgets form distinct parts of public finance. Health insurance sits alongside the state budget.', 'Státní rozpočet, sociální zabezpečení a místní rozpočty tvoří odlišné části veřejných financí. Zdravotní pojištění stojí vedle státního rozpočtu.'),
    gap: n('Main public-school and health routes are documented. Separate insurance schemes, private schools and regional exceptions are condensed.', 'Hlavní cesty veřejných škol a zdravotnictví jsou doloženy. Zvláštní pojistné režimy, soukromé školy a regionální výjimky jsou zjednodušeny.'),
    compare: {
      funding: [n('Taxes + social contributions + CSG', 'Daně + sociální odvody + CSG'), n('State, social security, local budgets', 'Stát, sociální zabezpečení, místní rozpočty'), n('Assigned taxes + transfers', 'Přidělené daně + transfery')],
      schools: [n('State pays public-school teachers', 'Učitele veřejných škol platí stát'), n('Commune / département / région', 'Obec / departement / region'), n('State payroll + local operating budgets', 'Státní mzdy + místní provozní rozpočty')],
      health: [n('Social contributions + earmarked taxes', 'Sociální odvody + účelové daně'), n('Assurance Maladie; ARS for regional allocations', 'Assurance Maladie; ARS pro regionální příděly'), n('Statutory reimbursements + complementary cover', 'Zákonné úhrady + doplňkové pojištění')],
    },
    routes: {
      funding: [
        route('budgets', n('Taxes across public budgets', 'Daně ve veřejných rozpočtech'), [taxes, n('Tax authorities', 'Daňová správa'), n('State & local budgets', 'Státní a místní rozpočty'), n('Services, payroll & transfers', 'Služby, mzdy a transfery')], n('Public finance includes both the state and local authorities. Transfers between them must be removed when adding up government spending.', 'Veřejné finance zahrnují stát i samosprávy. Při sčítání vládních výdajů je třeba vzájemné transfery vyloučit.'), ['frBudget']),
        route('social', n('The social-protection channel', 'Kanál sociální ochrany'), [n('Contributions & social tax · CSG', 'Pojistné a sociální daň · CSG'), n('Urssaf collection network', 'Výběr přes síť Urssaf'), n('Social-security branches', 'Odvětví sociálního zabezpečení'), n('Health, pensions & family benefits', 'Zdraví, důchody a rodinné dávky')], n('CSG helps fund social protection, including health. It is a tax, distinct from insurance contributions. Assigned taxes also contribute to social-security revenue.', 'CSG pomáhá financovat sociální ochranu včetně zdraví. Jde o daň, odlišnou od pojistného. K příjmům sociálního zabezpečení přispívají i přidělené daně.'), ['frCollection', 'frHealth']),
        route('finance', n('Borrowing', 'Půjčky'), [lenders, n('State debt issuance', 'Emise státního dluhu'), n('Budget financing', 'Financování rozpočtu')], n('Borrowing funds the financing requirement. It is not an additional tax or a receipt to add to consolidated revenue.', 'Půjčky pokrývají potřebu financování. Nejsou další daní ani položkou přičítanou ke konsolidovaným příjmům.'), ['frBudget']),
      ],
      schools: [
        route('teachers', n('Teacher salaries · directly from the state', 'Platy učitelů · přímo od státu'), [n('State taxes / budget', 'Státní daně / rozpočet'), n('Education ministry → académies', 'Ministerstvo školství → akademie'), n('State payroll', 'Státní výplata mezd'), n('Teachers in public schools', 'Učitelé veřejných škol')], n('The state recruits and pays teachers. The salary supports a school’s teaching without needing to enter the school’s own operating budget.', 'Stát přijímá a platí učitele. Plat financuje výuku školy, aniž by musel vstoupit do jejího vlastního provozního rozpočtu.'), ['frSchool']),
        route('buildings', n('Buildings & operation · by school level', 'Budovy a provoz · podle stupně školy'), [n('Local taxes & state transfers', 'Místní daně a státní transfery'), n('Commune / département / région', 'Obec / departement / region'), n('Primary school / collège / lycée', 'Základní stupeň / collège / lycée'), n('Buildings, equipment & support services', 'Budovy, vybavení a podpůrné služby')], n('Communes fund primary-school premises; départements fund collèges; régions fund lycées. Local authorities also fund relevant technical and support staff.', 'Obce financují budovy základních škol, departementy collèges a regiony lycées. Samosprávy financují i příslušné technické a podpůrné pracovníky.'), ['frSchool']),
      ],
      health: [
        route('care', n('Statutory health coverage', 'Zákonné zdravotní krytí'), [n('Contributions, CSG & assigned taxes', 'Pojistné, CSG a přidělené daně'), n('Assurance Maladie · national pooling', 'Assurance Maladie · celostátní sdružení'), n('Payment funds · including CPAM', 'Platební fondy · včetně CPAM'), providers], n('Statutory health insurance reimburses covered care. Some payments reimburse the patient after an upfront payment; others go directly to the provider.', 'Zákonné zdravotní pojištění hradí krytou péči. Část plateb vrací pacientovi výdaj zaplacený předem, jiné jdou přímo poskytovateli.'), ['frCollection', 'frHealth']),
        route('regional', n('Regional allocations & planning', 'Regionální příděly a plánování'), [n('National health envelopes', 'Celostátní zdravotní prostředky'), n('Regional health agencies · ARS', 'Regionální zdravotní agentury · ARS'), n('Facilities & regional programmes', 'Zařízení a regionální programy')], n('ARS plan provision and allocate selected envelopes. They are not a compulsory extra payment stop for every insurance claim.', 'ARS plánují péči a přidělují vybrané prostředky. Nejsou povinným platebním mezičlánkem každé pojistné úhrady.'), ['frHealth']),
        route('private', n('The remaining bill', 'Zbývající část účtu'), [n('Households / employer premiums', 'Domácnosti / pojistné zaměstnavatelů'), n('Complementary insurers + direct payments', 'Doplňkové pojišťovny + přímé platby'), n('Patient cost sharing', 'Spoluúčast pacienta')], n('Complementary cover pays part of the remaining costs; some spending still falls on households.', 'Doplňkové pojištění hradí část zbývajících nákladů; některé výdaje zůstávají domácnostem.'), ['frHealth']),
      ],
    },
  },
  {
    code: 'RUS', flag: 'ru', name: n('Russia', 'Rusko'),
    headline: n('Regions bridge the centre and local schools. Health uses insurance funds.', 'Regiony propojují centrum a místní školy. Zdravotnictví využívá pojistné fondy.'),
    summary: n('A structural map of federal, regional and local budgets plus compulsory medical insurance. Current implementation is less well verified.', 'Strukturální mapa federálních, regionálních a místních rozpočtů a povinného zdravotního pojištění. Současná praxe je ověřena méně podrobně.'),
    gap: n('Partial evidence: legal routes and an older WHO review support this outline. Current regional execution, recent amendments and classified spending are not reconstructed. No transfer shares are invented.', 'Částečné doložení: přehled vychází z právního rámce a starší zprávy WHO. Nezachycuje současné regionální plnění, poslední novely ani utajené výdaje. Podíly transferů nejsou domýšleny.'),
    compare: {
      funding: [n('Taxes, resource revenues & contributions', 'Daně, příjmy ze surovin a pojistné'), n('Federal / regional / local budgets + funds', 'Federální / regionální / místní rozpočty + fondy'), n('Tax assignments + federal transfers', 'Rozdělení daní + federální transfery')],
      schools: [n('Regional teaching subventions', 'Regionální subvence na výuku'), n('Region → municipality / founder', 'Region → obec / zřizovatel'), n('School allocations; local premises costs', 'Příděly školám; místní náklady na budovy')],
      health: [n('Contributions + budget payments', 'Pojistné + rozpočtové platby'), n('Federal → territorial funds → insurers', 'Federální → územní fondy → pojišťovny'), n('Insurance contracts + budget-funded services', 'Pojistné smlouvy + rozpočtově hrazené služby')],
    },
    routes: {
      funding: [
        route('tax', n('Taxes & resource receipts', 'Daně a příjmy ze surovin'), [n('Households, firms & resource sector', 'Domácnosti, firmy a surovinový sektor'), n('Tax / customs collection', 'Daňová / celní správa'), n('Federal & subnational budgets', 'Federální a územní rozpočty'), n('Services & regional transfers', 'Služby a regionální transfery')], n('Oil and gas fiscal receipts sit alongside other taxes. Company sales are not government revenue; only taxes and remitted payments enter budgets.', 'Rozpočtové příjmy z ropy a plynu doplňují ostatní daně. Tržby podniků nejsou vládní příjmy; do rozpočtů vstupují daně a skutečné odvody.'), ['ruBudget'], true),
        route('finance', n('Financing beyond revenue', 'Financování nad rámec příjmů'), [n('Lenders / fiscal reserves', 'Věřitelé / fiskální rezervy'), n('Federal financing operations', 'Federální finanční operace'), n('Budget cash needs', 'Hotovostní potřeby rozpočtu')], n('Borrowing and reserve use are financing operations. This map does not estimate their current shares or the undisclosed expenditure mix.', 'Půjčky a použití rezerv jsou finanční operace. Mapa neodhaduje jejich současné podíly ani skladbu nezveřejněných výdajů.'), ['ruBudget'], true),
      ],
      schools: [
        route('teaching', n('General education · regional funding', 'Všeobecné vzdělávání · regionální financování'), [n('Regional budget + federal transfers', 'Regionální rozpočet + federální transfery'), n('Regional education allocation', 'Regionální příděl na školství'), n('Municipality · earmarked subvention', 'Obec · účelová subvence'), schoolEnd], n('The legal framework assigns regions funding for core programmes, including pay and teaching materials, through subventions to municipalities. Some schools are directly regional or federal.', 'Právní rámec svěřuje regionům financování základních programů včetně platů a pomůcek prostřednictvím subvencí obcím. Některé školy jsou přímo regionální či federální.'), ['ruSchool'], true),
        route('operations', n('Premises & utilities', 'Budovy a energie'), [n('Local budget', 'Místní rozpočet'), n('Municipal founder', 'Obecní zřizovatel'), n('School buildings & utilities', 'Školní budovy a energie')], n('Building maintenance and utilities are distinguished from regional teaching subventions. Co-financing and regional arrangements can add further routes.', 'Údržba budov a energie jsou odlišeny od regionálních subvencí na výuku. Spolufinancování a regionální pravidla mohou přidávat další cesty.'), ['ruSchool'], true),
      ],
      health: [
        route('insurance', n('Compulsory medical insurance · OMS', 'Povinné zdravotní pojištění · OMS'), [n('Employer contributions + budget payments', 'Odvody zaměstnavatelů + rozpočtové platby'), n('Federal OMS fund', 'Federální fond OMS'), n('Territorial OMS funds', 'Územní fondy OMS'), n('Insurance organisations → providers', 'Pojišťovací organizace → poskytovatelé')], n('The standard territorial route uses funds and insurance organisations to pay contracted care. Federal providers and other exceptions can follow different routes; current exceptions are not fully mapped.', 'Standardní územní cesta využívá fondy a pojišťovací organizace k úhradě smluvní péče. Federální zařízení a další výjimky mohou mít jiné cesty; současné výjimky nejsou plně zmapovány.'), ['ruInsurance', 'ruHealth'], true),
        route('budget', n('Care outside the standard insurance route', 'Péče mimo standardní pojistnou cestu'), [n('Federal / regional budgets', 'Federální / regionální rozpočty'), n('Health authorities / owners', 'Zdravotní úřady / vlastníci'), n('Facilities, capital & specific services', 'Zařízení, investice a zvláštní služby')], n('Budget channels coexist with compulsory insurance. Public ownership does not mean all running costs are paid from one ministry budget.', 'Rozpočtové kanály existují vedle povinného pojištění. Veřejné vlastnictví neznamená, že všechny provozní výdaje platí jeden resort.'), ['ruHealth'], true),
        route('private', n('Private spending', 'Soukromé výdaje'), [patient, n('Direct payment / voluntary insurance', 'Přímá platba / dobrovolné pojištění'), providers], n('Legal entitlement to care does not eliminate private spending or differences in access between regions.', 'Právní nárok na péči neodstraňuje soukromé výdaje ani rozdíly v dostupnosti mezi regiony.'), ['ruHealth'], true),
      ],
    },
  },
  {
    code: 'UKR', flag: 'ua', name: n('Ukraine', 'Ukrajina'),
    headline: n('Teachers through local budgets. Care through a national purchaser.', 'Učitelé přes místní rozpočty. Péče přes celostátního plátce.'),
    summary: n('Domestic revenue and international support sustain public services during war. Grants and loans have different accounting roles.', 'Domácí příjmy a mezinárodní podpora udržují veřejné služby během války. Dotace a půjčky mají odlišnou účetní roli.'),
    gap: n('Wartime routes are simplified. Displacement, occupied areas, damaged facilities and donor projects limit like-for-like comparison; pre-war health spending is not presented as current.', 'Válečné cesty jsou zjednodušeny. Vysídlení, okupovaná území, poškozená zařízení a projekty dárců omezují srovnatelnost; předválečné zdravotní výdaje nejsou vydávány za současné.'),
    compare: {
      funding: [n('Domestic taxes + grants; loans as financing', 'Domácí daně + dotace; půjčky jako financování'), n('State Treasury, local budgets, social funds', 'Státní pokladna, místní rozpočty, sociální fondy'), n('Subventions + international budget support', 'Subvence + mezinárodní rozpočtová podpora')],
      schools: [n('State education subvention', 'Státní vzdělávací subvence'), n('Local budget → education authority / school', 'Místní rozpočet → školský úřad / škola'), n('Teacher payroll + local operations', 'Platy učitelů + místní provoz')],
      health: [n('General taxation / state budget', 'Obecné daně / státní rozpočet'), n('National Health Service · NHSU', 'Národní zdravotní služba · NHSU'), n('Provider contracts; local ownership separately', 'Smlouvy s poskytovateli; místní vlastnictví zvlášť')],
    },
    routes: {
      funding: [
        route('tax', n('Domestic public revenue', 'Domácí veřejné příjmy'), [taxes, n('Tax & customs authorities', 'Daňová a celní správa'), n('State / local budgets & social funds', 'Státní / místní rozpočty a sociální fondy'), n('Public services & transfers', 'Veřejné služby a transfery')], n('State and local budgets are separate. Shared tax receipts and intergovernmental transfers help fund local responsibilities.', 'Státní a místní rozpočty jsou oddělené. Sdílené daňové příjmy a mezivládní transfery pomáhají financovat místní úkoly.'), ['uaLocal']),
        route('support', n('International grants', 'Mezinárodní dotace'), [n('Partner governments / institutions', 'Partnerské vlády / instituce'), n('Budget support programmes', 'Programy rozpočtové podpory'), n('State budget · grant revenue', 'Státní rozpočet · dotační příjmy'), n('Eligible public spending', 'Způsobilé veřejné výdaje')], n('Grants do not create a repayment obligation and are revenue. Some support reimburses spending already incurred; the map shows the funding relationship, not settlement order.', 'Dotace nevytvářejí povinnost splácení a jsou příjmem. Část podpory proplácí již vzniklé výdaje; mapa ukazuje vztah financování, ne pořadí vypořádání.'), ['uaSupport']),
        route('loans', n('Loans & domestic bonds', 'Půjčky a domácí dluhopisy'), [n('International lenders / bond buyers', 'Mezinárodní věřitelé / kupci dluhopisů'), n('Ministry of Finance / Treasury', 'Ministerstvo financí / pokladna'), n('Deficit & refinancing needs', 'Schodek a refinancování')], n('Concessional loans remain borrowing, even when offered by partners. Do not add them to grant revenue. In-kind aid and off-budget projects are separate.', 'Zvýhodněné půjčky zůstávají dluhem, i když je poskytují partneři. Nepřičítají se k dotačním příjmům. Věcná pomoc a mimorozpočtové projekty jsou samostatné.'), ['uaSupport']),
      ],
      schools: [
        route('teachers', n('Teacher pay · education subvention', 'Platy učitelů · vzdělávací subvence'), [n('State budget', 'Státní rozpočet'), n('Education subvention · formula allocation', 'Vzdělávací subvence · rozdělovací vzorec'), n('Local budget / education authority', 'Místní rozpočet / školský úřad'), schoolEnd], n('The state sends the education subvention to local budgets for pedagogical salaries. Local authorities distribute the allocation and organise payment.', 'Stát posílá vzdělávací subvenci do místních rozpočtů na pedagogické platy. Místní úřady příděl rozdělují a zajišťují výplaty.'), ['uaSchool']),
        route('operation', n('Local operation & recovery', 'Místní provoz a obnova'), [n('Local revenue / targeted grants', 'Místní příjmy / účelové dotace'), n('Local founder / project authority', 'Místní zřizovatel / správce projektu'), n('School operation, repairs & shelters', 'Provoz škol, opravy a kryty')], n('Local funding complements the teacher subvention. Recovery and shelter projects may have separate state or donor funding; their exact routes and amounts are not reconciled here.', 'Místní financování doplňuje subvenci na učitele. Obnova a kryty mohou mít zvláštní státní či dárcovské financování; přesné cesty a částky zde nejsou sladěny.'), ['uaLocal', 'uaSchool'], true),
      ],
      health: [
        route('care', n('Medical Guarantees Programme', 'Program zdravotních záruk'), [n('General taxation / state budget', 'Obecné daně / státní rozpočet'), n('National Health Service · NHSU', 'Národní zdravotní služba · NHSU'), n('Contracted public & private providers', 'Smluvní veřejní a soukromí poskytovatelé'), n('Patient care & reimbursed medicines', 'Péče o pacienty a hrazené léky')], n('NHSU purchases covered services under national programmes. A local authority can own a hospital while NHSU pays for its contracted treatment.', 'NHSU nakupuje kryté služby v celostátních programech. Místní úřad může vlastnit nemocnici, zatímco NHSU platí její smluvní léčbu.'), ['uaHealth']),
        route('capital', n('Ownership & recovery', 'Vlastnictví a obnova'), [n('Local / state funds + donor projects', 'Místní / státní zdroje + projekty dárců'), n('Owner / programme administrator', 'Vlastník / správce programu'), n('Facilities & equipment', 'Budovy a vybavení')], n('Owners and recovery programmes can fund facilities separately from NHSU service contracts. Donor support is not all channelled through NHSU.', 'Vlastníci a programy obnovy mohou financovat zařízení odděleně od smluv NHSU. Veškerá dárcovská podpora neprochází přes NHSU.'), ['uaHealth', 'uaSupport']),
        route('private', n('Household spending remains', 'Výdaje domácností zůstávají'), [patient, n('Medicines / other direct payments', 'Léky / další přímé platby'), providers], n('Direct household payments remain important. The 2024 WHO review includes pre-war expenditure data; it does not establish a current wartime spending share.', 'Přímé platby domácností zůstávají významné. Zpráva WHO z roku 2024 obsahuje předválečné výdajové údaje; neurčuje aktuální válečný podíl.'), ['uaHealth']),
      ],
    },
  },
];

export function parseState(search) {
  const p = new URLSearchParams(search);
  return { country: countries.some(c => c.code === p.get('country')) ? p.get('country') : 'CZE', topic: ['funding', 'schools', 'health'].includes(p.get('topic')) ? p.get('topic') : 'schools' };
}

export function benchmarkRows(data, year = 2024) {
  return countries.map(country => {
    const series = data.series.find(row => row.country_code === country.code);
    const get = key => {
      const metric = series?.metrics[key];
      const point = metric?.values.find(row => row.year === year);
      return point && Number.isFinite(point.value) ? { value: point.value, status: point.status || (year <= metric.latest_actual_year ? 'actual' : 'estimate') } : null;
    };
    const revenue = get('revenue_pct_gdp'), spending = get('expenditure_pct_gdp'), balance = get('balance_pct_gdp');
    return { code: country.code, name: country.name, year, revenue, spending, balance };
  });
}
