// Curated, bounded examples. Values are billions of the stated currency unless unit=share.
// A repeated amount is an administrative continuation, never additional expenditure.
import {tr, sources as guideSources, socialRoutes, countries} from './funding-deep-dive.mjs';
const T=tr;
const N=(id,en,cs,value,row,col,noteEn='',noteCs='',kind='public')=>({id,label:T(en,cs),value,row,col,note:T(noteEn,noteCs),kind});
const E=(from,to,value,en,cs,status='actual')=>({from,to,value,label:T(en,cs),status});
const S=(title,url,table)=>({title,url,table});
export const ledgerSources={
 czEducation:S('MF ČR · FIN 1-12 OSS / FIN 2-12 M 2025','https://monitor.statnipokladna.gov.cz/datovy-katalog/transakcni-data','Chapter 333; paragraphs 31/32; PSD education dataset'),
 czHealth:S('MZ / MF · health insurers 2024','https://mzd.gov.cz/wp-content/uploads/2024/06/vz2024_hodnoceni_tab_1-1a-1b-1c-1d-2-4.xlsx','Table 1, part A; cash including taxable activities'),
 czPension:S(guideSources.czPension.title,guideSources.czPension.url,'Actual column: pension contributions and pension benefits'),
 usSchool:S('US Census · School System Finances FY2024','https://www.census.gov/newsroom/press-releases/2026/school-system-finances.html','Revenue and expenditures; rounded billions'),
 frSchool:S('France · RAP 2024, Programme 140','https://www.budget.gouv.fr/documentation/file-download/29612','Printed pp. 16–17: executed payment credits'),
 usPension:S('SSA · 2025 Trustees Report','https://www.ssa.gov/oact/TR/2025/III_A_cyoper.html','Table III.A1; OASI operations in calendar 2024'),
 usSocial:S('SSA · SSI Annual Statistical Report 2024','https://www.ssa.gov/policy/docs/statcomps/ssi_asr/2024/sect01.html','Table 2; payments allocated to month due'),
 frPension:S('Assurance retraite · statistical compendium 2024','https://www.statistiques-recherche.lassuranceretraite.fr/app/uploads/2025/09/1-Les-retraites-du-regime-general.pdf','Legal benefit expenses, 2024'),
 frSocial:S('DREES · Minima sociaux 2025','https://drees.solidarites-sante.gouv.fr/sites/default/files/2025-12/Drees-Pano-MS%202025_0.pdf','Overview; RSA benefit expenditure, 2023'),
 uaBudget:S('Ukraine Cabinet · adopted budget 2025','https://www.kmu.gov.ua/news/verkhovna-rada-ukrainy-pryiniala-derzhbiudzhet-na-2025-rik-oboronu-krainy-bude-zabezpecheno','Teacher salaries and Medical Guarantees Programme; initial plan'),
 uaPension:S('PFU · September 2025 budget','https://www.pfu.gov.ua/2174363-uryad-zatverdyv-byudzhet-pensijnogo-fondu-ukrayiny-na-2025-rik/','Resolution 1152; revised 2025 budget'),
 sha:S('OECD · System of Health Accounts','https://data-explorer.oecd.org/vis?df%5Bag%5D=OECD.ELS.HD&df%5Bid%5D=DSD_SHA%40DF_SHA&df%5Bvs%5D=1.1','DSD_SHA@DF_SHA 1.1; HF1, HF3 and residual; 2024'),
};
const graph=(id,country,topic,year,currency,total,title,note,sourceIds,nodes,edges,extra={})=>({id,country,topic,year,currency,total,title,note,sourceIds,nodes,edges,stage:'actual',unit:'billions',...extra});
export function createLedgers({education,healthInsurers,health,budget}){
 const result=[];
 const m=education.ministry,l=education.local;
 const transfer=m.education_local_transfers_czk_bn, residual=l.net_czk_bn-transfer, direct=m.education_actual_czk_bn-transfer;
 result.push(graph('cz-education','CZE','school',2025,'CZK',education.headline.consolidated_education_czk_bn,
 T('State money enters local education budgets.','Státní peníze vstupují do místních rozpočtů školství.'),
 T('Education including universities, not just schools. The local residual is calculated as net local expenditure minus the ministry transfer: it is not a measurement of local tax revenue. The consolidated total is a PSD cash-outturn estimate; timing and other funders are not fully reconciled.','Vzdělávání včetně vysokých škol. Místní zbytek je rozdíl čistých místních výdajů a transferu ministerstva: neměří místní daňové příjmy. Konsolidovaný součet je odhad PSD z pokladního plnění; časování a další zdroje nejsou plně sladěny.'),['czEducation'],[
 N('ministry','State budget · Education Ministry','Státní rozpočet · MŠMT',m.education_actual_czk_bn,0,0,'Education expenditure, chapter 333','Výdaje na vzdělávání, kapitola 333'),
 N('residual','Other local financing · residual','Další místní financování · rozdíl',residual,0,1,'Derived; sources not separately identified','Dopočet; jednotlivé zdroje nerozlišeny','derived'),
 N('local','Regional + municipal budgets','Krajské + obecní rozpočty',l.net_czk_bn,1,1,'Transfers + other financing; internal transfers removed','Transfery + další zdroje; bez vnitřních transferů','local'),
 N('direct','Direct ministry expenditure','Přímé výdaje ministerstva',direct,1,0,'Universities and other direct education spending','Vysoké školy a další přímé výdaje'),
 N('delivery','Education resources · counted once','Zdroje pro vzdělávání · započteny jednou',education.headline.consolidated_education_czk_bn,2,.5,'Estimated consolidated spending','Odhad konsolidovaných výdajů','merge')
 ],[E('ministry','local',transfer,'Intergovernmental transfer','Mezirozpočtový transfer'),E('residual','local',residual,'Unresolved financing mix','Nerozlišené zdroje','derived'),E('ministry','direct',direct,'Direct expenditure','Přímé výdaje','derived'),E('local','delivery',l.net_czk_bn,'Local expenditure, net','Čisté místní výdaje','derived'),E('direct','delivery',direct,'Direct expenditure','Přímé výdaje','derived')],{stage:'derived',localData:'/data/education-deep-dive.v1.json'}));
 result.push(graph('us-school','USA','school',2024,'USD',994.9,T('Three sources meet in school-system budgets.','Tři zdroje se setkají v rozpočtech školských systémů.'),T('Public elementary and secondary school systems, FY2024. Federal-source revenue can pass through state agencies; it remains federal-source money. The split between direct and passed-through federal funds is not available here. Revenue less expenditure is an arithmetic difference, not a reconciled change in cash reserves.','Veřejné základní a střední školské systémy, fiskální rok 2024. Federální peníze mohou procházet úřady států; stále mají federální původ. Podíl přímých a zprostředkovaných federálních peněz zde není rozlišen. Rozdíl příjmů a výdajů není ověřenou změnou peněžních rezerv.'),['usSchool'],[
 N('federal','Federal-origin revenue','Příjmy federálního původu',115.1,0,0,'Direct + via state agencies','Přímo + přes úřady států'),N('state','State-origin revenue','Příjmy z rozpočtů států',450,0,.5,'State is below the federal level','Stát je úroveň pod federací','local'),N('local','Local-origin revenue','Místní příjmy',429.8,0,1,'Property taxes and other local sources','Majetkové daně a další místní zdroje','local'),
 N('district','Public school-system budgets','Rozpočty veřejných školských systémů',994.9,1,.5,'Revenue received · all sources','Přijaté příjmy · všechny zdroje','merge'),N('current','Current spending','Běžné výdaje',842.3,2,0,'Salaries, support, routine operations','Mzdy, podpora, běžný provoz'),N('capital','Capital outlay','Kapitálové výdaje',113.1,2,.5,'Buildings and equipment','Budovy a vybavení','local'),N('other','Other expenditure','Ostatní výdaje',28.3,2,1,'983.7 − 842.3 − 113.1; rounded residual','983,7 − 842,3 − 113,1; zaokrouhlený rozdíl','derived')
 ],[E('federal','district',115.1,'Federal origin','Federální původ'),E('state','district',450,'State origin','Původ ve státech'),E('local','district',429.8,'Local origin','Místní původ'),E('district','current',842.3,'Current expenditure','Běžné výdaje'),E('district','capital',113.1,'Capital expenditure','Kapitálové výdaje'),E('district','other',28.3,'Other expenditure','Ostatní výdaje','derived')],{balance:T('$994.9bn received − $983.7bn spent = $11.2bn difference. Borrowing, asset transactions and cash balances need a separate reconciliation.','Přijato 994,9 mld. USD − vydáno 983,7 mld. USD = rozdíl 11,2 mld. USD. Půjčky, majetkové transakce a zůstatky vyžadují samostatné sladění.')}));
 result.push(graph('fr-school','FRA','school',2024,'EUR',26.685544935,T('The state pays teaching costs through its own administration.','Stát platí výuku prostřednictvím vlastní správy.'),T('Programme 140: public primary education only. These are spending categories within the state budget, not transfers to school bank accounts. Municipal buildings and operations are outside this total. Académies administer state funds; they are not elected regional budgets.','Program 140: pouze veřejné primární vzdělávání. Jde o výdajové kategorie státního rozpočtu, nikoli převody na účty škol. Obecní budovy a provoz jsou mimo tento součet. Akademie spravují státní prostředky; nejsou rozpočty regionální samosprávy.'),['frSchool'],[
 N('state','State budget · Programme 140','Státní rozpočet · program 140',26.685544935,0,.5,'Executed payment credits','Čerpané platební prostředky'),N('staff','Personnel · ministry / académies','Personál · ministerstvo / akademie',26.590427344,1,0,'Within the same state budget','Uvnitř stejného státního rozpočtu'),N('other','Other expenditure','Ostatní výdaje',.095117591,1,1,'Operations, interventions, capital and advances','Provoz, intervence, investice a zálohy','local'),N('pay','Gross remuneration','Hrubé odměňování',15.121145131,2,0),N('contributions','Employer contributions','Příspěvky zaměstnavatele',11.338601362,2,.5,'Includes pension contributions','Včetně důchodových příspěvků'),N('benefits','Staff benefits','Dávky zaměstnancům',.130680851,2,1)
 ],[E('state','staff',26.590427344,'Personnel allocation','Personální výdaje','classification'),E('state','other',.095117591,'Other expenditure','Ostatní výdaje','classification'),E('staff','pay',15.121145131,'Remuneration','Odměňování','classification'),E('staff','contributions',11.338601362,'Contributions','Příspěvky','classification'),E('staff','benefits',.130680851,'Benefits','Dávky','classification')]));
 result.push(graph('cz-health','CZE','health',2024,'CZK',healthInsurers.summary.expenditure_mczk/1000,T('Seven insurers receive money, then pay for care.','Sedm pojišťoven přijímá peníze a platí péči.'),T('Cash receipts and expenditure, including taxable activities. Expenditure includes more than healthcare payments. Provider-level cash payments are not reconciled here; accrual healthcare costs cannot be substituted for them. The financing gap is not an additional government grant.','Peněžní příjmy a výdaje včetně zdaňovaných činností. Výdaje zahrnují více než úhrady péče. Platby jednotlivým poskytovatelům zde nejsou sladěny; účetní náklady na péči je nemohou nahradit. Rozdíl financování není další státní dotací.'),['czHealth'],[
 N('receipts','Contributions, state payments + other receipts','Pojistné, státní platby + další příjmy',healthInsurers.summary.receipts_mczk/1000,0,0),N('gap','Expenditure above receipts','Výdaje nad příjmy',-healthInsurers.summary.cash_balance_mczk/1000,0,1,'Financing gap; source not decomposed','Rozdíl financování; zdroj nerozlišen','derived'),N('insurers','Seven health insurers','Sedm zdravotních pojišťoven',healthInsurers.summary.expenditure_mczk/1000,1,.5,'Cash expenditure envelope','Celkové peněžní výdaje','merge'),N('care','Providers: hospitals, clinics, pharmacies','Poskytovatelé: nemocnice, ordinace, lékárny',null,2,0,'Payment split not joined','Rozpad plateb nespojen'),N('admin','Administration + other expenditure','Správa + další výdaje',null,2,1,'Payment split not joined','Rozpad plateb nespojen','local')
 ],[E('receipts','insurers',healthInsurers.summary.receipts_mczk/1000,'Cash receipts','Peněžní příjmy'),E('gap','insurers',-healthInsurers.summary.cash_balance_mczk/1000,'Financing gap','Rozdíl financování','derived'),E('insurers','care',null,'Provider payments','Úhrady poskytovatelům','unknown'),E('insurers','admin',null,'Other payments','Ostatní platby','unknown')],{localData:'/data/cz-health-insurers-2024.json'}));
 for(const country of ['FRA','USA']){
  const h=health.countries[country],f=h.financing;
  result.push(graph(`${country.toLowerCase()}-health`,country,'health',h.year,country==='FRA'?'EUR':'USD',100,T('Who finances every 100 spent on healthcare?','Kdo financuje každých 100 vydaných na péči?'),T('Current health expenditure, public and private. “Government + compulsory schemes” includes compulsory private arrangements; it does not mean government budgets alone. These are financing-scheme shares, not a measured payer-to-provider matrix. Capital investment is excluded.','Běžné výdaje na zdravotnictví, veřejné i soukromé. „Vláda + povinné systémy“ zahrnuje povinné soukromé systémy; nejde jen o veřejné rozpočty. Podíly systémů financování nejsou maticí plateb od plátců poskytovatelům. Investice jsou vyloučeny.'),['sha'],[
   N('compulsory','Government + compulsory schemes','Vláda + povinné systémy',f.public_compulsory,0,0,country==='FRA'?'Assurance Maladie and other compulsory schemes':'Medicare, Medicaid and other compulsory schemes',country==='FRA'?'Assurance Maladie a další povinné systémy':'Medicare, Medicaid a další povinné systémy'),N('households','Households · direct payments','Domácnosti · přímé platby',f.out_of_pocket,0,.5,'Out of pocket','Z vlastní kapsy','local'),N('voluntary','Voluntary schemes + other','Dobrovolné systémy + další',f.voluntary_other,0,1,'Supplementary / voluntary financing','Doplňkové / dobrovolné financování','local'),N('care','Healthcare delivered','Poskytnutá zdravotní péče',100,1,.5,'Statistical total; not a single bank account','Statistický součet; nikoli jeden účet','merge')
  ],[E('compulsory','care',f.public_compulsory,'Financing share','Podíl financování','classification'),E('households','care',f.out_of_pocket,'Direct payments','Přímé platby','classification'),E('voluntary','care',f.voluntary_other,'Financing share','Podíl financování','classification')],{unit:'share',localData:'/data/country-health.v1.json'}));
 }
 const czPension=694.86701168712,czContributions=648.38544546944;
 result.push(graph('cz-pension','CZE','pension',2024,'CZK',czPension,T('Pension contributions do not cover the whole payment.','Důchodové pojistné nepokrývá celou výplatu.'),T('ČSSZ civilian pension benefits and pension contributions, actual 2024. The difference is a derived state-budget financing requirement, not a separately observed transfer to an independent pension fund. Administration and other pension schemes are excluded.','Důchodové dávky a důchodové pojistné ČSSZ, skutečnost 2024. Rozdíl je odvozená potřeba financování státním rozpočtem, nikoli pozorovaný transfer do samostatného penzijního fondu. Správa a další důchodové systémy jsou vyloučeny.'),['czPension'],[
 N('contributions','Pension contributions','Důchodové pojistné',czContributions,0,0),N('state','State-budget financing difference','Rozdíl krytý státním rozpočtem',czPension-czContributions,0,1,'Derived: benefits minus contributions','Dopočet: dávky minus pojistné','derived'),N('cssz','State budget · ČSSZ','Státní rozpočet · ČSSZ',czPension,1,.5,'National scheme, local offices','Celostátní systém, místní pobočky','merge'),N('people','Pension benefits','Důchodové dávky',czPension,2,.5,'Paid to pension recipients','Vypláceny příjemcům důchodů')
 ],[E('contributions','cssz',czContributions,'Collected contributions','Vybrané pojistné'),E('state','cssz',czPension-czContributions,'Financing difference','Rozdíl financování','derived'),E('cssz','people',czPension,'Benefits paid','Vyplacené dávky')]));
 result.push(graph('us-pension','USA','pension',2024,'USD',1327.159,T('A national trust fund combines income and reserves.','Celostátní fond kombinuje příjmy a rezervy.'),T('OASI only: old-age and survivor insurance, calendar 2024. Disability insurance and state/local employee pensions are outside this account. Other income combines benefit taxes, interest and reimbursements. The reserve drawdown covers the gap between total income and cost.','Pouze OASI: pojištění ve stáří a pozůstalých, kalendářní rok 2024. Invalidní pojištění a penze zaměstnanců států a obcí jsou mimo účet. Další příjmy zahrnují daně z dávek, úroky a náhrady. Čerpání rezerv kryje rozdíl příjmů a nákladů.'),['usPension'],[
 N('tax','Net payroll contributions','Čisté odvody ze mzdy',1105.586,0,0),N('other','Other income','Další příjmy',118.368,0,.5,'Benefit taxes, interest, reimbursements','Daně z dávek, úroky, náhrady','local'),N('reserves','Reserves drawn down','Čerpání rezerv',103.205,0,1,'Not a new tax receipt','Nejde o nový daňový příjem','derived'),N('fund','Federal OASI trust fund','Federální fond OASI',1327.159,1,.5,'SSA administers benefits nationally','SSA spravuje dávky celostátně','merge'),N('benefits','Retirement + survivor benefits','Důchody ve stáří + pozůstalostní',1316.360,2,0),N('othercost','Administration + railroad interchange','Správa + vyrovnání s železničním systémem',10.799,2,1,'4.939 administration + 5.860 interchange','4,939 správa + 5,860 vyrovnání','local')
 ],[E('tax','fund',1105.586,'Contributions','Odvody'),E('other','fund',118.368,'Other income','Další příjmy','derived'),E('reserves','fund',103.205,'Reserve financing','Financování z rezerv'),E('fund','benefits',1316.360,'Net benefit payments','Čisté výplaty dávek'),E('fund','othercost',10.799,'Other costs','Další náklady','derived')]));
 result.push(graph('fr-pension','FRA','pension',2024,'EUR',160.9,T('Regional pension offices administer a national scheme.','Regionální důchodové pokladny spravují celostátní systém.'),T('Legal benefit expenses of the general pension regime, 2024. This is an accrual expense, not a reconciled cash-transfer ledger. Other pension regimes and complementary pensions are excluded. Contributions and assigned resources are not quantified in this example.','Náklady na zákonné dávky všeobecného důchodového režimu, 2024. Jde o účetní náklad, nikoli sladěný přehled peněžních převodů. Další režimy a doplňkové důchody jsou vyloučeny. Pojistné a přidělené zdroje zde nejsou vyčísleny.'),['frPension'],[
 N('resources','Contributions + assigned resources','Pojistné + přidělené zdroje',null,0,.5),N('fund','Assurance retraite · CNAV / CARSAT','Assurance retraite · CNAV / CARSAT',160.9,1,.5,'Legal benefit expenses','Náklady na zákonné dávky','merge'),N('people','Pension entitlements','Důchodové nároky',160.9,2,.5,'General regime; accrual expense','Všeobecný režim; účetní náklad')
 ],[E('resources','fund',null,'Funding mix not joined','Zdroje nespojeny','unknown'),E('fund','people',160.9,'Benefit expense','Náklad na dávky','classification')],{stage:'accrual'}));
 result.push(graph('cz-social','CZE','social',2024,'CZK',47.55794099098,T('Social insurance also funds sickness benefits.','Sociální pojištění financuje také nemocenské dávky.'),T('One programme, not all social support: ČSSZ sickness-insurance benefits, actual 2024. Contribution receipts in this source combine sickness insurance with employment-policy contributions, so that combined number is not used as a sickness-only inflow.','Jeden program, nikoli veškerá sociální podpora: dávky nemocenského pojištění ČSSZ, skutečnost 2024. Zdroj spojuje příjmy nemocenského pojištění s příspěvkem na politiku zaměstnanosti, proto tento součet nevydáváme za příjem samotného nemocenského pojištění.'),['czPension'],[
 N('state','Social contributions · state budget','Sociální pojistné · státní rozpočet',null,0,.5),N('agency','ČSSZ · sickness-insurance programme','ČSSZ · nemocenské pojištění',47.55794099098,1,.5,'National administration','Celostátní správa','merge'),N('people','Sickness-insurance benefits','Dávky nemocenského pojištění',47.55794099098,2,.5,'Recipients, including maternity-related benefits','Příjemci, včetně dávek souvisejících s mateřstvím')
 ],[E('state','agency',null,'Programme-specific receipts missing','Příjmy programu nerozlišeny','unknown'),E('agency','people',47.55794099098,'Benefits paid','Vyplacené dávky')]));
 result.push(graph('us-social','USA','social',2024,'USD',63.079493,T('Federal and state SSI payments meet at the recipient.','Federální a státní dávky SSI se setkají u příjemce.'),T('Federally administered Supplemental Security Income only. Payments are attributed to the month due, net of overpayment recoveries; this is not a Treasury cash-year reconciliation. State-administered supplements and other benefits are excluded. Federal SSI uses general revenues, not OASI trust-fund contributions.','Pouze federálně spravované dávky Supplemental Security Income. Platby jsou přiřazeny měsíci nároku a sníženy o vrácené přeplatky; nejde o sladění s peněžním rokem ministerstva financí. Samostatně spravované státní doplatky a další dávky jsou vyloučeny. Federální SSI používá obecné příjmy, nikoli odvody do OASI.'),['usSocial'],[
 N('federal','Federal SSI payments','Federální dávky SSI',59.665127,0,0,'General-revenue programme','Program z obecných příjmů'),N('state','State supplements handled by SSA','Státní doplatky spravované SSA',3.414366,0,1,'Participating states','Zapojené státy','local'),N('ssa','SSA · federal administration','SSA · federální správa',63.079493,1,.5,'Two components of benefit payments','Dvě složky dávkových plateb','merge'),N('people','Eligible recipients','Oprávnění příjemci',63.079493,2,.5,'Aged, blind and disabled people with limited resources','Lidé ve stáří, nevidomí a lidé s postižením s nízkými zdroji')
 ],[E('federal','ssa',59.665127,'Federal component','Federální složka','classification'),E('state','ssa',3.414366,'State component','Státní složka','classification'),E('ssa','people',63.079493,'Benefits due','Dávky dle nároku','classification')]));
 result.push(graph('fr-social','FRA','social',2023,'EUR',12.218,T('RSA: the funder and payment agency are different.','RSA: financující úroveň a výplatní instituce se liší.'),T('RSA benefit expenditure, 2023, all funders. Départements normally finance RSA, with state-financed territorial exceptions. The national total cannot be assigned entirely to departmental budgets. CAF/MSA administer payments; other benefits and social services are excluded.','Výdaje na dávku RSA, 2023, všechny zdroje. Obvykle financují departementy, s územními výjimkami financovanými státem. Celostátní součet nelze celý přiřadit rozpočtům departementů. Výplaty spravují CAF/MSA; další dávky a sociální služby jsou vyloučeny.'),['frSocial'],[
 N('departments','Département budgets','Rozpočty departementů',null,0,0),N('state','State-funded territorial exceptions','Státem financované územní výjimky',null,0,1),N('caf','CAF / MSA · RSA benefit administration','CAF / MSA · správa dávky RSA',12.218,1,.5,'National benefit expenditure','Celostátní výdaje na dávku','merge'),N('people','Eligible households','Oprávněné domácnosti',12.218,2,.5)
 ],[E('departments','caf',null,'Funding split not joined','Rozdělení zdrojů nespojeno','unknown'),E('state','caf',null,'Funding split not joined','Rozdělení zdrojů nespojeno','unknown'),E('caf','people',12.218,'RSA benefit expenditure','Výdaje na dávku RSA')]));
 for(const [topic,total,midEn,midCs,endEn,endCs] of [['school',103.2,'Local budgets · education subvention','Místní rozpočty · školská subvence','Teacher salaries','Platy učitelů'],['health',175.5,'NHSU · Medical Guarantees Programme','NHSU · program zdravotních záruk','Contracted healthcare providers','Smluvní poskytovatelé péče']])result.push(graph(`ua-${topic}`,'UKR',topic,2025,'UAH',total,T('A national allocation, delivered through intermediaries.','Celostátní příděl, realizovaný přes zprostředkovatele.'),T('Initial adopted 2025 state-budget allocation, not actual payments. Later amendments and wartime execution can differ. This programme does not cover the whole sector; local own funding and other programmes are outside the diagram.','Příděl v původním schváleném státním rozpočtu 2025, nikoli skutečné platby. Pozdější změny a válečné plnění se mohou lišit. Program nepokrývá celé odvětví; vlastní místní zdroje a další programy jsou mimo schéma.'),['uaBudget'],[
 N('state','State budget · programme allocation','Státní rozpočet · příděl programu',total,0,.5),N('agency',midEn,midCs,total,1,.5,'Planned programme envelope','Plánovaný rámec programu','merge'),N('people',endEn,endCs,null,2,.5,'Actual payment not loaded','Skutečná platba není načtena')
 ],[E('state','agency',total,'Budget allocation','Rozpočtový příděl','plan'),E('agency','people',null,'Actual payment unknown','Skutečná platba neznámá','unknown')],{stage:'plan'}));
 result.push(graph('ua-pension','UKR','pension',2025,'UAH',1025.2,T('The Pension Fund also administers social payments.','Penzijní fond spravuje také sociální platby.'),T('Revised September 2025 PFU budget, not outturn and not pensions alone. The pension-insurance revenue category includes multiple funding sources; it is not all payroll contributions. The 6.2bn residual is calculated from rounded published figures. Planned expenditure is 1,020.9bn; income exceeds it by 4.3bn.','Upravený rozpočet PFU ze září 2025, nikoli skutečnost a nikoli jen důchody. Kategorie příjmů důchodového pojištění zahrnuje více zdrojů; nejde pouze o odvody. Zbytek 6,2 mld. je dopočet ze zaokrouhlených čísel. Plán výdajů je 1 020,9 mld.; příjmy jej převyšují o 4,3 mld.'),['uaPension'],[
 N('pension','Pension-insurance revenue','Příjmy důchodového pojištění',858.8,0,0,'Includes contributions and other assigned funds','Včetně pojistného a dalších přidělených zdrojů'),N('social','State budget · social payments','Státní rozpočet · sociální platby',117.3,0,.5),N('other','Other insurance + residual','Další pojištění + zbytek',49.1,0,1,'42.9 social insurance + 6.2 residual','42,9 sociální pojištění + 6,2 rozdíl','derived'),N('pfu','PFU · planned income','PFU · plánované příjmy',1025.2,1,.5,'A national fund, not local budgets','Celostátní fond, nikoli místní rozpočty','merge'),N('out','Planned total expenditure','Plánované celkové výdaje',1020.9,2,.5,'Pensions, social payments and other costs','Důchody, sociální platby a další náklady')
 ],[E('pension','pfu',858.8,'Pension-insurance category','Kategorie důchodového pojištění','plan'),E('social','pfu',117.3,'State-funded social payments','Státem financované sociální platby','plan'),E('other','pfu',49.1,'Other + residual','Další + rozdíl','derived'),E('pfu','out',1020.9,'Planned expenditure','Plánované výdaje','plan')],{stage:'plan'}));
 result.push(graph('ua-social','UKR','social',2025,'UAH',117.3,T('State social funding enters the Pension Fund.','Státní sociální peníze vstupují do penzijního fondu.'),T('The same 117.3bn allocation already included in the PFU diagram above, not additional expenditure. Revised September 2025 plan. Benefit-level execution is not loaded. Other social programmes and local services are outside this example.','Stejný příděl 117,3 mld. je již zahrnut ve schématu PFU výše; nejde o další výdaj. Upravený plán ze září 2025. Plnění jednotlivých dávek není načteno. Další sociální programy a místní služby jsou mimo příklad.'),['uaPension'],[
 N('state','State budget','Státní rozpočet',117.3,0,.5),N('pfu','PFU · state-funded social payments','PFU · státem financované sociální platby',117.3,1,.5,'Part of the PFU budget above','Součást rozpočtu PFU výše','merge'),N('people','Eligible households','Oprávněné domácnosti',null,2,.5,'Actual payments not loaded','Skutečné platby nejsou načteny')
 ],[E('state','pfu',117.3,'Planned state allocation','Plánovaný státní příděl','plan'),E('pfu','people',null,'Actual payment unknown','Skutečná platba neznámá','unknown')],{stage:'plan'}));
 return result;
}
export function missingLedger(code,topic){
 const c=countries.find(c=>c.code===code),routes=topic==='pension'?socialRoutes[code].pensions:topic==='social'?socialRoutes[code].social:c.routes[topic==='school'?'schools':topic];
 const route=routes[0];
 return graph(`${code.toLowerCase()}-${topic}-gap`,code,topic,null,code==='RUS'?'RUB':'',null,T('The route is documented. The amounts remain unverified.','Cesta je doložena. Částky zůstávají neověřené.'),T('No amount is inferred from the institutional structure. Dashed arrows mean an unverified amount, not zero. The routes below show the additional funding channels and their evidence.','Z institucionální struktury neodvozujeme částku. Přerušovaná šipka znamená neověřenou částku, nikoli nulu. Níže jsou další cesty financování a jejich zdroje.'),[],route.nodes.map((n,i)=>N('n'+i,n.en,n.cs,null,i,.5)),route.nodes.slice(1).map((_,i)=>E('n'+i,'n'+(i+1),null,'Unverified amount','Neověřená částka','unknown')),{stage:'unknown',references:route.sources.map(id=>guideSources[id])});
}
export function ledgerRows(g,lang='en',per100=false){
 const by=Object.fromEntries(g.nodes.map(n=>[n.id,n]));
 return g.edges.map(e=>({from:by[e.from].label[lang],to:by[e.to].label[lang],value:e.value===null?null:per100?e.value/g.total*100:e.value,unit:per100||g.unit==='share'?'per 100':`${g.currency} billion`,year:g.year,status:e.status,meaning:e.label[lang]}));
}
