import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{build}=require('../../lib/revenue-flow-model.js'),{assess}=require('../../lib/revenue-coverage-policy.js');
const profile={latest_year:2023,tax_detail:{personal_income:20,corporate_income:10,vat:25,excise:5,social_security:30,property:5,other:5},government_levels:{central:70,state:null,local:10,social_security:20},municipal_transfers:{year:2024,local_revenue_from_transfers_pct:50}};
test('Czech VAT retains the reported cash allocation and health is separate',()=>{const m=build({code:'CZE',profile,source:'vat'});assert.equal(m.recipients.find(r=>r.id==='municipal').amount,'146.56');assert.equal(m.recipients.find(r=>r.id==='municipal').share,25.84);assert(!m.edges.some(e=>e.kind==='transfer'&&e.active));const h=build({code:'CZE',profile,source:'health'});assert.equal(h.recipients.find(r=>r.id==='insurers').amount,'319.96');});
test('Unknown VAT allocation is never inferred from aggregate recipients or grants',()=>{const m=build({code:'AUS',profile,source:'vat'});assert(m.recipients.every(r=>r.amount===null));assert(!m.edges.some(e=>e.from==='collection'));});
test('German cash VAT split cannot be reused for another year',()=>{assert.equal(build({code:'DEU',profile,source:'vat'}).recipients.find(r=>r.id==='local').amount,'2.8');assert(build({code:'DEU',profile:{...profile,latest_year:2024},source:'vat'}).recipients.every(r=>r.amount===null));});
test('Reported ESA transfers appear independently and disappear from tax selections',()=>{const p={...profile,transfer_evidence:[{layer:'esa_transfers',sector:'S1311',category:'D7PAY_S1313',value:'50',year:2023}]};assert(build({code:'AUT',profile:p}).edges.some(e=>e.from==='recipient-central'&&e.to==='recipient-local'&&e.kind==='transfer'));assert(!build({code:'AUT',profile:p,source:'vat'}).edges.some(e=>e.kind==='transfer'));});
test('Zero is valid; missing and excluded manifest entries are unavailable',()=>{assert(assess(profile).eligible);assert(assess({...profile,municipal_transfers:{year:2023,local_revenue_from_transfers_pct:0}}).eligible);assert(!assess({...profile,municipal_transfers:null}).eligible);assert(!assess(profile,{eligible:false}).eligible);});

test('German historical VAT example remains distinct from a newer OECD year',()=>{const m=build({code:'DEU',profile:{...profile,latest_year:2024},cashExample:true});assert.equal(m.year,2023);assert.equal(m.sources[0].amount,'291.4');assert.equal(m.sources[0].unit,'EUR bn');assert.equal(m.recipients.find(r=>r.id==='local').amount,'2.8');assert(m.rows.every(r=>r.year===2023));});

test('EUR converts same-year Czech cash and residuals while retaining native amounts',()=>{const fx={source_url:'https://data-api.ecb.europa.eu/test',rates:{CZK:{2023:{value:'24'}}}};const m=build({code:'CZE',profile,currency:'EUR',fx,source:'vat'});const local=m.recipients.find(r=>r.id==='municipal');assert.equal(local.amount,'6.107');assert.equal(local.nativeAmount,'146.56');assert.equal(local.share,25.84);const budget=build({code:'CZE',profile,currency:'EUR',fx,recipient:'municipal'});assert(budget.details.some(r=>r[0].startsWith('Residual')&&r[1]==='-0.004 EUR bn'&&r[2].includes('-0.1 CZK bn')));});
test('EUR never uses nearest-year rates or turns unknown currency into euro',()=>{const {euros}=require('../../lib/revenue-flow-model.js');assert.equal(euros('100','CZK',2024,{rates:{CZK:{2023:{value:'24'}}}}),null);assert.equal(euros('100',null,2023,{rates:{CZK:{2023:{value:'24'}}}}),null);assert.equal(euros(null,'EUR',2023,null),null);assert.equal(euros('0','EUR',2023,null).value,0);assert.equal(build({code:'AUS',profile,currency:'EUR'}).sources[0].unit,'% of all taxes');});
