import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const context={};runInNewContext(readFileSync(new URL('../../lib/state-enterprise-model.js',import.meta.url),'utf8'),context);
const model=context.StateEnterpriseModel;
const base={fx:{rates:{CZK:25,EUR:1}},records:[{id:'foreign',country_code:'DEU',currency:'EUR',source_revenue_m:200},{id:'old',ico:'00005886',country_code:'CZE',currency:'CZK',source_revenue_m:999,ownership_pct:null}]};
const history=(year,revenue,scope='standalone')=>({year,revenue,scope,period_start:`${year}-01-01`,period_end:`${year}-12-31`,observations:{revenue:{normalized_unit:'CZK_million',value:String(revenue*1000),unit:'CZK_thousand',source_url:'https://example.org/accounts',source_report_year:year}}});
const rows=[{record_id:'dpp',national_id:'00005886',name:'DPP',entity_class:'controlled_enterprise',ownership_level:'central_or_mixed',financial_history:[history(2025,300),history(2024,200),history(2024,900,'consolidated')],source_url:'https://example.org/registry'},{record_id:'pmdp',national_id:'25220683',name:'PMDP',entity_class:'controlled_enterprise',ownership_level:'municipal',financial_history:[history(2025,80)],source_url:'https://example.org/registry'},{record_id:'regional',national_id:'12345678',name:'Regional',entity_class:'majority_public_owned_enterprise',ownership_level:'regional',financial_history:[history(2024,0)],source_url:'https://example.org/registry'}];
function shard(data=rows){const fields=Object.keys(rows[0]);return {fields,dictionary_fields:['entity_class'],dictionaries:{entity_class:['controlled_enterprise','majority_public_owned_enterprise']},records:data.map(row=>fields.map(k=>k==='entity_class'?['controlled_enterprise','majority_public_owned_enterprise'].indexOf(row[k]):row[k]))};}
test('published compact rows rank exact standalone 2024 and deduplicate editorial identity',()=>{const result=model.merge(base,shard());assert.equal(result.length,4);const dpp=result.find(r=>r.ico==='00005886');assert.equal(dpp.source_revenue_m,200);assert.equal(dpp.owner_level,'central_or_mixed');assert.equal(dpp.fx_rate,25);assert.equal(dpp.financial_history.length,3);assert.equal(result[0].id,'foreign');assert.equal(result.find(r=>r.ico==='25220683').source_revenue_m,null);assert.equal(result.find(r=>r.ico==='12345678').source_revenue_m,0);assert.equal(result.find(r=>r.ico==='25220683').ownership_pct,null);assert.equal(result.find(r=>r.ico==='12345678').owner_level,'regional');});
test('unresolved owner remains mixed; missing FX and duplicate histories reject',()=>{const noOld={...base,records:base.records.slice(0,1)};assert.equal(model.merge(noOld,shard())[1].owner_level,'central_or_mixed');assert.throws(()=>model.merge({...base,fx:{rates:{}}},shard()),/exchange rate/);assert.throws(()=>model.merge(base,shard([rows[0],rows[0]])),/Duplicate/);assert.throws(()=>model.merge(base,shard([{...rows[0],financial_history:[history(2024,1),history(2024,2)]}])),/Ambiguous/);});
test('explicit editorial group comparator is retained with separate individual history',()=>{const group={...base,records:[{id:'CZE-CEZ',ico:'45274649',country_code:'CZE',currency:'CZK',source_revenue_m:259200,metric_en:'state consolidation',source_url:'https://example.org/editorial'}]};const output=model.merge(group,shard([{...rows[0],national_id:'45274649',financial_history:[history(2024,100)]}]));assert.equal(output[0].source_revenue_m,259200);assert.match(output[0].ranking_scope,/editorial/);assert.equal(output[0].financial_history[0].revenue,100);});
test('actual published DPP and PMDP contract exposes 2024 ranking and all four history years',()=>{const fixture=JSON.parse(readFileSync(new URL('../fixtures/state-enterprise-published-contract.json',import.meta.url),'utf8'));const fields=Object.keys(fixture.records[0]);const compact={fields,dictionary_fields:[],dictionaries:{},records:fixture.records.map(r=>fields.map(k=>r[k]))};const output=model.merge({...base,records:[]},compact);for(const source of fixture.records){const result=output.find(r=>r.ico===source.national_id);assert.equal(result.source_revenue_m,source.financial_history.find(h=>h.year===2024).revenue);assert.equal(result.financial_history.length,4);assert.equal(result.owner_level,source.ownership_level);assert.notEqual(result.source_revenue_m,source.financial_history.find(h=>h.year===2025).revenue);}});
test('short or fiscal periods cannot enter calendar 2024 ranking',()=>{const altered={...rows[0],financial_history:[{...history(2024,20),period_start:'2024-07-01'}]};assert.equal(model.merge(base,shard([altered])).find(r=>r.ico==='00005886').source_revenue_m,null);});
test('documented editorial 2024 snapshot remains a labelled fallback, never latest-year substitution',()=>{const editorial={...base,records:[{...base.records[1],period:'2024',source_revenue_m:42,metric_en:'individual-entity turnover',source_url:'https://example.org/2024'}]};const result=model.merge(editorial,shard([{...rows[0],financial_history:[history(2025,900)]}]))[0];assert.equal(result.source_revenue_m,42);assert.equal(result.source_url,'https://example.org/2024');assert.match(result.ranking_scope,/2024 editorial snapshot fallback/);assert.equal(result.financial_history[0].revenue,900);assert.equal(model.merge(base,shard([{...rows[0],financial_history:[history(2025,900)]}])).find(r=>r.ico==='00005886').source_revenue_m,null);});
test('audited public transport bodies join enterprise ranking; ordinary budget bodies do not',()=>{const fare={year:2025,scope:'standalone',fare_revenue:5,observations:{fare_revenue:{normalized_unit:'CZK_million',source_sha256:'a'.repeat(64),source_url:'https://example.org/accounts',page:3}}};const operator={...rows[0],national_id:'17196264',entity_class:'statutory_public_body',financial_history:[fare]};const ordinary={...operator,national_id:'99999999',financial_history:[history(2024,400)]};const fields=Object.keys(operator);const result=model.merge({...base,records:[]},{fields,dictionary_fields:[],dictionaries:{},records:[operator,ordinary].map(row=>fields.map(k=>row[k]))});assert.equal(result.length,1);assert.equal(result[0].ico,'17196264');assert.equal(result[0].source_revenue_m,null);assert.equal(result[0].ownership_pct,null);assert.equal(result[0].directory_record.entity_class,'statutory_public_body');});
test('missing current percentage retains explicitly dated editorial share provenance',()=>{const editorial={...base,records:[{...base.records[1],period:'2024',ownership_pct:100,source_url:'https://example.org/editorial'}]};const result=model.merge(editorial,shard())[0];assert.equal(result.ownership_pct,100);assert.equal(result.owner_level,'central_or_mixed');assert.equal(result.ownership_snapshot.kind,'editorial snapshot');assert.equal(result.ownership_snapshot.period,'2024');assert.equal(result.ownership_snapshot.source_url,'https://example.org/editorial');});
